### ISSUE TITLE
Class declaration modifications needs to be better specified

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1043]
**Reported by per&#x2e;ostlund on 21 Mar 2013 12:57 UTC**
Modifying class declarations are not very well specified in the specification. What I mean is modifications such as this:
```
class A
  class B
    parameter Real x;
  end B;

  B b;
end A;

class C
  A a(B(x = 1.0));
end C;
```
The grammar allows such constructs, and the modification section in the spec usually refers to e.g. elements or declarations instead of components and classes. But none of the examples demonstrates that it's possible to modify class declarations. So at the very least it would be a good idea to have some examples of such modifications.

There's also at least one issue that I've found. Consider this model:
```
class A
  class B end B;
end A;

class C
  class D end D;
  A a(B = D);
end C;
```
The behaviour of the 'B = D' modification does not seem to be specified, and it's unclear to me what it might mean. For components this notation changes the default value of the component, but this makes no sense for classes. In my opinion this is a redeclaration of B that's missing the redeclare keyword, so it should be forbidden. If it should be allowed then the behaviour of such modifications needs to be specified.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1043

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
