### ISSUE TITLE
New style guide. For absolute names use a "."

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1061]
**Reported by otter on 3 Apr 2013 10:19 UTC**
Recently, the following bug occurred in MSL (trunk):

  In an example of a sub-library the following declaration was present:
```
Blocks.Sources.RealExpression expr(y=...)

```

  At the time of implementation, this model was correct. Now, later in this sub-library a new package "Blocks" was introduced. As a result, the above (previously correct) example was invalidated because the name-lookup found the wrong "Blocks" package.

Similar issues occurred to me also previously with the package name "Utilities" (because this name is used in a lot of packages, on different hierarchical levels, and sometimes even as root level package name).

I really would like to get rid of this completely unnecessary ambiguous definition of Modelica models. The solution is simple:

 1. If there are no good reasons for relative path names (as e.g. in Media), use always absolute path names.
 1. If absolute path names are intended, define this unambiguously using the leading "." (such as ".Modelica.Blocks").
 1. Optionally, use "import" to shorten absolute path names (usually only for manually constructed models).

If you agree, as a first step one could change in MSL trunk easily with an editor "extends Modelica.XXX" to "extends .Modelica.XXX". As a side effect, this might also help to speed-up the name lookup of some tools (see ticket #518).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1061

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 25 Oct 2018 15:26 UTC**
Unhide tickets in preparation for move to GitHub.
(Examined tickets before.)

**Comment by HansOlsson** [comment]
Does not seem active, and there seems to be opposition to the actual proposal.

Note that tools can implement this stye-guide and/or detect when you add a new element that would cause shadowing; reducing this problem.
