### ISSUE TITLE
Returning an error code from an external object

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1071]
**Reported by garron&#46;fish on 10 Apr 2013 08:43 UTC**
```
```
External objects as described in Section 12.9.7 
of the Modelica Specifications have the following limitations:
* "The constructor shall have exactly one output argument in 
   which the constructed type derived from ExternalObject is 
   returned".
* "The destructor shall have no output arguments"

If an error occurs in the constructor or destructor it is 
difficult to work out which object instance is the cause, with
these limitations.

A method of returning an errorCode from the constructor and 
destuctor functions would be a big improvement to the 
external objects.  If a method already exists, adding the 
description to the documentation would be good.
```

}}}
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1071

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 29 Apr 2013 09:26 UTC**
Except from:

```
Modelica/Resources/C-Sources/ModelicaUtilities.h:void ModelicaError(const char *string);
```

I cannot see any backwards compatible way to actually \*return\* an error. This would require either to wrap the return value or to hand in a special argument to the methods. In both cases we would need to change/extend the interface in a non-backward compatible way.

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 20 Jun 2014 13:07 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 20 Jun 2014 14:50 UTC**
I would say this is a tool issue. You just call `ModelicaError`, `ModelicaFormatError`, or `ModelicaVFormatError`. If a tool reports for which component the error was triggered, there should be no issue.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 24 Apr 2015 12:09 UTC**

**Comment by HansOlsson** [comment]
> 
> 
> **Comment by sjoelund.se on 20 Jun 2014 14:50 UTC**
> I would say this is a tool issue. You just call `ModelicaError`, `ModelicaFormatError`, or `ModelicaVFormatError`. If a tool reports for which component the error was triggered, there should be no issue.

Makes sense.
