### ISSUE TITLE
Is 'final replaceable' allowed?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1165]
**Reported by eshmoylova on 10 Jun 2013 18:37 UTC**
According to 7.3.3 Specs 3.2 Rev 1:
  an element declared as final may not be modified, and thus not redeclared

According to Section 7.3:
  A modifier with the keyword replaceable is automatically seen as being a redeclare.

The question is when the error should be given. Should it be given at the time an element declared as **final replaceable** or only at the time when there is a **redeclare**-clause for this element?

Based on the specification, I would think the former. But it looks like tests:
Redeclare/Restrictions/FinalRedeclareElementClass.mo
Redeclare/Restrictions/FinalRedeclareElementComp.mo
Redeclare/Restrictions/FinalRedeclareModifierClass.mo
Redeclare/Restrictions/FinalRedeclareModifierComp.mo

in the Modelica Compliance Test Suite #1101 expect the error to be given only at the time when a redeclare is called.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1165

**Comment by modelica-trac-importer** [comment]
**Comment by perost on 10 Jun 2013 19:12 UTC**
Note that the second rule only applies to _modifiers_, so it has no influence at all on the referenced tests which only use replaceable _elements_. Declaring an element to be 'final replaceable' is of course silly, and a good tool should tell the user that. But as it stands I don't think there's anything in the specification that forbids such a construct, which is why I wrote tests for it.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Jun 2013 11:19 UTC**
As noted in #1101 there is a similar issue with 'replaceable constant'.
7.3.3 states that constant may not be redeclared
7.3 includes constant in the list of attributes preserved from the original declaration
So - not only is the silly case present for constant, but there is even a special rule for the case that cannot occur!

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 12 Jun 2013 11:54 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by eshmoylova on 29 Nov 2013 22:35 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by volker&#46;beuter on 30 Nov 2013 22:09 UTC**
A similar case is the declaration of a **final parameter** without a value. Even if this may be legal due to the current specification IMO this ought to be marked illegal in future. A class which can never ever be used should be considered illegal itself I think. In other aspects Modelica follows the policy to detect errors as early as possible (like in the introduction of the requirement of locally balanced classes in 3.0). So I propose to act in the same direction of the cases here concerning **final**. 
Backward compatibility ought to be no problem here, because such classes cannot be used. The only library to be changed may be the Compliance Checker.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 2 Dec 2013 09:49 UTC**
Note that we have to be careful by exactly what we mean by "without a value".

The following example should be ok:
```
  final parameter Real x(fixed=false);
initial equation
  x=...;
```
I am not sure if we have to specify semantics to rule out "meaningless" examples and should spend to find the exact rules; or could just have a comment in the specification stating what we currently believe to be meaningless.

**Comment by beutlich** [comment]
Issue is open while milestone is closed -> removing milestone.

**Comment by HansOlsson** [comment]
There seems to be a lack of interest in this (6 years later). I agree that clarifying it would be good, but not strictly needed - and thus closing.
