### ISSUE TITLE
ModelicaError shall never return but how

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1197]
**Reported by beutlich on 3 Jul 2013 14:54 UTC**
In 12.9.6 it reads for ModeliaError: This function never returns to the calling function.

How can this requirement technically be solved:

 * Calling `exit` is not possible as the entire application is closed.
 * Using `setjmp` / `lonjmp` is inappropriate as the stack is not cleaned up and a local context is missing.
 * Using Microsoft C exceptions `__try` / `__except` is not platform independent.

Also: Is it always necessary to do a clean up (free memory, close file handles etc.) before calling ModelicaError.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1197

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 3 Jul 2013 14:55 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 3 Jul 2013 15:19 UTC**
I agree that we could add a note that resources should be cleaned up; and that exit is a bad idea.


However, I don't see a problem with setjmp/longjmp. Obviously the Modelica tool calling the external function calling ModelicaError has to make the setjmp - but that is controlled by the tool (and I don't see the problem with stack and local context - setjmp/longjmp was sort of designed for this kind of use-case). Yes, it may not be pretty - but I do not see any other solution that is platform independent in C.


Having a platform dependent solution should be ok - on that platform. There is no requirement that a Modelica tool must have platform independent code. (And even C++ exceptions _may_ work.)

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 3 Jul 2013 18:23 UTC**
For the record, OpenModelica uses setjmp/longjmp and has no issues with cleaning things up. Unless somehow the external function does not clean up before calling ModelicaError. But since the function is not supposed to return, that is the caller's problem.

And before we used setjmp/longjmp we used a C++ runtime, so we could try/catch/throw it using C++ exceptions.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 9 Jul 2013 07:05 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 9 Jul 2013 10:28 UTC**
IMO, "never return" can only mean that no external C function is called after ModelicaError, any other case is not observable from the outside anyway.

**Comment by modelica-trac-importer** [comment]
**Comment by bastian on 10 Jul 2013 11:22 UTC**
Indeed there is a problem with Microsoft Visual Studio 2005 and `longjmp` in connection with (certain) signal handlers, cf. https://groups.google.com/forum/#!msg/microsoft.public.vc.language/gRixZUaSb0Y/YxWelRjaMwUJ
`longjmp` screws up the exception handler chain.

However, it seems that in MS VS 2010 this does not happen any longer and -- more important -- there is no need to use signal handlers for ModelicaError.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 10 Jul 2013 17:06 UTC**
Replying to [comment:5 choeger]:
> IMO, "never return" can only mean that no external C function is called after ModelicaError, any other case is not observable from the outside anyway.

As written, one should assume from the text that the function is declared with `_Noreturn` (but spec was written before this was standardised in C).

> This function never returns to the calling function, but handles the error similarly to an assert in the Modelica code

And assert in Modelica code means you do not keep executing, instead trying a different solver step. Regardless, it is talking about the C function, not the Modelica function calling the C function.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 28 Oct 2013 09:58 UTC**
Replying to [comment:2 hansolsson]:
> I agree that we could add a note that resources should be cleaned up; and that exit is a bad idea.

It is still not clear to me where to clean up after a raised ModelicaError exception in an external object.
 1. Should the external object do the clean up, that is basically call the destructor before ModelicaError is raised?
 1. Should the simulation tool call the destructors in its exception handling?

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 15 Nov 2013 13:19 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 3 Dec 2013 13:49 UTC**
Replying to [comment:8 beutlich]:
> Replying to [comment:2 hansolsson]:
> > I agree that we could add a note that resources should be cleaned up; and that exit is a bad idea.
> It is still not clear to me where to clean up after a raised ModelicaError exception in an external object.
>  1. Should the external object do the clean up, that is basically call the destructor before ModelicaError is raised?
>  1. Should the simulation tool call the destructors in its exception handling?

If the external object is created and returned from C to "Modelica" I would say the tool should call the destructor; anything not yet returned must be cleaned up before calling ModelicaError. 

The reason is that the external function can not know all external objects so it could not handle all of them.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 7 Apr 2014 09:10 UTC**
I added the _Noreturn/etc with some ifdefs, etc to ModelicaUtilities.h in r7484,r7485 since they seem to be necessary to compile C-code with MSVC without resorting to compiler flags to disable warnings.
They are necessary to run static analysis tools without all too many false positives on ModelicaExternalC and ModelicaTables anyway.

**Comment by modelica-trac-importer** [comment]
**Comment by anonymous on 7 Apr 2014 10:30 UTC**
Replying to [comment:11 sjoelund.se]:
> I added the _Noreturn/etc with some ifdefs, etc to ModelicaUtilities.h in r7484,r7485 since they seem to be necessary to compile C-code with MSVC without resorting to compiler flags to disable warnings.
> They are necessary to run static analysis tools without all too many false positives on ModelicaExternalC and ModelicaTables anyway.

Thank you for this very essential fix.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 14 May 2015 19:56 UTC**
> If the external object is created and returned from C to "Modelica" I would say the tool should call the destructor; anything not yet returned must be cleaned up before calling ModelicaError. 

sjoelund: Does OMC call the destructors of the external objects after a raised ModelicaError? Also in the case the ModelicaError happens in a constructor of an external object?

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 15 May 2015 13:45 UTC**
Replying to [comment:13 beutlich]:
> @sjoelund.se: Does OMC call the destructors of the external objects after a raised ModelicaError?

I'm not sure. If it doesn't, I would consider it a bug.

> Also in the case the ModelicaError happens in a constructor of an external object?

No. There is no external object returned which means you can not call a destructor (no void pointer to pass it); however, the constructor function can undo all operations before calling ModelicaError as it knows everything it did.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 15 May 2015 14:06 UTC**
Replying to [comment:14 sjoelund.se]:
> No. There is no external object returned which means you can not call a destructor (no void pointer to pass it); however, the constructor function can undo all operations before calling ModelicaError as it knows everything it did.

Right.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 31 Mar 2016 12:50 UTC**
I would propose to just close this as worksforme.

Alternatively we could add text to the specification in 12.9.6 (after the table):
\--
Before calling ModelicaError (or one of the other error-functions that does not return) resources allocated in that C-function call should be cleaned up. Internally ModelicaError may use longjmp or similar constructs.
\--

**Comment by beutlich** [comment]
Issue is open while milestone is closed -> removing milestone.

**Comment by HansOlsson** [comment]
Closing according to first proposal.

**Comment by beutlich** [comment]
> 
> 
> Closing according to first proposal.

Which fiirst proposal actually? Was anything improed in the spec. text?

**Comment by HansOlsson** [comment]
> 
> 
> > Closing according to first proposal.
> 
> Which fiirst proposal actually? Was anything improed in the spec. text?

Closed as worksforme, I was referring to:

> 
> 
> **Comment by hansolsson on 31 Mar 2016 12:50 UTC**
> I would propose to just close this as worksforme.
> 
> Alternatively we could add text to the specification in 12.9.6 (after the table):
> --
> Before calling ModelicaError (or one of the other error-functions that does not return) resources allocated in that C-function call should be cleaned up. Internally ModelicaError may use longjmp or similar constructs.
> --

**Comment by beutlich** [comment]
OK, I can live with it.
