### ISSUE TITLE
Does a modification that is replaced by another modification need to be valid?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1219]
**Reported by stefanv on 23 Jul 2013 20:42 UTC**
Consider:

```mo
model Sub 
    parameter Real a = b; // note that there is no "b" in scope
    Modelica.Blocks.Interfaces.RealOutput y;
equation 
    y = a;
end Sub;

model Main 
    Sub s(a=1);
end Main;
```

Model `Sub` is clearly illegal on its own, because b is nowhere defined.

However, is model `Main` legal? The modification `a=1` overrides the modification `a=b` inside `Sub`.

MapleSim and Dymola 7.4 Demo both accept `Main`, but reject `Sub` when processed on its own. Is this actually correct behaviour, or should any (non-partial) model be able to stand on its own?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1219

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 31 Mar 2016 13:08 UTC**
Replying to [ticket:1219 stefanv]:
> Consider:
> 
> ```mo
> model Sub 
>     parameter Real a = b; // note that there is no "b" in scope
>     Modelica.Blocks.Interfaces.RealOutput y;
> equation 
>     y = a;
> end Sub;
> 
> model Main 
>     Sub s(a=1);
> end Main;
> ```
> 
> Model `Sub` is clearly illegal on its own, because b is nowhere defined.
> 
> However, is model `Main` legal? The modification `a=1` overrides the modification `a=b` inside `Sub`.
> 
> MapleSim and Dymola 7.4 Demo both accept `Main`, but reject `Sub` when processed on its own. Is this actually correct behaviour, or should any (non-partial) model be able to stand on its own?

I would say that it is acceptable behavior. The model 'Sub' is clearly wrong - but I don't see that tools should be required to report that when translating 'Main'.
For other similar issues see #1314.

I don't know if the specification needs to be updated for this, but would propose to close as 'worksforme'.

**Comment by HansOlsson** [comment]
Closing as proposed.
