### ISSUE TITLE
Inconsistent rule for preserving type properties at redeclaration

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1253]
**Reported by petfr on 18 Aug 2013 12:18 UTC**
In MS 3.2 rev 2, section 7.3 about Redeclaration
we have the following:

...In redeclarations some parts of the original declaration is automatically inherited by the new declaration.
...
[Note: The inheritance is from the original declaration.  In most cases replaced or original does not matter. It does matter if a user redeclares a variable to be a parameter and then redeclares it without parameter.]

This rule about the original declaration is a nonintutive special
rule and should be changed.
 It should not matter which way a class is created, whether
declared directly or created via redeclaration. The rules should
be the same in both cases.

For example, using the current nonintutive rule:

class C9Base
  replaceable discrete Real x = 10.2;
end C9Base;

class C9A = C9Base(redeclare parameter Real x);
class C9Aexpanded
  parameter Real x = 10.2;
end C9Aexpanded;

If we subsequently redeclare C9A without parameter, it will get the discrete prefix of the original declaration in C9Base, not the replaced one in C9A:

class C9B = C9A(redeclare Real x);

class C9Bexpanded
  discrete Real x = 10.2;
end C9Bexpanded;

Instead, with a more consistent language rule, the current definition of C9A should
be used, causing the expanded C9B to be:

class C9Bexpanded
  parameter Real x = 10.2;
end C9Bexpanded;

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1253

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 23 Sep 2013 10:01 UTC**
Seems like a good idea, but I would see it as an extension for 3.4.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 24 Sep 2013 10:29 UTC**
Language group:
The example above is currently illegal (as far as I can tell), since C9Bexpanded is not a sub-type of C9AExpanded (redeclaration changing a parameter to discrete).

Thus in practice the user is forced to repeat the type-prefixes on all new redeclaration; which is tedious. (But seems like a rare case.)

Should ideally be inherited from the constraining clause - but not possible to have type-prefixes in constrainedby.

Conclusion: Needs a more complete design.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 1 Mar 2017 13:54 UTC**
The proposed semantics can be viewed as local semantic sugar; and to evaluate it it would be preferable if we had actual user examples.

**Comment by HansOlsson** [comment]
As indicated we would need actual user examples to evaluate this proposal.
