### ISSUE TITLE
Modelica Parsing Compliance Test Suite?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1318]
**Reported by adrpo on 10 Oct 2013 18:13 UTC**
Hi all,

I think that in addition to Modelica Language Compliance Test Suite we should maybe also have a Modelica Parsing Compliance Test Suite.
There are tools that accept models that are not conform to the grammar. Example (this model is happily accepted by an unnamed tool even if it should not parse):
```
model ArrayDimsInConstrainedBy
 constant Integer nCon = 10;

 record ParameterConstruction
  Real x = 1;
 end ParameterConstruction;

 replaceable parameter
   ParameterConstruction conPar[nCon]
    constrainedby ParameterConstruction[nCon];

end ArrayDimsInConstrainedBy; 
```

Such tests unfortunately cannot be added to the Modelica Language Compliance Test Suite as it would render it un-parse-able.

The danger with having a Modelica tool accepting models that should not even parse is that some libraries will not be Modelica compliant. 

A Modelica language compliance testsuite should include also a parsing testsuite. Otherwise is not really a Modelica language compliance testsuite (is just a Modelica language semantics testsuite).

I think this is not a big effort as wrong parsing is not that common. Whenever we find a model that parses in some tool even if it should not we could add it to the ModelicaParserCompliance/3.x/shouldNotParse/ directory in Subversion.
For the other case where we find a model that should be accepted but is not we can add it to ModelicaParserCompliance/3.x/shouldParse/.

Sorry for the long ranting but sometimes I'm really annoyed by wrong things popping up in libraries out there. 
Feel free to disagree with me.

Cheers,
Adrian Pop/

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1318

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 10 Oct 2013 18:35 UTC**
That sounds like a good idea. FWIW, moparser rejects this model with :

```
syntax error on line 10 of parse-test.mo: expected ";" but received "["
```

From this, I assume you did not find this code in the MSL, since the MSL gets run through moparser before release.

**Comment by modelica-trac-importer** [comment]
**Comment by adrpo on 10 Oct 2013 18:42 UTC**
No. The code was not in MSL but that's normal as MSL is tested with several tools.
This particular case appeared in the Buildings library and was already removed.
But there are tons of other libraries out there that are not tested with several tools.

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 11 Oct 2013 06:16 UTC**
Since moparser is available from the Modelica svn, all library developers can (and should) use it. Therefore, it seems that one should just make this more visible to library developers. Note, the Modelica Standard Library is tested with moparser since several years and from time to time finds errors in MSL. Furthermore, the grammar description in ModelicaReference is also based on moparser.

A dedicated "Modelica Parsing Compliance Test Suite" would provide exactly the same feature (but eventually developed by other people and be open source). Therefore, I currently do not feel that it is necessary to develop it.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 11 Oct 2013 06:22 UTC**
Martin O., the feature here is different:
A set of models that all tools have to handle in the same way (and that the MA could certify this tool has a sane parser).

Note that also moparser contains minor bugs that deviate from the spec (quoted identifiers, etc).

Using existing libraries for testing your parser is a bad way since many of them should not parse (especially older ones).

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 11 Oct 2013 06:26 UTC**
Replying to [comment:3 otter]:
> Since moparser is available from the Modelica svn, all library developers can (and should) use it. Therefore, it seems that one should just make this more visible to library developers. Note, the Modelica Standard Library is tested with moparser since several years and from time to time finds errors in MSL. Furthermore, the grammar description in ModelicaReference is also based on moparser.
> 
> A dedicated "Modelica Parsing Compliance Test Suite" would provide exactly the same feature (but eventually developed by other people and be open source). Therefore, I currently do not feel that it is necessary to develop it. 

Hm. I do not have a strong opinion here. But whoever makes a parser might make errors. Therefore, from a practical point of view, the essential test seems to be to check a library with at least two parsers implemented by different people. The advantage of moparser is that it is **available** and when it contains small errors it seems sufficient to report them to Stefan and (at least in the past), Stefan quickly made a fix.

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 11 Oct 2013 06:33 UTC**
Still another idea:
Other tool vendors could make their parsers also a public executable with the same arguments as moparser:
  
  moparser -e -r Modelica > log_Modelica.txt

  -e: redirector errors to standard outputs
  -r: recurse into directories

With a simple script all the parsers can then be checked on a library and the library developer has a first test that his/her library will at least parse in the respective tools.

**Comment by modelica-trac-importer** [comment]
**Comment by adrpo on 11 Oct 2013 06:40 UTC**
True, having several vendor parsers available would be good.

The problem however still remains but it is pushed to the library developers
which I'm not sure they care about running additional tools on their models.
If their tool say the model is correct they are happy with that and that's it.

A parsing testsuite ensure that vendors fix their tools.

This doesn't need to be supported by MA with anything but SVN access.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 11 Oct 2013 07:28 UTC**
Creating a tool to verify parsers is quite simple (at least for moparser and OpenModelica):
```py
#!/usr/bin/env python

import tempfile
from subprocess import call

def checkMOParser(filename):
  return 0 == call(["moparser","-q",filename])

def checkOMC(filename):
  f = tempfile.NamedTemporaryFile(suffix='.mos')
  f.write('exit(if loadFile("%s") then 0 else 1);' % filename)
  f.flush()
  return 0 == call(["omc",f.name])

tools = {'moparser' : checkMOParser, 'OpenModelica' : checkOMC}

def checkAllTools(filename):
  for tool in tools.keys():
    print filename,tool,tools[tool](filename)

checkAllTools("a.mo")
checkAllTools("b.mo")
```

Such an interface would be quite simple for most vendors to comply to I assume (doesn't require you to provide the exact arguments of moparser, etc).

Anyway, this returns (b.mo is an invalid file):
```
a.mo OpenModelica True
a.mo moparser True
b.mo OpenModelica False
b.mo moparser False
```

Creating a nice report from this if you have this interface (filename to boolean), and a set of files to test, is not hard.

I did manage to write a script to launch Dymola too, but it returns true on errors and actually partially loads the models. Maybe it needs a hidden flag to make it actually respect parser errors that it detects.

**Comment by modelica-trac-importer** [comment]
**Comment by Dag Brück on 11 Oct 2013 08:17 UTC**
You have discovered that Dymola is a development environment, not à compiler. 

Dag

**Comment by modelica-trac-importer** [comment]
**Comment by adrpo on 11 Oct 2013 08:45 UTC**
Nobody mentioned the word "compiler" in this ticket before.
A development environment is however a tool.
Even development environments have to be compliant, or they get an exception? :)

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 11 Oct 2013 12:05 UTC**
Replying to [comment:10 adrpo]:
> Nobody mentioned the word "compiler" in this ticket before.

No, but Martin did assume in his test that it would _behave_ like a compiler, i.e. exit with an error when given a malformed file - something that is definitely not what you would expect from a development environment.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 11 Oct 2013 12:28 UTC**
I did not assume it would behave like a compiler. I expected a scripting environment for Modelica and got one. It just did not do what I expected was possible. I expected there was an option to make it possible to script loading a malformed file and detect that this happened. Dymola returns true (success), and prints an error-message saying the model was bad. That is all. Just unexpected.

My point was just to say it is a minor change to allow a tool to deliver the functionality needed for a parsing test. I wanted to do it with 3 tools in a very short piece of code but don't know how Dymola works because I don't use it often. Maybe the model management add-on handles this. I wouldn't know. And I could probably do it in Dymola too by parsing output from the savelog command, but that somehow did not seem like a very stable solution to show in a small script (again, because I don't know when the tool would output such a string; also for warnings?).

Anyway, is there anyone who is against the concept of having a parsing testsuite along with the compliance suite?

**Comment by modelica-trac-importer** [comment]
**Comment by adrpo on 11 Oct 2013 13:04 UTC**
This is really not about how tools should be tested by the vendors.
The testing can be done internally using whatever method the vendors 
want.

This is really about trying to make tools more homogeneous 
by forcing them to be Modelica Specification compliant.
This in turn will make models/libraries more portable between 
tools without too much hassle.

I've spent countless hours fixing libraries so that 
they work as expected in several tools which have
slight incompatibilities. And most of the issues
arise from the fact that some of the tools are 
not really Modelica Specification compliant.

This will hopefully improve with the ModelicaCompliance 
testsuite but that covers only the semantic parts.

I do think that a small repository of models 
that should or should not parse would help 
vendors making their tools more compliant.

Truth is that one could just report these issues 
as bugs to the tool vendor. But if there is no
incentive for the vendor to fix the bug it will
never be fixed. And that will generate even more
incompatible libraries and models.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 11 Oct 2013 15:36 UTC**
Replying to [comment:12 sjoelund.se]:
...
> Anyway, is there anyone who is against the concept of having a parsing testsuite along with the compliance suite?

I doubt that anyone is against a correct parsing testsuite, assuming they have access to it. (Parsing is the easiest part of semantics.)

Originally syntax errors were even intended to be part of the semantic test-suite, but they were not straightforward to combine with having the compliance-status stored inside the compliance-models.

However, test-suites don't magically appear:

A compliance test-suite require that the tests are correct - otherwise it is meaningless; both constructing  and verifying them takes effort; as we have seen for the semantic test-suite developed for Modelica Association.

Who will pay for that?

And before MA takes on a new compliance project I would propose we first finish the current compliance projects (which were discussed e.g. at the last design meeting):
* Delivery of semantic test-suite to MA (after finalizing it).
* Simulation result comparison.

Then Modelica Assocation can decide on future projects like improving libraries, parsing test-suite, marketing, etc.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 11 Oct 2013 15:40 UTC**
Well, parsing is much simpler than semantics. Put a bunch of files in the should succeed pile and a bunch in the should not succeed pile. Done.

We have a bunch of models lying around that could not go into the compliance suite because they simply should not parse.

**Comment by modelica-trac-importer** [comment]
**Comment by troy on 14 Oct 2013 08:37 UTC**
We (ITI) would appreciate a test suite for checking Modelica parsing compliance since it would definitely help to detect errors in the implementation of the parser and to improve the diagnostics for syntactic errors.

I have one remark: In general a tool has no clue which version of the Modelica language specification was used when the Modelica file was written and ideally a tool should still accept models written for earlier Modelica versions (with earlier versions of the tool). A tool has different ways to handle this: either it contains different parsers for different versions of the Modelica standard or it contains one parser which also tolerates syntactic constructions which are not valid w.r.t. current Modelica but are still supported for legacy reasons. In the latter case the tool should warn about the usage of deprecated syntax. The strategy how one deals with different versions of a language standard is very tool dependent and I don't see any arguments why one strategy should be better than another one.

**Comment by HansOlsson** [comment]
It doesn't seem like a bad idea, but there doesn't seem much interest in constructing this test-suite.
Focusing on adding relevant cases to the semantic test-suite, https://github.com/modelica/Modelica-Compliance seems more urgent. 

Any syntactically legal can, of course, be added to that test-suite.
Syntactically illegal models could even be added, provided they are in a separate directory (as separate files.)
(Since the current idea is that the validity of models is stored inside the model; which requires the model to parse.)
