### ISSUE TITLE
Definition of built-in operators ticksInState()/timeInState() not clear

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1354]
**Reported by otter on 21 Nov 2013 08:08 UTC**
In Modelica 3.3 the following built-in operators are defined:

 **ticksInState**()
 Returns the number of clock ticks since a transition was made to the currently active state. This function can only be used in transition conditions of state machines not present in states of higher level state machines.

 **timeInState**()
 Returns the time duration as Real in [s] since a transition was made to the currently active state. This function can only be used in transition conditions of state machines not present in states of higher level state machines.

These definitions are not fully clear. Probably, what is meant: A state machine A may have states A1, A2, A3, ... In one of these states, say A2, another state machine B with states B1, B2, B3, .. is present. If there is a transition from B1 to B2 and the condition of this transition uses ticksInState(), then this is an error, because B is in A.

It seems not obvious, why such a restriction is present. Furthermore, if state machine B is constructed and later used in a state machine A, then suddenly an error will occur. This will look surprising for a user.

If possible, the definition should be changed to:

 This function can only be used in transition conditions of state machines. It returns the number of clock ticks since the source state of the respective transition was active. [_For example if there is a transition from state A1 to A2 and the condition is ticksInState() >= 5, then this transition will fire at the fifth clock tick after state A1 became active (if A1 is active at 4ms, 6ms, 8ms, 10ms, 12ms, then the transition will fire at 12ms)._]

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1354

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 18 May 2016 07:58 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 5 Aug 2016 05:59 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 11 May 2017 11:45 UTC**
To me this seems like an enhancement (generalizing the operators to hierarchical state machines) and not a defect.

What isn't clear is what is the desired behavior for ticksInState when re-entering a super-state, and examples would help. It seems logical that sub-states are ignorant of being sub-states, so ticksInState() is reset if the super-state is reset but continues from the previous value if the super-state is re-entered without reset.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 10 Jan 2018 08:22 UTC**

**Comment by HansOlsson** [comment]
> 
> 
> **Comment by hansolsson on 11 May 2017 11:45 UTC**
> To me this seems like an enhancement (generalizing the operators to hierarchical state machines) and not a defect.

And that was solved in the duplicate PR #2454
