### ISSUE TITLE
Remove symmetric operator

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1370]
**Reported by otter on 2 Dec 2013 10:50 UTC**
Discussion at the design meeting:
The built-in operator "symmetric(..)" seems to be confusing and should probably be removed in the future (the operator seem to be not used).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1370

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 2 Dec 2013 11:26 UTC**
I found references to symmetric in the following libraries:
```
$ grep -R symmetric\(  2>/dev/null | cut -d/ -f1 | sort -u
ModelicaCompliance 3.2
Modelica_LinearSystems2 2.3.1
ModelicaReference
ModelicaReference trunk
```

So only LinearSystems2 seems to use it.

**Comment by HansOlsson** [comment]
It doesn't seem as there is much interest in removing symmetric; even though isn't wildly used.
We have decided to improved its definition after this ticket, so I assume we intend to keep it.

**Comment by henrikt-ma** [comment]
Even though we just improved on it, I'd still say getting rid of it was a pretty good idea…
