### ISSUE TITLE
vectors of elements of graphical annotations

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1384]
**Reported by ahaumer on 17 Dec 2013 09:50 UTC**
Are vectors of elements of graphical annotations legal? 
e.g. a vector of Rectangles:
```
model Test
  parameter Integer n=3;
  parameter h[4]={-99 + j*10 for j in 0:n};
annotation(Icon(graphics={
  {Rectangle(
    pattern=LinePattern.None, 
    fillPattern=FillPattern.Solid,
    extent=DynamicSelect({{-99,99},{-60,-99}},
      {{-99,h[j+1]},{-60,hScale[j]}}),
    fillColor={95,95,95}) for j in 1:n}}));
end Test;
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1384

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 23 Oct 2015 09:10 UTC**
I read "The graphics is specified as an ordered sequence of graphical primitives, ..." in 18.6 that arrays of graphical primitives are not legal.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 23 Oct 2015 13:33 UTC**
I think they are legal, as all the examples in Chapter 18 show them that way. Yes, the specification states, "an ordered sequence of graphical primitives", but arrays are the only way we have to write such sequences in Modelica.

Furthermore, the non-normative text clearly suggests that this is syntactically an array, although a heterogeneous one (which is not valid outside of annotations).

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 23 Oct 2015 13:43 UTC**
To me using this variant is too limited.

It would allow you to define an array of one primitive, but you cannot combine it with other primitives: you can neither have functions returning the this heterogeneous list, nor use cat to simple combine them.

I would propose to not allow it for now (after all it is not an ordered sequence of graphical primitives - it is something that can be expanded into an ordered sequence of graphical primitives), and instead later try to handle it in a good way.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 23 Oct 2015 13:56 UTC**
Hans, I'm not sure what you mean by proposing to not allow it. It already<ins>is</ins> allowed, and there are thousands of annotations in the MSL that use it. It's just that we use array<ins>syntax</ins> to write "ordered sequences of graphical primitives" in annotations.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 23 Oct 2015 14:42 UTC**
Replying to [comment:4 stefanv]:
> Hans, I'm not sure what you mean by proposing to not allow it. It already<ins>is</ins> allowed, and there are thousands of annotations in the MSL that use it.

I agree that there are lots of models that use the allowed form:
```
annotation(Icon(graphics=
  {Rectangle(
    pattern=LinePattern.None, 
    fillPattern=FillPattern.Solid,
    extent=DynamicSelect({{-99,99},{-60,-99}},
      {{-99,h[j]},{-60,hScale[j]}}),
    fillColor={95,95,95})}));
```
but they do not use:
```
annotation(Icon(graphics={
  Rectangle(
    pattern=LinePattern.None, 
    fillPattern=FillPattern.Solid,
    extent=DynamicSelect({{-99,99},{-60,-99}},
      {{-99,h[j]},{-60,h[j]}}),
    fillColor={95,95,95}) for j in 1:4}}));
```
I cannot see that allowing reduction expressions here (and implicitly expanding them) was the intention - especially since every other non-literal value has to use DynamicSelect to give a static variant as well. 

In addition allowing an extra {} around Rectangle would mean that we not only have a heterogeneous array in terms of the "type" of the array elements, but also a heterogeneous array where some elements are scalars and some are arrays. I don't think we want such ambiguity for the future.

There are also other issues with the example, e.g. I would assume the default is one rectangle and that the number of rectangles could vary, which would require some new use of DynamicSelect.

I would propose we solve it in a proper way by having proper support for heterogeneous arrays.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 23 Oct 2015 15:04 UTC**
Ah, sorry. I did not notice the reduction expression in the original. I thought the question was simply whether arrays of graphic elements are allowed (which is pretty much what the text of the original question asked).

Given that, I agree with what you just wrote.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 31 Mar 2016 15:33 UTC**
The question is answered (about using reduction expressions - not just arrays in graphic elements). Would thus propose to close as 'worksforme'.

**Comment by HansOlsson** [comment]
Closing as previously proposed.
