### ISSUE TITLE
Shortcomings in the Modelica language for efficient media property calculations

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1419]
**Reported by johan&#x2e;windahl on 11 Feb 2014 08:10 UTC**
Hello,
attached is a document that summarizes shortcomings in the Modelica language for implementation of media models. 
The purpose is to make the Modelica community aware of these shortcomings and that it hopefully can lead to a discussion on how this issue could be solved. 
In the end of the document a suggested solution is presented which requires changes in the Modelica language.

Best Regards,
Johan Windahl

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1419

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 11 Feb 2014 08:25 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 11 Feb 2014 10:55 UTC**
Is it just me, or is the font in that pdf hardly readable?

> The fundamental problem is that a medium is defined as a package, i.e. a structure with no possibility to modify any of its data during simulation.

I don't buy that idea about objects. The proposal seems to add imperative features into a (yet) declarative language. And this in a way that looks awfully like Delphi or early versions of C++. I understand that people coming from an imperative background see that as "efficient", but the language paradigma does not influence neither the ability to implement iterative algorithms nor their effectiveness. On the other hand a declarative language brings safety and simpler implementations.

That being said, objects bring in a lot of requirements: memory management (garbage collection), side-effects, order-of-evaluation concerns, probably something like exceptions, etc.

My proposal would be to:

1. **If** Modelica users need an imperative language, we should blow up the external C-interface instead of trying to specify our own poor man's version of C++. Everything your use case required could be done via a C-module and some extensions to the standardized interface.
2. **When** that approach has proven useful (say there are more then 10 new such C-modules in the MSL), we might consider implementing the ```object``` proposal by a clear and precise translation into such a C-module, i.e. we would define a **second** language with the whole purpose to extend Modelica in a convenient way.

> That implements a solver callback interface. Used to update iteration start values in a controlled way

This particular interface extension seems like a good idea indeed. I guess it should be fairly simple to implement and has a lot of other use cases.

**Comment by modelica-trac-importer** [comment]
**Comment by otter on 11 Feb 2014 11:13 UTC**
Replying to [comment:2 choeger]:
> Is it just me, or is the font in that pdf hardly readable?

Hm. Everything is fine for me (inspecting with Adobe Reader).
  
> 
> > The fundamental problem is that a medium is defined as a package, i.e. a structure with no possibility to modify any of its data during simulation.
> 
> I don't buy that idea about objects. The proposal seems to add imperative features into a (yet) declarative language. And this in a way that looks awfully like Delphi or early versions of C++. I understand that people coming from an imperative background see that as "efficient", but the language paradigma does not influence neither the ability to implement iterative algorithms nor their effectiveness. On the other hand a declarative language brings safety and simpler implementations.

The goal of this project is to improve and extend Modelica.Media and there is a budget for it (within the CleanSky project). Answering to implement an improved Modelica.Media in "C" or "C++" is not very helpful (and they explain that they have analyzed the usage of ExternalObjects and that this has a lot of severe limitations). I quickly looked through the proposal and agree that it is quite far from current Modelica. However, it might be that one can reach similar goals with less drastic enhancements. The important point is to understand the requirements and limitations of Modelica for Media implementations. 

We should discuss this ticket at the next Modelica Design Meeting in Lund (therefore changed Milestone to Design82)

**Comment by modelica-trac-importer** [comment]
**Comment by kurzbach on 11 Feb 2014 11:32 UTC**
What's about a `last(x)` operator (like `pre()`)?
It could return the value of x from the last valid step or x.start at initialization time.
But probably it wouldn't be allowed to call it in a function (also like `pre()`).

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 11 Feb 2014 11:51 UTC**
Spec sec 11.1.2 says:
> A non-discrete variable is initialized with its start value (i.e. the value of the start-attribute).
> ...
> in order that an algorithm section cannot introduce a "memory"

And for these algorithms, it is useful to not initialise as such, instead keeping memory... And the start-value is of course a parameter, so you cannot fool a tool to initialise with something else.

There is a problem with allowing something like `pre` or `last` for continuous-time variables though: it is very easy to write something produces different results depending on solver settings. So it is easy to shoot yourself in the foot, and it is why this is restricted in the first place (especially `last(time)`).

> But probably it wouldn't be allowed to call it in a function (also like `pre()`).

That's not a problem: pass the start-values as inputs to the function.

**Comment by modelica-trac-importer** [comment]
**Comment by c&#46;schulze on 11 Feb 2014 12:49 UTC**
Replying to [comment:2 choeger]:
> My proposal would be to:
> 
> 1. **If** Modelica users need an imperative language, we should blow up the external C-interface instead of trying to specify our own poor man's version of C++. Everything your use case required could be done via a C-module and some extensions to the standardized interface.

I don't see a way to implement something that has a constructor and can be instantiated in functions - which would be required.
- In most cases external objects are static objects.
- Calculation of start values and parameters is only possible with a static object
- It is complicated to implement a library that shares the same interface for external and modelica functions, particularly if you want to have a convenient user interface.

Since we have a C-Implementation, I know that it is not equivalent.

A better integration of external source would be important for Modelica in general.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 12 Feb 2014 09:22 UTC**
Replying to [comment:6 c.schulze@…]:
> Replying to [comment:2 choeger]:
> I don't see a way to implement something that has a constructor and can be instantiated in functions - which would be required.

It's possible.

> - Calculation of start values and parameters is only possible with a static object

That absolutely is a tools issue and comes from the way most "compilers" work. AFAIK omc **does** that for external objects.

> A better integration of external source would be important for Modelica in general.

As I said, I agree that the C-interface needs a lot of improvments. What I **don't** agree with is just another single-purpose massive change to the language. In the end, who does the work on the specification? Who writes up how memory management works in Modelica? Who does a evaluation order definition? We have had a massive quality problem IMO in the last years and the spec changed alot just for the purpose of clarification and bugfixes. I don't see any convincing reason to open up yet another construction site that never will be finished. 

I am not against expansion of Modelica, and if someone wants to make a Java or Smalltalk or even Python clone out of it, it's not a big issue for me, but I **strongly** suggest that we do not expand the language based on a design that cannot be executed (i.e. exists only on paper). 
If we change the language before we have a working external solution, we don't even know precisely what the scope is. Let alone test cases, examples etc.

I also know that it might seem painful to first expand the C-interface when the longterm goal is a tight integration anyway, but there will be other use cases down the road, and they will benefit from the C-interface.

**Comment by modelica-trac-importer** [comment]
**Comment by johan&#x2e;windahl on 18 Feb 2014 11:29 UTC**
It’s good that this will be discussed at the next design meeting, I will try to be there.
I am aware that the suggestion is quite far from how Modelica is defined today. And I agree with Martin that the most important part is that we have a discussion about requirements and limitations. If we can find another way to solve these issues it would be great.

**Comment by HansOlsson** [comment]
Is this still relevant?

I added the attachment from trac just in case.
[ShortComingsMedia.pdf](https://github.com/modelica/ModelicaSpecification/files/4199300/ShortComingsMedia.pdf)
