### ISSUE TITLE
Initialization of Function Outputs

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1440]
**Reported by jfrenkel on 11 Mar 2014 14:49 UTC**
Regarding to Specification I could only find in Chapter 12 how to initialize local variables in functions but not how to initialize output variables in functions. Maybe I simple not found it but I thinks it should be clear defined to avoid unexpected behavior.

In the past I reported some tickets about usage of uninitialized variables in functions.
#1412
#1425
#1427
#1428
#1429
#1430

* If output variables of functions are initialized automatic (type default value) this tickets may should be interpreted again. 
* If output variables of functions not automatic initialized I have a list of MSL functions return (not in all cases) undefined values for some outputs. (For example #1422)

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1440

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 12 Mar 2014 05:50 UTC**
If you read 12.4.4 it becomes clear that unbound output formal parameters also have undefined value.

Also, if you want to be picky about uninitialized things, many of the external lapack functions called do not always modify the output. So if you don't initialize the output (to 0 or zeros) **_and_** call it the function using the variable as output you should get undefined results. I think most tools instead initialize to 0 for external functions to avoid problems, but the MSL has some of these lapack functions that could be fixed also at the Modelica source.

**Comment by modelica-trac-importer** [comment]
**Modified by frenkel on 13 Mar 2014 09:56 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 13 Mar 2014 13:20 UTC**
Replying to [comment:2 frenkel@…]:
> So if most of the tools initialize local variables and output variables to "0" (default values of the type) (what also for me seems to be the most secure practical solution) change the text in the specification to something like:

To me there are two related issues:
* Using the variable before it is set to zero.
* Using the variable before it has the right value.
Using 0 default only corrects the first issue, but e.g. #1422 was an error of the second kind - and by initializing everything to zero we hide those kind of errors.

Compilers and tools normally have good tools for finding these issues (both statically - although a bit pessimistic and dynamically for specific test-cases).

Theoretically there is the possibility that any value will work and give the same result - it usually fails for NaN.

The pragmatic solution would be to state that using unitialized values is wrong, but it is recommended to initialize them to 0 - or the closest allowed value.

(The reason for the extra text is that 0 is not always allowed by min.)

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 8 Apr 2014 11:14 UTC**
Your check detects false positives (I stopped after 4 functions; all the ones I checked were false positives):
- Modelica.Utilities.Files.createDirectory.existDirectory
- Modelica.Utilities.Files.loadResource
- Modelica.Utilities.Examples.expression.primary
- Modelica.Utilities.Examples.readRealParameter

`readRealParameter` I would fix anyway to help static analysis. Note that you either need an annotation for noreturn function or analyse all called functions to determine if they never success (`Strings.syntaxError`, etc never return).

Or you use a more conservative method (if any branch defines the variable, treat it as defined).

**Comment by HansOlsson** [comment]
This seems like a duplicate of #1708
