### ISSUE TITLE
Should Operator Overloading Perhaps Define '=' Too?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1466]
**Reported by stefanv on 23 Apr 2014 19:20 UTC**
Currently, operator records allow one to define the equality comparison operator `'=='`. This means (using Complex as an example), one can write:

```mo
Complex a, b;
...
if a == b then ...
```

And, because operator overloading attempts to apply type conversions, one can also write:

```mo
Complex a;
Real r;
...
if a == r then ...
```

The appropriate Complex constructor, if it exists, will be called on r.

However, the current mechanism does not allow one to write:

```mo
Complex a;
Real r;
...
a = r;
```

Furthermore, this means that `x = y` (where x and y are of the same operator record type) uses a different definition of equality for equation solving than `x == y` does for equality testing.

I see two possible solutions to this problem:

1. We add `'='` to the list of "operators" that can be overridden.

2. A tool must rewrite `x = y` as `x - y = '0'()` where x and y are of compatible types, and `'0'()` is the call to the `'0'` constructor of the result type.  

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1466

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 17 Jun 2014 09:11 UTC**
Another possibility would be that we for an equation x=y check if it is type-compatible, and if not we use similar rule as 14.4 item 3 to call a constructor for either x or y to make them of compatible type.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 17 Jun 2014 15:04 UTC**
Jesper: last idea has a slight issue e.g. for polar representation of complex where angle is only defined mod 2\*pi.

Agreement to postpone since a change.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 28 Apr 2015 14:58 UTC**
Just in case it isn't an obvious result of accepting the above proposal, I want to add that the same thing should happen within modifications. I.e., the following should work,

```mo
    Modelica.ComplexBlocks.ComplexConstant cc(k=3.14);
```

automatically calling the Real-to-Complex constructor on `3.14`.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 16 Sep 2016 13:15 UTC**
Replying to [comment:2 hansolsson]:
> Jesper: last idea has a slight issue e.g. for polar representation of complex where angle is only defined mod 2\*pi.
> 
> Agreement to postpone since a change.

This is one example of the more general issue that an operator record can have a non-minimal representation. We currently assume that if we have an operator record with n Real elements equality gives n equations. 

That is not the case for e.g. 3x3 rotation matrices: there are only 3 residuals, and the constructor only takes 3 independent real inputs. Alternatively we can view this as having 6 real constraints on rotation matrices (allowing mirroring is another complication). Note that rotation matrices do not have subtraction defined, indicating that the second proposed solution will not work for them.

Replying to [comment:3 stefanv]:
> Just in case it isn't an obvious result of accepting the above proposal, I want to add that the same thing should happen within modifications. I.e., the following should work,
> 
> ```mo
>     Modelica.ComplexBlocks.ComplexConstant cc(k=3.14);
> ```
> 
> automatically calling the Real-to-Complex constructor on `3.14`.

Agreed. Note that modification handling is simpler - since the direction of the conversion is given, whereas `a=b` doesn't indicate whether a or b (or both?) should be converted.

**Comment by HansOlsson** [comment]
This is a complex issue, to handle operator record classes with non-minimal representation. It is not clear that there is any interest in this enhancement for now.
