### ISSUE TITLE
Issues to import FMUs in a portable way into Modelica (such as fmi2CompletedIntegratorStep)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1626]
**Reported by otter on 10 Dec 2014 13:15 UTC**
FMUs are imported into Modelica by defining a wrapper model in Modelica in which the FMUs external C-Code is called using an external object for the FMU. The generated Modelica code for an FMU should be according to Modelica 3.3. This is, however, not possible, and therefore importing an FMU into Modelica leads to a tool specific, non-portable, Modelica code (the Modelica model that utilizes the FMU can only be simulated by the tool that imported the FMU). This is unsatisfactory. In this ticket, all portability issues with FMI shall be discussed.

**Issue 1: fmi2CompletedIntegratorStep**
This fmi function must be called after a successful step of an integrator. This cannot be defined with Modelica 3.3. Both Hans and Torsten had made proposals in the past how to fix this, but I did not find them anymore. Please, can you provide them (I vaguely remember to specify an additional ExternalObject function, besides constructor and destructor, add completedIntegratorStep that must be called for every successful integrator step, if provided).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1626

**Comment by modelica-trac-importer** [comment]
**Comment by thiele on 8 May 2015 07:31 UTC**
The following is copied from the discussion on the mailing list (including the reply from Martin Otter).

Some potential use cases for the new functions for external objects that come to my mind:

- completedIntegeratorStep: Might be used for injecting real-time synchronization code into a Modelica model.
- enterEventMode: Maybe useful to ensure that external inputs (e.g., from sensors or buses) are read at the beginning of a "sample" event
- enterContinuousTimeMode: Could be used to write external outputs after a "sample" event has been processed

As I understand it there would be probably a call to "completedIntegeratorStep" before any call to "enterEventMode", or is that assumption wrong?
> completedIntegratorStep MUST be called before enterEventMode. I will include this missing requirement into the MCP. Also between enterEventMode and enterContinuousTimeMode, completedIntegratorStep MUST NOT be called.

Are there any intricacies if one would generate a FMU from a Modelica model that contains an external object that uses this new functions?

> No. If the optional functions like completedIntegratorStep are defined in the Modelica definition of an ExternalObject, the tool knows that it has to call these functions in particular situations. If these functions are called INSIDE an FMU, the simulation environment does not know about them and then these C-functions are just as any other C-functions, so (as long as the call inside the FMU makes sense), there is no issue.

**Comment by modelica-trac-importer** [comment]
**Modified by adrpo on 8 May 2015 08:02 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by c&#46;schulze on 8 May 2015 14:10 UTC**
The three above mentioned functions are a great extension to the external object, but I want to add another aspect.

The ModelicaError-functions cannot be accessed from an external dll since they are not defined in the dll. It would be great if external libraries could get access to these functions before the first call. Otherwise it will be impossible to output error messages correctly. This applies to external objects and all other external functions. 

Currently I use the workaround below. The pointers to the ModelicaError-function is passed to the external library. But I have to make sure that this function is called before any other function is called.


```

function redirectModelicaFormatMessage
input Real y=0;
output Integer x;
  external"C" x=TILMedia_redirectModelicaFormatMessage_wrapper() annotation (Include="
#ifndef TILMEDIAMODELICAFORMATMESSAGE
#define TILMEDIAMODELICAFORMATMESSAGE
#ifdef DYMOLA_STATIC
int TILMedia_redirectModelicaFormatMessage(void* _str);
int TILMedia_redirectModelicaFormatError(void* _str);
...
int TILMedia_redirectModelicaFormatMessage_wrapper(){
  TILMedia_redirectModelicaFormatMessage((void*)ModelicaFormatMessage);
  TILMedia_redirectModelicaFormatError((void*)ModelicaFormatError);
...
  return 0;
}
#endif
#endif
",Library="TILMedia331Dev");

end redirectModelicaFormatMessage;

```

I have the same problem with the location of the resources folder, but until now I don't have a solution for that problem.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 8 May 2015 17:49 UTC**
Replying to [comment:9 c.schulze@…]:
> The ModelicaError-functions cannot be accessed from an external dll since they are not defined in the dll.

That's just a tool issue. Ask your tool vendor to export the symbols.

> I have the same problem with the location of the resources folder, but until now I don't have a solution for that problem.

What problem is this? That the dll is not copied to the location of the executable? Sounds like another tool issue.

**Comment by modelica-trac-importer** [comment]
**Comment by c&#x2e;schulze on 8 May 2015 18:04 UTC**
Replying to [comment:10 sjoelund.se]:
> Replying to [comment:9 c.schulze@…]:
> > The ModelicaError-functions cannot be accessed from an external dll since they are not defined in the dll.
> 
> That's just a tool issue. Ask your tool vendor to export the symbols.

I don't think that it is a tool issue. If I have to import a tool specific export of the symbols, my external library is tool specific. I'd like to avoid this.

> 
> > I have the same problem with the location of the resources folder, but until now I don't have a solution for that problem.
> 
> What problem is this? That the dll is not copied to the location of the executable? Sounds like another tool issue.

I'm not referring to the external library itself. I need the localtion of the Resources folder to load additional data files. So for instance if I implement media properties from refprop in my external library, I have to tell Refprop where it should load the FLD-Data files from. So currently implementing Refprop in a "portable" FMU is impossible.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 8 May 2015 18:12 UTC**
That's also just a tool issue. If you have a [loadResource()](https://build.openmodelica.org/Documentation/Modelica.Utilities.Files.loadResource.html) call, the tool can mark this up and copy both the resource and how to construct an absolute path at run-time to actually load the data.

**Comment by modelica-trac-importer** [comment]
**Comment by c&#x2e;schulze on 8 May 2015 18:38 UTC**
To forward this path to the external library I'd have to pass this string to every function call that could be first in the causality (e.g. _density_pT(1e5,300,"Refprop.CO2.FLD",mygetpathfunction())_). This would be possible using a default value for the last argument. But constructing and passing a string to every function call in a library seems awkward and inefficient to me.

On the other side this could be fixed by the tools with a single call to the external library after loading the dll. This call could include links to the above mentioned ModlicaError functions. IMHO the better solution. Since we (TLK) already have implemented terrible tool specific workarounds for both, it is not our libraries I care about.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 9 May 2015 10:13 UTC**
I agree that it would be a good idea to have an explicit initialization point for external libraries. That way, Modelica could be somewhat more specific that just "a C-symbol has to lie around here somewhere". However, that would probably require us to standardize on how external libraries are defined (i.e. inside the model) so we could express in Modelica that a certain library should be loaded (once). Currently we specify relationships between Modelica symbols and C-symbols, thats a different story.

**Comment by modelica-trac-importer** [comment]
**Comment by pharman on 11 May 2015 18:43 UTC**
Replying to [comment:6 otter]:
> Martin will write a Modelica Change Proposal (state: In development).

I'm interested in the motivation in standardisation of this feature, is there an intention for the MA to publish a library for consuming FMUs within Modelica?


> Tool vendors will test with prototype implementations.

Doing this would benefit from having a test model in ModelicaCompliance, is there an existing simple example that would serve this purpose?

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 11 May 2015 18:47 UTC**
Replying to [comment:15 pharman]:
> Doing this would benefit from having a test model in ModelicaCompliance, is there an existing simple example that would serve this purpose?

I suppose it would have to be a source FMU in that case. Do many Modelica tools support source FMU's?

**Comment by modelica-trac-importer** [comment]
**Modified by anonymous on 25 Jun 2015 06:54 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 25 Jun 2015 06:55 UTC**
Here is another incompatibility, although not a severe one.  (I know that there is more than one issue already in this ticket, but the only sensible way of numbering is to continue from the last numbered issue.)

**Issue 2: Variability of nominal values for states**
In FMI, the nominal values for state variables have discrete variability, whereas nominal values are attributes in Modelica.

For some applications it can be possible to model changing nominal values in Modelica by using auxiliary variables that always have nominal value 1.0, together with discrete variables that model the nominal values.  However, this method obscures the initialization of FMU states.

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 5 Oct 2015 09:56 UTC**
**Issue 3: Integer range of FMI value references vs extern "C" interface**
In FMI the range for value references is that of an unsigned 32 bit integer.  In Modelica, the extern "C" interface maps Modelica `Integer` to `int` in C, which on most modern platforms is a signed 32 bit integer.  This means that the extern "C" interface cannot be used in the natural way for many FMU wrapper functions, such as `fmi2GetReal`.

The ugly workaround for this is not not represent the FMI value references as `Integer` in the Modelica FMU wrapper, but to use something like a `String`, a `Real`, or an `(Integer, Integer)` struct instead.  It would be much better if there was an external language interface in Modelica that allowed an FMI value reference to be represented as a single `Integer`.

One possible solution would be to add a new external language, say `extern "FMI"`, where Modelica `Integer` is mapped to `int64_t` (to make it more generally applicable than `uint32_t`), and Modelica `Boolean` is mapped to `char`.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 5 Oct 2015 10:07 UTC**
@henrikt: You could pass external objects to the external FMI function. A simple malloc in the constructor and free in the destructor. You could even pass the value reference as a string and atol it in the external code. But I suspect this would be slow. You could of course have two external functions: one taking two integers in case Modelica tools are unable to handle the length of the reference.

Or you could simply use the corresponding signed number `Integer a = -5 /* 4294967291 */;` and pass that instead. The C-code can convert it to unsigned easily:

```c
int main()
{
  int a = -5;
  unsigned int b = *(unsigned int*)(&a);
  printf("%d %u\n", a, b);
}
```

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 5 Oct 2015 10:21 UTC**
Replying to [comment:20 sjoelund.se]:
> Or you could simply use the corresponding signed number `Integer a = -5 /* 4294967291 */;` and pass that instead. The C-code can convert it to unsigned easily:
> 
> ```c
> int main()
> {
>   int a = -5;
>   unsigned int b = \*(unsigned int\*)(&a);
>   printf("%d %u\n", a, b);
> }
> ```

Or just:

```c
 int main()
 {
   int a = -5;
   unsigned int b = (unsigned int)(a);
   printf("%d %u\n", a, b);
 }
```
That cast is perfectly ok; whereas conversion in the other direction is implementation-defined (usually it just works). Thus it seems possible to work around this issue in the importing tool (the number -5 doesn't have to constructed by a simple cast).

However, having more general variants for mapping in the C-interface would be good in general and specifically e.g. for embedded targets.

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 7 Oct 2015 07:33 UTC**
Sure, the `reinterpret_cast` approach is another feasible workaround, but it is a low-level technique that doesn't fit at all into the otherwise high level of abstraction in Modelica.

Further, the `reinterpret_cast` approach doesn't solve the incompatible mapping of `Boolean`, which would be solved elegantly with `external "FMI"`.  (Although, at the same time as it solves the mapping of `Boolean`, it would introduce similar issues for `Integer`.)

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 7 Oct 2015 08:23 UTC**
Replying to [comment:22 henrikt]:
> Sure, the `reinterpret_cast` approach is another feasible workaround, but it is a low-level technique that doesn't fit at all into the otherwise high level of abstraction in Modelica.

To be clear: the `(unsigned)(a)` - is a `static_cast` in C++ and is not really low-level, it is defined as the result mod 2<sup>32</sup> (which just happens to have the same bit-pattern in two’s complement representation - which happens to be almost every computer).

The `*(unsigned*)(&a)` seems to be a `reinterpret_cast`, but I am not sure if it is legal C/C++ - and in either case the result will depend on the computer architecture (but will likely work as expected on almost all computers). 
I agree that we should avoid that, and especially avoid mixing these two variants.
(I didn't realize this difference before.)

> Further, the `reinterpret_cast` approach doesn't solve the incompatible mapping of `Boolean`, which would be solved elegantly with `external "FMI"`.  (Although, at the same time as it solves the mapping of `Boolean`, it would introduce similar issues for `Integer`.)

I agree that it would be good with a more well-defined mapping - it's just that it isn't **that** blocking.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Oct 2017 10:02 UTC**
To discuss at meeting. Some should be possible to trivially close.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2017 07:41 UTC**
MCP in #1727

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 24 Oct 2017 13:41 UTC**
I recall that a working group was set up for this at the meeting, but I can find it neither in Trac nor in the minutes. One of my colleagues at Maplesoft would like to participate.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 24 Oct 2017 14:31 UTC**
Noted. And the minutes are not yet complete - I got carried away with the unit-checking.

**Comment by modelica-trac-importer** [comment]
**Modified by stefanv on 25 Oct 2017 13:30 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 10 Jan 2018 08:23 UTC**

**Comment by HansOlsson** [comment]
This has been changed into an MCP ticket, #1727 - so closing this as duplicate to simplify overview.
