### ISSUE TITLE
Lookup of base classes

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1645]
**Modified by choeger on 22 Jan 2015 10:13 UTC**
According to section 5.6.1 the lookup of baseclasses defined in the local scope should not depend on extends classes further down the scope, i.e. the following class would be illegal:

```mo
class A 
  class D
    class C Real x; end C;
  end D;
  class B
    extends D; 
  end B;

  extends B.C;
end A;
```

My reasoning is, that B.C cannot be found until the flattening of B has happened which violates the sentence:

> It should be possible to flatten all extends-clauses in a class before inserting the result of flattening.

But what about "outside" super classes?

```mo
class D
  class C Real x; end C;
end D;

class B
  extends D; 
end B;

class A 
  extends B.C;
end A;
```

Is it allowed to extend from a class that is inherited? 

----

**Reported by choeger on 18 Jan 2015 12:07 UTC**
According to section 5.6.1 the lookup of baseclasses defined in the local scope should not depend on extends classes further down the scope, i.e. the following class would be illegal:

```mo
class A 
  class D
    class C Real x; end C;
  end D;
  class B
    extends D; 
  end B;

  extends B.C;
end A;
```

My reasoning is, that B.C cannot be found until the flattening of B has happened which violates the sentence:

> It should be possible to flatten all extends-clauses in a class before inserting the result of flattening.

But what about "outside" super classes?

```mo
class D
  class C Real x; end C;
end D;

class B
  extends D; 
end B;

class A 
  extends B.C;
end A;
```

Is it allowed to extend from a class that is inherited?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1645

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 22 Jan 2015 10:13 UTC**
My confusion comes from the sentence quoted above. If it should be possible to flatten all extends-clauses before inserting the result of flattening, that means that the extends clauses "see" only the lexical definitions, right?

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
