### ISSUE TITLE
Lookup elements in base classes

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1649]
**Reported by choeger on 22 Jan 2015 10:31 UTC**
Unfortunately, I wasn't able to provide a smaller test model, sorry for the inconvenience.

```mo
package test
  model F model D type S = Integer; end D; end F;
  model D type S = Real; end D;
  type S = Boolean;
  model A
    extends B.C;
    extends F;
    
    model B
      extends D;
      model C
        type T = S;
      end C;
    end B;
  end A;

  A.T t;
end test;
```

In the above model, when flattening `test.A` section 5.6.1 states that `test.A.B.C` should be flattened and inserted into `test.A`. By definition in section 5.2 `test.A` is partially flattened during this process. 

So to lookup `S`, two questions need to be answered:

1. Has `extends D` already been merged into `test.A.B`?
2. If yes, has `extends F` already been merged into `test.A`?

If both questions are to be answered "no", the result should be `Boolean t`, if 1. has been answered "yes" and 2. has been answered "no" the result should be `Real t`, otherwise the result should be `Integer t`.

The specification does not seem to care about the order of extends clause flattening, but only demands that the **lookup** be well-defined for each extends clause alone.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1649

**Comment by modelica-trac-importer** [comment]
**Modified by choeger on 22 Jan 2015 10:32 UTC**

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
