### ISSUE TITLE
Are Class Types recursive?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1654]
**Reported by choeger on 30 Jan 2015 12:10 UTC**
See for example `Modelica.Media.Air.MoistAir.PsychrometicData` which contains `Modelica.Media.Air.MoistAir.PsychrometicData.Medium` which defaults to `Modelica.Media.Air.MoistAir`.

So the following type can be found?

`Modelica.Media.Air.MoistAir.PsychrometicData.Medium.PsychrometicData.Medium.PsychrometicData.Medium`

If so, this means, section 6.2.2 can never be implemnted as, the Class Type contains:

> For elements that are classes: Inheritance interface or class type of the element.

So to compute the Class Type of `Modelica.Media.Air.MoistAir`, one needs to compute the Class Type of `Modelica.Media.Air.MoistAir` ...

It is, of course, possible to define recursive class types. But the specification does not give any hint on how to do so and on what the rules are for a compatible class type. 

In the above example, to create a compatible `Medium`, would that  `Medium` contain `MoistAir` as an element?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1654

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 14 Mar 2017 13:54 UTC**
These issues should be resolved with the new flattening.
If that is not the case they need to reference an issue in the new description.

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
