### ISSUE TITLE
Scope of redeclarations-as-modifications

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1680]
**Reported by choeger on 12 Mar 2015 09:03 UTC**
In #1458, the discussion came up on how to evaluate redeclarations in extends-clauses. In particular, it seems that they are two conflicting views on what the scope of the redeclaration's right-hand-side is.

```mo
class A
  replaceable class R end R;
end A;

class S type T = Real; end S;

class B 
  extends A(redeclare class R = S);
  extends C;
  //What is B.R.T? C.S.T or .S.T?
end B;

class C
  class S type T = Integer; end S;
end C;
```

Obviously, there are two evaluation strategies, that can be applied here: by-name and by-value. By-name would take the class-level-expression "S" and put it literally into the superclass. Hence it would evaluate to B.S (since it's scope is that of B + all superclasses). By-value would evaluate S **first** and merge the result into the superclass. Hence it would evaluate to the global class .S.

I always thought the by-value strategy would have to be used here, since otherwise the short-style redeclaration could simply be rewritten into a normal element-style redeclaration. 

Could we please clarify and update the specification? In case of the call-by-name strategy, could we also please consider specification by rewriting, since it would make implementation so much easier. 

As an additional bonus: In case of call-by-name, recursive evaluation becomes easy (as it already is in the element-redeclaration case). Could we update the specification on how to handle that?

Note: I consider this a defect since the specification seems to be unclear about the result of class-instantiation.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1680

**Comment by modelica-trac-importer** [comment]
**Comment by perost on 12 Mar 2015 09:14 UTC**
For what it's worth, both Dymola and OpenModelica say B.R.T = C.S.T = Integer.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 12 Mar 2015 09:49 UTC**
Replying to [comment:1 perost]:
> For what it's worth, both Dymola and OpenModelica say B.R.T = C.S.T = Integer.

JModelica.org also gives that result. We evaluate the S access in the redeclare after resolving the extends.

**Comment by modelica-trac-importer** [comment]
**Comment by kurzbach on 12 Mar 2015 10:19 UTC**
Same in SimulationX.

**Comment by modelica-trac-importer** [comment]
**Comment by pharman on 12 Mar 2015 10:30 UTC**
Replying to [comment:1 perost]:
> For what it's worth, both Dymola and OpenModelica say B.R.T = C.S.T = Integer.

So does the CyDesign compiler

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 12 Mar 2015 13:27 UTC**
MapleSim too. So we should clarify the specification such that we are all wrong.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 12 Mar 2015 14:18 UTC**
An interesting question is what happens if we reverse the order of the two extends clauses in B. It should, of course, make no difference, but does it in any tool?

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
