### ISSUE TITLE
Instantiate array of array type with modifier

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1687]
**Reported by perost on 30 Mar 2015 10:25 UTC**
Consider this model:
```mo
model M
  type A = Real[4](unit = {"m3/d", "g/m3", "g/m3", "g/m3"});
  input A[3] a3;
end M;
```
A normal user would probably expect this to work, yielding a flat model like:
```mo
model M
  Real a3[1, 1](unit = "m3/d");
  Real a3[1, 2](unit = "g/m3");
  Real a3[1, 3](unit = "g/m3");
  Real a3[1, 4](unit = "g/m3");
  Real a3[2, 1](unit = "m3/d");
  ...
end M;
```
However, both Dymola and OM treats this model as though it's equivalent to:
```mo
model M
  input A[3, 4] a3(unit = {"m3/d", "g/m3", "g/m3", "g/m3"});
end M;
```
This is not a valid model since the type of the modifier doesn't match the type of a3, so both tools give a warning or error about the modifier on A. It seems odd to me to have types which can't be used to define arrays, but the specification doesn't seem to say how this case should be handled.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1687

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
