### ISSUE TITLE
Granularity of local base classes

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1696]
**Reported by choeger on 15 Apr 2015 10:20 UTC**
The specification seems to lack a paragraph about locally defined base classes. In the following example:

```mo
package test

type T = Integer;

class A
    extends B.C;
    class B
      type S = T;
      class C
        type T = Real;
      end C;
    end B;

    B.S s;
  end A;

end test;
```

is `test.A.B` a local base class of `test.A` or just `test.A.B.C`?

Is result of instantiating `A.s`:

* `Integer s` when it is considered a base class (hence the superclasses are not taken into account) 
* An error (by the same reasoning as  above but after inheritance the result differs)
* `Real s` because `B` is not a local base class. If so, what is the surrounding class of `B.C`?

Personally, I'd say that the result should be `Integer s` (because that error thing is really hard to detect/depends on dynamic semantics). However, what did tool vendors implement?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1696

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 15 Apr 2015 11:06 UTC**
JModelica.org gives `Real s`, because we look up the base class before looking up anything else. Then, when looking up T from `type S = T`, we look for a T in the surrounding class of B - i.e. A, including its base classes. If we hadn't found it there then we would have continued looking in `test` and found the definition that binds it to Integer. The surrounding class of C is of course B, but we only need that when looking up names used _in_ C, i.e. only `Real`.

**Comment by modelica-trac-importer** [comment]
**Comment by perost on 15 Apr 2015 12:46 UTC**
It seems to me that the spec does specify this case, see 5.3.1 Simple Name Lookup:
>This lookup in each scope is performed as follows
>  \* Among declared named elements ... of the class (including elements inherited from base-classes).

So in B we should look up T, which is not found. We then go to the next scope which is A, and look for T among the declared and inherited elements, and find it among the inherited elements.

**Comment by modelica-trac-importer** [comment]
**Comment by kurzbach on 15 Apr 2015 12:54 UTC**
SimulationX gives also `Real s`, in the same way as JModelica does.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 15 Apr 2015 13:02 UTC**
It is not so simple. The spec also says that to flatten `A` you flatten the base classes without taking into account the inheritance. To flatten `A.B.C` you (partially) flatten `A.B`. So you end up with an endless recursion.

The problem is: A (local) base class might use its scope, which in turn might use the inheritance "above".

This loop is apparent here:

```mo
package test

type T = Integer;

class A
    extends B.C;
    class B
      type S = T;
      class C
        type T = S;
      end C;
    end B;

    B.S s;
  end A;

end test;
```
 
If I attempt to do what JModelica and SimulationX appear to do here, the lookup of `T` in the right hand side of `S` yields "in the baseclass `B.C`", here the lookup of `S` on the rhs of `T` yields "outside in the scope of `A.B`", ad infinitum.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 15 Apr 2015 13:34 UTC**
Replying to [comment:4 choeger]:
> It is not so simple. The spec also says that to flatten A you flatten the base classes without taking into account the inheritance. To flatten A.B.C you (partially) flatten A.B. So you end up with an endless recursion.

Why do you flatten A.B? You only need A.B.C.

Also, we only stated what our tools do, not that it necessarily was correct behavior. 

JModelica.org doesn't actually _do_ partial flattening - it works differently, but tries to give the same behavior. Thus the corner cases that are hard to describe as partial flattening give straight-forward answers for us, while other things like models with recursion to a limited depth are problematic for us. There have been quite a few tickets where the rules for partial flattening come in question. Maybe we would be better off describing the flattening process in another way?

> If I attempt to do what JModelica and SimulationX appear to do here, the lookup of `T` in the right hand side of `S` yields "in the baseclass `B.C`", here the lookup of `S` on the rhs of `T` yields "outside in the scope of `A.B`", ad infinitum.

Well... if you introduce a loop where `T = S` and `S = T` then of **course** there is a loop. You could just as easily have written the following for the same result:
```mo
model A
  type T = S;
  type S = T;
  S s;
end A;
```

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 15 Apr 2015 13:51 UTC**
Replying to [comment:5 jmattsson]:
> Why do you flatten A.B? You only need A.B.C.

Because it is in the spec. To lookup `S` in `A.B.C` you lookup `S` in the flattened enclosing classes.
 
> Also, we only stated what our tools do, not that it necessarily was correct behavior. 

Since my point is that correct behavior is not defined, that is to be expected ;).

> Well... if you introduce a loop where `T = S` and `S = T` then of **course** there is a loop. 

The loop does not exist, if you consider `A.B` a local base class. In that case `T` and `S` are found ignoring the extends-clause. (thus the result is Integer).

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 15 Apr 2015 13:58 UTC**
Replying to [comment:6 choeger]:
> The loop does not exist, if you consider `A.B` a local base class. In that case `T` and `S` are found ignoring the extends-clause. (thus the result is Integer).

OK, though I still say there was no loop in the original example. The change that "made the loop apparent" _introduced_ the loop (that possibly isn't there, depending on interpretation of the spec and the current weather).

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 15 Apr 2015 14:00 UTC**
Replying to [comment:7 jmattsson]:
> OK, though I still say there was no loop in the original example. The change that "made the loop apparent" _introduced_ the loop (that possibly isn't there, depending on interpretation of the spec and the current weather).

Of course, I meant that the loop exists in your way of name resolution (not that this was particularly wrong, I'd just rather make such a loop explicit in the specification).

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 15 Apr 2015 14:49 UTC**
To answer the original question, MapleSim gives `Real s`.

I do hope no one writes code like that for other than academic interest.

**Comment by modelica-trac-importer** [comment]
**Comment by pharman on 15 Apr 2015 15:37 UTC**
`Real s` here also

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
