### ISSUE TITLE
Spec does not index import

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1697]
**Reported by jriel on 16 Apr 2015 18:11 UTC**
There is no entry for **import** in the index of the Modelica Language Specification.  It should point to the appropriate pages in the **Packages** chapter.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1697

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 6 Sep 2016 12:37 UTC**
Modelica specification tickets.

**Comment by HansOlsson** [comment]
After the change of specification format the entire index needs to be re-done (and preferably be made more consistent). Thus no need for specific issues in old index.
