### ISSUE TITLE
Enclosing classes and redeclarations

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1716]
**Modified by choeger on 6 May 2015 17:37 UTC**
Consider the following example (hopefully I got all the package/model restrictions right this time, Hans ;)):

```mo
package test

package A
      package B
        replaceable type D = Real;
	model C	
 	  type X = B.D;
	  type Y = A.B.D;
 	  X x;
 	  Y y;
 	  equation
	   x = 2.3;
	 end C;	  
      end B;
end A;

package B2
  extends A.B(redeclare type D = String);
end B2;

model E
  B2.C c;
end E;

end test;
```

When instantiating `test.E`, what is the type of `c.x` and `c.y`? The type declarations are found in the enclosing classes, that much is clear. But is `B` found in `A`, or is `B.D` subject to the redeclaration of `D` in `B2`? How about `A.B.D`?

At least in the second case I have the strong opinion that `y` is not redeclared. JModelica agrees. However, openmodelica and dymola seem to disagree with me. In the `x`-case, I do not have a strong opinion, but jmodelica seems to find `B` in `A` and hence does not change `X` after redeclaration. 

----

**Reported by choeger on 6 May 2015 17:37 UTC**
Consider the following example (hopefully I got all the package/model restrictions right this time, Hans ;)):

{
#!mo
package test

package A
      package B
        replaceable type D = Real;
	model C	
 	  type X = B.D;
	  type Y = A.B.D;
 	  X x;
 	  Y y;
 	  equation
	   x = 2.3;
	 end C;	  
      end B;
end A;

package B2
  extends A.B(redeclare type D = String);
end B2;

model E
  B2.C c;
end E;

end test;
}

When instantiating `test.E`, what is the type of `c.x` and `c.y`? The type declarations are found in the enclosing classes, that much is clear. But is `B` found in `A`, or is `B.D` subject to the redeclaration of `D` in `B2`? How about `A.B.D`?

At least in the second case I have the strong opinion that `y` is not redeclared. JModelica agrees. However, openmodelica and dymola seem to disagree with me. In the `x`-case, I do not have a strong opinion, but jmodelica seems to find `B` in `A` and hence does not change `X` after redeclaration. 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1716

**Comment by modelica-trac-importer** [comment]
**Modified by choeger on 6 May 2015 17:37 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by choeger on 7 May 2015 05:41 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 14 Mar 2017 13:54 UTC**
These issues should be resolved with the new flattening.
If that is not the case they need to reference an issue in the new description.

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
