### ISSUE TITLE
Are enclosing classes strictly evaluated?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1735]
**Reported by choeger on 17 Jun 2015 06:44 UTC**
Consider this example:

```mo
package A
  class Error
    class Loopy
      constant Real c = 42.0;
      extends Error;
    end Loopy;

    class Ok
      Real x = 2.0 /* or = Loopy.Loopy.Loopy.c */;
    end Ok;
  end Error;
end A;
```

In this example, `A.Error.Ok` does not contain any obvious errors. However, the enclosing class `A.Error` contains an infinite amount of `Loopy` classes. So it cannot be flattened (or rather flattening it will never terminate). My question is, what does the spec demand (and what do tools implement) when flattening `A.Error.Ok`?

Is it:

* Some error
* Nontermination
* Termination

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1735

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 17 Jun 2015 07:27 UTC**
Since JModelica.org only flattens the classes it actually needs, it will happily flatten `A.Error.Ok`, `A.Error.Ok` with the expression in the comment instead of `2.0`, `A.Error.Loopy` or `A.Error` if asked to. The `A.Error.Loopy.Loopy` will only be flattened when it is used, not just because `A.Error.Loopy` is used.

We are probably not according to spec about this. Since we have another approach to flattening then the one described in the spec, we have tried to figure out what the intended results of the described procedure is and implement that.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 17 Jun 2015 07:53 UTC**
Replying to [comment:1 jmattsson]:
> Since JModelica.org only flattens the classes it actually needs, it will happily flatten `A.Error.Ok`, `A.Error.Ok` with the expression in the comment instead of `2.0`, `A.Error.Loopy` or `A.Error` if asked to. The `A.Error.Loopy.Loopy` will only be flattened when it is used, not just because `A.Error.Loopy` is used.
> 
> We are probably not according to spec about this. Since we have another approach to flattening then the one described in the spec, we have tried to figure out what the intended results of the described procedure is and implement that.

The resolution for #1458 should ideally allow that, since we only need 'A.Error' to find 'Ok' and potentially elements used inside 'Ok'. 
For lookup inside 'A.Error.Ok' we need to know that 'A.Error.Loopy' exists as a class, but not the details.
For lookup inside 'A.Error.Loopy' we need to know that the base-class gives us local classes 'Loopy' and 'Ok' - but since they are not used we don't need their contents.
If the classes are actually used I would expect that we either have an infinite recursion for base-classes, or in terms of components.

Note that currently not even check in Dymola and 3DExperience detects the issue (for this particular case - it may depend on details that are not important for this ticket; you can even check 'A.Error.Loopy.Loopy.Loopy.Ok'), one could argue that check should detect this - but the exact details of the 'check' operation is not part of the specification.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 17 Jun 2015 10:29 UTC**
MapleSim flattens the first example (`x=2.0`) and gives an error on the second (`x=Loopy.Loopy.Loopy.c`):

```
Class `A.Error.Loopy` cannot extend its containing class `A.Error`
```

A class is not flattened unless it is needed, and flattening a class does not automatically flatten all the contained classes (if it did, flattening any model would require flattening the entire MSL).

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 14 Mar 2017 13:54 UTC**
These issues should be resolved with the new flattening.
If that is not the case they need to reference an issue in the new description.

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
