### ISSUE TITLE
Add support for SVG and MathML

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#174]
**Reported by dietmarw on 27 May 2009 07:47 UTC**
Although probably being a tool issue, this ticket should act as an reminder to add SVG and MathML support in some future version of Modelica

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/174

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 27 May 2009 07:51 UTC**
There is no real "version" to this.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 17 Jun 2014 15:42 UTC**
- We should discuss adding support for SVGs in graphic annotations (BitMap).
- We should also make sure that documentation annotations allow for svg to be used (tools using a web browser widget will get this for free; just clarify MSL can start using it for plots in documentation instead of png's).

**Comment by modelica-trac-importer** [comment]
**Changelog removed by sjoelund&#x2e;se on 17 Jun 2014 15:42 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 19 Dec 2014 07:01 UTC**
Ticket retargeted after milestone closed

**Comment by modelica-trac-importer** [comment]
**Comment by dhedberg on 15 Mar 2016 07:52 UTC**
I think this is a great idea! This ticket was opened 7 years ago, but it appears that there's not been much discussion?

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 15 Mar 2016 08:56 UTC**
This is one more example where tools are simply ahead of the language. For icons with SVG you might test [TestSVG.mo](https://github.com/tbeu/TestSVG).

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 15 Mar 2016 12:07 UTC**
For MathML (and LaTeX and ...)  support there is an even simpler solution with the help of MathJax. This is already supported by OpenModelica's document browser. Both, loading MathJax from online CDN or loading it locally from a library resource. See also #78.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 15 Mar 2016 14:27 UTC**
Replying to [comment:5 beutlich]:
> This is one more example where tools are simply ahead of the language. For icons with SVG you might test [TestSVG.mo](https://github.com/tbeu/TestSVG).

And not only is it supported now, but based on the colorful logo this test seems like something added a few years ago.

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 16 Mar 2016 10:27 UTC**
Well "some tool**s**" still decide to display the SVG in a raster low quality fashion ;-) (also only supported since the last official version (would not really call this years ago).

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Oct 2017 10:02 UTC**
To discuss at meeting. Some should be possible to trivially close.

**Comment by svorkoetter** [comment]
I would like to add a contrary point of view. IMO, the entire purpose of the Bitmap annotation was to make it possible to include things in a graphical annotation that could not easily be expressed in terms of graphic primitives (e.g. a photograph or complex 3D rendering of a part). Supporting SVG is both redundant (anything expressible in SVG can be expressed in terms of graphic primitives), and adds a lot of extra work for a tool vendor.

**Comment by beutlich** [comment]
I get your point @svorkoetter. There even is an (incomplete) editor for Modelica Vector Graphics available at https://github.com/modelica-tools/MoVE.

**Comment by sjoelund** [comment]
There are good points for supporting SVG images.

* You can re-use the same image easier than you can with Modelica graphics (should you really add a new component to a model just to be able to re-use an image?)
* Easier to import existing graphics/logotypes (is there any SVG to Modelica vector graphics tool?)
* Is there any opacity in Modelica graphics?
* Filter effects?
* Probably much more

For us, I believe supporting SVG is a no-op because Qt already supports SVG images. When you implemented support for PNG/JPEG, did you write your own decompression algorithm?

**Comment by MartinOtter** [comment]
One drawback of svg is that it is a huge, complicated standard with various versions and therefore it is easily possible that svg exported from one tool and imported in another tool either supports not a feature or draws it differently. Therefore, it is not a robust solution for cross-tool development. If all Modelica tool vendors would use the same version of Qt, this is a good solution. If Modelica tool vendors use different base software, the cross-tool compatibility will be not robust.

The png format has the huge advantage that the standard is simple and does not change. I never experienced any problems to generate and use png-images with different tools, contrary to svg.

As a end-user, I also would prefer to use svg, but I also would like that Modelica models exported from one tool can be imported in another Modelica tool without destroyed graphical images.

**Comment by svorkoetter** [comment]
Martin S: Not everyone uses Qt for their UI. No, we did not write our own PNG and JPEG decompressors. There are widely available, very portable, very stable, open source libraries to do these things. And Martin O is right, that the PNG standard is simple and stable (as is JPEG). SVG is far from simple, and I don't know how stable it is.

One _could_ make an argument to support SVG in Modelica annotations, but then I think the argument should be to use SVG _as_ graphical annotations (i.e. replace our existing primitives with SVG, just like we use HTML in the Documentation primitive).

**Comment by henrikt-ma** [comment]
None of us should write their own SVG renderer, and Qt is of course not the only alternative.

SVG support in web browsers is widespread today, meaning that this is not a small format in terms of adoption.  There are many reasons why one might want to use vector graphics instead of bitmaps in icons, and SVG is the obvious choice of format with its stable history (version 1.1 released in 2003, with its second edition in 2011), easily accessible specification, and breadth of supporting implementations.  I guess it was for this kind of reasons that it was decided to allow use of SVG in Modelica.

**Comment by casella** [comment]
I also agree with @svorkoetter that the scope of SVG is definitely too wide for Modelica model icons and documentation. I'm fine with PNG and JPG.
