### ISSUE TITLE
"start" value at events

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1787]
**Reported by garron&#x2e;fish on 23 Sep 2015 06:50 UTC**
The start keyword is only used during initialization and is not used during events.

Guess values for variables at events would be helpful.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1787

**Comment by HansOlsson** [comment]
This seems to need additional design, and there haven't been any new insights for years. Closing until we get them.
