### ISSUE TITLE
Rendering arrows for Line annotations

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1894]
**Reported by stefanv on 26 Jan 2016 17:25 UTC**
The Arrow type is declared as:

```mo
type Arrow = enumeration(None, Open, Filled, Half);
```

The meaning of `None` is obvious.

`Open` and `Filled` are relatively obvious, except it's not clear where the arrowhead is to be drawn: overlapping the end of the line, or after the end of the line:

```
given line without arrow: ---------------
with arrow like this?:    ------------->>
or like this?:            --------------->>
```

The meaning of `Half` is less clear. What is half an arrow? Which side of the line is it on? Is it open or filled?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1894

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 26 Jan 2016 17:34 UTC**
I'd say the most reasonable for Open & Filled is that the tip of the arrowhead is in the point the line ends in - otherwise you would need to end the line one arrowhead length from the point you want the arrow to point to.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 26 Jan 2016 17:37 UTC**
Also, what should the width of the arrow be?

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 26 Jan 2016 17:41 UTC**
Replying to [comment:2 stefanv]:
> Also, what should the width of the arrow be?

For that matter, what length? The meaning of `arrowSize` isn't clear.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 26 Jan 2016 17:42 UTC**
Replying to [comment:1 jmattsson]:
> I'd say the most reasonable for Open & Filled is that the tip of the arrowhead is in the point the line ends in - otherwise you would need to end the line one arrowhead length from the point you want the arrow to point to.

That is what I though too, except that I notice that many of the lines that end in arrowheads are too short when the arrowheads are not rendered.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 26 Jan 2016 17:44 UTC**
Replying to [comment:3 jmattsson]:
> Replying to [comment:2 stefanv]:
> > Also, what should the width of the arrow be?
> For that matter, what length? The meaning of `arrowSize` isn't clear.

Isn't it just arrowSize/initialScale to get to CoordinateSystem coordinates?

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 26 Jan 2016 17:52 UTC**
Replying to [comment:4 stefanv]:
> Replying to [comment:1 jmattsson]:
> > I'd say the most reasonable for Open & Filled is that the tip of the arrowhead is in the point the line ends in - otherwise you would need to end the line one arrowhead length from the point you want the arrow to point to.
> 
> That is what I though too, except that I notice that many of the lines that end in arrowheads are too short when the arrowheads are not rendered.

It seems that the cases where I experienced this behaviour are cases where the arrow annotation isn't actually being used; the arrowheads are just being drawn as polygons. So, your interpretation is probably correct.

But the questions about `Half` and arrow width still stand.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 26 Jan 2016 17:58 UTC**
Replying to [comment:6 stefanv]:
> So, your interpretation is probably correct.

It should probably still be clarified in the specification.

> But the questions about `Half` and arrow width still stand.

And arrow length, especially since it isn't even clear if `arrowSize` is used for that at all.

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 27 Jan 2016 08:59 UTC**
Replying to [comment:2 stefanv]:

I have assumed that arrowSize specifies the arrow width at the base, not the length. The unit of arrowSize is 'mm', see definition of DrawingUnit in 18.6.1.


> Also, what should the width of the arrow be?

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 27 Jan 2016 09:05 UTC**
Regarding Half arrow: for what I know, this is intended as a bond graph arrow. I think it is often drawn on the left side when viewing in the direction of the arrow, but I have seen bond graphs with a mix of left and right side arrows.

**Comment by modelica-trac-importer** [comment]
**Modified by stefanv on 3 Mar 2016 16:48 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 7 Mar 2016 18:01 UTC**
Modelica design meeting:
Tip of arrow-point at end of line.
Open as V-shaped arrow-head.
Bond graph as left-side in the direction of the arrow (away from mid-point of line).

Discussion about on what arrowSize means: width of base (full base for half?), or length of arrow-part. Some would prefer multiplication of thickness.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 8 Mar 2016 11:00 UTC**
Some comments:
The arrowSize should have the same meaning for all arrows: Half, Open, and Filled (so that the relevant parts overlap if the are otherwise identical), right?

I assume the filled shape is independent of the line-thickness.

But for open and half-arrow: should the line-thickness also be used for the lines of the arrow? (Dymola does this.)

(I could not easily find the exact arrow-width in Dymola - lineThickness 10 and arrowSize 12 about match in width.)

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 8 Mar 2016 14:04 UTC**
I think it makes sense to use the the line thickness also for stroking the arrowhead; I see no other alternative without introducing additional arrowhead parameters (and even if it was parameterized, I'd probably never use anything else than the line thickness).

Given that we agree on an interpretation of `arrowSize` (where I agree with Hans' proposal in comment 12), the only thing that then remains to make arrowheads completely specified would be to specify the angle at the tip of the arrowhead.  In my opinion, 40°, would be a good choice.  Using an angle instead of the length of the arrowhead makes the arrowhead scale nicely when changing the `arrowSize`.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 8 Mar 2016 15:04 UTC**
In Dymola we have 18.4349488 degrees between the center-line and each arrow-part.
(It is atan(1/3).) So about the same.

**Comment by HansOlsson** [comment]
I don't see that we can finalize the discussion before 3.5.
