### ISSUE TITLE
Const array inputs to external C functions

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1955]
**Reported by rfranke on 10 Mar 2016 06:57 UTC**
The Modelica 3.3 spec, section 12.9.1.2 Arrays gives the example
```mo
function foo
  input Real a[:,:,:];
  output Real x;
  external;
end foo;
```
and states that the corresponding external C function signature is:
```C
double foo(double *, size_t, size_t, size_t);
```

Modelica requires that inputs to functions must not be changed. This is why the function signature shall be:
```C
double foo(const double *, size_t, size_t, size_t);
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1955

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 28 Mar 2016 09:48 UTC**
The same applies to the function `fie` in the same section 12.9.1.2. 

Const qualifiers for function inputs allow code optimizations, e.g. avoid an unnecessary copy operation if an input is not changed. They also enable the detection of possible errors when calling an external function that has no const qualifier because it changes its call argument.  

The trunk version of ModelicaTest.Tables contains 3 \*_usertab examples with:
```mo
    encapsulated function getUsertab
      import Modelica;
      extends Modelica.Icons.Function;
      input Real dummy_u[:];
      output Real dummy_y;
      external "C" dummy_y = mydummyfunc(dummy_u)
      annotation(IncludeDirectory="modelica://Modelica/Resources/Data/Tables",
             Include = "#include \"usertab.c\"
double mydummyfunc(double* dummy_in) {
    return 0.;
}
");
    end getUsertab;
```
It must be: `double mydummyfunc(const double* dummy_in)`.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 29 Mar 2016 07:42 UTC**
Replying to [comment:1 rfranke]:
> The same applies to the function `fie` in the same section 12.9.1.2. 
> 
> Const qualifiers for function inputs allow code optimizations, e.g. avoid an unnecessary copy operation if an input is not changed. They also enable the detection of possible errors when calling an external function that has no const qualifier because it changes its call argument.  

I agree with the detection of possible errors, and think this should be updated.

However, it doesn't allow many automatic code optimizations since code could internally cast away that const-qualifier. Clearly that is bad code (especially if the value isn't restored) - but still well-defined unless you call getUserTab with a const-declared array.

**Comment by modelica-trac-importer** [comment]
**Modified by rfranke on 30 Mar 2016 08:21 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 14 Apr 2016 05:56 UTC**
r9291 introduces the const qualifiers to the trunk version of the ModelicaTest.Tables.\*.*_usertab examples as stated in comment:1.

This should not harm any tool because it follows a common ANSI C convention. See also other examples in the Modelica spec and MSL that use const for inputs, e.g. section 12.9.6 Utility Functions:
```C
  ModelicaMessage(const char* string)
```

or Modelica/Resources/C-Sources/ModelicaMatIO.h:
```C
EXTERN matvar_t  *Mat_VarDuplicate(const matvar_t *in, int opt);
```

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 14 Apr 2016 06:58 UTC**
I'd propose to **first** update the MLS and **then** apply it to the MSL. Currently it feels strange that r9291 added the const qualifier to three functions only. Your commit neither is in accordance with the current MLS 3.3 rev1 nor complete within the MSL.

The example with const char\* is in accordance with the MLS as Modelica Strings are always considered as const char\*.

The example with Mat_VarDuplicate is not a Modelica external function.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 14 Apr 2016 07:01 UTC**
Forgot: I agree that this should be fixed.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 14 Apr 2016 16:31 UTC**
I don't think I changed MSL. It's only a function called `mydummyfunc` in three table tests. I'm sure that this does not harm anyone. If so, then we can revert it of course.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 26 Jan 2017 14:10 UTC**
@rfranke: Wenn you say, that it does not harm to add const qualifiers, you did not see #2077 where adding const leads to GCC warnings.

I propose to fix it porperly for MLS v3.4 and afterwards in the MSL based on that language version. So r9291 should be reverted as long as const qualifiers on input arrays are non-standard.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 3 Feb 2017 09:53 UTC**
I don't really understand what the invalid ticket #2077 about a bug in an old beta version of Dymola 2017 has to do with this ticket. 

If the use of C const qualifiers is that unclear, then this ticket needs to be classified as blocker for any version of the Modelica spec.

Any C library I'm aware of uses const qualifiers if function inputs are passed by reference. Even the Modelica spec defines `const char*` for string inputs, see MLS3.3, section 12.9.1.1. The missing `const` qualifier for arrays of other types, see section 12.9.1.2 Arrays, makes the external C interface unapplicable with external C libraries that use arrays of other types than char, like double.

Don't say that people who want to use Modelica should cast const types away. This takes away type safety. If this is really intended than it must be clearly stated in the Modelica spec.

See also numerous explanations about proper C programming, like  [securecoding.cert.org](https://www.securecoding.cert.org/confluence/display/c/DCL13-C.+Declare+function+parameters+that+are+pointers+to+values+not+changed+by+the+function+as+const)

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 3 Feb 2017 10:23 UTC**
Remember, I said that I also want to have it fixed.

Dymola (independent of the version) generates that `const` for prototypes on input arrays which simply is not compliant with the Modelica standard. And you can imagine that this causes a lot of trouble for library vendors and even the MSL itself, see [#1774](https://github.com/modelica/Modelica/issues/1774). If we fix it by introducing `const` in the Modelica standard, it will be considered as a backward-compatibility breaking change that will raise many complaints from library vendors and users that there code suddenly generates compiler warnings.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 3 Feb 2017 15:34 UTC**
If tools do already add `const` qualifiers, then the impact of a clarification in the Modelica spec might not be that big.

**Comment by HansOlsson** [comment]
Proposal:

Inputs to C-function should have const-pointers.

**Comment by HansOlsson** [comment]
Agreement.

**Comment by beutlich** [comment]
I am aware that Dymola already distributes modifed MSL C-Sources to comply with that change. @HansOlsson Can you please create a draft PR for MSL where array function inputs are const. Thank you.
