### ISSUE TITLE
Add an array reshape function

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1980]
**Reported by beutlich on 8 Apr 2016 06:41 UTC**
The Modelica standard misses a _reshape_ function (as available in MATLAB) to easily flatten higher-dimensional arrays or build-up higher-dimensional arrays from lower-dimensional arrays.

MATLAB-Example:
```m
A = [4,5,6;16,19,20;10,18,23]; // 3x3
B = reshape(repmat(A,1,2),[3,3,2]); // 3x3x2
```

Modelica equivalent:
```mo
Real A[3,3] = [4,5,6;16,19,20;10,18,23];
Real B[3,3,2] = reshape(cat(2,A,A),[3,3,2]); // {{{4,4},{5,5},{6,6}},{{16,16},{19,19},{20,20}},{{10,10},{18,18},{23,23}}}
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1980

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 8 Apr 2016 07:54 UTC**
Replying to [ticket:1980 beutlich]:
> The Modelica standard misses a _reshape_ function (as available in MATLAB) to easily flatten higher-dimensional arrays or build-up higher-dimensional arrays from lower-dimensional arrays.
> 
> MATLAB-Example:
> ```m
> A = [4,5,6;16,19,20;10,18,23]; // 3x3
> B = reshape(repmat(A,1,2),[3,3,2]); // 3x3x2
> ```
> 
> Modelica equivalent:
> ```mo
> Real A[3,3] = [4,5,6;16,19,20;10,18,23];
> Real B[3,3,2] = reshape(cat(2,A,A),[3,3,2]); // `4,4},{5,5},{6,6}},{{16,16},{19,19},{20,20}},{{10,10},{18,18},{23,23`
> ```

Some minor details.

I believe the Modelica variant should be (using a vector - not matrix as 2nd argument to reshape).
```
  Real A[3,3] = [4,5,6;16,19,20;10,18,23];
  Real B[3,3,2] = reshape(cat(2,A,A), {3,3,2}); 
  // `4,4},{5,5},{6,6}},{{16,16},{19,19},{20,20}},{{10,10},{18,18},{23,23`
```
The vector allows the natural:
```
  Real B[3,3,2] = reshape(cat(2,A,A), size(B)); 
```

And this is an enhancement - not a defect, right?

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 8 Apr 2016 08:03 UTC**
Changed to enhancement.

Yes, vector for second argument. And which dimensionality for first argument?

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 8 Apr 2016 08:08 UTC**
Replying to [comment:2 beutlich]:
> Changed to enhancement.
> 
> Yes, vector for second argument. And which dimensionality for first argument?

I would say _any_ dimensionality for the first argument (which is only possible for a builtin function).

**Comment by modelica-trac-importer** [comment]
**Comment by kurzbach on 8 Apr 2016 09:38 UTC**
... and
```
Real A[1]={3};
Real B=reshape(A,zeros(0));
```
,meaning `reshape` with empty vector as second argument gives a scalar !?

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 8 Apr 2016 09:42 UTC**
More likely it should give an error. To reshape an array I assume it should hold that the product of dimensions in the first argument and the product of elements in the second should be equal. 0 dimensions means a size of 0, which means it can't be reshaped into a scalar. A scalar I assume you would do `scalar(reshape(A,{1}))`.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 8 Apr 2016 09:58 UTC**
Replying to [comment:5 sjoelund.se]:
> More likely it should give an error. To reshape an array I assume it should hold that the product of dimensions in the first argument and the product of elements in the second should be equal. 0 dimensions means a size of 0, which means it can't be reshaped into a scalar. A scalar I assume you would do `scalar(reshape(A,{1}))`.

I actually agree with G. Kurzbach, and note that `product(zeros(0))` is 1, i.e. scalar is empty size - not size 0.

` respace(A, s); `
Requires:
s is a vector
A is an array/matrix/vector/scalar
product(size(A))=product(s)
Result:
size(reshape(A, s))=s

And each element of A is mapped to an element of the result (in a yet to be described way).

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 8 Apr 2016 10:26 UTC**
But shouldn't it be, `Real B = reshape(A,ones(0))`, as this is the degenerate case of `reshape(A,ones(N))` to reshape A to an N-dimensional single-element array?

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 8 Apr 2016 11:16 UTC**
Replying to [comment:7 stefanv]:
> But shouldn't it be, `Real B = reshape(A,ones(0))`, as this is the degenerate case of `reshape(A,ones(N))` to reshape A to an N-dimensional single-element array?

`ones(0)`, `zeros(0)`, and `fill(112313, 0)` all return the same thing, so I think this distinction does not matter.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 8 Apr 2016 16:15 UTC**
Replying to [comment:8 sjoelund.se]:
> Replying to [comment:7 stefanv]:
> > But shouldn't it be, `Real B = reshape(A,ones(0))`, as this is the degenerate case of `reshape(A,ones(N))` to reshape A to an N-dimensional single-element array?
> 
> `ones(0)`, `zeros(0)`, and `fill(112313, 0)` all return the same thing, so I think this distinction does not matter.

That is true, but I think Stefan's point is when _explaining_ we could write (assuming p is a scalar and we allow the first input of reshape to be a scalar):

|N | result of `reshape(p, ones(N))`|
|-|-|
|0 | p scalar|
|1 | {p} vector|
|2 | [p] matrix|
|3 | {[p]} array with dimensionality 3|


This seems obvious, but is only obvious in hindsight; I didn't notice this at first.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 8 Apr 2016 16:25 UTC**
Precisely. They all return the same thing in practice in most tools, but in theory, they are different.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 30 Nov 2016 14:27 UTC**
One thing that is missing from this proposal is to define exactly how items are mapped.
One idea would be to say that the column-major order layout of the elements is the same before and after reshaping:
https://en.wikipedia.org/wiki/Row-_and_column-major_order
But that did not seem consistent with the example at the start.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 30 Nov 2016 14:47 UTC**
Idea is to it the MATLAB way (https://de.mathworks.com/help/matlab/ref/reshape.html) and maintain the columnwise order.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 30 Nov 2016 15:32 UTC**
Replying to [comment:12 beutlich]:
> Idea is to it the MATLAB way (https://de.mathworks.com/help/matlab/ref/reshape.html) and maintain the columnwise order.

Ok, it seems I made an error when checking the column-major order, since the last line below is zero indicating that elements are the same in column-major order.
```
A=[4,5,6;16,19,20;10,18,23];
B=`4,4},{5,5},{6,6}},{{16,16},{19,19},{20,20}},{{10,10},{18,18},{23,23`;
C=cat(2,A,A);
{C[1+mod(i,3),1+div(i,3)] for i in 0:17}-{B[1+mod(i,3),1+mod(div(i,3),3),1+mod(div(i,9),2)] for i in 0:17}
```

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Oct 2017 09:46 UTC**
So the complete proposal is that:
`reshape(x, y)`
returns an expression with the same element as `x` and in the same column-wise order (need to be spelled out) satisfying: `size(reshape(x, y))==y`, `product(y)==product(size(x))`

The expression `x` may have any dimensionality.
The number of elements of the vector `y` must be constant known during translation.

(With comment including reshape(p, ones(N)).) 

Additional points:


* We might add a special case for returning all elements as a vector if the function only has one input, e.g.: `reshape(x)==reshape(x, {product(size(x))}) `.
* Based on that we might consider a different name, e.g. columnWise

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Oct 2017 10:02 UTC**
To discuss at meeting. Some should be possible to trivially close.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2017 09:41 UTC**
Discussion about column-major vs. row-major.
For converting vector to 1xn or nx1 matrix we have `[v]` and ` {v} `.

Stefan: `[1, 2; 3, 4]` and ` {{1, 2}, {3, 4}} ` is sort of row-major in terms of entering the numbers. Therefore it makes no sense for reshape to be column-major.

Hans: Could have "columnWise" to make it clear that columnMajor - and possibly also have "rowMajor".

Possibilities: Have other name for this to make it clear? 
Henrik: Was there a compelling use-case?
Hans: No, a typical use-case would be creating a matrix (or higher-dimensional) of parameter-values and transforming it to a vector to call a function (e.g. simulation) for all cases - that functions expects a vector of values - and transform the result back to a matrix.
Stefan: Vectorization solves part of this; but may need to be extended.

**Conclusion:** Need more compelling use-case.

**Comment by HansOlsson** [comment]
Closing until we see a compelling use-case. The design of the functionality is fairly complete.
