### ISSUE TITLE
Initialization of models containing arrays

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#1985]
**Reported by adrpo on 15 Apr 2016 14:46 UTC**
Since is not possible to set the start value for only one array element anymore `(x[1](start = 1))` initialization of models containing arrays is really cumbersome. Just think how would you set the start value of a variable such as: `a.b[1].c[2].d[10].e`.

As far as I know each tool have their own way to help with this via mat files for initialization or scripts.

I think we should make this uniform if possible so that all tools behave the same. This is really important as without proper initialization start values the models might work (or not at all) differently in different tools.

There are several possibilities here:
1. via annotations `annotation(Initialization(var1=val1, var2=val2, ...))`
2. via an new initialization section in the Modelica language:
```mo
model M
  vars
initialization
  var1 = val1;
  var2 = val2;
  var3 = val2;
equation
  equs
end M;
```

This would behave basically the same in all tools.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1985

**Comment by modelica-trac-importer** [comment]
**Comment by adrpo on 15 Apr 2016 14:48 UTC**
Myself I would prefer to have a new initialization section as you could do more advanced initialization and also better checking.

**Comment by modelica-trac-importer** [comment]
**Comment by lochel on 15 Apr 2016 15:14 UTC**
I don't think that annotations should be used to influence the initialization.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 15 Apr 2016 15:21 UTC**
Replying to [ticket:1985 adrpo]:
> Since is not possible to set the start value for only one array element anymore `(x[1](start = 1))` initialization of models containing arrays is really cumbersome. Just think how would you set the start value of a variable such as: `a.b[1].c[2].d[10].e`.
> 
> As far as I know each tool have their own way to help with this via mat files for initialization or scripts.
> 
> I think we should make this uniform if possible so that all tools behave the same. This is really important as without proper initialization start values the models might work (or not at all) differently in different tools.
> 
> There are several possibilities here:
> 1. via annotations `annotation(Initialization(var1=val1, var2=val2, ...))`
> 2. via an new initialization section in the Modelica language:
> ```mo
> model M
>   vars
> initialization
>   var1 = val1;
>   var2 = val2;
>   var3 = val2;
> equation
>   equs
> end M;
> ```

Modelica already has "initial equation" so you can write:
```mo
model M
  Real x[3];
initial equation
  x[1] = 1;
  x[2] = 2;
  x[3] = 5;
equation
  der(x)=ones(3)-x;
end M;
```
This should behave basically the same in all tools, and works if you want strict start-values (similar to fixed=true) - I am not sure if there is a major need for something for guess-values.

You can also propagate start-values for other cases, and thus I don't really understand what is missing here.

**Comment by modelica-trac-importer** [comment]
**Comment by adrpo on 15 Apr 2016 16:40 UTC**
Of course you can use initial equations but they are not flexible enough.

For example you cannot override an initial equation in the top model and if you add another initial equation for the same variable you cannot solve the initialization system. 
Also forcing initial equations somewhere deep in the instance hierarchy is not always desired.
And there are the guess start values with fixed=false as you say that are sometimes needed depending on how the system is solved. Propagating would work but it clutters the model for no good reason.

**Comment by modelica-trac-importer** [comment]
**Modified by adrpo on 15 Apr 2016 16:43 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 16 Apr 2016 12:26 UTC**
I think we cannot solve this issue without a proper component-array modification semantics. I think there was a good reason to forbid `(x[1](start = 1))`, but cannot remember it. Can anyone dig it up?

**Comment by modelica-trac-importer** [comment]
**Comment by adrpo on 16 Apr 2016 12:28 UTC**
@choeger: #1638

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 18 Apr 2016 07:27 UTC**
Replying to [comment:4 adrpo]:
> Of course you can use initial equations but they are not flexible enough.
> 
> For example you cannot override an initial equation in the top model and if you add another initial equation for the same variable you cannot solve the initialization system. 

But we know how to handle that:
```mo
model M
  Real x[3];
  parameter Boolean initializeStates=true;
initial equation
  if initializeStates then
    x[1] = 1;
    x[2] = 2;
    x[3] = 5;
  end if;
equation
  der(x)=ones(3)-x;
end M;
```
and instead of adding 'initialization' section we could see if we could make this more convenient - and if we really want to push the idea we could require that initial equations are conditional (probably that would be a bad idea).

It might be that there is more to this, but then we need more realistic examples.

**Comment by HansOlsson** [comment]
As indicated above some cases can currently be handled, and nothing has happened for a couple of years. It may be that more is needed, but then we need realistic examples.
