### ISSUE TITLE
Clarification of enclosing classes

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2013]
**Modified by sjoelund&#x2e;se on 21 Jun 2016 16:05 UTC**
Dear colleagues,

I found an example for lookup that seems to be unspecified:

```mo
class C
  constant Integer y = B.z; //== .C.B.z == 21
  class B
    constant Integer z = 21; 
    class A
      constant Integer x = y + z; // .C.y + .C.B.z == .C.B.z + .C.B.z == 21 + 21
    end A;
  end B;
end C;

class D
 extends C.B(z=2);
 constant Integer result = A.x; // == .D.A.x == .C.y. + .D.z == .C.B.z + .D.z == 23 ?
end D;
```

The comments reflect my (and openmodelica's) understanding of the lookup. The important points here are:

1. `.D.A.x` resolves to `.D.z` since `.D` is a modification of an entry of `.D.A`'s set of enclosing classes.
2. `.C.y` does not resolve to `.D.z` but to `.C.B.z`, since the modified entry has been passed during lexical lookup (and I do not see a way to "keep" it somehow)

I think point 1 is crucial for Modelica's model of hierarchic modifications to work. 
However, point 2 is also crucial, since otherwise it would be pretty much impossible to understand the effects of a modification (with my proposal it is clearly bound by hierarchical limits).

What do you think?

So here is my proposal for a clarification of the specification:

> During lookup in a set of enclosing classes, it is possible to encounter modified enclosing classes (i.e. instead of finding the lexically enclosing class, one can find a class modifying/extending it). 

> If an element is found in such a modifying/extending class, it's right hand side is looked up using the set of enclosing classes of the modifying/extending class. Any entries encountered before the one in which the element is found are discarded (i.e. modifying an element does not affect the lexical environment of that element, but only elements of the class containing the modified element).

> If an element is not found in the modifying/extending class, lookup continues with the rest of the original set (i.e. each entry in the set of enclosing classes has **its own set** of enclosing classes that may be different from the rest of the set containing the entry).

----

**Reported by choeger on 16 Jun 2016 08:25 UTC**
Dear colleagues,

I found an example for lookup that seems to be unspecified:

```mo
class C
  constant Integer y = B.z; //== .C.B.z == 21
  class B
    constant Integer z = 21; 
  class A
    constant Integer x = y + z; // .C.y + .C.B.z == .C.B.z + .C.B.z == 21 + 21
  end A;
end B;
end C;

class D
 extends C.B(z=2);
 constant Integer result = A.x; // == .D.A.x == .C.y. + .D.z == .C.B.z + .D.z == 23 ?
end D;
```

The comments reflect my (and openmodelica's) understanding of the lookup. The important points here are:

1. `.D.A.x` resolves to `.D.z` since `.D` is a modification of an entry of `.D.A`'s set of enclosing classes.
2. `.C.y` does not resolve to `.D.z` but to `.C.B.z`, since the modified entry has been passed during lexical lookup (and I do not see a way to "keep" it somehow)

I think point 1 is crucial for Modelica's model of hierarchic modifications to work. 
However, point 2 is also crucial, since otherwise it would be pretty much impossible to understand the effects of a modification (with my proposal it is clearly bound by hierarchical limits).

What do you think?

So here is my proposal for a clarification of the specification:

> During lookup in a set of enclosing classes, it is possible to encounter modified enclosing classes (i.e. instead of finding the lexically enclosing class, one can find a class modifying/extending it). 

> If an element is found in such a modifying/extending class, it's right hand side is looked up using the set of enclosing classes of the modifying/extending class. Any entries encountered before the one in which the element is found are discarded (i.e. modifying an element does not affect the lexical environment of that element, but only elements of the class containing the modified element).

> If an element is not found in the modifying/extending class, lookup continues with the rest of the original set (i.e. each entry in the set of enclosing classes has **its own set** of enclosing classes that may be different from the rest of the set containing the entry).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2013

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 16 Jun 2016 09:17 UTC**
We already have an MCP with ticket for improving the flattening and lookup, #1829 - that explicitly discusses the tree for instantiated classes.
I believe 5.6.1 and 5.6.2 contains this in some form.
If still unclear we need to improve that proposal - not create a new one that would later need to be merged, but otherwise we should just close this ticket.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 16 Jun 2016 09:34 UTC**
I do not think it is a good idea to merge all specific cases into one huge ticket, this will make the discussion extremely confusing. Let us just refer to this ticket in #1829 in order to not confuse the issues.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 16 Jun 2016 09:42 UTC**
Edit: Reading the new proposal, I think the main point is the meaning of scope and modification environment:

A modification environment needs to know its scope, which is formed by a class-tree node with a possible modification environment.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 21 Jun 2016 16:05 UTC**
Fixing the indentation of the example code.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 21 Jun 2016 16:16 UTC**
Conclusion: Agree with result above, should be clear from #1829

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 23 Jun 2016 11:46 UTC**
Should be clarified in next version.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 14 Mar 2017 13:54 UTC**
These issues should be resolved with the new flattening.
If that is not the case they need to reference an issue in the new description.

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
