### ISSUE TITLE
Overloading unary '+'

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2026]
**Reported by choeger on 14 Jul 2016 10:41 UTC**
Chapter 14 seems to allow only `not` and `-`. Is there a principal reason for leaving out `+`?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2026

**Comment by HansOlsson** [comment]
As indicated above this seems like a minor enhancement, that is not strictly needed. Thus closing until we see a clearer need.
