### ISSUE TITLE
Restricting connections to certain types

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2098]
**Reported by perost on 7 Nov 2016 11:12 UTC**
We got a question from a library developer on how to avoid that a library user uses connectors incorrectly:
>Currently we are working on a modelling effort to develop a library with standardised control functions for room control. The semantics of the input and output variables of this functions blocks may be very specific, e.g. one block requires an “Indoor Air Temperature” as an Input and another block requires a “Outdoor Air Temperature” as an Input. To avoid that a library user connects ports which do not have the same semantic (indoor vs. outdoor) we intend to use the connector compatibility checking of Modelica to ensure semantic correctness of the connected function blocks.

This ticket is meant to be a discussion on how such restrictions can be implemented, and whether it requires an extension of Modelica or not.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2098

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 7 Nov 2016 15:33 UTC**
I see the following possibilities:
* Instead of RealInput-variant have it as a structured connector with a sub-field "inDoor" or "outDoor".
* Use the quantity-attribute #1284 for a RealInput-variant.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2018 08:36 UTC**
Cleaning up unspecified tickets to prepare for move to GitHub

**Comment by HansOlsson** [comment]
No discussion for more than a year, and there were some suggestion for solving this with existing capabilities.
