### ISSUE TITLE
Support platform-specific Library annotation

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2104]
**Modified by beutlich on 18 Jan 2017 22:15 UTC**
For Modelica libraries like [Modelica_DeviceDrivers](https://github.com/modelica/Modelica_DeviceDrivers) depending on platform-specific system libraries (like e.g., pthread on Linux or Winmm on Microsoft Windows) the linking of the objectes is problematic.

Luckily, the issue can be avoided for MSVC by using a compiler-specific pragma as done in [b6ee3b7](https://github.com/modelica/Modelica_DeviceDrivers/commit/b6ee3b7685ad2a1197de94902f15beab6a743a6e) for Modelica_DeviceDrivers.

However, for GCC (including MinGW) the issue remains unresolved as https://github.com/modelica/Modelica_DeviceDrivers/issues/114 (Caution: long thread) demonstrates.

It would be nice if platform-specific library dependencies would be supported by the `Library` annotation of the external function/object.

----

**Reported by beutlich on 11 Nov 2016 07:08 UTC**
For Modelica libraries like [Modelica_DeviceDrivers](https://github.com/modelica/Modelica_DeviceDrivers) depending on platform-specific system libraries (like e.g., pthread on Linux or Winmm on Microsoft Windows) the linking of the objectes is problematic.

Luckily, the issue can be avoided for MSVC by using a compiler-specific pragma as done in [b6ee3b7](https://github.com/modelica/Modelica_DeviceDrivers/commit/b6ee3b7685ad2a1197de94902f15beab6a743a6e) for Modelica_DeviceDrivers.

However, for GCC (including MinGW) the issue remains unresolved as https://github.com/modelica/Modelica_DeviceDrivers/issues/114 (Caution: long thread) demonstrates.

It would be nice if platform-specific library dependencies would be supported by the `Library` annotation of the external funnction/object.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2104

**Comment by HansOlsson** [comment]
Seems that part of the more general build-project issue #1668. So closing as duplicate.
