### ISSUE TITLE
Evaluating assert only for accepted steps

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2110]
**Reported by Filip Jorissen on 14 Nov 2016 09:19 UTC**
In the Annex 60 library (https://github.com/iea-annex60/modelica-annex60/issues/564) we used to use asserts to verify if the results of two models are identical. For instance consider two states a and b where we do assert(abs(a-b)<1e-8). This caused problems in JModelica since JModelica uses finite differences to evaluate the Jacobian, which perturbs the states a and b, which causes the assert to fail. 

Based on the Modelica specification we established that the JModelica implementation is correct:

"level = AssertionLevel.error: The current evaluation is aborted. The simulation may continue with another evaluation [e.g., with a shorter step-size, or by changing the values of iteration variables]. If the simulation is aborted, message indicates the cause of the error."

Therefore we removed the assert statements from Annex 60. 

This ticket is to suggest some more flexibility in the use of assert(), i.e. it could be made possible that an assert is only evaluated for each 'accepted' step of the integrator, or even only when results are stored, on an event, etc. This would allow us to do consistency checks as before, which is a lot more convenient. Also it could limit the computational overhead since we are using a lot of assert statements to do some checks (e.g. checking flow reversal, conservation of energy, etc) that do not need to be evaluated each iteration of the integrator. I did some tests and this computation time is not negligible.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2110

**Comment by HansOlsson** [comment]
It was entirely clear exactly how to improve this, and how much was tool-specific. Thus closing to get better overview.
