### ISSUE TITLE
Prohibit clocks as input for hold

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2174]
**Reported by jfrenkel on 31 Mar 2017 08:44 UTC**
Since the type `Clock` is a base type it is a Component Expression and Component Expression are valid as input for `hold`.
But the result of a holded Clock seems useless or at least obfuscating.
Hence Clocks as input for `hold` should be prohibited.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2174

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 10 May 2017 14:56 UTC**
Replying to [ticket:2174 Jens Frenkel]:
> Since the type `Clock` is a base type it is a Component Expression and Component Expression are valid as input for `hold`.
> But the result of a holded Clock seems useless or at least obfuscating.
> Hence Clocks as input for `hold` should be prohibited.

It says that the input to `hold` is a clocked Component Expression, and for clocked variables it says:
"The elements of clocked variables r(ti) are of base type Real, Integer, Boolean, enumeration, String that are associated uniquely with a clock c(ti)."

A simple way of stating this is that: clock variables are not clocked variables!

Thus it seems this restriction is already present, and we can close this ticket.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 18 May 2017 15:13 UTC**
Language group:
The restrictions are not clear - it references 16.2.3 is referenced, but does not defined "clocked component expression" ("clocked" is defined in 16.2.1).
Could be other similar cases as well.
Combining "clocked" and "component expression" gives the restriction.

**Comment by HansOlsson** [comment]
There is a decision, but the text isn't updated yet.
