### ISSUE TITLE
Improve specification of clock constructors with respect to dimensionality

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2177]
**Reported by Michael Schellenberger Costa on 4 Apr 2017 12:01 UTC**
Hi,

in the specification section 16.3 Clock "Constructors" there is no reference to the dimensionality of the constructor arguments, e.g. "intervalCounter" or "interval". As in the latter text arrays of clocks are explicitely mentioned, I would assume that multidimensional arguments are valid and the following example from the spec:
```
    Clock c1[3] = {Clock(1), Clock(2), Clock(3)};
```
would be equivalent to:
```
    Clock c2[3] = Clock({1, 2, 3});
```
I would therefore propose to expand the description of the clock constructors with a remark that either allows or dissallows this. We would also have to add restrictions regarding optional parameters, as they have to either be of the same dimensionality or scalar with implicit expansion.

The same also applies for all functions defined in sections 16.5.2 "Sub-clock conversion operators", e.g 
```
    Clock c3[3] = subsample(Clock({1, 2, 3}), 5).
```

However, this makes no sense in clocked When-Statements
```
    when Clock({1, 2, 3}) then ...
```
as in that case clock inference is impossible. Sadly the spec only states:
```
when clock-expression then
    clocked-equation
    …
end when;
```
I would propose to add a sentence, that specifies that clock-expression must be a scalar for clocked When-Statements.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2177

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 10 May 2017 14:45 UTC**
If the intent were to allow construction of arrays of clocks it seems quite odd that it is missed in the current text.

I would propose that we first make it explicit that only scalar calls of clock-constructors are allowed - and similarly when using clock-expressions, since it seems the most restricted.

We call later investigate if arrays of clocks is natural - including the handling of e.g. `sample(x, c)` if `c` is an array of clocks.

**Comment by HansOlsson** [comment]
Proposal:

No vectorization: 
Only scalar calls of the clock-constructors are allowed and any operator taking clock expressions only take scalar clocks.

And change (should likely be separate PR):
In 16.2.3: https://specification.modelica.org/master/synchronous-language-elements.html#argument-restrictions-component-expression
The built-in operators in this chapter may not be called in functions.

**Comment by HansOlsson** [comment]
None of the operators can be vectorized, but can for some pass through a vector as clock expression.
And not callable in functions.
Agreement.
