### ISSUE TITLE
Clarifications for MCP-0014: automatic conversions of models

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2178]
**Reported by jmattsson on 7 Apr 2017 09:59 UTC**
While considering the implications of the newly defined conversion scripts, we came across a few things that need clarification.

1. The new text contains: "Both convertElement and convertModifiers only use inheritance among user models". Shouldn't this apply to all conversions? In particular, this example shows a case where the restriction would be good for `convertClass` & `convertClassIf`:
```mo
package Lib
    package A
        model C
        end C;
    end A;
    package B
        model C
        end C;
    end B;
annotation(version=1);
end Lib;

package Lib
    package A
        model C
            // Moved here from B.C in version 1
        end C;
    end A;
    package B
        extends A;
    end B;
    package D
        model E
            // Moved here from A.C in version 1
        end E;
    end D;
annotation(version=2, conversion(from=1, change={
    convertClass("A.C", "D.E");
});
end Lib

model User
    Lib.B.C x;
end User;
```
2. The description of `convertClassIf` says that it should be performed if "the literal modifier for oldElement has the value whenValue". What does "the literal modifier" mean here? Should it be the exact text? Does the modifier have to be a literal in the Modelica syntax sense? If it should be a literal, does it have to be written exactly like that? If we have `convertClassIf("A", "x", "1.0", "B")`, does `(x = 1.)` match? Does `(x = 1)`? `(x = "1.0")`? Can you match on enumeration values, e.g. "Colors.red"?
1. Does string literals have to be escaped, i.e. `"\"abc\""`? It seems that they have to be for `convertModifiers`, since it would be impossible to parse reliably otherwise. For `convertClassIf` it isn't as clear, but being consistent with `convertModifiers` seems like a good idea. In any case it would probably be good to clarify.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2178

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 7 Apr 2017 10:02 UTC**
Syntax highlighting seems to be broken in the upgraded Trac.
```mo
model Test "abc"
```

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 10 May 2017 13:23 UTC**
Replying to [ticket:2178 Jesper Mattsson]:
> While considering the implications of the newly defined conversion scripts, we came across a few things that need clarification.
> 
> 1. The new text contains: "Both convertElement and convertModifiers only use inheritance among user models". Shouldn't this apply to all conversions? 

Yes, it should be made clear that it apply to all. 

However, the issue for convertElement and convertModifiers is quite common  - but moving classes in packages that are extended from seems a bit special.

> 1. The description of `convertClassIf` says that it should be performed if "the literal modifier for oldElement has the value whenValue". What does "the literal modifier" mean here? Should it be the exact text? Does the modifier have to be a literal in the Modelica syntax sense? If it should be a literal, does it have to be written exactly like that? If we have `convertClassIf("A", "x", "1.0", "B")`, does `(x = 1.)` match? Does `(x = 1)`? `(x = "1.0")`? Can you match on enumeration values, e.g. "Colors.red"?

Restricting it to a literal without any fancy stuff will likely suffice - combined with a clarification for enumeration (so that it will not matter if you write `A.Colors.red` `.A.Colors.red` or `Colors.red` combined with `import A.Colors;`).

The usual idea would be to use multiple convertClassIf to convert it to different classes depending on the value of `x`. That requires that you can enumerate the possible values of `x` - i.e. it has be a Boolean or possibly enumeration/Integer.

People normally don't write `1>2` instead of `false` - but they might write `p` where p is parameter with default value 'true' - and that case can anyway not be automatically handled in a good way (unless there is a default-case using convertClass or convertMessage).

> 1. Does string literals have to be escaped, i.e. `"\"abc\""`? It seems that they have to be for `convertModifiers`, since it would be impossible to parse reliably otherwise. For `convertClassIf` it isn't as clear, but being consistent with `convertModifiers` seems like a good idea. In any case it would probably be good to clarify.

Yes, and should be clarified.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 11 May 2017 13:26 UTC**
Using new version to mark these as reported defects for Modelica 3.4 Specification.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 18 May 2017 15:25 UTC**
Language group:
Agreement on 1 (generalize statements to all convert-variants) and 3 (need to quote strings).
Enumeration part of 2 is unclear - wait for actual examples.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 10 Jan 2018 08:19 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by hansolsson on 21 Mar 2018 08:22 UTC**

**Comment by jespermattsson** [comment]
The enumeration part isn't resolved. In addition to Hans' comment about matching for different ways of writing the enumeration literal in the model, it also isn't clear how you should write the literal in the conversion rule.

**Comment by HansOlsson** [comment]
Added that part as new issue, to better keep track of issues.
