### ISSUE TITLE
Erroneous example for Inferencing of solverMethod

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2182]
**Reported by jfrenkel on 24 Apr 2017 08:21 UTC**
In chapter **16.8.4 Inferencing of solverMethod** the example `model InferenceTest` is erroneous.

```
model InferenceTest
  Real x1;
  Real x2;
  Real z1;
  Real z2;
  Real w;
  Real ww;
equation
  // Physical model
  der(x1) = -100*x1 + hold(z2);
  x2 = x1+time;

  // Controller submodels
  der(z1) = -100*z1 + sample(x2, Clock(Clock(1, 100), solverMethod="ImplicitEuler"));
  w = 0.9*previous(w) + superSample(z1, 3);
  when Clock(Clock(1,20), solverMethod="ExplicitEuler") then
    ww = superSample(w);
  end when

 der(z2) = -z2 + ww;
end InferenceTest;
```

The clock of z1 is Clock(1, 100). 
The clock of w is super sampled with a factor of 3.
For this reason the clock of w is Clock(1, 300).
The clock of ww is Clock(1,20). Hence the confersion from w to ww should be a
subsample with a factor of 15 and not a supersample because the clock of w is slower than the clock of ww.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2182

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 10 May 2017 14:20 UTC**
Your analysis seems correct, and Dymola gives the same result as error message:

Deduced non-integer supersampling factor for superSample(w)
in ww = superSample(w);
.
The argument was deduced to have the period superSample(Clock(1, 1), 300).
The equation was deduced to have the period superSample(Clock(1, 1), 20).
It implies a non-integer supersampling factor of 1/15.

And a semi-colon is also missing after "end when".

However, changing to subsample Dymola indicates that the solverMethods are inconsistent - so we need to investigate the example in more detail.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 11 May 2017 13:26 UTC**
Using new version to mark these as reported defects for Modelica 3.4 Specification.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 18 May 2017 16:33 UTC**
B. Thiele to make better example.

Modified it to:
```
model InferenceTest
  Real x(start=3) "Explicitly using ExplicitEuler";
  Real y "Explicitly using ImplicitEuler method";
  Real z "Inferred to use ExplicitEuler";
equation 
  der(x)=-x+sample(1,Clock(Clock(1,10), solverMethod="ExplicitEuler"));
  der(y)=subSample(x,2)+sample(1,Clock(Clock(2,10), solverMethod="ImplicitEuler"));
  der(z)=subSample(x,2)+1;
end InferenceTest;
```

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 May 2017 10:38 UTC**
Trying to rephrase specification:
For each sub-clock partition with continuous-time equations we iteratively build a set of sub-clock partition - by adding any sub-clock partitions (with or without specified solverMethod) that are connected to a sub-clock partition in the set without a specified solverMethod.
->
For each sub-clock partition with continuous-time equations we iteratively build a set starting from this sub-clock partition. For each sub-clock partition in the set without a specified solverMethod, we add all sub-clock partitions connected to them; and repeat this until convergence.

If this set contains multiple different solverMethods it is an error.
If this set contains no solverMethod it is an error or use explicit Euler?
Otherwise we use the specified solverMethod.
[Thus two sub-clock partitions can be connected and specify different solverMethod.]

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 6 Oct 2017 06:10 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2017 12:00 UTC**
Next attempt:

For each sub-clock partition we build a set corresponding from this sub-clock partition. 
These sets are then merged as follows: for each set without a specified solverMethod we merge it with sets connected to it (these may contain a solverMethod); and this is repeated until it is not possible to merge more sets.
If this set contains multiple different solverMethods it is an error.
If the set contains continuous time-equations:
* If this set contains no solverMethod it is an error.
* Otherwise we use the specified solverMethod.
If the set does not contain continuous time-equations there is no need for a solverMethod.

*: Using e.g. subsample connects the two partitions.

Agreement.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2017 12:04 UTC**
Illegal example:
```
model InferenceTest "Illegal"
  Real x(start=3) "Explicitly using ExplicitEuler";
  Real y "Explicitly using ImplicitEuler method";
  Real z ;
equation 
  der(x)=-x+sample(1,Clock(Clock(1,10), solverMethod="ExplicitEuler"));
  der(y)=subSample(x,2)+sample(1,Clock(Clock(2,10), solverMethod="ImplicitEuler"));
  der(z)=subSample(x,4)+1+subSample(y);
end InferenceTest;
```
Here z is a continuous-time equation connected directly to both x and y partitions that have different solverMethod.

**Comment by modelica-trac-importer** [comment]
**Comment by jfrenkel on 19 Oct 2017 12:23 UTC**
Replying to [comment:7 Hans Olsson]:
> If the set contains continuous time-equations:
> \* If this set contains no solverMethod it is an error.
> \* Otherwise we use the specified solverMethod.

I prefer to use External in case no solverMethod is specified because it works better in combination with the case of a not supported solverMethod.
"If a tool does not support the integration method defined in a model, typically a warning message is printed and the method is changed to “External”"

**Comment by modelica-trac-importer** [comment]
**Modified by hansolsson on 25 Oct 2017 08:09 UTC**

**Comment by henrikt-ma** [comment]
The commit 93631c67075416ae9a83d2c78e6259e2c8e3557a failed to do this part:
*: Using e.g. subsample connects the two partitions.

**Comment by HansOlsson** [comment]
> The commit 93631c6 failed to do this part:
> *: Using e.g. subsample connects the two partitions.

This should now be corrected. (As well as other issues.) I
