### ISSUE TITLE
Description of overriding of access protection is confusing

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2193]
**Reported by jriel on 21 Jun 2017 18:05 UTC**
In section 18.9.1 of the Modelica Language 3.3 Rev 1 spec is this paragraph

  The access annotation holds for the respective class and all classes that are hierarchically on a lower level, unless overriden by a Protection annotation with access [e.g. if the annotation is given on the top level of a package and at no other class in this package, then the annotation holds for all classes in this package].
Overriding access=Access.hide and access=Access.packageDuplicate has no meaningful effect.

That last sentence is confusing.  If one cannot override either
extreme, than what can one override?  The implication is that one
cannot make protection either more or less restrictive.

The way it should work is that the access level is set by the enclosing explicit declaration.  If there is none, than the default
is in effect. 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2193

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 22 Jun 2017 07:53 UTC**
Replying to [ticket:2193 jriel@…]:
> In section 18.9.1 of the Modelica Language 3.3 Rev 1 spec is this paragraph
> 
>   The access annotation holds for the respective class and all classes that are hierarchically on a lower level, unless overriden by a Protection annotation with access [e.g. if the annotation is given on the top level of a package and at no other class in this package, then the annotation holds for all classes in this package].
> Overriding access=Access.hide and access=Access.packageDuplicate has no meaningful effect.
> 
> That last sentence is confusing.  If one cannot override either
> extreme, than what can one override?  

I believe the last sentence should just be a non-normative comment with additional explanation:

If Open.Hidden has access=Access.hide it is hidden and we cannot inspect any part of that package - where would we see the class Open.Hidden.Icon in e.g. package browser if it had access=Access.icon?

If Open has access=Access.packageDuplicate it states that we can copy that the package itself  - and that copy should include a copy of Open.Hidden. Whether you can copy Open.Hidden directly or not hardly matters.

**Comment by HansOlsson** [comment]
Language group:: 
Overriding “access=Access.hide” has no effect. Overriding “access=Access.packageDuplicate” has no effect, since it will not prevent copying the entire package including this class.
Favor: 3
Overriding “access=Access.hide” or “access=Access.packageDuplicate” is not possible.
Favor: 1
Overriding “access=Access.hide” or “access=Access.packageDuplicate” has no effect. 
Favor: 6
Overriding “access=Access.hide” or “access=Access.packageDuplicate” is an error.
Favor 3

Conclusion: Overriding “access=Access.hide” or “access=Access.packageDuplicate” has no effect.
