### ISSUE TITLE
Incomplete for-loop semantics in Modelica specification

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2205]
**Reported by cbuerger on 2 Oct 2017 13:26 UTC**
The specification of the semantics of `for` loops is incomplete. The specification of Section **11.2.2 For-statement** states:
_The expression of a for-statement shall be a vector expression. It is evaluated once for each for-statement, and is evaluated in the scope immediately enclosing the for-statement. The loop-variable (IDENT) is in scope inside the loop-construct and shall not be assigned to. The loop-variable has the same type as the type of the elements of the vector expression._

Nothing is said about the actual values of `IDENT` throughout execution, i.e., about execution semantics. Although there are examples given with comments for the value of the iteration variable, it is nowhere defined. This holds also for the very simple case of a vector expression.

Further, the Section is very similar to Section **8.3.2 For-Equations – Repetitive Equation Structures**; for sake of clarity and consistency Section 8.3.2 should just forward to Section 11.2.2 or vise-versa. Section 8.3.2 suffers from the same problem of incomplete semantics as Section 11.2.2.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2205

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 3 Oct 2017 14:17 UTC**
While we're at it, I think there should also be an explanation why the expression needs to be a vector expression.  To me, this is just a confusing limitation.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 3 Oct 2017 14:22 UTC**
@Henrik: What else would you want to iterate over?

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 3 Oct 2017 14:55 UTC**
I don't know exactly what Henrik was thinking of, but one could imagine iterating over a matrix (or higher-dimensional array) instead of just a vector, but unfortunately there are two conflicting interpretations:
* iterate over all elements of the matrix
* iterate over each row (or column) of the matrix
and without good use-cases we cannot say which one is preferable, and it seems we need a different ticket for this.

The case of a vector of records (or operator record) should hopefully already work.

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#46;se on 3 Oct 2017 16:24 UTC**
If you have a 2D variable, you just call `vector(x)` and iterate over that directly in a reduction or loop. If you want to iterate over the 1D vectors of `x` you currently need to use size operators, ranges and for statements. So it seems logical that you would want to be able to iterate over the vectors in a matrix (if anything).

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 4 Oct 2017 06:01 UTC**
Right.  I don't have a good example of how iterating over a higher-dimensional array would be useful in the case of a `for` equation, but the same phrase is used in the case of reduction expressions in section 10.3.4.1, and `for` statements in section 11.2.2.  Even if higher-dimensional arrays would be an esoteric construct in the case of `for` equations, I don't think that the specification should forbid them per se, but rather leave it to the user to find out that it may not be that useful.  Let's talk about the one of the useful cases instead, say reduction expressions.

I have a type `T`, a function from `T` to `Real`, and a vector with elements of type `T`; why should I not be able to do a `sum` reduction of my elements?
```
partial model ReductionOfVectors

  type T = Real[3];

  function f
    input T x;
    output Real y;
  algorithm
    y := x[1] * x[2] + x[3];
  end f;

  T[5] xx;
  Real acc;

equation
  
  acc = sum( f(x) for x in xx );

end ReductionOfVectors;
```

(By the way, what has happened to the `modelica` macro processor?)

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 4 Oct 2017 07:27 UTC**
I agree that Henrik's example seems to make sense; but I think it would be better to have it in a separate ticket (as it is an enhancement).

Replying to [comment:4 Martin Sjölund]:
> If you have a 2D variable, you just call `vector(x)` and iterate over that directly in a reduction or loop. 

But that only works if it is a row or column-matrix, not for general matrix (well, generalizing `vector(x)` is of course a possible proposal).

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Oct 2017 10:02 UTC**
To discuss at meeting. Some should be possible to trivially close.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 13 Oct 2017 09:42 UTC**
Replying to [comment:4 Martin Sjölund]:
> If you want to iterate over the 1D vectors of `x` you currently need to use size operators, ranges and for statements.

Or you can let the tool handle that by excluding the `in` part (in current Modelica):
```mo
for i loop
  x[i,:] = f(i);
end for;
```
That works for reduction expressions, iterating over columns instead, etc. The only thing I can think of that it doesn't work for is when you want to use two arrays of different sizes, e.g. `x[i] + y[i]`, where x and y have different sizes, but there it's probably better to require the user to specify the range explicitly anyway.

As for Henrik's example with `type`, I'd say that the problem is that e.g `Real[5,3]` is in the spec clearly described as a matrix or a 2-dimensional array - _not_ as a vector of vectors, as in some languages. But on the other hand, `T[5]` (with `T = Real[3]`) is clearly logically a vector of vectors but is still in the language equivalent with `Real[5,3]`. I think that we must either pick one interpretation for both of them and stick with it (this is the current situation, i.e. both are matrices not vectors of vectors), or make them actually be different things that aren't type compatible.

**Comment by modelica-trac-importer** [comment]
**Comment by cbuerger on 13 Oct 2017 10:19 UTC**
With regard to my original intent, I think your last example:
```
for i loop
  x[i,:] = f(i);
end for;
```
shows that the current specification needs to concisely state what the values of iteration variables throughout iteration are. There are many ways to define iteration ranges in Modelica, each with its implicit semantics for the value of iteration variables (vector, range expression, implicit as in your example). I am not sure, if semantics are already well-defined for each and just scattered all-over the specification or if we indeed miss to specify some cases. If they are already well-defined, we should at least link to the respective places in the `for`-loop section and/or unify them.

Anyway, Sections **11.2.2** and **8.3.2** should be aligned and duplications eliminated.

**Comment by modelica-trac-importer** [comment]
**Comment by henrikt on 13 Oct 2017 11:35 UTC**
My proposal regarding the restrictions to _vector expressions_ has been filed separately as #2208.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2017 15:03 UTC**
The loop-variable has the same type as the type of the elements of the vector expression.
->
The body of the for-loop is evaluated once for each outermost element of the evaluated array expression, and the loop-variable has that value, in the normal order.

And ensure that no duplication between 11.2.2 and 8.3.2.

Agreement by acclamation.

**Comment by modelica-trac-importer** [comment]
**Modified by hansolsson on 25 Oct 2017 08:28 UTC**

**Comment by HansOlsson** [comment]
When attempting to add this decision to the specification I came to two conclusions:

- The new text is as confusing as before.
- We should have a common sub-section for the common part between for-equations and for-statements, and then in for-equations refer to that common part and add the unique part (it must be a parameter expression).

I find the new text is confusing since the full paragraph is (italic for old and bold for new):

The \lstinline!expression! of a for-statement shall be a vector expression. It is
evaluated once for each for-statement, and is evaluated in the scope
immediately enclosing the for-statement. The loop-variable (\lstinline!IDENT!) is in
scope inside the loop-construct and shall not be assigned to. _The
loop-variable has the same type as the type of the elements of the
vector expression._
**The body of the for-loop is evaluated once for each outermost element of the evaluated array expression, and the loop-variable has that value, in the normal order.**

Issues:

- At the start it is called a "vector expression", but at the end it is called "array expression".
- We don't use "outermost" anywhere else.
- It is not clear what "that value" refers to and when the loop-variable has "that value".

I would propose something like:
...
shall be a vector expression, **where more general array expressions are treated as vector of vectors or vector of matrices.**.
...
**The iteration range of a for-equation can also be specified as Boolean or as an enumeration type, see
\autoref{types-as-iteration-ranges} for more information.**
**For each element of evaluated vector expression, in the normal order, the loop-variable gets the value of that element and that is used to evaluate the body of the for-loop.**

And add this in the section on for-equations, and only refer to it in the section on for-algorithm. (Will make a separate pull-request.)
