### ISSUE TITLE
Memory allocation functions for external functions/objects

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2215]
**Modified by beutlich on 22 Nov 2017 14:58 UTC**
External objects (e.g., the CombiTables of the MSL) and possibly also external functions allocate memory using the provided allocation functions of the C runtime. If external objects are exported in FMUs, they still use their own allocation functions instead of the one provided by the FMI.

For me it looks that FMI introduced these customized allocation functions, which are not yet supported by Modelica external C  functions/objects.

Is this a tool, library or specification issue? Is it an issue at all?

----

**Reported by beutlich on 17 Nov 2017 11:57 UTC**
External objects (e.g., the CombiTables of the MSL) and possibly also external functions allocate memory using the provided allocation functions of teh C runtime. If external objects are exported in FMUs, they still use their own allocation functions instead of the one provided by FMI.

For me it looks that FMI introduced these customized allocation functions, which are not yet supported by Modelica external C  functions/objects.

Is this a tool, library or specification issue? Is it an issue at all?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2215

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 17 Nov 2017 21:55 UTC**
Thinking more about it, the cleanest solution is simple and straightforward: ModelicaUtilities.h should be extended by the following new utility macros

```c
#ifndef ModelicaAllocateMemory
#define ModelicaAllocateMemory(size, num) calloc(size, num)
#endif
#ifndef ModelicaFreeMemory
#define ModelicaFreeMemory(ptr) free(ptr)
#endif
```

> Is this a tool, library or specification issue?

So, yes, it is all of them. The specification needs to update section 12.9.6 on the new redefintion options of the utility functions, the MSL C-Sources need to take the new utility functions into account and tool vendors are free to implement alternative utility functions, such that the simulation also works as expected for an FMU-exported Modelica model.
Luckily, the uthash and zlib dependencies of the MSL C-Sources already have such convenience macros for the redefinition of the allocation/deallocation functions.

> Is it an issue at all?

It might sound like an artificial issue right now, but at least it solves one more inconsistency between Modelica and FMI.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 22 Nov 2017 14:45 UTC**
It is possible to solve it by defining malloc/calloc/etc in the code that the tool adds to the FMU. They will then be used in place of the ones from the C runtime library.

An actual specified approach such as what you propose would probably be better, though.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 22 Nov 2017 14:50 UTC**
Yes, as long as tools deal on source code level it is fine.

But if custom libraries (static or dynamic linked ones, does not matter) are involved, we even must rely on exported functions ModelicaAllocateMemory/ModelicaFreeMemory since FMU-exporting Modelica tools have full control of the ModelicaUtilities only.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 22 Nov 2017 14:58 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 22 Nov 2017 15:02 UTC**
Replying to [comment:3 Thomas Beutlich]:
> But if libraries (static or dynamic linked ones, does not matter), we even must rely on exported functions ModelicaAllocateMemory/ModelicaFreeMemory since FMU-exporting Modelica tools have full control of the ModelicaUtilities.

I'm sorry, I don't understand what you mean here.

In JModelica.org, we implemented the approach I described to get an external dependency (that we included as a static library when linking the FMU dll) to use the alloc/free provided by the environment loading the FMU. It does not work on external libraries in dlls, since they are already linked to specific implementations of alloc/free. That problem wouldn't be solved by your approach either - the DLL can often be an external dependency for the user as well (i.e. they can't recompile it).

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 22 Nov 2017 15:04 UTC**
Replying to [comment:5 Jesper Mattsson]:
> I'm sorry, I don't understand what you mean here.

I edited my previous post. Is it clearer now? We probably mean the same w.r.t. DLL libraries.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 24 Nov 2017 10:19 UTC**
Replying to [comment:6 Thomas Beutlich]:
> I edited my previous post. Is it clearer now? We probably mean the same w.r.t. DLL libraries.

Partially. If you mean that whenever external code is used, then the approach I described doesn't work - then on the contrary, it does work for external code in a static library (assuming they do use alloc/free and not some other memory allocation method) since it isn't liked to actual implementations of the functions until they are linked into a DLL or EXE.

That said, it is fragile in many ways (won't work for Fortran, maybe not C++ depending on implementation, wont work for DLLs, etc.) so a formalized way to do it would be better. However, using defines in the way you describe means that if you have your external code in a static library, then the library must be compiled separately for each tool (since defines are resolved during compilation, not during linking).

Also, for the external code from a DLL case, the user will have to implement some mechanism to pass the alloc/free functions to the DLL anyway, since the tool runtime lib won't be available when linking the DLL.

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 24 Nov 2017 10:37 UTC**
This problem is not limited to memory allocation. If you are using the i/o system there is most likely a global state for standard input and output, and you had better use compatible runtime libraries.

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 10 Jan 2018 08:23 UTC**

**Comment by beutlich** [comment]
Memory management functions will be removed for FMI 3.0.0 (https://github.com/modelica/fmi-standard/pull/928) and deprecated for FMI 2.0.2 (https://github.com/modelica/fmi-standard/issues/931). No need to keep this issue open any longer.
