### ISSUE TITLE
Update MCP Template Documents

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2218]
**Modified by beutlich on 7 Dec 2017 15:04 UTC**
The MCP Template Documents are still on 3.3 and need to be updated to reflect the 3.4 specification structure and availability.

MCP_Template_Overview.dotx
MCP_Template_Overview.html
MCP_Template_SpecChanges.doc
MCP_Template_SpecChanges.html

----

**Reported by beutlich on 7 Dec 2017 15:04 UTC**
The MPC MCP Template Documents are still on 3.3 and need to be updated to reflect the 3.4 specification structure and availability.

MCP_Template_Overview.dotx
MCP_Template_Overview.html
MCP_Template_SpecChanges.doc
MCP_Template_SpecChanges.html

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2218

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 7 Dec 2017 15:04 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 10 Jan 2018 08:23 UTC**

**Comment by HansOlsson** [comment]
I believe this is (mostly) solved in #2301 and that we can close this issue.
Note that:

- Specification change document is gone. We should make a pull-request with the actual changes instead.
- HTML document is converted to markdown. (The Word-document is kept to preserve the possibility to make drawings etc without creating friction for the creative process.)

**Comment by HansOlsson** [comment]
Seems that it is resolved as indicated above.
