### ISSUE TITLE
Redeclarable by Parameter

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2228]
**Reported by matt&#x2e;waddell on 8 Feb 2018 14:10 UTC**
Hi, My name is Matt, and I'm an Engineer at United Technologies, currently using Dymola/Modelica to model a number of systems. I've run into a problem, and I don't think Modelica currently has a solution for it. I'm trying to make a part re-declarable based on the users selection of an enumeration. I.E. if the user selects one value in the enumeration a part gets redeclared as A, else if B, else C, etc. The other solution to this is to use the Choices annotation with replaceable, and the user can manually select the part, however, there is know was for the code to know which model the user redeclared the part as. (The model structure changes based on which component the user selects). It would be nice if I could somehow reference a components class type inside the code. Example: Interfaces.Flowport inlet[nPorts]; Interfaces.PressurePort outlet[nPorts]. I would then like a function all: getClass(inlet) which would return "FlowPort". If you have any questions, or would like an example snippet of code, please let me know. Thanks, Matt 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2228

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Feb 2018 15:57 UTC**
Matt,

In order to analyze this we will likely need more complete examples.

Of the two alternatives above it seems that the redeclare-variant is the simplest to get to work and also the most problematic.
You could make it work by adding a "final parameter Enumeration ...=..." in each of the options and test for that.
However, the problem is that redeclarations are open-ended - i.e. a user can redeclare with any class satisfying the constraints - and the code that does different things depending on the class cannot know about any new alternatives.

For the other alternative there are already ideas of making redeclarations depending on parameters, but it is not unproblematic.

However, you can emulate it by having a class with conditional components that are enabled/disabled based on the enumeration-value. Have you tried this alternative? Are there any severe disadvantages?

**Comment by modelica-trac-importer** [comment]
**Comment by matt&#46;waddell on 12 Feb 2018 17:10 UTC**
Hi Hans, thanks for the replay, here's a couple snippets of code to hopefully better explain what we're trying to do. 

Example 1 - Using enumeration: 
  type PortType = enumeration(
      flow_model,
      pressure_model);

  parameter PortType portType=PortType.flow_model;

//if statement causes an error
  replaceable connector inletPortModel =
      if portType == PortType.flow_model then FlowPort else PressurePort;
//this works
  replaceable connector outletPortModel = PressurePort;

  inletPortModel inlet;
  outletPortModel outlet;
equation
if portType == PortType.flow_model then 
//structure 1
else if if portType == PortType.pressure_model then 
//structure 2


In this example, we want to make the declaration of the parameter based on an enumeration. Unfortunately, the code above does not actually work, but it would be a very simple way to accomplish our task. 

Example 2 - Redeclare by choices:

replaceable FlowPort inlet[nPorts_in] annotation (choices(choice(redeclare FlowPort inlet[nPorts_in]),choice(redeclare PressurePort inlet[nPorts_in])));

equation
if inlet == FlowPort then 
//structure 1
elseif inlet == PressurePort then 
//structure 2

in example 2, there is no way for the user to determine which choice the user made.


For a better explanation of what we're trying to do.. we're making a variable structure segmented pipe model which has an inlet port, and outlet port, an array of flow models, and an array of volume models. In the equation section, we then have for loops to make connections between the flow models and volume models. The structure the user selects determines the order that the components get connected. Start with flow/volume, end with flow/volume. 

The problem with using conditional components is when changing the structure on the higher level, connections will need to be remade as two conditional components cannot have the same name. I would need an inlet1, inlet2, outlet1, and outlet2. 

We do have this model working if we don't change the connector ports on either side of the model. We can use Booleans to change the order of connections, but it would be nice to change the port models for icon reasons. I don't see any reason why one of the two solutions above shouldn't work, you can do both of those things in many other coding languages.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2018 08:38 UTC**
Cleaning up unspecified tickets to prepare for move to GitHub

**Comment by HansOlsson** [comment]
No discussion for more than two years. Closing, but it can be reopened if we get more information.
