### ISSUE TITLE
Component variable reference with Replaceable Redeclare

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2233]
**Reported by matt&#46;waddell on 14 Feb 2018 15:11 UTC**
I'm trying to make a model in which one of the components can be swapped out for any number of models, and I'm using the replaceable functionality to do so, along with he "choices" annotation. During the redeclare, I would like like to reference variables on the component level, but am unable to do so.. here is an example.. 

model pipe 
  parameter SI.Length L=0.254 "Line Length" annotation(Dialog(group="Common"));
  parameter SI.Diameter D=0.0254 "Line Diameter" annotation(Dialog(group="Common"));
  parameter Real K = 0 "Minor loss coefficient";
  parameter SI.Position dz = 0 "Height_out - height_in";
  parameter Real LOD = 0 "Effective length over diameter";

 replaceable Restrictions.PipeLoss R[n](each L=L,
    each D=D) "Resistance Model"
    annotation (choices(choice(redeclare Restrictions.PipeLoss_Detailed R[n](
    each L=L,
    each D=D,
    each dz=dz/n,
    each LOD=LOD/n,
    each K=K/n) "Segmented Moody")),Placement(transformation(extent={{-30,-10},{-10,10}})));

end pipe;

This checks without any issue, however, when I drag this pipe model into a system model, and try redeclaring "R" I get a bunch of errors saying the variables do not exist. This is because the redeclaration happens at the system level, where as the variables being referenced are on the component level. The redeclaration should theoretically be: 

annotation (choices(choice(redeclare Restrictions.PipeLoss_Detailed R[ComponentName.n](
    each L=ComponentName.L,
    each D=ComponentName.D,
    each dz=ComponentName.dz/ComponentName.n,
    each LOD=ComponentName.LOD/ComponentName.n,
    each K=ComponentName.K/ComponentName.n) "Segmented Moody")),Placement(transformation(extent={{-30,-10},{-10,10}})));

The feature I'm suggesting, trying to use, would be very similar to the "this" operator in java where you can reference variables by typing this.L or this.D

Is there currently a way to do this in modelica? If not, is there any plans to implement a feature like this? I feel as though it could be very beneficial in object oriented programming. 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2233

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Oct 2018 08:38 UTC**
Cleaning up unspecified tickets to prepare for move to GitHub

**Comment by HansOlsson** [comment]
No discussion for more than two years, to me it seems as if this would work without any modifiers on the redeclared component due to how parameters of replaceable components are handled. Closing, but it can be reopened if we get more information.
