### ISSUE TITLE
Overriding descriptions in modifiers

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2237]
**Reported by hansolsson on 2 Mar 2018 11:31 UTC**
The semantics of description strings on modifiers should be clarified.

One interpretation is that they are descriptions of the modifications themselves (this is used in e.g. Dymola), another is that (if present) they override the description of the original element (used in Simulation X) - and is thus used in e.g. parameter dialogs, summary of connectors, and in tooltips.

The latter seems useful, e.g.:
```
block Division "Output first input divided by second input"
  extends Modelica.Blocks.Interfaces.SI2SO(
    u1 "Dividend",u2 "Divisor", y "Quotient u1 / u2");
equation
  y = u1/u2;
end Division;
```
It does not seem as overriding description will cause an overhead in an implementation, since it is just one string or the other and no additional lookup or scoping.

Obviously if the description string is missing from the modifier nothing is changed. Redeclarations might need further investigation.

Based on https://github.com/modelica/Modelica/pull/2471#issuecomment-368647725

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2237

**Comment by modelica-trac-importer** [comment]
**Comment by perost on 2 Mar 2018 12:02 UTC**
Redeclarations are also allowed to have annotations according to the grammar, but I don't think the semantics of such annotations are specified either.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 2 Mar 2018 16:42 UTC**
Replying to [comment:1 perost]:
> Redeclarations are also allowed to have annotations according to the grammar, but I don't think the semantics of such annotations are specified either.

True - but that is considerably more complex (we have experimented with it in Dymola): they might involve lookup, hierarchical merging, etc. 
Thus that would likely need an MCP - including analyzing the benefits and costs; and as I recall it is already part of some user-defined annotation MCP.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 20 Mar 2018 13:56 UTC**
Language group:
Description string of modifier overrides if present. (Nothing special for redeclarations.)

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 23 Mar 2018 08:05 UTC**

**Comment by beutlich** [comment]
@ooer FYI
