### ISSUE TITLE
MCP-0030 IsClocked Operator

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2238]
**Reported by jfrenkel on 9 Mar 2018 13:05 UTC**
Describing the synchronous behavior of control systems is possible with the Synchronous Language Elements. But checking if a class is used in the continuous-time partition or a clocked partition is not possible. The `isClocked` operator address the issue of checking the usage of Component Expression in clocked or continuous-time partitions. The benefit would be improved error messages of misused classes in clocked or the continuous-time partition.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2238

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Mar 2018 09:35 UTC**
Having some examples would be helpful, and in particular define what the errors this can detect and the current possibilities - in order to better understand this.

Note that we technically have three categories (after clock partitioning): not clocked (continuous-time), clocked discrete-time and clocked discretized continuous-time.

Using `der(x)` implies that it cannot be part of "clocked discrete-time".
Using `when Clock()` implies that it is clocked.

Is `when Clock()` not usable in these cases, or is the goal to check that the class cannot be clocked?

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 12 Mar 2018 12:12 UTC**
There are some test cases in the internal MCP directory, in case you missed them: https://svn.modelica.org/projects/MCP/MAinternal/MCP-0030_IsClocked_Operator/TestModels

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 12 Mar 2018 13:01 UTC**
Replying to [comment:2 Thomas Beutlich]:
> There are some test cases in the internal MCP directory, in case you missed them: https://svn.modelica.org/projects/MCP/MAinternal/MCP-0030_IsClocked_Operator/TestModels

I actually missed the existence of the internal MCP directory, https://svn.modelica.org/projects/MCP/MAinternal/MCP-0030_IsClocked_Operator/ but I still don't see why this is needed. 

I might be missing something more; can you provide the error message for the motivational example with and without the "isClocked" - as that might help me understand the issue.

\--
As I see it:
Currently if you directly use `time` as in the Clock-block it cannot be in a clocked partition.

Requiring the user to add `assert(not isClocked())` in all models that directly use time seems superfluous to me.  

Additionally there is a risk that this assertion will be over-used also used in a model containing `der(x)` - even though it could be a clocked discretized continuous-time partition.

We might also ask if we should forbid `time` in clocked discretized continuous-time partition, since a user can write 
```
model M
  RealOutput x;
initial equation
  x=time;
equation
  der(x)=1;
end M;
```
Which generates a time-signal that can be used in a clocked discretized continuous-time partition. Clearly time can be a problem a real-time system (I remember such an issue for the Patriot missiles); but as this example shows we can get the same issue if we integrate as well.

**Comment by modelica-trac-importer** [comment]
**Comment by jfrenkel on 15 Mar 2018 15:12 UTC**
This is the error message from Dymola 2018 for the example 
`MAinternal\MCP-0030_IsClocked_Operator\TestModels\IsClockedExample.mo` :
(Line 9 comment out to avoid error messages about unknown Function isClocked)
```
Translation of IsClockedExample:

Continuous time parts and discrete parts don't decompose for:
assignClock1.clock.isTicking
assignClock1.u
assignClock1.y
Clock_0.isTicking
Clock_1.isTicking
Clock_2.isTicking
clock.y
periodicClock1.y.isTicking

Equations:
equation
if (periodicClock1.useSolver) then 
periodicClock1.y = Clock_1;
else
periodicClock1.y = Clock_2;
end if;
periodicClock1.y = assignClock1.clock;
when assignClock1.clock then
assignClock1.y = assignClock1.u;
end when;
clock.y = clock.offset+(if time < clock.startTime then 0 else time-clock.startTime);
clock.y = assignClock1.u;
Clock_1 = Clock(
Clock_0, 
periodicClock1.solverMethod);
Clock_0 = Clock(periodicClock1.period);
Clock_2 = Clock(periodicClock1.period);

Decomposition in base clocks failed.
See the file dsmodelBaseClockDecomposition0.mof.

Errors or failure to handle clock inference.

Translation aborted.

ERRORS have been issued.
```

Even for such a simple model it is difficult to see that `time` is used in the equation for `clocky`.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 15 Mar 2018 15:24 UTC**
Replying to [comment:4 Jens Frenkel]:
> This is the error message from Dymola 2018 for the example 
> `MAinternal\MCP-0030_IsClocked_Operator\TestModels\IsClockedExample.mo` :
> (Line 9 comment out to avoid error messages about unknown Function isClocked)
> ```
> Translation of IsClockedExample:

I agree that above error message wasn't ideal, and thus for the next release we have changed that error message to:

```
Continuous time parts and discrete parts don't decompose.

It is necessesary to introduce sample or hold elements replacing one of these:
  connect(clock.y, assignClock1.u);

  The following sequence indicates that the involved variables and equations are continuous time:
    clock.y : clock.y = clock.offset+(if time < clock.startTime then 0 else time- clock.startTime);
  However, this is in contradiction with
    assignClock1.u : when assignClock1.clock then
    assignClock1.y = assignClock1.u;
    end when;
```

> Even for such a simple model it is difficult to see that time is used in the equation for clocky.

I agree that this is still an issue, and we might improve it even further.
```

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 20 Mar 2018 13:25 UTC**
ESI-ITI will see if there are other issues for code-generation of models in libraries (besides time) and based on that we will revisit the ticket.

**Comment by HansOlsson** [comment]
> Comment by hansolsson on 15 Mar 2018 15:24 UTC
> I agree that above error message wasn't ideal, and thus for the next release we have changed that error message to:

For details see: https://modelica.org/events/modelica2019/proceedings/html/papers/Modelica2019paperP01.pdf

**Comment by HansOlsson** [comment]
Closing as inactive.
