### ISSUE TITLE
inStream: Bounds of expression with constant values

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2242]
**Reported by vitalij&#x2e;ruge on 27 Mar 2018 06:51 UTC**
the bounds(min, max) of an expression wiht constant value should defined as the value of the expression. 

For the example:
```
m1 = 0;
m = m;
h = positiveMax(m, eps) // positiveMax inside inStream
```
modelica tools, will simplified `h=0`. But [ModelicaSpec33](https://www.modelica.org/documents/ModelicaSpec33.pdf) p.178 we need here a defined`m.max<0` otherwiese `h=eps`.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2242

**Comment by modelica-trac-importer** [comment]
**Comment by vitalij&#46;ruge on 27 Mar 2018 09:34 UTC**
update example:
```
  m1 = 0;
  m = m1;
  h = if m.max <= 0 then positiveMax(m, eps) else 0.0 ; //inside inStream
```

after alias elimnation we get maybe
```
  h = if 0.max <= 0 then positiveMax(0, eps) else 0.0 ; //
```
the question is, have `0.max` to defined as 0.

**Comment by modelica-trac-importer** [comment]
**Comment by eshmoylova on 27 Mar 2018 14:02 UTC**
Replying to [comment:1 vitalij.ruge@…]:
> update example:
> ```
>   m1 = 0;
>   m = m1;
>   h = if m.max <= 0 then positiveMax(m, eps) else 0.0 ; //inside inStream
> ```

What are the types of m, m1, and h in your examples? The max attribute of m is determined by how m is declared. For example, if m is declared as:
```mo
Real m;
```
`m.max` is set to +Inf (see Section 4.8.1 Real Type in the specification). The max attribute is independent of the value assigned to m.

Also it is not entirely clear from your example if the expression for h is an equation written this way in the model or if it is part of the internal computation of inStream. Note that it is illegal to use `m.max` in the equation for h in a model. See section 4.8 (Specification 3.4):
 Attributes cannot be accessed using dot notation, and are not constrained by equations and algorithm sections.

**Comment by modelica-trac-importer** [comment]
**Comment by vitalij&#46;ruge on 27 Mar 2018 14:41 UTC**
the types are
```
  flow Medium.MassFlowRate m;
  flow Medium.MassFlowRate m1;
  Medium.MassFraction h;
```
the example which motivated me to write this ticket, can be found here:
https://trac.openmodelica.org/OpenModelica/ticket/4441

cite: "Other tools detect if a model sets the mass flow rate explicitly to zero" 
but the definition of inStream which use the attribute (of course modelica-tool should use, not the user inside the model) need `m.max < 0` or `m.min > 0` depend on the flower direction.

So if after alais elimnetion the  modelica tool
has `Medium.MassFlowRate m1 = 0; // m1.max= Inf, min=-Inf` the accepted simplification whit zero is wrong??
inStream should be simlified here to eps /\* max(0,eps) = eps, eps > 0, eps is real number \*/ because max, min attributes not in range for simplification.

Or maybe I wrong here and missing some part in the spefication of inStream for constant expression?

**Comment by modelica-trac-importer** [comment]
**Comment by vitalij&#46;ruge on 27 Mar 2018 14:43 UTC**
* update wrong type for ` Medium.SpecificEnthalpy h`

**Comment by HansOlsson** [comment]
Language group:
Hans - my interpretation is that it asks if we know that m>=0 can we then use the rules for m.min>=0 for instream-simplification? (And similarly for max.

Agreement by acclamation.
