### ISSUE TITLE
Standardizing  background color for images

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2244]
**Reported by hansolsson on 28 Mar 2018 15:26 UTC**
In 18.7 after "The annotation groupImage references an image using an URI (see Section 13.2.3), and the image is intended to
be shown together with the parameter-group (only one image per group is supported). Disabling the input field
will not disable the image."

add 

"The background of the groupImage should preferably be transparent (intended to be a light color) - or white."

and in 18.2 add: 
"The background of any images used in the html documentation should preferably be transparent (intended to be a light color) - or white."

Based on https://github.com/modelica/ModelicaStandardLibrary/issues/2346

There are four parts to this:
1. Why standardize?
2. What is the change?
3. Why white/light?
4. Why transparent?

Answers:

1. The reason to standardize is that this is already the current behavior for most (all?) uses in current libraries, and can be shown seamlessly in several tools (i.e. without showing an edge between the groupImage and the rest of the dialog, and similarly in html-documentation). 

Note that this does not prevent a tool from using a different background color in the parameter-dialog - and adapting the groupImage to that.

For a dark background color either the tool would need to invert the image or add a light rectangle behind the image. That is no worse than the current situation.

2. The change is that currently an image could have dark background or e.g. a gradient as background, and it is not clear how well that would work in tools, and currently nothing indicates that it shouldn't work.

The proposal makes it clear that it is not the intention to use that. (However, a tool could add e.g. a gradient to the entire parameter dialog - including the image(s); a transparent background makes that easier.)

3. White/light is the existing standard (and commonly used in other user interfaces as well) and there are several studies indicating that it is better for readability (but some studies indicating that it depends on other factors). 

Icons of models are similarly designed.

4. A transparent background (assumed to be light) is a nice-to-have. There are some indications that a light gray background color can be better that pure white, and a transparent background would allow that in a simple way.

Obviously a tool could modify the white background color instead for those cases - so in one sense it is just a nice-to-have.

However, it seems preferable that tools can use libraries without any visual changes - not even showing a different background color in images.

The "or white" can either be deprecated in the future, or never added.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2244

**Comment by HansOlsson** [comment]
"The background of the groupImage and image used in HTML-documentation is recommended to be transparent (intended to be a light color) - or white."
Agreement by acclamation.
