### ISSUE TITLE
Use of := for input or local bindings in functions is deprecated, but ...

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2249]
**Reported by stefanv on 7 May 2018 18:00 UTC**
Section 12.2 states that, "Using assignment (:=) is deprecated.", however section 12.1 explicitly refers to "declaration assignments", and in the non-normative text, uses ":=".

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2249

**Comment by HansOlsson** [comment]
Language group:
Should consistently deprecate ":=" for bindings, and call them "binding equations".
