### ISSUE TITLE
Libraries for external functions ... Windows

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2252]
**Reported by stefanv on 18 Jun 2018 14:59 UTC**
Section 12.9.4 specifies the meaning of the `Library` and `LibraryDirectory` annotations, and the hierarchy of platform specific subdirectories, but is vague (intetionally?) about what form the libraries must take.

On Linux, this is not an issue, as a library can be specified as either a `.a` or `.so` file, but on Windows it's a bit more complex. A static library is specified by a `.lib` file, and a shared (dynamic link) library by a `.dll` file. However, in order to link a shared library using the linker (instead of writing code to explicitly open and link at run time), a `.lib` file must _also_ be present.

The example in the non-normative text suggests that this is required, since it shows one library in `.lib`-only format, and another in `.dll` format with an accompanying `.lib` file. But, since the non-normative text is not normative, one can't be sure that this was intended.

So, I think it should be clarified in what form external libraries must be specified for Windows. We can't leave this as tool-dependent as this would make it impossible to provide external libraries that work with all tools.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2252

**Comment by modelica-trac-importer** [comment]
**Modified by stefanv on 18 Jun 2018 15:03 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 18 Jun 2018 15:05 UTC**
I agree that this should be clarified.

Explicitly allowing dll-files without lib-files on Windows would be a good idea; and Dymola supports it since Dymola 2016 (under some restrictions - in particular that you cannot combine this with Include-annotation) so it seems possible to implement.

However, I believe there are also other issues to consider for this.

**Comment by modelica-trac-importer** [comment]
**Modified by hansolsson on 18 Jun 2018 15:10 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 18 Jun 2018 15:39 UTC**
Yes, it is possible to implement in the non-`Include` case, since everything you need to link it using code (i.e. `dlopen` and friends) can be derived from the Modelica part of the declaration. But if that is intended to be the case, it should be specified.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 19 Jun 2018 11:00 UTC**
Replying to [ticket:2252 Stefan Vorkoetter]:
> However, in order to link a shared library using the linker (instead of writing code to explicitly open and link at run time), a `.lib` file must _also_ be present.

Such a `.lib` file is called _import_ library (in MSVC speech) in contrast to a _static_ library. Import libraries are the preferred way to write C++ external functions, since otherwise, C++ static libraries are not compatible between different VS versions.

**Comment by HansOlsson** [comment]
Note that SimulationX only uses dll-file and Dymola uses lib-file if present (but can link directly to dll).
JModelica.org (or Optimica Compiler Toolkit) could probably auto-generate dll-file.

So allow dll-file (without a lib) as well under Windows:
Favor: 4
Against: 0
Abstain: 2

Conclusion add this.
