### ISSUE TITLE
Clarify inStream

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2253]
**Reported by hansolsson on 21 Jun 2018 15:33 UTC**
Appendix D.2 introduce inStream as follows:

"We establish this quantity using a dedicated operator
$inStream(h_{outflow,i})=h_{mix}(\dot{m}_{i}>=0)$."

I hope the math-notation is clear enough to understand how the formula looks like, otherwise look at the current document. However, what does it mean? 

It cannot be multiplication of $h_{mix}$ and an indicator function right?
It cannot be that h_mix is a function - with argument, right?

My best guess is that it is saying that inStream is h_{mix} when the mass-flow is positive, so the parenthesis could be replaced by e.g. "when $\dot{m}_{i}>=0$.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2253

**Comment by modelica-trac-importer** [comment]
**Comment by eshmoylova on 21 Jun 2018 16:05 UTC**
Replying to [ticket:2253 Hans Olsson]:
> "We establish this quantity using a dedicated operator
> $inStream(h_{outflow,i})=h_{mix}(\dot{m}_{i}>=0)$."

I agree that this notation does not make much sense.

> My best guess is that it is saying that inStream is h_{mix} when the mass-flow is positive, so the parenthesis could be replaced by e.g. "when $\dot{m}_{i}>=0$.

The sentence just before the one you quoted:

"Whenever the mixing enthalpy is used in a model it is therefore the mixing enthalpy under the assumption of fluid flowing into said model."

So I think your guess is correct, it was meant to be when \dot{m}_{i}>=0 and your suggestion for replacement is a good one.

**Comment by HansOlsson** [comment]
Francesco: intended to mean "assuming that" - not "when".
Agreement to change by acclamation.
