### ISSUE TITLE
Meaning of "a function that is a component".

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2255]
**Reported by stefanv on 6 Jul 2018 21:06 UTC**
In section 12.4.2, it is written that:

 A functional input argument can be provided in one of the following forms to be passed to a scalar formal parameter of function type in a function call:

 a) as a function name
 b) as a function partial application
 c) as a function that is a component
 d) as a function partial application of a function that is a component

Is it the case that the only possible meaning of "a function that is a component" is "a formal parameter of function type of the enclosing function"?

Put another way, are any of the following possible:

* To have an array of functions from which you can select one to pass as an argument?
* To have an if-expression select one of several functions to pass as an argument?

Put a third way, can the choice of function passed as an argument in a particular function call appearing in the model's equations ever vary at run time?

I believe, but am not entirely sure, that the answer is "no". The spec needs to be clarified in this regard.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2255

**Comment by HansOlsson** [comment]
Is it the case that the only possible meaning of "a function that is a component" is "a formal parameter of function type of the enclosing function"?

Conclusion: Yes to first question. (Same as "No" to the other two.)
Not clear if this needs clarification - probably a good idea.
