### ISSUE TITLE
Typos in specification

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2256]
**Reported by hansolsson on 9 Jul 2018 13:31 UTC**
4.6 Specialized Classes
Extra dot.
"The components directly declared in a record may only be of specialized class record and type.."

5.3.2 Composite Name Lookup
Two cases of mismatched parenthesis:
"(e.g., B and B.C]"

(Might add more; just wanted a ticket to not forget.)

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2256

**Comment by HansOlsson** [comment]
Agreement to change by acclamation.
