### ISSUE TITLE
External "library" specified as .o or .obj

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2257]
**Reported by stefanv on 9 Jul 2018 20:26 UTC**
A customer recently sent us a model that uses an external function, and the external library referenced in the `Library` annotation was specified as a `.obj` file. A `.obj` file (or `.o` file under Unix) is not technically a library, so it's not clear to me that this is supposed to work. Apparently it does in at least one other tool.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2257

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 10 Jul 2018 08:35 UTC**
Most compiler tool chains manage object files and libraries of object files in a consistent way. Do you see any problem in regarding also .obj files as "external library"?

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 11 Jul 2018 13:09 UTC**
I don't see a problem with it, but the text as written doesn't imply that it should work, since it refers to libraries, not "all things linkable by compiler toolchains". However, it is also possible that there exist compiler toolchains that do not treat object files and libraries in a compatible way.

**Comment by modelica-trac-importer** [comment]
**Comment by awittkop on 11 Jul 2018 14:13 UTC**
Actually most compilers manage object files in completely incompatible ways. For example, construct an object file with a newer version of gcc, then try to use it with an older version - this fails.
Similar comments for different versions of MSVC on windows, but I think the incompatibility there is bi-directional - an object file constructed in MSVC 12 cannot be used in a compile done with MSVC 14 and vice versa. I have not once gotten an object file constructed with an entirely different tool to work properly on Windows.

Even if backward compatibility did work, and we modified the Modelica distribution process to have subdirectories for the compiler underneath the platform, constructing an object file to ship as part of a Modelica library would require the author to have access to oldest possible versions of gcc, MSVC, etc. to support those compilers.

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 11 Jul 2018 14:31 UTC**
Replying to [comment:3 awittkop@…]:
> Actually most compilers manage object files in completely incompatible ways. For example, construct an object file with a newer version of gcc, then try to use it with an older version - this fails.

Well, while your comment is largely true it was not really the topic as I understand it. The question here is the handling of `.obj` vs. `.lib`, assuming compatible compiler versions.

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 11 Jul 2018 14:38 UTC**
Replying to [comment:2 Stefan Vorkoetter]:
> However, it is also possible that there exist compiler toolchains that do not treat object files and libraries in a compatible way.

With similar arguments the C language does not assume `int` is represented in two's-complement, leading to some unfortunate undefined behavior. Maybe we shouldn't care?

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 11 Jul 2018 14:39 UTC**
No, it **is** the topic as I intended it. If the intent really is to allow `.obj`/`.o` where the spec currently implies only `.lib` and `.dll`/`.so`, then it is unreasonable to expect any given external function to work in any variation of the environment(s) other than the one(s) it was developed in.

I am not assuming compatible compiler versions, since one doesn't need compatible compiler versions when using actual libraries instead of object files. On Linux for instance, I could create a `.so` or `.lib` using gcc, Intel's C/C++ compiler, or even FreePascal, and it will link into a Modelica tool. The same is not necessarily true of object files.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 11 Jul 2018 14:41 UTC**
There's a big difference between the behaviour of `int` and the compatibility of `.obj` files, which is that invariably, `int` **is** represented in two's-complement everywhere on a given platform, and that `.obj` files invariably are **not** compatible between tools.

Dealing with `int` in the spec is solving a problem that is extremely unlikely to happen, whereas dealing with `.obj` is solving a problem that does happen.

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 11 Jul 2018 14:54 UTC**
Replying to [comment:6 Stefan Vorkoetter]:
> No, it **is** the topic as I intended it. If the intent really is to allow `.obj`/`.o` where the spec currently implies only `.lib` and `.dll`/`.so`, then it is unreasonable to expect any given external function to work in any variation of the environment(s) other than the one(s) it was developed in.
> 
> I am not assuming compatible compiler versions, since one doesn't need compatible compiler versions when using actual libraries instead of object files. On Linux for instance, I could create a `.so` or `.lib` using gcc, Intel's C/C++ compiler, or even FreePascal, and it will link into a Modelica tool. The same is not necessarily true of object files. 

Mea culpa. I made the simplistic assumption that libraries are collections of object files, hence compatible libraries would require compatible object files. The consistency of ABIs varies between platforms of course.

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 30 Jul 2018 07:24 UTC**
Our experience with external libraries on Windows is that unless all the used libraries are compiled with the same version of the compiler, something breaks. That might not be the case if the libraries are pure C, though. Many of our libraries are C++ wrapped in a C layer.

**Comment by HansOlsson** [comment]
Poll:
Only library files (not obj-files): 5
Also obj-files: 0
Clear conclusion.
