### ISSUE TITLE
Medium package in function

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2258]
**Reported by anonymous on 10 Jul 2018 08:21 UTC**
Also see this SO question:
https://stackoverflow.com/questions/51247315/how-to-call-medium-functions-inside-other-function

I wanted to ask whether it is allowed to have a package inside a function.
Section 12.2 of the Modelica Spec 3.4 says:
  A function may only contain components of the restricted classes type,   record, operator record, and function; i.e. no model or block components.

But what about packages, are they allowed or not? And what would the syntax look like?
If it is not allowed, this means it is impossible to use Medium properties inside a function!? 

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2258

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 6 Aug 2018 12:38 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by jmattsson on 6 Aug 2018 13:30 UTC**
The quoted sentence only limits what _components_ are allowed in a function, not what _classes_ are allowed there. Packages are classes, not components, so it does not apply to them. 

So yes, you could have a package within a function. It would not be possible to refer to it from outside the function other than through modifications, though. If we have model M, containing function f, that in turn contains replaceable package Medium, then you could not in M write f.Medium. You could do something like `model M2 = M(f(redeclare package Medium = SomeOtherMedium));`, however.

**Comment by HansOlsson** [comment]
As far as I can see the question has been answered.
