### ISSUE TITLE
Events in array range operator ":"

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2262]
**Reported by pavel&#x2e;grozman on 18 Jul 2018 09:17 UTC**
The Modelica specification allows continuous variable arguments in the array range operator **_start_:_stop_** and **_start_:_step_:_stop_**.

Should the array range operator generate events when the size of the result is changed?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2262

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 18 Jul 2018 09:37 UTC**
It is not specified that it should. 

If we consider a model array variable bound to this expression it will generate a dynamically sized variable, and breaking the assumptions of the size-operator - i.e. the dynamic size doesn't work. 
We could consider allowing dynamic sized arrays in the models - but it would need motivation, and involve general support for it - not just using the array range operator.

If it just appears inside an expression (like Real x=sum(1:time); ) it just seems esoteric. I believe that would be easier to support.

**Comment by HansOlsson** [comment]
The question was answered and closing the rest awaiting input.
