### ISSUE TITLE
Why is the within-clause important?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2265]
**Reported by leo&#x2e;gall on 24 Aug 2018 14:39 UTC**
Is there some existing documentation, why the within-clause is required in Modelica? (I tried reading #885, #573 and #1728).

Many Modelica users work in a way, where they copy packages from one study to the next one:
```
MyProject
  StudyA
    ModelA
    ComponentA
  StudyB
    ModelA
    ComponentA
```

When using SVN or GIT in order to copy these files, \*all\* files are changed, just due to the within statement.

So, I was asked many times by end-users, if the within-clause is required.

There are probably good reasons for having it. Could you please explain the background? Thanks!

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2265

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 24 Aug 2018 14:51 UTC**
The problem with just copying files is that you lose the context, and if you are not careful that can change the behavior.

The context means that e.g. in StudyA you could use ComponentA or StudyA.ComponentA or MyProject.StudyA.ComponentA or .MyProject.StudyA.ComponentA to refer to ComponentA, and only the first will behave as expected when you copy files. 

There is no simple way to ensure that the other ones are not used - and they would refer to the original one creating issues. (If you copy StudyA inside Dymola - and assumedly in other tools (no need to list them all) - that is handled automatically. Note that this is only relevant when storing in a file-system that user can easily change - we don't have something similar on the 3D Experience Platform; where models are stored in a data-base.)

In addition if you copy between different top-level packages there is an implicit dependency on the uses-annotations that are located in MyProject.
\-
In addition there is a risk that you misplace a file inside a package breaking things.

**Comment by modelica-trac-importer** [comment]
**Comment by leo&#46;gall on 25 Sep 2018 10:15 UTC**
Maybe my initial description wasn't clear enough on what we mean by using SVN/GIT: 
We want to use a Modelica IDE which cares about the context.
After working in the Modelica IDE, we commit these changes to GIT.
Now, if you want to track, which changes have been made, there are many files which might only have local context, so they shouldn't have changed. But they are reported modified, because the within-clause had been updated. 
The same holds for renaming a project library. All files are modified, but no relevant content is modified.

Do I understand correctly: the only technical reason for having the within-clause is to prevent miss-placed folders in the file hierarchy? Or are there other technical reasons?

**Comment by modelica-trac-importer** [comment]
**Comment by atroy on 25 Sep 2018 10:37 UTC**
The SimulationX licensing mechanism is working with absolute identifiery and relies on the within clause. 

Assume there is a Modelica class `A.B.C` (implemented in A/B/C.mo) which is license protected and the user does not have the necessary license for it. As the class it license protectedt there is an entry for the identifier `A.B.C` in the SimulationX license database. If the user moves the file C.mo somewhere else, e.g. to MyPackage/C.mo, this would result in the identifier `MyPackage.C`. This identifier is not covered by the license database and SimulationX would classify the class as not licensed and the user would be able to use the class without having the correct license. In order to prevent this, SimulationX includes the within clause in encrypted files and rejects them if they don't match the expected environment.

**Comment by modelica-trac-importer** [comment]
**Comment by leo&#x2e;gall on 26 Sep 2018 09:49 UTC**
Replying to [comment:3 atroy]:
>In order to prevent this, SimulationX includes the within clause in encrypted files and rejects them if they don't match the expected environment.

Sounds great. Probably, this holds as long as you don't find Protection annotations with 
`Access.nonpackageDuplicate` or `Access.packageDuplicate`?

Ok, so within-statements might make sense for encrypted packages.

**Comment by modelica-trac-importer** [comment]
**Comment by atroy on 26 Sep 2018 10:31 UTC**
> Sounds great. Probably, this holds as long as you don't find Protection annotations 
> with `Access.nonpackageDuplicate` or `Access.packageDuplicate`?

It's more about the question if the class is available at all (with a specific license). As soon as you have a license for the class, the protection annotations define how you are allowed to use it.

**Comment by HansOlsson** [comment]
I believe the question has been answered.
