### ISSUE TITLE
7.3.4 Enumeration type example with choices

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2267]
**Reported by beutlich on 17 Sep 2018 11:24 UTC**
The enumeration type example in section 7.3.4 on choices should use the enumeration type as parameter if it is modified, i.e., change

```mo
type KindOfController=Integer(min=1,max=3)
  annotation(choices(
    choice=1 "P",
    choice=2 "PI",
    choice=3 "PID"));
model A
  KindOfController x;
end A;
A a(x=3 "PID");
```
to
```mo
type KindOfController=Integer(min=1,max=3)
  annotation(choices(
    choice=1 "P",
    choice=2 "PI",
    choice=3 "PID"));
model A
  parameter KindOfController x;
end A;
A a(x=3 "PID");
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2267

**Comment by HansOlsson** [comment]
I agree that stylistically this is clearer, even if one could imagine some implementation of this where the controller could be changed at discrete events.

**Comment by HansOlsson** [comment]
Agreement to change by acclamation.
