### ISSUE TITLE
Should rescaling a connector preserve aspect ratio?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2268]
**Reported by stefanv on 28 Sep 2018 17:42 UTC**
In the component `Modelica.Electrical.Analog.Basic.M_Transformer`, the positive pin has a Placement transformation:
```
annotation (Placement(transformation(extent={{-110,-60},{-90,60}})));
```
The negative pin has a similar one.

It seems that the expectation is that the normally square electrical pin icon be transformed into a tall narrow rectangle, and of course it makes sense to do so, given the design of the icon (several parallel inductors all connected to the same two pins).

However, I see nothing in the specification that states that this should happen. The coordinateSystem of the pin icon has (whether written explicitly or by default), `preserveAspectRatio=true`. There is no way that I can see in the specification to override this, so purely based on the specification, I would expect the pin to remain square, and to be centered in the specified extent.

Is there something missing from the specification? Should the Transformation annotation include a preserveAspectRatio field? Or should it just be specified that preserveAspectRatio is considered to be false for Placements?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2268

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 28 Sep 2018 17:44 UTC**
And of course, the same issue arises for placing an icon in a diagram.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 28 Sep 2018 18:18 UTC**
Related to #2247.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 28 Sep 2018 18:47 UTC**
Related, but different. In #2247, there is a hint that preserveAspectRatio of a connector is actually honoured, which isn't actually the case (at least not in the tools used to design the various library components, like M_Transformer, that are expecting the connector to be stretched).

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 1 Oct 2018 13:42 UTC**
Perhaps the simplest solution is that we add `preserveAspectRatio` to the `Placement.transformation` record, and make it `false` by default there, since that is what tools seem to do.

**Comment by HansOlsson** [comment]
Possibilities:
Change pin - and some additional connectors to have preserveAspectRatio=false: 2
Explicitly ignore preserveAspectRatio for connector-icon on component icon/diagram: 0
Add preserveAspectRatio to Placement.transformation (and change these specific cases - with default inherited from component): 4
Add preserveAspectRatio to Placement.transformation (with false default): 0
Consider preserveAspectRatio to just be a hint (so that extent takes precedence): 3
(The text of the last one needs to be clearer.)

No clear decision.

**Comment by casella** [comment]
No idea how to do it, but definitely nice to have

**Comment by HansOlsson** [comment]
Language group: 

Also a discussion about preserving aspect ratio for bitmaps (there is no possibility to turn that off).

1. Add preserveAspectRatio to Placement.transformation (and change these specific cases - with default inherited from component) and scale to fit inside extent if preserveAspectRatio=true and extent is not consistent with coordinate system: 1
2. Consider preserveAspectRatio to just be a hint for the GUI  (the GUI should preserve the _current_ aspect ratio of the component, but the given extent is used for rendering): 5
3. Consider preserveAspectRatio to just be a hint for the GUI  (the GUI should preserve the _original_ aspect ratio of the component, but the given extent is used for rendering): 1

Stefan's tool (separate from MapleSim) when rendering shrinks them to fit into the given extent (to preserve aspect ratio within the given extent)
SystemModeler and Dymola 2020 honors extent when rendering.
SystemModeler preserves current aspect ratio when resizing, Dymola 2020 preserves original aspect ratio when resizing.

Clear decision.
