### ISSUE TITLE
Are clock operators vectorizable?

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2269]
**Reported by eshmoylova on 4 Oct 2018 15:12 UTC**
Chapter 16 Synchronous Language Elements (Specification 3.4) defines a number of built-in operators (with function syntax). What is not clear if they can be vectorized according to the rules of Section 12.4.6.

The arguments of the operators are often defined in terms of a component expression introduced in section 16.2.3.
 **Component Expression**:
 A Component Reference which is an Expression, i.e. does not refer to models or blocks with equations. It is an instance of a (a) base type, (b) derived type, (c) record, (d) an array of such an instance (a-c), (e) one or more elements of such an array (d) defined by index expressions which are parameter expressions (see below), or (f) an element of records.

The option (d) allows for the component expression to be an array. How should the arrays be handled?

What about arrays passed where the arguments are not specified as component expressions. For example, the definition of sample(u,c) in 16.5.1 states that the "Input argument u is a continuous-time expression" but does not require it to be a scalar.

Which operators are allowed to be vectorized?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2269

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 5 Oct 2018 08:16 UTC**
Should they be vectorized or should they work for vectors, possible in some other way?

In addition to `sample` we have `interval` and `firstTick`. To me it is natural to write `interval(u)` - even if u is an array, and have it return a scalar. (This actually works in Dymola.)

Having `interval(u)` return an array of intervals seems unnatural to me.

However, 
* This needs to be specified.
* Can the input be constructed to have different clocks? If so that error case must be handled. An alternative might be to "vectorize" sample (including splitting records), but require interval to have homogeneous clocks.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 5 Oct 2018 08:29 UTC**
Test-cases in Dymola:
```
model Ok
  Clock c=Clock(1);
  Real xv[2]={time,2*time};
  Real x[:]=sample(xv, c);
  Real dt=interval(x);
  Boolean b=firstTick(x);
end Ok;
```

And interval for non-homogeneous array causing problems:
```
  Real d[2]={sample(time, Clock(1)), sample(time, Clock(2))};
  Real d2=interval(d);
```

And finally a test that subsample vectorize:
```
  Real d[2]={sample(time, Clock(1)), sample(time, Clock(2))};
  Real dd[2]=subSample(d, 2);
```

Thus it seems that we should specify which ones vectorize (including the new vectorization of records). And that interval and firstTick always return a scalar and don't vectorize, but require that the input is on one clock.

**Comment by modelica-trac-importer** [comment]
**Comment by eshmoylova on 10 Oct 2018 14:35 UTC**
What about clock constructors? It seems like it should be possible to say:
```mo
  Clock c1[2] = Clock({1,2});
```

**Comment by modelica-trac-importer** [comment]
**Comment by michael&#46;schellenbergercosta on 11 Oct 2018 06:03 UTC**
I think one has to differentiate between arrays of clocks and everything else. The Modelica-specification explicitely states in section 16.3 Clock Constructors:

Clock variables can be used in a restricted form of expressions. Generally, every expression containing clock variables must have parametric variability [in order that clock analysis can be performed when translating a model.]. Otherwise, the following expressions are allowed:
 * Declaring arrays of clocks [Example: Clock c1[3] = {Clock(1), Clock(2), Clock(3)} ]
 * Array constructors of clocks: {}, [], cat(..).
 * Array access of clocks [Example: sample(u, c1[2])]
 * Equality of clocks [Example: c1 = c2].
 * If-expressions of clocks in equations [Example: Clock c2 = if f>0 then subSample(c1, f) elseif f < 0 then superSample(c1, f) else c1].
 * Clock variables can be declared in models, blocks, connectors, and records,. A Clock variable can be declared with the prefixes input, output, inner, outer, but not with the prefixes flow, stream, discrete, parameter, or constant [Example: connector ClockInput = input Clock;]

So you can declare arrays of clocks and access them accordingly. It becomes tricky with respect to the built-in functions. Here the most deciding aspect is the behaviour with respect to the Base/Sub-clock-partitioning. 

Assume you have an array of clocks `c[N]`. And you would sample time with it. 
```
    Real[N] clockTimes = sample(time, c);
```

This expression does not make any sense at all, because due to clock inference the array expression `clockTimes` would collaps all the sub-clocks into a single sub-clock-partition, effectively becoming a
```
    Real[N] clockTimes = fill(sample(time, c[0]), N);
```

Therefore all Sub-clock conversion operators as defined in section 16.5.2 only take an input argument of type clock, which must be a scalar. This is exemplified by the ommission of the clock, as then it has to be infered which doesnt make any sense in a vectorized context.

However, the continuous-time expression `u` in `sample(u, c)` can be anything you want. As I read the specification for sample:

    The operator returns a clocked variable that has c as associated clock and has the value of the left limit of u when c is active.

Consequently there is an assignment in the equation `y = sample(u, c);` and it immediately follows that the dimension of `y` and `u` must match.

The other operators `firstTick` and `interval` are again different, as the reference the clock rather than the input expression. As a given expression can only have one assiciated clock, it follows that `firstTick` and `interval` only ever return a scalar value with respect to that clock.

**Comment by modelica-trac-importer** [comment]
**Comment by eshmoylova on 11 Oct 2018 14:52 UTC**
Replying to [comment:4 michael.schellenbergercosta@…]:
> I think one has to differentiate between arrays of clocks and everything else. The Modelica-specification explicitely states in section 16.3 Clock Constructors:
> 
> Clock variables can be used in a restricted form of expressions. Generally, every expression containing clock variables must have parametric variability [in order that clock analysis can be performed when translating a model.]. Otherwise, the following expressions are allowed:

I have a problem with this paragraph too. I filed a separate ticket about it: #2272.

>  \* Declaring arrays of clocks [Example: Clock c1[3] = {Clock(1), Clock(2), Clock(3)} ]
>  \* Array constructors of clocks: {}, [], cat(..).
>  \* Array access of clocks [Example: sample(u, c1[2])]
>  \* Equality of clocks [Example: c1 = c2].
>  \* If-expressions of clocks in equations [Example: Clock c2 = if f>0 then subSample(c1, f) elseif f < 0 then superSample(c1, f) else c1].
>  \* Clock variables can be declared in models, blocks, connectors, and records,. A Clock variable can be declared with the prefixes input, output, inner, outer, but not with the prefixes flow, stream, discrete, parameter, or constant [Example: connector ClockInput = input Clock;]
> 
> So you can declare arrays of clocks and access them accordingly. It becomes tricky with respect to the built-in functions. Here the most deciding aspect is the behaviour with respect to the Base/Sub-clock-partitioning. 
> 
> Assume you have an array of clocks `c[N]`. And you would sample time with it. 
> ```
>     Real[N] clockTimes = sample(time, c);
> ```
> 
> This expression does not make any sense at all, because due to clock inference the array expression `clockTimes` would collaps all the sub-clocks into a single sub-clock-partition, effectively becoming a
> ```
>     Real[N] clockTimes = fill(sample(time, c[0]), N);
> ```
> 

Why would it collapse to this? And what is `c[0]`? Based on 16.7.1 Flattening of Model:
 The clock partitioning is conceptually performed after model flattening, i.e., redeclarations have been elaborated, arrays of model components expanded into scalar model components, and overloading resolved. Furthermore, function calls to inline functions have been inlined. [_This is called “conceptually”, because a tool might do this more efficiently in a different way, provided the result is the same as if everything is flattened. For example, array and matrix equations and records don’t not need to be expanded if they have the same clock._]


There is an explicit mentioning of the possibility that array or matrix equations may have different clocks and that in that case they need to be expanded. So I would expect that after flattening and expanding arrays into scalars you get:
```
clockTimes[1] = sample(time,c[1]);
...
clockTimes[N] = sample(time,c[2]);
```
And only then you perform clock partitioning.
 
> Therefore all Sub-clock conversion operators as defined in section 16.5.2 only take an input argument of type clock, which must be a scalar.

The sub-clock conversion operators defined in Section 16.5.2 may also take a clocked expression as the input argument `u`.

> This is exemplified by the ommission of the clock, as then it has to be infered which doesnt make any sense in a vectorized context.
> 

I do not see where it says that the clock argument may be omitted for the operators defined in Section 16.5.2. From what I can see you can omit factor in subSample or superSample, but not the clock.

> However, the continuous-time expression `u` in `sample(u, c)` can be anything you want. As I read the specification for sample:
> 
>     The operator returns a clocked variable that has c as associated clock and has the value of the left limit of u when c is active.
> 
> Consequently there is an assignment in the equation `y = sample(u, c);` and it immediately follows that the dimension of `y` and `u` must match.
> 
> The other operators `firstTick` and `interval` are again different, as the reference the clock rather than the input expression. As a given expression can only have one assiciated clock, it follows that `firstTick` and `interval` only ever return a scalar value with respect to that clock.

**Comment by modelica-trac-importer** [comment]
**Comment by michael&#x2e;schellenbergercosta on 12 Oct 2018 10:50 UTC**
We talked about this a bit in the office. Indeed it seems to be valid to put an arry of clocks into sample
```
Real[N] clockTimes = sample(time, c);
```

However, I believe this is just an elaborate way to shoot oneself in the foot. Generally what happens is that you cannot use any component if `clockTimes` in the same equation as that would merge the two sub/base-clock partitions. 

In the end a base-clock partition can be seen as a independent part of the whole model, that is connected to the outside via sample/hold. So a vectorized clock is effectively the same as a vectorized model. 

The construct with a vectorized clock feels more like a poor mans vectorized model with bade scoping.

**Comment by modelica-trac-importer** [comment]
**Comment by eshmoylova on 18 Oct 2018 15:23 UTC**
I have done some more testing using Dymola and OpenModelica. It looks like they have different interpretation of how `firstTick` and `interval` should be handled if vectors are passed.

In Dymola, as Hans pointed out in #comment:2, they both expect to return a scalar regardless of the type of input and give an error if the vector that is passed has different clocks assigned to different members.

In OpenModelica, both `firstTick` and `interval` are vectorized if an array is given and the clock inference is performed after the vectorization. The following model works in OpenModelica but fails in Dymola.
```
model M
  Clock c1 = Clock(1,10), c2 = Clock(1,20);
  Real[2] xd;
  Real[2] dt1, dt2;
equation
  xd = sample({time, time+1},{c1,c2});
  dt1 = interval({c1,c2});
  dt2 = interval(xd);
end M;
```

The same example with `firstTick` instead of `interval` would also work in OpenModelica but fail in Dymola.

Which interpretation should be correct?

Note also that in OpenModelica firstTick returns Real, not Boolean. If I define:
```
model M
  Clock c1 = Clock(1,10);
  Boolean dt;
equation
  dt = firstTick(c1);
end M;
```

I get an error: "Type mismatch in equation dt=firstTick(c1) of type Boolean=Real."

If I change the declaration of `dt` to use `Real` instead of `Boolean` then the model simulates but the result for dt is 0 everywhere. (I am using version 1.12.0.)

It puts into question OpenModelica's implementation of firstTick and how it should be vectorized.

**Comment by modelica-trac-importer** [comment]
**Comment by michael&#x2e;schellenbergercosta on 25 Oct 2018 07:37 UTC**
Regarding the implementation of firstTick there is a clear Error on OpenModelica's side. From the specification:
```
This operator returns true at the first tick of the clock of the expression, 
in which this operator is called. The operator returns false at all subsequent 
ticks of the clock.
```

Furhtermore, the `interval()` definition in the specification explicitely states:
```
This operator returns the interval between the previous and present tick of the 
clock of the expression, in which this operator is called.
...
The return value of the interval operator is a scalar Real number.
```

As i read it there are two requirements that follow from this text:
1. The passed expression must have exactly one clock.
2. We cannot assign to an array as the return value is a scalar So we would have to flatten first

Lets assume we have a clocked variable `Real[N] var` with a given single clock  and an array `Clock[N] cocks`. 

According to the definition of `interval()` and the fact that clock partitioning is only done after flattening it would follow, that `interval(clocks)` expands to
```
{interval(clocks[1]), ..., interval(clocks[N])}
```

As the array `clocks` would first be flattened and we would then assign a scalar Real to every element of
```
Real[N] myIntervals = {interval(clocks[1]), ..., interval(clocks[N])};
```

So far so good. However this becomes completely bogus if we consider that we have the clocked variable `Real[N] var`. As clock partitioning happens **after** flattening, we would have to expand `interval(var)` to 
```
{interval(var[1]), ..., interval(var[N])}
```

Consequently we would assign the the scalar Real to every element of the array
```
Real[N] myVarIntervals = {interval(var[1]), ..., interval(var[N])};
```
This effectively means that `interval()` of an array \*must\* return an array of Real values rather than just the interval of the one clock the array has.

From my point of view this is completely out of the question. However, if we forbid `interval()` to be flattened then we cannot use it in the context of arrays of clocks.

**Comment by HansOlsson** [comment]
Conclusion: Not vectorized.

Note that interval is already defined to return a scalar real number, and the input is declared as only being used for clock inference.

A related issue is that it is unclear if the input can be both a clocked expression and a clock (or array of clock); seems that both should be allowed.

**Comment by HansOlsson** [comment]
Should clarify that the optional argument u for firstTick and interval can be a (clocked) expression or clock variable (or a more general "clock expression" that needs to be defined)..
