### ISSUE TITLE
Discrepancy in argument requirements for clock conversion operators

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2270]
**Reported by eshmoylova on 4 Oct 2018 15:36 UTC**
Clock conversion operators hold (defined in Sections 16.5.1 Base-clock conversion operators, Specification 3.4) and backSample (defined in 16.5.2 Sub-clock conversion operators, Specification 3.4) have a requirement that the first input argument is a component expression. The definition of the component expression is given in 16.2.3 and the examples for "The input argument is a Component Expression" specifically state that a general expression is not allowed.
```
y5 = previous(2*u); // error (general expression, no Component Expression)
```

However, in the Section 16.7.1 Flattening of Model it says:
 Furthermore, each non-trivial expression (non-literal, non-constant, non-parameter, non-variable), expr_i, appearing as first argument of any clock conversion operator is recursively replaced by a unique variable, v_i, and the equation v_i = expr_i is added to the equation set.

What should a tool do? Issue an error if non-trivial expression is used as the first argument in hold and backSample? Or not issue an error and replace it with a variable?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2270

**Comment by HansOlsson** [comment]
Proposal:
Furthermore, each non-trivial expression (non-literal, non-constant, non-parameter, non-variable), expr_i, appearing as first argument of a clock conversion operator (except hold and backSample) is recursively replaced by a unique variable, v_i, and the equation v_i = expr_i is added to the equation set.

Agreement.

The reason for the special case for hold is to use the start-value before the first tick. The same reason is given for backSample - but that case also seems to be explicitly forbidden.
Need to further investigate backSample.
