### ISSUE TITLE
Attributes of Clock type

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2271]
**Reported by eshmoylova on 4 Oct 2018 21:21 UTC**
The Clock type used to define clock variables (Section 16.2.1) is referred to as a base type. But there is no explicit definition of the attributes of the Clock type given. Shouldn't there be one? The base types Real, Integer, Boolean, and String have their attributes clearly specified in Section 4.8 Specification 3.4.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2271

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 5 Oct 2018 08:00 UTC**
Interesting question, but what would be attributes be used for?

For `Real x(min=2, start=4, unit="kg", displayUnit="g");` the attributes have semantics. For `Clock c=Clock(1);` it is less clear.

One way is to think that a Clock is somewhat similar to a Boolean variable, and Boolean variable has fixed, start, quantity, and the actual value. But Clocks are not initialized as normal variables, and therefore should not have fixed and start. Thus the only remaining attribute is "quantity", but it is not clear what "quantity" would mean for a clock.

One possibility would be to move Clock to the next section "other predefined types" - and similarly as ExternalObject don't specify its contents.

**Comment by HansOlsson** [comment]
Conclusion:
Move Clock to the next section "other predefined types" (and don't call it "base type") - and similarly as ExternalObject don't specify its contents.
