### ISSUE TITLE
Restriction on clock expressions being parameteric

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2272]
**Reported by eshmoylova on 11 Oct 2018 14:19 UTC**
Restrictions on clock variables are specified in Section 16.3 (Specification 3.4) as follows.
 Clock variables can be used in a restricted form of expressions. Generally, every expression containing clock variables must have parametric variability [_in order that clock analysis can be performed when translating a model._]....

What does it mean? If taken literally, the expression
```
xd = sample(x,c);
```
where x is a continuous variable, xd is a clocked variable, and c is a clock variable should be illegal. Or what about clocks with non-parametric intervals?
```
Clock c = Clock(nextInterval,1000);
```
where nextInterval is a clocked variable, technically falls under the category of "every expression" and it does not have the parametric variability.

I think it should be specified more clearly what "every expression" means or what is meant by the parametric variability. It would make sense to me that if there is a for-loop in which a clock variable or a clock constructor occurs then the bounds of the for-loop must be parametric. Or the conditions of an if-expression in the example later in this section must be parametric:
 * If-expressions of clocks in equations [_Example: Clock c2 = if f>0 then subSample(c1, f) elseif f < 0 then superSample(c1, f) else c1_].

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2272

**Comment by HansOlsson** [comment]
> I think it should be specified more clearly what "every expression" means or what is meant by the parametric variability.

I also think that is the key. Subscripts on Clock-variables, conditions for switching between Clock-variables, and subsample/superSample factors for Clock variables must be parameter expressions.

Note that `Clock(sin(time)>0)` is allowed, i.e. the clock themselves can be constructed using continuous-time expressions, it's the relation-ship between clocks that must parametric.

However, I realize a related flaw. Consider:
 `Clock c2 = if f>0 then subSample(c1, f) elseif f < 0 then superSample(c1, f) else c1;`
What is the right-hand side? 
Should we call it a "Clock expression" and have "Clock variable" as a special case of it?

**Comment by HansOlsson** [comment]
Language group:

The restrictions on subsample and superSample (as well as shiftSample and backSample) are already there so only specify that subscripts on Clock-variables, and conditions for switching between Clock-variables must be parameter expressions.

Agreement by acclamation.
