### ISSUE TITLE
Array types in external functions should be const

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2278]
**Reported by stefanv on 31 Oct 2018 17:15 UTC**
Section 12.9.1.2 of Modelica Specification 3.4 states,

```
The type T is allowed to be any of the simple types which can be passed
to C as defined in Section 12.9.1.1 or a record type as defined in
Section 12.9.1.3 and it is mapped to the type T' as defined in these
sections for input arguments.

+--------------+--------------------------------+
|   Modelica   |      C Input and Output        |
+--------------+--------------------------------+
| T[dim1]      | T' *, size_t dim1              |
| T[dim1,dim2] | T' *, size_t dim1, size_t dim2 |
| ...          |                                |
+--------------+--------------------------------+
```

For all except the String type, I think that the `T' *`s should be `const T' *`, as section 12.9.3 states, "An external function is not allowed to internally change the inputs (even if they are restored before the end of the function)."

For the String type, I believe it should be `const char * const*`, a constant pointer (`const*`) to pointers to constant characters (`const char*`).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2278

**Comment by modelica-trac-importer** [comment]
**Modified by stefanv on 1 Nov 2018 00:40 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by anonymous on 1 Nov 2018 06:39 UTC**
Seems right, but simply too late for a backward compatible fix. Also, similar issue as #1955.

**Comment by modelica-trac-importer** [comment]
**Comment by dag on 1 Nov 2018 09:07 UTC**
If I remember correctly, we decided on `T*` rather than `const T*` because we observed that a lot of existing code did not use `const`, in particular FORTRAN libraries converted to C using f2c. Although I agree with you on principle grounds, I thought the compatibility argument was valid at the time.

Note that you need different types for input and output arguments.

**Comment by HansOlsson** [comment]
Should use the same for both generated and header-files.
(This is only for C.)
Note: a header with declaration can already use const.
If a literal array is passed to the function a tool may have to cast-away-const (or make a copy). `foo({1,2,3})`
Poll:
Change arrays to 'const': 1
No change: 5
Deprecate non-const (i.e. indicate that header-files should use const, but not enforce it): 7

Deprecate non-const seems preferred, will later allow const.
