### ISSUE TITLE
ModelicaAllocateString and String arrays

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2279]
**Reported by stefanv on 1 Nov 2018 00:33 UTC**
Section 12.9.6 states that `ModelicaAllocateString` is to, "Allocate memory for a Modelica string which is used as a return argument of an external Modelica function. Note, that the storage for string arrays (= pointer to string array) is still provided by the calling program, as for any other array."

This is somewhat ambiguous. I _assume_ it means that storage for the array itself (i.e. the array of `char *` pointers) is allocated by the caller, but that the entries in the array are pointers to memory allocated by `ModelicaAllocateString`. This could perhaps be clarified.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2279

**Comment by modelica-trac-importer** [comment]
**Modified by stefanv on 1 Nov 2018 00:39 UTC**

**Comment by HansOlsson** [comment]
update - removing "note":
"Allocate memory for a non-literal string which is used as a return argument of an external Modelica function."

Seems an issue with a function returning a string that was given as input. After a bit of discussion the conclusion was to allow returning a string given as input. So, the legal return values for strings are:
* Literal string
* Given as String input (to the external function)
* Returned by `ModelicaAllocateString*`
