### ISSUE TITLE
Clarification on reserved name Real vs. Clock

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#2280]
**Reported by beutlich on 2 Nov 2018 12:28 UTC**
Why is the Clock type not treated as reserved type like Real, Integer etc. in section 4.8, i.e., 

```mo
model A "This is legal"
  type Clock = enumeration(
    HSI "HSI clock", 
    HSE "HSE clock", 
    HSI_PLL "HSI with PLL", 
    HSE_PLL "HSE with PLL") "Clock";
  constant Clock c = Clock.HSI;
end A;
```

but

```mo
model B "This is illegal"
  type Real = enumeration(
    FIN "Finite", 
    INF "Infinite", 
    NAN "Not a number") "Real";
  constant Real r = Real.NAN;
end B;
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/2280

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 2 Nov 2018 12:32 UTC**
I assume it is due to the prior existence of Modelica.Blocks.Sources.Clock (and possibly similar models in other libraries).

**Comment by HansOlsson** [comment]
Agreement with reason and no change; even if not ideal.
