### ISSUE TITLE
Clarification of IconMap/DiagramMap in short-class definitions

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2281]
Clarify that IconMap/DiagramMap of section 18.6.3 can also be used in short-class definitions, since it is currently not supported by all tools. Additionally, add a new example C in non-normative text.

Derived from https://github.com/modelica/ModelicaStandardLibrary/issues/2765

**Comment by HansOlsson** [comment]
Agree, but discussion that it should be consistent for all annotations on extends-clauses (stating for all of them that they can be applied to short-class-definition as well). However, IconMap/DiagramMap are the only annotations allowed on extends-clauses.
