### ISSUE TITLE
Is it legal to modify an outer parameter?

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaSpecification#2283]
Consider this snippet of Modelica:

```modelica
record Record
    Real K;
end Record;

model Model
    outer parameter Record R;
    Real x;
equation
    x = R.K;
end Model;

model Main
    inner parameter Record R(K=3.14);
    Model m(R(K=42.0)); // Edited. I had originally mistakenly written m(K=42.0)
    Real y;
equation
    y = R.K;
end Main;
```
Questions:

1. Is the modification ~~`m(K=42.0)`~~ `m(R(K=42.0))` even legal?
2. If so, which takes precedence, `R(K=3.14)` or ~~`m(K=42.0)`~~ `m(R(K=42.0))`?

**Comment by svorkoetter** [comment]
Yes, `m(R(K=42.0))` is what I meant.
I agree it should be made clearer. Even now that you've pointed it out, it's not clear to me what happens when an outer declaration with an inner prefix has a modification. What is modified?

**Comment by svorkoetter** [comment]
So to clarify, this model,
```modelica
record Record
    Real K;
end Record;

model SubModel
    outer parameter Record R;
    Real w;
equation
    w = R.K;
end SubModel;

model Model
    inner outer parameter Record R;
    SubModel s;
    Real x;
equation
    x = R.K;
end Model;

model Main
    inner parameter Record R(K=3.14);
    Model m(R(K=42.0));
    Real y;
equation
    y = R.K;
end Main;
```
should yield the following equations,
```modelica
Main.m.s.w = Main.m.R.K
Main.m.x = Main.m.R.K
Main.y = R.K
```
where,
```
Main.m.R.K = 42
R.K = 3.14
```

**Comment by HansOlsson** [comment]
@svorkoetter 

Almost, except that `Main.m.x = R.K`, since local references to R refer to the outer element that is then matched to a corresponding inner element.

**Comment by HansOlsson** [comment]
Agreement that specification is correct, but should be clarified (as indicated).
