### ISSUE TITLE
Clocked variables missing in appendix C?

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2286]
As disocvered by @casella and @GallLeo: Are the clocked variables contained in equation 1 of the Modelica DAE Representation in Appendix C? Looks like they were missed there.

**Comment by HansOlsson** [comment]
Proposal:

Clocked variables are handled similarly as z and m (depending on type) , but using previous instead of pre and only solved in the first iteration of the event-loop.

**Comment by HansOlsson** [comment]
Agreement as a start (no time for more).
