### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2292]
There should be a LICENSE file in the repository to make the license of the source files obvious.

**Comment by HansOlsson** [comment]
Extract from document, and see if basically CC-BY-allow commercial use (something).

**Comment by beutlich** [comment]
> That seems like CC BY-SA

Which would match the [FMI specification license](https://github.com/modelica/fmi-standard/blob/master/LICENSE.txt):

> The FMI specification is released under the CC-BY-SA (Creative Common Attribution ShareAlike 4.0 International)

**Comment by HansOlsson** [comment]
Agreement by acclamation.
