### ISSUE TITLE
Fix incorrect wording for builtin function symmetric

### ISSUE THREAD

**Issue by miscco** [modelica/ModelicaSpecification#2295]
Currently the specification states:

>The following set of built-in matrix and vector algebra functions are available. The function transpose can be applied to any matrix. The functions outerProduct, symmetric, cross and skew require Real/Integer  vector(s) or matrix as input(s) and returns a Real vector or matrix: 

However, symmetric clearly doesnt make sense with respect to vectors. Also these operations should return integer matrices when applied to a matrix of type integer.

I would propose the following wording instead:
>The following set of built-in matrix and vector algebra functions are available. The functions transpose and symmetric can be applied to any matrix. The functions outerProduct, cross and skew require Real/Integer vector(s) or matrix as input(s) and return a Real/Integer vector or matrix: 

Also we should either require a square matrix for symmetric or remove the word "diagonal" from the wording in the table:

> Returns a matrix where the diagonal elements and the elements above the diagonal are identical to the corresponding elements of matrix A and where the elements below the diagonal are set equal to the elements above the diagonal of A, i.e., B := symmetric(A) -> B[i,j] := A[i,j], if i <= j, B[i,j] := A[j,i], if i > j.

This seems more or less confusing and we only need the mathematical description.

**Comment by HansOlsson** [comment]
I assume everyone else also agrees with this.

**Comment by sjoelund** [comment]
I must have missed this... In #622 we clarified that the `Integer` variants were not needed (and that's what is implemented in tools as far as I know)

**Comment by HansOlsson** [comment]
> I must have missed this... In #622 we clarified that the `Integer` variants were not needed (and that's what is implemented in tools as far as I know)

As far I can see it was proposed, but not implemented.

**Comment by sjoelund** [comment]
It was implemented, and the specification was changed. 3.2r1 didn't say anything about the types and 3.2r2 clearly states that it returns a Real vector.

**Comment by HansOlsson** [comment]
> It was implemented, and the specification was changed. 3.2r1 didn't say anything about the types and 3.2r2 clearly states that it returns a Real vector.

Oops. Then we should revert as you wrote.

**Comment by sjoelund** [comment]
OK, I'll provide a PR

**Comment by HansOlsson** [comment]
> OK, I'll provide a PR

Which is #2673 and it has been merged.
