### ISSUE TITLE
Connector inheriting from expandable connector?

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2298]
When reviewing https://github.com/modelica/ModelicaStandardLibrary/pull/2799 I looked through the inheritance table and noticed that a connector may inherit from an expandable connector (but not the reverse).

Since there are many special rules for expandable connectors (variables are only potentially present, variables are automatically connector-variables) it was not clear if this is desirable.

**Comment by HansOlsson** [comment]
Can anyone see a problem with forbidding a connector to inherit from an expandable connector?

**Comment by svorkoetter** [comment]
I don't see any problem with prohibiting it. To my mind, expandable connectors aren't really connectors at all; they are models consisting entirely of an ever growing collection of connectors.

**Comment by henrikt-ma** [comment]
Yeah, wouldn't it be strange to have something declared as a plain connector in the end being an expandable creature due to inheritance?

**Comment by HansOlsson** [comment]
Language group agrees by acclamation.
