### ISSUE TITLE
Clarify order of inherited components

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2310]
It is not yet clarified that the order of the components (in the parameters dialog) depends on the position of the extends clause in case of inherited components involved. Currently tools behave differerently here: Dymola respects the order according to the position, SimulationX always groups inherited components last (independently of the position). We want to fix this in a consistent way, but need to rely on a unambiguous specification here as clean reference.

See the following example and check the order of the dialog tabs, dialog groups and parameters in the three model instances.

```mo
model M
  model Base
    parameter Real base1=1 "Parameter" annotation(Dialog(group="BaseGroup1", tab="BasePage1"));
    parameter Real base2=2 "Parameter" annotation(Dialog(group="BaseGroup1", tab="BasePage1"));
    parameter Real base3=3 "Parameter" annotation(Dialog(group="BaseGroup2", tab="BasePage1"));
    parameter Real base4=4 "Parameter" annotation(Dialog(group="MixedGroup1", tab="MixedPage1"));
    parameter Real base5=5 "Parameter" annotation(Dialog(group="BaseGroup1", tab="MixedPage1"));
  end Base;

  model Model1
    extends Base; // inherited parameters are sorted first
    parameter Real model5=5 "Parameter" annotation(Dialog(group="ModelGroup1", tab="ModelPage1"));
    parameter Real model6=6 "Parameter" annotation(Dialog(group="MixedGroup1", tab="MixedPage1"));
    parameter Real model7=7 "Parameter" annotation(Dialog(group="ModelGroup1", tab="MixedPage1"));
    parameter Real model8=8 "Parameter" annotation(Dialog(group="ModelGroup1", tab="ModelPage2"));
  end Model1;

  model Model2
    parameter Real model5=5 "Parameter" annotation(Dialog(group="ModelGroup1", tab="ModelPage1"));
    parameter Real model6=6 "Parameter" annotation(Dialog(group="MixedGroup1", tab="MixedPage1"));
    extends Base; // inherited parameters are mixed in
    parameter Real model7=7 "Parameter" annotation(Dialog(group="ModelGroup1", tab="MixedPage1"));
    parameter Real model8=8 "Parameter" annotation(Dialog(group="ModelGroup1", tab="ModelPage2"));
  end Model2;

  model Model3
    parameter Real model5=5 "Parameter" annotation(Dialog(group="ModelGroup1", tab="ModelPage1"));
    parameter Real model6=6 "Parameter" annotation(Dialog(group="MixedGroup1", tab="MixedPage1"));
    parameter Real model7=7 "Parameter" annotation(Dialog(group="ModelGroup1", tab="MixedPage1"));
    parameter Real model8=8 "Parameter" annotation(Dialog(group="ModelGroup1", tab="ModelPage2"));
    extends Base; // inherited parameters are sorted last
  end Model3;
  Model1 model1 annotation(Placement(transformation(extent={{-60,60},{-40,80}})));
  Model2 model2 annotation(Placement(transformation(extent={{-20,60},{0,80}})));
  Model3 model3 annotation(Placement(transformation(extent={{20,60},{40,80}})));
end M;
```

**Comment by HansOlsson** [comment]
Would be good to have this clarified at the meeting.

**Comment by HansOlsson** [comment]
Henrik: Could specify that variables in groups and tabs should be in declaration order, where inherited ones are added at the place of extends and then also define order of groups, or leave entirely undefined.
Poll:
Specify order completely: 4
Only specify order within groups: 3
Entirely undefined: 3
Abstain: 2
Seems narrow majority for completely defined.

Henrik: But tearing heuristics (etc) is influenced by order; so reordering for dialog may cause problems. One solution would be to have special annotations to re-order them in the parameter-dialog. Another use-case is moving inherited parameters - but might also want to change tab/group?

Should we first add that parameter dialog is according to declaration order (and then allow re-arranging the parameter-dialog by an optional annotations):
Favor: 6
Against: 1
Abstain: 3
