### ISSUE TITLE
Using state machines in Modelica

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2313]
In Modelica there are multiple ways of building state machines:
* Just use when-statements
* Using [Modelica.StateGraph](https://github.com/modelica/ModelicaStandardLibrary/blob/master/Modelica/StateGraph.mo) (alternatively using [Modelica_StateGraph2](https://github.com/modelica/Modelica_StateGraph2))
* Synchronous state machines as part of the specification

But I don't see many uses of either of the latter two - or any comparison, which leads to two questions:
* Is anyone using them? If so, is there any feedback? If not, why not - is something missing? Ticket #2287 is relevant for this.
* How do the different variants compare? 

To answer the second question, I tried to see if it was possible to construct synchronous state-machines corresponding to Modelica.StateGraph.Examples and it only sort of worked. It is obvious that the formalism are similar, so most things work. However, one major issue is that the example use `time`  as condition, and you cannot use that in a synchronous partition - and another is that Modelica.StateGraph has time-delay for transitions and synchronous state-machines has clocked transitions.

Is it meaningful to construct such examples for comparison?

I understand that the synchronous state-machines is a recent addition so it could be that use hasn't started yet, but for the same reason we might also have missed some necessary improvement.

[StateMachineExamples.zip](https://github.com/modelica/ModelicaSpecification/files/2851245/StateMachineExamples.zip)

**Comment by beutlich** [comment]
Im aware of the Buildings library that utilize Modelica.StateGraph and even converted from Modelica_StateGraph2 for improved tool interoperability: https://github.com/lbl-srg/modelica-buildings/issues/504

**Comment by HansOlsson** [comment]
Ok, so one obvious difference is that Modelica_StateGraph2 uses non-standard extensions (Modelcia.StateGraph does not), specifically 
Connections.uniqueRootIndices and Connections.uniqueRoot

And there is no corresponding MCP or similar proposal for adding them.

The uniqueRoot is just intended for nicer diagnostics (compared to normal roots) - and we could do without it; or add it as a general improvement for roots.
The uniqueRootIndices is more needed (for analyzing lack of delay in a graph); but it might be possible to find this issue in another way. (Constructing equations that are singular without a delay.)

**Comment by HansOlsson** [comment]
Looking through the uses in the Buildings-library (and the Modelica.StateGraph.Examples again) I see that the following features are missing if we want to replace Modelica.StateGraph (or Modelica_StateGraph2) by the state machines added in Modelica Language Specification 3.3:

* Something that best could be described as triggered (non-synchronous) state machines:
  * Different transitions triggered by different non-clocked boolean signals: as noted in #2287
  * Delayed transitions (with relative time), as noted in #2287
* GUI
  * Connecting a (non-clocked) boolean signal to a transition
  * Having a boolean signal corresponding to a (sampled) boolean signal of whether the state is active
  * The different style of the transitions compared to connections might also be reconsidered for this case

The design philosophy differs: Modelica.StateGraph is designed around interacting with an external system (explaining the connections to transitions and from active state), whereas the state machines in Modelica are designed around having the system within the state machine.

It seems clear that these differences are non-trivial; so the minimum would be to clearly describe this.

**Comment by beutlich** [comment]
I added some [feedback](https://trac.modelica.org/Modelica/browser/ModelicaDesign/trunk/MeetingMinutesMaterial/min98_2019_Regensburg/ESI_ITI_Feedback_ModelicaStateMachines.docx) on the Modelica State Machines from a control engineer at ESI ITI. Main focus was on usability, especially in SimulationX, and comparison with other solutions.

**Comment by beutlich** [comment]
One more (new) user of Modelica.StateGraph: The ControlSystems of the [Greenhouses-Library](https://github.com/queraltab/Greenhouses-Library)

**Comment by HansOlsson** [comment]
Language group:
Issue: A clocked state graph would have that different transitions with have different clocks. Having multiple clocks for a state machine would be complicated. 

One application for clocked state machines would be a controller running every milli-second, with state machine for modeling its logic - could that be handled by a state-graph with clocked transition conditions?

Seems that no language extension is needed.
