### ISSUE TITLE
Lower part of TOC in HTML version is unreachable

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaSpecification#2319]
When looking at the [HTML version](https://specification.modelica.org/master/MLS.html) then the left TOC frame can not be fully accessed once a section is opened that contains many entries (like [E Modelica Revision History](https://specification.modelica.org/master/A5.html)).

This needs to be improved.

**Comment by HansOlsson** [comment]
I agree that it needs to be improved. 

As far as I can tell it is a recent **regression in this project**.

- Originally the left part scrolled with the window. (I had some old version.)
- I get the same issue locally; without updating LaTeXML; so it does not seem like a problem with specification.modelica.org or with some external dependency.

The earlier variant wasn't _ideal_ as you have to scroll the page to top to navigate - but losing part of the navigation is worse. I see that some other web-sites have multiple scrollable parts without scrollbars; that seems like a fairly simply solution.

**Comment by dietmarw** [comment]
We simply need to [embrace frames](http://www.angelfire.com/super/badwebs/) again :smiling_imp:
