### ISSUE TITLE
https://specification.modelica.org/ should forward to a working page

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaSpecification#2327]
Currently, you can not access the HTML version specification page unless you know the deep link target. So ideally https://specification.modelica.org/ should forward to something working. 

(This works fine on https://modelica.readthedocs.io/ w/o problems.)

**Comment by HansOlsson** [comment]
I agree that would be good.

I don't know who can do it, and I don't know if we should redirect to HTML or have a front-page with links to HTML and PDF and possibly for multiple revisions. (Similarly as doc.modelica.org; but obviously not tool-specific versions.)

**Comment by sjoelund** [comment]
Should this be manually updated or should we read all branches and tags to create a list automatically by Jenkins?

**Comment by sjoelund** [comment]
Actually, should we simply turn the README.md into HTML and host it there? Or link back to the github repo?
