### ISSUE TITLE
Generated PDF misses section numbers in bookmarks

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2337]
It would be more convenient if the generated PDF contains the section numbers in the bookmarks (as was the case for the PDF generated from Word).

Current bookmark:

![2019-03-26 07_54_45-MLS pdf - SumatraPDF](https://user-images.githubusercontent.com/14896695/54977161-c3347c00-4f9c-11e9-8417-129e51fca31e.png)

Desired bookmark:

![2019-03-26 07_53_37-ModelicaSpec34 pdf -  Modelica - A Unified Object-Oriented Language for Systems ](https://user-images.githubusercontent.com/14896695/54977169-c891c680-4f9c-11e9-9371-1ea25dbb4c21.png)

**Comment by HansOlsson** [comment]
Closed by #2372, I realize I should have updated the comment to refer to the duplicate ticket and not only to #2367.
