### ISSUE TITLE
How to include incorrect models as examples in packages?

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2340]
When looking at https://github.com/modelica/Modelica_StateGraph2/issues/1 one of the issues is that the library contains incorrect models to illustrate what types of errors the library will detect.

Generating an error message for them during check of the package doesn't make sense, and thus a non-standard annotation (`__Dymola_inhibitCheck=true`) inhibits the check. Note that the intent is different from `annotation (__ModelicaAssociation(TestCase(shouldPass = false))) `- which is used in the semantic test-suite to indicate a model where we want to test the diagnostics.

One way of avoiding this issue - found in parts of MSL - is to only have images representing such models, and not include them as actual models. That might be good enough in some cases.

Added: Note that above it says "during check of the package". The reason is that this allows users (and developers) to check Modelica_StateGraph2 and get a clean result.

If someone tries to check/translate the specific incorrect model it doesn't make sense to do anything special. I can see at least two scenarios where that happens:
- The user want to see the error message for the incorrect model (to understand how it is diagnosed)
- The user is confused and selected the wrong model

In both cases just generating the normal error message makes perfect sense.

**Comment by HansOlsson** [comment]
Language group:

"Don't check" seems too generic. Would prefer more specific description of what fails - but not clear if that is the same for all tools. So just "error" might work, and in one sense similar to ModelicaCompliance - and will check whether that suffices. An issue is whether this produces too much diagnostics.

Note that the compliance annotations used in ModelicaCompliance are not part of the language specification - but would make sense to standardize those, and then consider this as a use-case as well.

Agreement.

**Comment by HansOlsson** [comment]
A proposal for this:

Classes may have an annotation `TestCase` described as a record:
```
record TestCase
  parameter Boolean shouldPass;
end TestCase;
```
If `shouldPass` is `false` it indicates that the translation or the simulation of the model should fail. If a tools checks a package where classes have `shouldPass=false` they should not generate errors - and testing them may even be skipped; if a model with `shouldPass=false` translates and simulates without error that should generate a diagnostics.
Similarly as a class with obsolete-annotation a class with TestCase annotation (regardless of the value of shouldPass) shall not be used in other models, unless those models also have a TestCase annotation.
[This means that we can freely change them between versions. The reason for skipping tests of cases that should fail is that we would need to simulate the model to ensure whether it fails or not - and that may be too time-consuming in some cases; but obviously possible as well. ]


This would update ModelicaCompliance so that instead of:
```
 annotation (
    __ModelicaAssociation(TestCase(shouldPass = false, section = {"4.8.7.1"})),
```
we would have:
```
   annotation (
    TestCase(shouldPass = false, __ModelicaAssociation(section = {"4.8.7.1"})),
```
What I considered:

- Standardizing what fails (instantiation/translation/simulation)? We already found that it was too difficult, basically if the simulation will fail some tools fail early - e.g. detecting that assert will always be false or that we unconditionally divide by a value that is zero. Specifying that the tools must detect that seems too much standardization-work, and requiring that tools must translate them and don't fail until simulation seems to standardize suboptimal behaviour.
- Should shouldPass have a default? Regardless of value I believe that `shouldPass=false` (or true) is a good idea and thus lacking a default seems better.
- Standardizing error-reference, but it seems difficult to cover all cases; and just having "Error" container without any specified contents doesn't seem to add much.
- Something for textually describing what is tested. However, currently the documentation does a good job for that - and I don't see any problem with that (unless the documentation itself is what is tested, but that is just one case and can likely be worked around).
- Thus I believe that the simplest idea is that the documentation can start with/contain a link (http: or modelica:) to the relevant description, i.e. replace section by a link to that spec-section in the documentation. No need to write that in the specification; it's just good style.

Thus leading to something
```
   annotation (
    TestCase(shouldPass = false),
    Documentation(info="<html>https://specification.modelica.org/master/class-predefined-types-and-declarations.html#stateselect describes that stateSelect...</html>")
```

**Comment by GallLeo** [comment]
I think this proposal is a very good step forward and should be straight-forward to add for Modelica 3.5?

Later, one could add an alternative experiment annotation, something like TestCase(shouldPass=true, experiment(...))
this can be useful to change the default experiment annotation for testing purposes. E.g.
a) only use a short simulation time for chaotic examples
b) use more output intervals and stricter tolerance for regression testing

**Comment by maltelenz** [comment]
> This could be useful to change the default experiment annotation for testing purposes.
> E.g.
> 
>     1. only use a short simulation time for chaotic examples
> 
>     2. use more output intervals and stricter tolerance for regression testing

I see this part as problematic, since it means testing would no longer happen on what the user of the model actually experiences. Such things should not be encouraged. We already have problems with MSL reference results differing from what a user sees, since the reference results are generated with more output intervals.

**Comment by GallLeo** [comment]
> I see this part as problematic, since it means testing would no longer happen on what the user of the model actually experiences. Such things should not be encouraged. We already have problems with MSL reference results differing from what a user sees, since the reference results are generated with more output intervals.

I agree, for most cases. The MSL examples should just be changed to be accurate enough.

But, this language feature is not only about MSL or other public libraries.
There will always be scenarios where you do want to change the test setup and this annotation would be a very transparent way to do so (much more transparent than changing it in some test-tool setup).
But, maybe it is not needed, once we have inheritance on annotations.
Then, the simple shouldPass=true might be enough.

**Comment by henrikt-ma** [comment]
> Later, one could add an alternative experiment annotation, something like
> `TestCase(shouldPass=true, experiment(...))`

I think it would be even more useful to reverse the inclusion.  Having more than one `experiment` annotations has many more applications beyond defining test cases, but there could be a subset of all experiments that are meant to be used as test cases.  Some models, of course, could just have a single experiment that constitutes a test case.

Therefore, without introducing multiple experiments right now, I'd propose to simply place the `TestCase` inside the only `experiment` annotation:
```
   annotation (
    experiment(
      …,
      TestCase(shouldPass = false, __ModelicaAssociation(section = {"4.8.7.1"}))),
```

**Comment by HansOlsson** [comment]
> Therefore, without introducing multiple experiments right now, I'd propose to simply place the `TestCase` inside the only `experiment` annotation:
> 
> ```
>    annotation (
>     experiment(
>       …,
>       TestCase(shouldPass = false, __ModelicaAssociation(section = {"4.8.7.1"}))),
> ```

I don't think we should necessarily combine the two as there can be incorrect models that aren't meant to be simulated. Perhaps not for stateSelect in 4.8.7.1, but certainly in other cases.

Problems can be detected for checks of non-simulation model, during checks/translation for simulation model, during initialization and starting of simulation model, and some later time during simulation. (Whether something is detected during translation or during initialization/simulation is not always clear - thus it might make sense to simulate the model to detect the error if no error is detected during translation.)

Only in the last case is the normal part of the experiment-annotation needed, so I don't see that it's good to combine the two.

**Comment by henrikt-ma** [comment]
I thought of that too, but come to the conclusion that such models would simply not have a `StopTime` in their `experiment`.  Still, I agree that the `experiment` isn't the most natural place for `TestCase` when the model it isn't meant for simulation at all.

**Comment by maltelenz** [comment]
And in fact, we want to avoid adding `experiment` annotations to classes that are not meant for simulation. At least System Modeler uses the presence of that annotation as an indication that the class is meant for simulation (as part of a heuristic).

**Comment by HansOlsson** [comment]
Agreement on TestCase.
