### ISSUE TITLE
Clarification on named argument for Clock constructors

### ISSUE THREAD

**Issue by Daiwen** [modelica/ModelicaSpecification#2344]
When defining the Clock constructors in section 16.3, it is left unspecified whether the constructors can be called with named arguments.
It is worth noting that "Modelica_Synchronous.ClockSignals.Clocks.PeriodicExactClock" uses a call to Clock with the named argument `solverMethod`.

When defining `homotopy` which can be called with named arguments, the specification uses the named argument syntax, in the call example, to make it clear that it is possible. I suggest that we do something similar for these constructors.

**Comment by HansOlsson** [comment]
I agree and I see two reasons for using named arguments for Clock:

- Knowing which argument is which, similarly as looking at a call of homotopy I don't want to wonder about the order of the arguments - and the names are clearer than the order. 
- The named arguments make it easier to separate the different overloaded variants. If I see Clock(n) and Clock(p) and Clock(c, "ExplicitEuler") it is less clear which variant is which.

**Comment by HansOlsson** [comment]
Language group:

All argument to Clock can be used as named arguments (with current names).
Similarly for multi-letter arguments for subSample, superSample, backSample, shiftSample - and change 2nd argument of sample to "clock".

Agreement by acclamation.
