### ISSUE TITLE
Ambiguities in Text annotation

### ISSUE THREAD

**Issue by adeas31** [modelica/ModelicaSpecification#2346]
The text annotation record is defined in section 18.6.5.5 as,
```
record Text
 extends GraphicItem;
 extends FilledShape;
 Extent extent;
 String textString;
 Real fontSize = 0 "unit pt";
 String fontName;
 TextStyle textStyle[:];
 Color textColor=lineColor;
 TextAlignment horizontalAlignment = TextAlignment.Center;
end Text;
```
With a following text,

> The textColor attribute defines the color of the text. The text is drawn with transparent background and no
> border around the text (and without outline). The contents inherited from FilledShape is deprecated.

If the `FilledShape` contents are deprecated then why `extends FilledShape` is still there? Is this for backwards compatibility? If so maybe this should be clarified in the specification.

Moreover the text record is also defined in section 18.6.4 as,
```
record Text
 extends GraphicItem;
 extends FilledShape;
 Extent extent;
 String string;
 Real fontSize = 0 "unit pt";
 String fontName;
 TextStyle textStyle[:];
 Color textColor=lineColor;
 TextAlignment horizontalAlignment = if index<0 then TextAlignment.Right
 else TextAligment.Left;
 Integer index;
end Text;
```

The difference compared to other declaration of the record is that new field `index` is added. Also note that field `textString` is changed to `string`. Why do we have two different declarations? Isn't is easy to have one record?

**Comment by HansOlsson** [comment]
> If the FilledShape contents are deprecated then why extends FilledShape is still there? Is this for backwards compatibility? If so maybe this should be clarified in the specification.

Yes, it is kept for backwards compatibility, I don't know when we can realistically remove it. 
Note that the inherited "lineColor" is used.

We could change "is deprecated" to "is deprecated, but kept for compatibility reasons".

> The difference compared to other declaration of the record is that new field index is added.

They are for slightly different uses: pure text - vs. text on a connection line (which explains the index).
Note that another important difference is that the extent is offset from that connection point.

**Comment by adeas31** [comment]
> Note that the inherited "lineColor" is used.
You mean it is used when there is no `textColor`, right?

> We could change "is deprecated" to "is deprecated, but kept for compatibility reasons".
Sounds reasonable.

> They are for slightly different uses: pure text - vs. text on a connection line (which explains the index).
Well we can still have only one record which contains the `index`.
> Note that another important difference is that the extent is offset from that connection point.
True but they still have the same types. All we need is just better explanation of two different use cases. Not to forget `textString` and `string`.

**Comment by HansOlsson** [comment]
> You mean it is used when there is no textColor, right?

Yes.

> Well we can still have only one record which contains the index.

We could - but that means another incompatible change as well (for the strings) - with deprecation if we want to ensure backward compatibility etc; and then we need to explain that the index can only be used in some cases. If we want to unify it seems that having two separate records in combination with inheritance would allow us to clearly show the similarity and difference without introducing any backward incompatibility.

> True but they still have the same types. All we need is just better explanation of two different use cases

Unifying variables that have the same type, but different semantics can in my opinion be more confusing than helping.

To me this is more one of those issues that we can keep in mind for future changes, but don't change now.
