### ISSUE TITLE
What does noClock(Clock(1)) mean?

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2355]
Based on #2272 it was found that noClock is defined in a table of sub-clock conversion operators - where all the others can take a Clock as input.

Language group: Agree that noClock should not be allowed to take a Clock as input.

**Comment by miscco** [comment]
I have a small trouble with the result of the `noClock` operator. From the specification I read:

> The clock of y = noClock(u) is always inferred. At every tick of the clock of y, the operator returns the value of u from the last tick of the clock of u. If noClock(u) is called before the first tick of the clock of u, the start value of u is returned.

If I understand it correctly if there a two subClocks with the same BaseClock that activate at the same time, `noClock(x)` should return `previous(x)`.

For a concrete example
```
model NoClock
	Clock baseClock = Clock(0.3);
        Clock subClock  = subSample(baseClock, 2);
	Real x;
        Real y;
	equation
                x = sample(time, baseClock);
		when subClock then
			y = noClock(x);
		end when;
end NoClock;
```

As I currently read the specification the variable `y` should have the value 0 at time `t==0.0` and 0.3 at time `t==0.6`. In contrast Dymola evaluates `y` to 0.6 at time `t==0.6`.

If it would indeed be correct that `y` evaluates to 0.6 at time `t==0.6`. then we would have to guarantee the evaluation order of the subClocks. Therefore, we should make clear, that `noClock(x)` is equivalent to `previous(x)` however ignoring partition boundaries.

However, in my opinion `noClock(Clock(1))` is defined perfectly fine. From the specification for the rational clock constructor

>The output argument is of base type Clock that ticks when time becomes t_start, t_start+interval1, t_start+interval1+interval2,...

Consequently before the first clock tick `noClock(Clock(1))` should return `t_start` and afterwards the corresponding time of the clock tick

**Comment by miscco** [comment]
in the light of !2365 I believe that the behavior of Dymola is indeed incorrect and it should return the value from the last clock tick even if the two tick co-occur, aka an implicit `previous`

**Comment by HansOlsson** [comment]
> Consequently before the first clock tick noClock(Clock(1)) should return t_start and afterwards the corresponding time of the clock tick

That does not work,, as the that would be a Real value and not a Clock, whereas the caption says "If u is an expression of type Clock, the operator returns a Clock."

>in the light of #2365 I believe that the behavior of Dymola is indeed incorrect and it should return the value from the last clock tick even if the two tick co-occur, aka an implicit previous

Wouldn't that make noClock equivalent to sample(hold(..)) - which we don't want (as stated in #1094 ).

**Comment by miscco** [comment]
I always interpreted as Clock to be more of an execution time, but yeah it it technnically a different type, so scratch that.

I believe the difference between `noClock(u)` and `sample(hold(u))` is the lack of event Iterations. In the later case, whenever `u` changes its value we need to perform an event iteration in the continuous-time system. However this is not the case with `noClock(u)`
