### ISSUE TITLE
Make unit attribute constant to enable unit checking

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2362]
In the definition of `Real` in 4.8.1 _Real Type_, we declare the `unit` attribute like this:
```
parameter StringType unit = "" "Unit used in equations";
```
By not requiring this to be `constant`, users may actually use parameter expressions, which may not be treated as structural parameters today since unit checking hasn't been standardized.

Later, if we manage to standardize unit checking, this would require constant evaluation of the `unit`, causing any parameters being used in the expression to also be constant evaluated.

To me, it just seems unnecessary to not make users aware of this already today by instead saying:
```
constant StringType unit = "" "Unit used in equations";
```
Then, there will be no surprises when doing unit checking in the future.

**Side note:** The same could also be said for several of the other attributes.  At least, I think it would be natural for `quantity` to have the same variability as `unit`.  On the other hand, I don't think there is any compelling reason to make `displayUnit` constant (even though I would guess that current tool support for changing it after translation is rare at best).  In a perfect world, one would also change `fixed` and `stateSelect`, but here I'm afraid that users may already be depending on translation time evaluation of parameters, so fixing these would probably break more existing models.

**Comment by HansOlsson** [comment]
We have had more than a year without new discussion, and we have #2754 for new discussions about structural parameters.

**Comment by henrikt-ma** [comment]
This topic is now being revisited as part of #3386.
