### ISSUE TITLE
Implement 99th Design Meeting polls for MCP-0033

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2363]
The following notes from the 99th Design Meeting should be implemented on the [MCP/0033](https://github.com/modelica/ModelicaSpecification/blob/MCP/0033/RationaleMCP/0033/predefined-plots.md) branch:

> Demonstrated Dymola and Wolfram Systems Modeler.
> One issue is how much to add; one issue was displayUnit – in particular for time. (Axis changes also needed?) Animation is a separate issue (as a separate MCP, no overlap).

> Polling: 
> 
> Remove axis-range:
> Favor: 1
> Against: 6
> Abstain: 7

> Add HTML-captions (possibly several paragraphs – describing the purpose of the plot etc):
> Favor: 7
> Against: 0
> Abstain: 7

> Sub-plot title (on each plot with separate x-y axis) – note that caption may be below or on the side, so caption does not replace title:
> Favor: 10
> Against: 0
> Abstain: 4

> A separate optional identifier for each plot (in addition to title – for programmatic access, label in LaTeX):
> Favor: 9
> Against: 0
> Abstain: 5

**Comment by HansOlsson** [comment]
Merged into branch, thus closing. (I haven't figured out how to automate this for branches.)
