### ISSUE TITLE
Show numbering of chapters and sections in PDF table of contents

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2367]
The current PDF table of contents (not the table of contents in the main document, before the preface) doesn't show the numbering of chapters and sections, making it less useful for quickly locating a section by number.

**Comment by beutlich** [comment]
Is this a duplicate of #2337?

**Comment by HansOlsson** [comment]
> Is this a duplicate of #2337?

Yes. Note that the proposed solution is not 100% identical though as the PR has bookmarks with "A ..." instead of "Appendix A ...".

**Comment by henrikt-ma** [comment]
Yes.  Closing as _Duplicate_.
