### ISSUE TITLE
Fix formatting of brackets surrounding non-normative text

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2368]
There are 51 occurrences of the following in the sources:
```
\emph{{[}
```

As far as I can tell, this should always have been formatted with the bracket outside of the emphasis (487 matches):
```
{[}\emph{
```

**Comment by HansOlsson** [comment]
I agree that it would be better and consistent. 
However, note that in many (all?) of the cases we had the same issue in the Word-version of the document - so it was just converted as is to the new format.

**Comment by henrikt-ma** [comment]
Sure.  When should we start moving all non-normative text into separate paragraphs in the `nonnormative` environment?

**Comment by henrikt-ma** [comment]
Too bad we didn't decide this during the meeting, as it would be nice to coordinate this kind of large but not very controversial change in time with a thing like #2364 (already in progress) that is also modifying almost all parts of the specification source code.

**Comment by henrikt-ma** [comment]
The most important part of what remains of this is now reported separately as #2536.  Closing.
