### ISSUE TITLE
Rename "documentation string" and "documentation comment"

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2371]
Section 2.2 says:

> There is also a kind of “documentation comment,” really a documentation string that is part of the Modelica language and therefore not ignored by the Modelica translator. 

In B.1 it is called "description string":

> Description strings (= production “string-comment” in the grammar) and ...
(It is also called "description" in other places.)

Since we also have a different annotation documentation (in 18.2) it seems better to consistently call this "description" and rewrite section 2.2 to:

> There is also a “description string,” that is part of the Modelica language and therefore not ignored by the Modelica translator. 

(Removing hedging words; such as "kind of" and no need to call it "comment".)

**Comment by HansOlsson** [comment]
On second thought:

Why not consistently call it "description-string" also in the grammar?

The paragraph above would then become:

> There is also a description-string, that is part of the Modelica language and therefore not ignored by the Modelica translator.

and the other one something like:

> Each description-string or string in annotations (= STRING with production annotation-comment in the grammar) may contain any member of the Unicode character set.

**Comment by svorkoetter** [comment]
I like the "description-string" suggestion, since it really isn't a "comment" in the usual programming language sense of the word (i.e. completely ignored by the interpreter or compiler).

**Comment by svorkoetter** [comment]
Also, in conjunction with #2435, we should change the name of the "comment" rule, since neither part of it would be considered a comment any more. Probably "description" would be a better name.

**Comment by HansOlsson** [comment]
And an additional poll for, also running to 2019-12-19:

- Using "description-string" instead of "documentation string" (and "string-comment" in grammar); i.e. `Real x "description string";
- Use "description" instead of "comment" in grammar.

```
description:    description-string [ annotation-something ] 
description-string:    [ STRING { "+" STRING } ] 
```
The annotation-something depends on the result of #2435 

Just use either thumbs up or thumbs down-reaction:
![Reactions2](https://user-images.githubusercontent.com/13217430/70222518-79ff1380-174a-11ea-81b1-6a2d6241cccb.png)

**Comment by dietmarw** [comment]
Could you clarify what :+1:  is for and what :-1: is for?
