### ISSUE TITLE
Make built-in attributes 'min' and 'max' constant to allow translation time simplifications

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2373]
The built-in attributes `min` and `max`, defined for `Real` and `Integer`, are defined as having parameter variability.  This suggests that it should be possible to change these after translation, and hence that these are not meant for use in symbolic processing during translation.

If I'm not mistaken, these attributes are already being used during symbolic processing by Dymola, and this is clearly something that would be generally useful in any tool.  For example, knowing that a mass flow is non-negative may lead to key simplifications of `semiLinear` expressions.

To make it clear that these may be used for symbolic processing, and that it isn't the intention that they should be changed after translation, I suggest that they are declared with variability `constant` rather than `parameter`.

**Comment by HansOlsson** [comment]
> The built-in attributes min and max, defined for Real and Integer, are defined as having parameter variability. This suggests that it should be possible to change these after translation, and hence that these are not meant for use in symbolic processing during translation.
>
>If I'm not mistaken, these attributes are already being used during symbolic processing by Dymola,

The same is true in the same sense for most other attributes: quantity, unit, displayUnit, fixed, nominal, unbounded, and stateSelection. The only exception is start - where we for non-literal value don't force an evaluation, but handle more general parameter-expression.

Lifting the restriction for most min/max attributes even seems easier than for fixed, and stateSelection.

Technically there are a number of variants:
* We store a value for attributes in models  - they must currently be literal; but it is not really part of the symbolic processing; and we can just decide to not store it (as for start).
* Unit-checking currently requires literal values for unit and displayUnit.
* We use attributes like min/max/fixed/stateSelect during symbolic processing.

We also require evaluation of structural parameters for array sizes, conditional components, and unbalanced if-statements. Some of these may also be reduced in the future.

**Comment by henrikt-ma** [comment]
I'm aware that most attributes are useful during symbolic processing, but I think it would help the discussion if we could consider a few of them at a time, and `min`/`max` seemed like a good starting point.

When you say _lifting the restriction_, do you mean to allow changing these after translation?  It may be the intuition that it should be easy to change these after translation that make `min` and `max` such a good starting point for this discussion.  The point I'm trying to make here is that by making clear that these shouldn't be changed after translation, it would become clear to everybody that they are OK to use during translation.  For others, such as `fixed`, it may be so obvious that it won't make sense to change after translation that it doesn't even seem necessary to mark as having `constant` variability.

I basically agree with your categorization into three variants, having only minor remarks:
* Why would an attribute value such as `start` need to be a literal?  Haven't we all seen examples where a parameter that is solved in the initialization problem is used to set the `start` attribute of another variable?
* I don't think we should talk about what unit checking currently requires, since this is still a somewhat open issue.  I can imagine checking units after flattening, and then it would be enough that `unit` was possible to constant evaluate, that is, have `constant` variability.  Then, I'm actually surprised that `displayUnit` would be needed during unit checking at all, but this may not be the right ticket for educating me on this point.  (I can see that a literal value for `displayUnit` can be statically verified against `unit`, but I'd like to think of `displayUnit` as something that can be changed after translation, and even after simulation.)

I'd also like to comment on the situation with "structural parameters" [double quotes to mark sarcasm, since there is no such thing in the specification], since I think it points to one of the core design principles that should guide us here.  For some things in the language, it makes sense to start with just the simplest cases, and leave it to future versions of the language to generalize and cover more difficult cases.  For other things, having the courage to say that there is no plan to lift a restriction gives valuable stability to the echo system.  To me, this applies to the "structural parameters" — lift these restrictions and you get a language that is so different that it shouldn't even be called Modelica any more; perhaps Modia would be better name.

Given the discussion so far, would it be a better idea to change all attributes except `start` and `displayUnit` at once, instead of just starting with `min` and `max`?

**Comment by HansOlsson** [comment]
> When you say lifting the restriction, do you mean to allow changing these after translation? It may be the intuition that it should be easy to change these after translation that make min and max such a good starting point for this discussion.

Yes, allowing changing parameters used for min/max after translation - in many cases.

Not all cases, since the parameter for flow-reversal indirectly influences the symbolic processing through setting a min-attribute that is evaluated, and then used in streams-connector-processing.

**Comment by HansOlsson** [comment]
> I'd also like to comment on the situation with "structural parameters" [double quotes to mark sarcasm, since there is no such thing in the specification], since I think it points to one of the core design principles that should guide us here. 

However, the need to evaluate some parameters during translation is mentioned in:
1.2 Scope of the Specification 
16.2.3 Argument Restrictions (Component Expression

I believe that was deliberately a bit vague, and deliberately doesn't mention "structural parameters", since it is mostly important for parameter-sweeps etc that are not considered, and with just-in-time compilers it might be that even "structural parameters" can be changed efficiently. (Maybe, I don't know.)

**Comment by henrikt-ma** [comment]
Right, so the problem with the current state of affairs is that you don't know what you get for a parameter.  For a constant, you know that it can't be changed after translation (according to the non-normative text in 4.4.4), so there is no question whether it should be used during symbolic processing.  Making use of a parameter always comes with the unpleasant consequence that it cannot be changed after translation, so it becomes a matter of taste whether it is better to use it or to leave it a parameter of the simulation.

Hence, for the things we agree that it doesn't make sense to change after translation, we should therefore be clear about what to expect by declaring them `constant`.

Regarding sweeps over structural parameters and use of just-in-time compilers, I'd consider these some sort of just-in-time translations, and as such, it would still hold that the values of the structural parameters are only changed before translation, showing that there would not be a conflict in declaring them `constant`.

Similarly to the automated sweeps over constants, I think it would make perfect sense if a tool would also present (some selection of) constants in the same way as parameters after translation, and a user changing these constants would then understand that this would re-trigger translation and that all sorts of structural changes may follow.  Again, this shows that there is no need to be afraid of declaring structural parameters `constant`.

**Comment by HansOlsson** [comment]
> Again, this shows that there is no need to be afraid of declaring structural parameters constant.

My concern is that introducing a separate prefix for structural parameters - with current restrictions on constant expressions - cause a rippling wave of changes in models; especially when some want a parameter to be structural - and some want it variable for more easily changing it.

In C++ some see similar issues for `const`; and it can be a real issue and that's one reason C++ has the ability to cast away const-ness, and we don't have something similar in Modelica.

To me it would actually make sense to go the other way and remove the current `parameter `prefix in many models, e.g. Modelica.Electrical.Analog.Basic.Resistor might as well have a non-parameter as Resistance (similarly as VariableResistor), and then use current `annotation(Dialog(...))` or something else for indicating what should be in the parameter-dialog. 

But parameter would still keep the current meaning of not changing during a simulation - so we cannot _just_ make the capacitance in Modelica.Electrical.Analog.Basic.Capacitor variable. (It requires more changes.)

**Comment by henrikt-ma** [comment]
> > Again, this shows that there is no need to be afraid of declaring structural parameters constant.
> 
> My concern is that introducing a separate prefix for structural parameters - with current restrictions on constant expressions - cause a rippling wave of changes in models; especially when some want a parameter to be structural - and some want it variable for more easily changing it.

I don't see any need for a separate prefix for structural parameters; `constant` works fine, except that GUIs tend to treat them as if they shouldn't be changed at all.  Currently, I think the easiest way to deal with this is to use a Dialog annotation to make it clear that the variable shouldn't be hidden.  I think the required changes in GUI logics would come very natural once it was accepted that `constant` is a great way to model a structural parameter.

> In C++ some see similar issues for `const`; and it can be a real issue and that's one reason C++ has the ability to cast away const-ness, and we don't have something similar in Modelica.

But C++ has pointers and member functions.  I'm not convinced that Modelica would have the same pressing need to cast away variability.

Compare the following two variants on this theme.  First, the current, where parameters may turn into constants during translation; as a modeler, you don't really know what the parameters of you simulation will be.  Then, a world where structural parameters are declared `constant`, and parameters are guaranteed to remain parameters of the simulation; a tool can then figure out which constants that weren't needed to evaluate during translation, and provide a way to set them after translation.  In only one of these variants, parameters can be considered part of a well defined interface to the simulation (and be guaranteed to remain parameters in FMI export, etc).  

With tools being able to determine which constants that weren't needed to evaluate during translation (implementing this should be far easier than implementing correct handling of translation-time evaluated parameters), I think there should no more fear of lacking a variability cast in Modelica.

**Comment by sjoelund** [comment]
The only real problem from the language perspective if we did not care about backwards compatibility is with making structural parameters be forced to be declared constants is things like inheritance from an interface (only structural in some of the classes that inherit the element) and nested if-conditions (where a certain expression is only structural depending on what some other thing is set to). This can be overcome by good design (for the former) and marking more things constant than perhaps might need it (the latter).

For existing models to use constants instead it is a huge amount of code that needs to be updated. But the gain for the users to be able to predetermine which parameters can be changed without recompilation is equally huge. Perhaps losing the ability to optimise some expressions by evaluating a parameter to break an algebraic loop is a loss in performance but in that case it could be made constant or perhaps be given a hint `Evaluate=true` to mean "allow evaluating this if you think it improves performance" (`constant` means "evaluate this").

**Comment by henrikt-ma** [comment]
> To me it would actually make sense to go the other way and remove the current `parameter `prefix in many models, e.g. Modelica.Electrical.Analog.Basic.Resistor might as well have a non-parameter as Resistance (similarly as VariableResistor), and then use current `annotation(Dialog(...))` or something else for indicating what should be in the parameter-dialog.
> 
> But parameter would still keep the current meaning of not changing during a simulation - so we cannot _just_ make the capacitance in Modelica.Electrical.Analog.Basic.Capacitor variable. (It requires more changes.)

**Rambling warning!**

I see no contradiction with what I'd like to do for "structural parameters" here.  Having given this some though since you wrote this, I'm ending up thinking that it's been a mistake to consider `parameter` a different variability than discrete-time (`discrete`).  From an equation-solving point of view, it would make perfect sense to merge the two variabilities into one (discrete-time).  What is missing in Modelica, on the other hand, and that would also naturally be called a _parameter_, is a variable that isn't determined by the equations, and that only enters the equations in such a way that it can be set to a user-chosen value at initialization (or at events in general).  To avoid conflict with the current meaning of `parameter`, I will say _tunable_ (and use `tunable` as declaration prefix) when referring to the new meaning.

A `parameter` that is bound to a literal value is the perfect example of a tunable.  Using a `tunable` with binding equation can then be seen as syntactic sugar for just setting the `start` attribute which is to be used in case the user doesn't provide a value at initialization, so the binding equation shouldn't really be considered an equation for in the sense of the perfect matching rule.  The `tunable` prefix would then simply indicate that the variable should not be matched against any equation, and that the binding equation isn't really an equation but just a way to specify a default value.

The variability of a `tunable` would then be discrete-time, allowing other discrete-time variables to depend on it.  Likewise, the variability of the tunable's `start` attribute would also be discrete-time.  As long as the user doesn't provide a value for the tunable, the `start` attribute expression is re-evaluated as needed at every event (due to changes in other discrete-time variables), updating the value of the tunable.  When a user provides a value, that value remains in effect until the user sets another value or removes the value, in which case the `start` attribute expression becomes active again.

What is a non-fixed `parameter` today would then simply become just a discrete-time variable with non-fixed `start` attribute, an initial equation, and a dummy equation.  It would be nice if there was a canonical way to express the dummy equation for a discrete-time variable that doesn't change after initialization, similar to the current meaning of `parameter`, perhaps like this:
```
  discrete Real x(start = 1.0, fixed = false) = pre; /* Special binding equation for variable that doesn't change after initialization. */
initial equation
  x * x = 2;
```

The meaning of `final` for a tunable might then just mean that its attributes (and binding equation) can't be modified using Modelica constructs; it would still be possible to say that a user would be allowed to set the value after translation.  It would also be possible to say that it is then no longer possible to set after translation, but that would go against the basic definition of what defines a tunable.  What is a `final` `parameter` today would translate into a `final` (non-tunable) discrete-time variable.

While all talk of introducing `tunable` goes way beyond the scope of the current ticket, the fact that it points to some unfortunate semantics of `parameter` actually provides another reason to avoid the use of `parameter` for "structural parameters" and use `constant` instead.

Would anyone be interested in trying the idea of `tunable` in an MCP, perhaps combined with more general support for declaring and using discrete-time variability?

**Comment by HansOlsson** [comment]
> What is missing in Modelica, on the other hand, and that would also naturally be called a parameter, is a variable that isn't determined by the equations, and that only enters the equations in such a way that it can be set to a user-chosen value at initialization (or at events in general). 

Those two aren't necessarily the same, and introducing events here seems like a step in the wrong direction.

Consider an electrical Capacitor - in more detail than before: in MSL the usual one has a parameter and the equation: `i=C*der(v)`, but the VariableCapacitor (if we remove some guards) have the equations: `Q=C*v; der(Q)=i;`, which could be written as `i=der(C*v)`.

In this case it is well-known how to write the equations to handle changes in the tunable parameter, but in general it might be less clear and we don't want to incorrectly include such effects.

Additionally if the equations are written to handle changes in C they work also for non-discrete changes, and C should just be something that appears in the parameter-dialog, without any restriction on variability.
Finally if `C=0` it sort of becomes a structural parameter.

**Comment by henrikt-ma** [comment]
(I didn't think `der(C * v)` was valid Modelica?)  I think that there are pros and cons of both approaches.  First processing the equations as if `C` was differentiable, and then allowing it to be tuned in a non-differentiable way seems like a source of problems.  If `C` is declared to be tunable from the start, on the other hand, changing `C` as a tunable wouldn't be any more strange than a `reinit`.  (Given that a discrete change in `C` doesn't seem really physical in the first place, is it really that clear that there is only one "correct" way to do it?)

Are "big events" (aka _external events_) really that confusing?  I always thought is seemed like a nice thing to have in FMI, and something that would also be very useful for real-time Modelica simulations.

Some questions: Are you suggesting that `C` should appear in the parameter dialog, where it should be possible to bind it to a continuous-time expression?  Should it be declared without the `parameter` prefix and a binding equation, while tools should still present is as something that can be changed after translation?  Isn't that confusing?  Or are you saying that any variable without an equation (binding or not) is automatically becoming a parameter of the simulation?  What about detecting errors using the excellent perfect matching rule?

**Comment by henrikt-ma** [comment]
> For existing models to use constants instead it is a huge amount of code that needs to be updated. But the gain for the users to be able to predetermine which parameters can be changed without recompilation is equally huge.

The change can be made gradually by first deprecating the translation-time conversion of parameters to constants.

> Perhaps losing the ability to optimise some expressions by evaluating a parameter to break an algebraic loop is a loss in performance but in that case it could be made constant or perhaps be given a hint `Evaluate=true` to mean "allow evaluating this if you think it improves performance" (`constant` means "evaluate this").

Again, I think it would be better to make a `constant` declaration, and leave it to the tools to figure out when there is no point in evaluating it during translation, so that it can be treated as a (non-official) parameter of the simulation instead.

I can still see the use for the current meaning of `Evaluate = true`, but only as a quick and dirty way of setting up an experiment to evaluate the benefits of turning parameters into constants, without having to make all the propagated changes.  Therefore, I wouldn't go as far as to say that `Evaluate = true` should be deprecated, just that it should come with a mandatory warning about all the parameters that are affected by the annotation.

**Comment by HansOlsson** [comment]
> (I didn't think der(C * v) was valid Modelica?)

It is (sort of) valid since Modelica 2.2. 
However, it is only valid if both C and v are differentiable, since it is the same as `der(C)*v+C*der(v)`.

> Some questions: Are you suggesting that C should appear in the parameter dialog, where it should be possible to bind it to a continuous-time expression? Should it be declared without the parameter prefix and a binding equation, while tools should still present is as something that can be changed after translation? 

Without the current parameter-prefix, but some other indication that it is suitable for the "parameter dialog" (e.g., annotation(Dialog()). How that should interact with changing it after translation is less clear.

>Are "big events" (aka external events) really that confusing?

I would say that "big events" and "external events" are different; adding to the confusion. 
An "external event" would just be an input changing discontinuously.

**Comment by henrikt-ma** [comment]
Now that the discussion about turning model parameters into time-varying variables has had some time to sink in, perhaps we can put it aside and get back to the original topic of certain built-in attributes?

Would it be easier to agree on making just `min` and `max` constant to start with, or would it be easier if we also included `fixed`, `stateSelect` and `unit`?

**Comment by HansOlsson** [comment]
> Now that the discussion about turning model parameters into time-varying variables has had some time to sink in, perhaps we can put it aside and get back to the original topic of certain built-in attributes?
> Would it be easier to agree on making just min and max constant to start with, or would it be easier if we also included fixed, stateSelect, unit, and displayUnit?

Neither. (And as previously indicated we might consider not forcing evaluation of min/max in the future - unless they are used for the symbolic processing.)

I still see that as having a massive impact (and thus causing problems with backwards compatibility) without giving clear advantages. It's true that some users want to more clearly control/understand what parameters are evaluated/structural - but at the same time they also want to modify this within the models.

The latter part takes several form, and indicates that a strict separation into "parameter" and "constant" doesn't conform with user expectations (on the other hand user also want to understand what parameters are evaluated as structural parameters).

As an example of this: due to customer requirements, we last year updated the Dymola kernel to handle: 
```
parameter Boolean p=false; 
parameter Real x=2 annotation(Evaluate=p);
```
If we want to make some change I would say removing "constant" (and allowing parameters in packages) and also "discrete" might be an alternative. 

That would separate variables into two sets: the ones that have one value for the entire simulation ("parameter"), and the ones that may vary during the simulation (non-parameter).

Another (largely overlapping) separation would be those that should appear in parameter-dialogs (currently parameters and variables with `annotation(Dialog(...))`) and the ones that shouldn't.

**Comment by HansOlsson** [comment]
We have had more than a year without new discussion, and we have #2754 for new discussions about structural parameters.

**Comment by henrikt-ma** [comment]
I'm afraid all #2754 can give us here is that `min` and `max` could become structural parameters, but that would only mean that the _can_ be determined during translation, it doesn't give us any way to express that they _should_ be determined during translation.

If the question is rephrased as how to express that they _should_ be determined during initialization, isn't it close enough to the discussion in this issue to reopen rather than open a new issue?

**Comment by henrikt-ma** [comment]
How about resolving this by making the attributes except `start` of the built-in types have `Evaluate = true`?
