### ISSUE TITLE
Stray underscore at end of Q-IDENT rule

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2377]
The last alternative for the `Q-IDENT` lexer rule looks wrong:
```
… | " "_
```
Was the underscore supposed to be an _open box_ (U+2423 or &amp;blank;) used to represent the space character?
```
… | "␣"
```

**Comment by sjoelund** [comment]
This is the rule in Chapter 2. I didn't see anything like that in the appendix and it seems like a typo.

**Comment by henrikt-ma** [comment]
Right, section 2.3.1 _Identifiers_.

**Comment by HansOlsson** [comment]
> This is the rule in Chapter 2. I didn't see anything like that in the appendix and it seems like a typo.

Agreed, seems like a simple typo that was introduced in Modelica Language 3.2 (together with the correct variant in the appendix).
