### ISSUE TITLE
Operator overloading, replaceable fields and units.

### ISSUE THREAD

**Issue by Daiwen** [modelica/ModelicaSpecification#2379]
Consider the following model:
    
    model AmbiguousOpRedeclare
        type KmReal = Real(final unit = "km");

        operator record R1
          replaceable Real x;

          operator function '*'
            input R1 c1;
            input R1 c2;
            output R1 c = R1(c1.x * c2.x);
          end '*';
        end R1;

      operator record R2 = R1(redeclare KmReal x);
      R1 c1;
      R2 c2;
    equation
      0 = c1 * c2;
    end AmbiguousOpRedeclare;
of which there is a concrete example in
`Modelica.Magnetic.QuasiStatic.FundamentalWave.Components.MultiPhaseElectroMagneticConverter` at line 67 as `j * omega * Phi`.

I think that `R1` and `R2` are different types, this would in fact be obvious if we had redeclared `x` to be of type `String`.

When resolving the overloading of `*`, according to the second item in `Section 14.4`:

>Otherwise, if there exists exactly one function f in the union of A.op and B.op such that f(a,b) is a valid match for the function f , then a op b is evaluated using this function. It is an error, if multiple functions match. If A is not an operator record class, A.op is seen as the empty set, and similarly for B. [Having a union of the operators ensures that if A and B are the same, each function only appears once.]

We find the candidates to be `R2.'*'` and `R1.'*'`.
Since there are two of them, this should be an invalid use of operator overloading.

Additionally, this example also hints at the fact that something needs to be done with regards to units and how it relates to types. Indeed, `R2` is defining `*` as a function that takes records whose fields have `km` as a unit, it multiplies them and still returns a record whose field has `km` as a unit instead of `km^2`.

**Comment by HansOlsson** [comment]
This is already handled since https://specification.modelica.org/master/Ch14.html says:

> If an operator record was derived by a short class definition, the overloaded operators of this 
> operator record are the operators that are defined in its base class

Additionally the usual case of `operator record R2 = R1(x(final unit="km"));` is the allowed by section 4.6 ( https://specification.modelica.org/master/Ch4.html#specialized-classes ) - I don't know if we should view this as allowed as well:

>It is not legal to extend from an operator record (or connector inheriting from operator record), 
> except if the new class is an operator record or connector that is declared as a short class definition, 
> whose modifier is either empty or only modify the default attributes for the component elements 
> directly inside the operator record

I can't remember which ticket introduced this. The idea is that the operations in operator record are "unit-less".

**Comment by Daiwen** [comment]
That answers my questions.
