### ISSUE TITLE
Equation counting for records (similar to #1190 for arrays)

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaSpecification#2388]
I have recently encountered an issue with a customer library, which boils down to the following:

    record Record
        Real a, b;
    end Record;
    
    model Main
        Record r;
    equation
        r.a = 3.14;
    algorithm
        r.b := 2.78;
    end Main;

When we flatten this model and generate a (conceptual) function to implement the algorithm, we see that record instance r is used in the model, and generate an initialization for both r.a and r.b, resulting in the following flattened model with one too many equations:

    model Main
        parameter Real r_a_start(fixed = false);
        Real r_a;
        Real r_b;
    initial equation
        r_a_start = r_a;
    equation
        r_a = 3.14;
        r_a = r_a_start;
        r_b = 2.78;
    end Main;

Is the original model incorrect (as it would be if r were an array of Real, r.a replaced with r[1], and r.b replaced with r[2], as decided in #1190), or is it incorrect for an algorithm to implicitly initialize all fields of a record used on the LHS of an assignment?

**Comment by HansOlsson** [comment]
I would say that it is wrong to initialize all fields of a record used in the LHS of an assignment.

The reason it makes sense to consider the entire array assigned to is that it can be difficult to statically determine which elements are assigned to, and if we try to have a special case when using literals as in `x[1]:=0;` some will use `i:=1;x[i]=0;`.

Record fields don't have a similar issue in Modelica.

**Comment by HansOlsson** [comment]
For arrays #1190 introduced the following for arrays:
"If at least one element of an array appears on the left hand side of the assignment operator, then the complete array is initialized in this algorithm section. "
The decision here was to not add anything similar for records, so there is no need to update the specification.
(Obviously it could be clarified further, but does not seem high priority.)
