### ISSUE TITLE
12.7.1 Using the Derivative Annotation

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaSpecification#2397]
To be honest, the above mentioned section explains a lot, but not really "what has to be provided by the derivative function". After some trial and error I know what has to be specified by the derivative function. Feel free to include the enclosed example to section 12.7.1.
[Saturation.pdf](https://github.com/modelica/ModelicaSpecification/files/3413756/Saturation.pdf)

**Comment by HansOlsson** [comment]
The code from that example should be (using zeroDerivative):
```
function L   
  input Real I0, L0, Linf;   
  input Real i;   
  output Real L; 
algorithm    
  L := (L0 - Linf)*(if abs(i)/I0<Modelica.Constants.small then      1 else atan(i/I0)/(i/I0));   
  annotation(derivative(zeroDerivative=I0,zeroDerivative=L0,zeroDerivative=Linf)=der_L); 
end L;

function der_L 
   input Real I0, L0, Linf;
   input Real i;
   input Real der_i;
   output Real der_L; 
algorithm
   der_L := (L0 - Linf)*(if abs(i)/I0<Modelica.Constants.small then   
     0 else (1/((i/I0)^2 + 1) - atan(i/I0)/(i/I0))/(i/I0))*der_i; 
end der_L;
```
The existing examples contain all kinds of variables, including differentiated inputs and outputs, and thus the only addition compared to the existing examples are the actual algorithms.

If we want to add an actual algorithm I would propose something much simpler.

**Comment by HansOlsson** [comment]
Language group: Do nothing.
