### ISSUE TITLE
Type inference/propagation through connectors

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#240]
**Reported by dietmarw on 19 Nov 2009 12:36 UTC**
There wasn't a ticket on this yet...
## From [milestone:Design63]
**Status:** _none_
**Short Description:**
 Continue the design so that type constraints can be introduce for connector variables, e.g., in order to propagate medium properties via the connection structure.
 Latest document of the design from the 54th minutes: [source:ModelicaDesign/trunk/MeetingMinutesMaterial/min63/Slides-and-Documents/TypeInference-Total.doc TypeInference-Total.doc]
Another solution might be there if function pointers are used

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/240

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 20 Dec 2016 14:01 UTC**
Unhide for GitHub transition.

**Comment by HansOlsson** [comment]
Note: If you have Dymola 2019 FD01 or 3D Experience Platform 2019x; or later versions you can test a possibility for media propagation through connectors in the diagram layer by setting Advanced.MediaPropagation=1;

**Comment by HansOlsson** [comment]
I have added the old document just in case.

[TypeInference-Total.pdf](https://github.com/modelica/ModelicaSpecification/files/4306896/TypeInference-Total.pdf)

Since it has been inactive for several years, and it is possible to implement support without any language changes I'm closing for now.
