### ISSUE TITLE
Size of memory allocated by ModelicaAllocateString

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2402]
In section 12.9.6 _Utility Functions_, it wouldn't hurt to specify the number of bytes that should be allocated by `ModelicaAllocateString(n)`.  As far as I can tell, the size to allocate is `n + 1`.

Even though it is clear at the moment that _ModelicaStrings.c_ makes this assumption, not having it specified makes it unclear what an independent developer should pass to `ModelicaAllocateString` when trying to write future-proof external code.

**Comment by beutlich** [comment]
Duplicate of #2307?

**Comment by henrikt-ma** [comment]
Indeed.  The reason being that the _Issues_ search field by default suggests to only search among issues, not PRs.  Closing as duplicate.

**Comment by henrikt-ma** [comment]
Duplicate of #2307
