### ISSUE TITLE
Is ModelicaAllocateString(0) null-terminated?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2403]
Some functions in _ModelicaStrings.c_ return the result of `ModelicaAllocateString(0)` without storing a null terminator at the end of the string.  Is it the MLS that fails to specify that `ModelicaAllocateString` should always store a terminating null in the first byte of the string (or at the end, or only when the string length is 0), or is it _ModelicaStrings.c_ that shouldn't rely on something that isn't specified?

**Comment by sjoelund** [comment]
Because it is not specified, OpenModelica only sets the last byte to 0. That way the user gets gibberish if they allocate a string of length 10 but never assign to it, and the application does not crash because it was not null-terminated.

**Comment by HansOlsson** [comment]
> Some functions in ModelicaStrings.c return the result of ModelicaAllocateString(0) without storing a null terminator at the end of the string.  

I agree that it is bug, that should be corrected. 

It would be possible to change ModelicaAllocateString so that it initializes the returned buffer, but to me it seems better to be able to detect and correct these issues. 

Another possibility, also relevant for this case, would be to have a function allocating a specific string (instead of requiring ModelicaAllocateString+strcpy).
However, especially for this case there seems to be a simpler solution, I commented in #3092

**Comment by beutlich** [comment]
> Another possibility, also relevant for this case, would be to have a function allocating a specific string (instead of requiring ModelicaAllocateString+strcpy).

Something like ModelicaDuplicateString as equivalent of strdup.

**Comment by henrikt-ma** [comment]
### Polls at 100th design meeting

Size of allocated memory for `ModelicaAllocateString(len)`:
- `len` bytes: 0
- `len` + 1 bytes: 8
- Abstain: 0

Introduce `ModelicaDuplicateString(const char* str)` along with `ModelicaDuplicateStringWithErrorReturn`:
- Yes: 5
- No: 0
- Abstain: 3

Null-termination:
- First byte: 0
- Last byte: 6
- All bytes: 7
- First and last: 0
- Undefined: 2

Memory allocated with `MemoryAllocateString(0)` is writable:
- Yes (in agreement with return type being `char*` and not `const char*`): 6
- No (returning string constant `""` would be fine): 0
- Abstain: 3

**Comment by henrikt-ma** [comment]
Plan to revisit poll on null-termination later today to try to find a more clear outcome.

**Comment by HansOlsson** [comment]
Revisiting null-termination:
* First byte: 0
* Last byte: 4
* First and last byte: 0
* All bytes: 3
* Undefined: 2 
No-one objecting to "last byte", so go with that.
