### ISSUE TITLE
Single-quoted identifier representation in filenames, package.order, and simulation results

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2408]
First, as a follow-up to #1176, what is the correct filename for the following model names?
1. `'\b'`
1. `'\t'`
1. `'\"'`
1. `'"'`

Second, how should the files be listed in _package.order_?  Is it the Modelica `IDENT` syntax with ambiguous representation of `"` and `?`, a plain text listing of filenames, or some other sort of text format with support for escape characters?

Third, even it this may first of all be a matter for the distribution of MSL reference results, if the identifiers were names of variables, what would the names look like in a CSV file?  In a .mat file?

**Comment by henrikt-ma** [comment]
By the way, which of the `Q-IDENT` rules is the correct one, the one that requires anything except `"` as the first character inside the quotes, or the one that allows the quoted part to be empty?  That is, section 2.3.1 _Identifiers_, or B.1 _Lexical conventions_?

**Comment by HansOlsson** [comment]
> First, as a follow-up to #1176, what is the correct filename for the following model names?

As discussed in #886 there might not be a correct filename for all of them, and even the simpler 'a/b' will fail. If possible you have to store those classes in the enclosing package.mo

> Second, how should the files be listed in package.order?  

The package.order is described as a list of classes (and constants), not files; so I would expect it to just be the IDENT followed by line-break.

> Is it the Modelica IDENT syntax with ambiguous representation of " and ?, a plain text listing of filenames, or some other sort of text format with support for escape characters?

Regarding the ambiguity do you mean that the one variant is used in package.order, and the class be stored in package.mo (or in a separate file) with a different variant? I don't believe that is specified, and it should be. I don't care so much whether it is forbidden or allowed.

> Third, even it this may first of all be a matter for the distribution of MSL reference results, if the identifiers were names of variables, what would the names look like in a CSV file?  In a .mat file?

That is a different tricky issue. 

I know that Dymola uses double-quotes when necessary for these variable names, in order to be compatible with other programs reading/writing CSV-files. (These double quotes are also automatically removed.)

Mat-files can just use the name as is.

**Comment by henrikt-ma** [comment]
> As discussed in #886 there might not be a correct filename for all of them, and even the simpler 'a/b' will fail. If possible you have to store those classes in the enclosing package.mo

While you are right that `'a/b'` is a very troublesome name, I was mostly wondering about the problems related to `S-ESCAPE` and the ambiguous representation of `"` and `?` this time.

For example, in the SystemModeler interface, we never expand the `S-ESCAPE` parts of an identifier, so the user will see the identifier as declared.  Except for the ambiguous representations of `"` and `?`, this works well for us.  While the choice of how to present identifiers in tool interface seems like a design choice for each tool to make, I still see the need for agreement when it comes to the parts where there is exchange with other tools, such as filenames and names in result files.

I agree with @svorkoetter's [suggestion](https://github.com/modelica/ModelicaSpecification/issues/886#issuecomment-435629990) to specify an encoding that will solve most of these issues on case sensitive file systems.

> > Second, how should the files be listed in package.order?
> 
> The package.order is described as a list of classes (and constants), not files; so I would expect it to just be the IDENT followed by line-break.
> 
> > Is it the Modelica IDENT syntax with ambiguous representation of " and ?, a plain text listing of filenames, or some other sort of text format with support for escape characters?
> 
> Regarding the ambiguity do you mean that the one variant is used in package.order, and the class be stored in package.mo (or in a separate file) with a different variant? I don't believe that is specified, and it should be. I don't care so much whether it is forbidden or allowed.

OK, then I suggest that we be clear and say that _package.order_ contains Modelica identifiers (`IDENT`) instead of just saying _names_, perhaps like this:

"where each line contains the name of one class or constant (using its Modelica `IDENT` form)"
 
> I know that Dymola uses double-quotes when necessary for these variable names, in order to be compatible with other programs reading/writing CSV-files. (These double quotes are also automatically removed.)

Right, there is another level of up-quoting that may be needed in CSV-files, I didn't even think of that.  I was thinking of the result variable name before the CSV level of up-quoting, similar to the .mat file case below.

> Mat-files can just use the name as is.

The question is how to interpret `'x\t'`; to which of these Modelica `IDENT` identifiers does it correspond?
- `'x\\t'` (name in .mat file is down-quoted)
- `'x\t'` (name in .mat file is not down-quoted; down-quoting this would have resulted in a tab instead of '\t')

**Comment by HansOlsson** [comment]
Trying to summarize: 
1. It may not always be possible to store classes on separate files (due to limitations of file-systems). For non file-based storage it is different.

2. A proposal is to improve package.order to say:

> In order to preserve the order of sub-entities it is advisable to create a file package.order  where each line contains the name of one class or constant _(using its Modelica IDENT form)_.

3. For Mat-files I don't believe we have standardized them, but would propose a name without down-quoting, e.g., `'x\t' `for `'x\t'`. In C-code normal C-quoting will apply, i.e., `"'x\\t'"`.

**Comment by henrikt-ma** [comment]
> For Mat-files I don't believe we have standardized them, but would propose a name without down-quoting, e.g., `'x\t' `for `'x\t'`. In C-code normal C-quoting will apply, i.e., `"'x\\t'"`.

I just want to point out that down-quoting would solve the problem with ambiguous representation of `"` and `?` in a clean way for .mat files.

Alternatively, if we really want to keep the ambiguous representations, we could limit the damage by making all but one of the alternative forms allowed only for a Modelica `IDENT` as part of Modelica source code.  It could be stated like this:
> When `IDENT` is used outside the context of Modelica source code, the escaped forms of `"` and `?` (that is, `\"` and `\?`) are not allowed.  For example, a variable declared with name `'foo\?'` in the Modelica code shall be stored with name `'foo?'` in a result file.
