### ISSUE TITLE
Extending functions with algorithms

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2415]
Is it allowed to extend a function with an algorithm and specify an algorithm in the extension? For example:
```
function f
  input Real u;
  output Real y;
algorithm
  y := u+1;
end f;

function g
  extends f;
  output Real z;
algorithm
  z := u + 3;
end g;
```
I couldn't find anything in the specification that explicitly forbids it. If it is allowed how the two algorithms should be combined?

In Section 7.1 (Specification 3.4), it says:
>The elements of the flattened base class become elements of the flattened enclosing class, and are added at the place of the extends-clause: specifically components and classes, the equation sections, algorithm sections, optional external clause, and the contents of the annotation at the end of the class, but excluding import-clauses.

According to that, it seems like the definition of ```g``` would be:
```
function g
  input Real u;
  output Real y;
algorithm
  y := u+1;
public
  output Real z;
algorithm
  z := u + 3;
end g;
```
The result then is that the function has two algorithm sections. According to section 12.2:
> A function can have at most one algorithm section or one external function interface (not both), which, if present, is the body of the function.

Does it mean that it is illegal to extend from a function with an algorithm section and add another algorithm?

**Comment by HansOlsson** [comment]
> Does it mean that it is illegal to extend from a function with an algorithm section and add another algorithm?

Yes, that would be the intent - the algorithm section is inherited as for any other class (as you indicate above) and therefore there are two algoritm sections, which is one too many.
I don't know if that sentence should be reformulated to make it clearer.

**Comment by svorkoetter** [comment]
What if either the base function OR the derived function doesn''t already have an algorithm section?

**Comment by henrikt-ma** [comment]
Language group at 100th design meeting:

Agreement that not allowed.  Revisit when/if actual use case is found.

Needs further clarification (to go into 12.2 _Function as a Specialized Class_, item about having at most one `algorithm` section):
- Yes: 
- No: 
- Abstain:

**Comment by henrikt-ma** [comment]
Can a this function without `algorithm` section be extended?
```
function f
  input Real x;
  output Real y = x;
end f;
```

**Comment by eshmoylova** [comment]
> Can a this function without `algorithm` section be extended with an `algorithm`?
> 
> ```
> function f
>   input Real x;
>   output Real y = x;
> end f;
> ```
> 
> Like so:
> 
> ```
> function g
>   extends f;
> algorithm
>   y := y + 1;
> end g;
> ```

There are many examples of functions like that in the MSL and there is one example (with "redeclare function extends" mechanism) in section 7.3.1 in the Specification.

**Comment by HansOlsson** [comment]
> There are many examples of functions like that in the MSL and there is one example (with "redeclare function extends" mechanism) in section 7.3.1 in the Specification.

But in those cases the base-class (always?) lacks "y=x", and thus the algorithm is necessary.

**Comment by eshmoylova** [comment]
> > There are many examples of functions like that in the MSL and there is one example (with "redeclare function extends" mechanism) in section 7.3.1 in the Specification.
> 
> But in those cases the base-class (always?) lacks "y=x", and thus the algorithm is necessary.

Sorry. I missed that part.

**Comment by beutlich** [comment]
Would be good to have it also available in the [Modelica compliance test suite](https://github.com/modelica/Modelica-Compliance).

**Comment by HansOlsson** [comment]
Seems to work at the design meetings.
