### ISSUE TITLE
Introduce ModelicaDuplicateString

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2417]
In #2403, it was found that we want a `ModelicaDuplicateString` (and `ModelicaDuplicateStringWithErrorReturn` in addition to `ModelicaAllocateString` and its friend.

Suggested formulation:
- `char* ModelicaDuplicateString(const char* str)`
- `char* ModelicaDuplicateStringWithErrorReturn(const char* str)`
> Returns a duplicate of the null-terminated string `str`.  The duplicate shall be used as return argument of an external Modelica function.  In case of error, `ModelicaDuplicateString` calls `ModelicaError`, whereas `ModelicaDuplicateStringWithErrorReturn` returns 0.

Section 12.9.1.1 _Simple Types_ also needs to be updated to not assume that `ModelicaAllocateString` is the only function that may have been used to allocate `String` memory.

It would make sense to use the same style for the definitions of `ModelicaDuplicateString` (`ModelicaDuplicateStringWithErrorReturn`) and `ModelicaAllocateString` (`ModelicaAllocateStringWithErrorReturn`).  In particular, if the new functions are defined as suggested above, the old functions should also be merged into one defining paragraph.  On the other hand, non-normative talk about cleaning up resources shouldn't go into both definitions.

**Comment by HansOlsson** [comment]
Agreement by acclamation.
