### ISSUE TITLE
Confusing statement about type of x in der(x)

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2423]
In 3.7.2 _Derivative and Special Purpose Operators with Function Syntax_, it is said regarding `der(expr)` that:
> If the expression `expr` is a scalar it needs to be a subtype of Real.

However, 10.6 _Scalar, Vector, Matrix, and Array Operator Functions_ also says:
> In all contexts that require an expression which is a subtype of Real, an expression which is a subtype of Integer can also be used; the Integer expression is automatically converted to Real.

It was my understanding that this wasn't restricted to just the operator functions in 10.6, but a general rule of Modelica.  I was therefore surprised when @Daiwen told me about a the ModelicaCompliance test `ModelicaCompliance.Operators.Special.DerConstantIncorrect1` which is expected to fail because it takes the derivative of an Integer.

To me it would seem reasonable to also apply the formulation from 10.6 in the context of 3.7.2, meaning that `der(2)` would be OK.  This also makes perfect sense from a mathematical point of view given that we allow this:
```
  Real x;
  Real y = der(2 * x);
```
It would be natural to allow application of the product rule without becoming invalid Modelica:
```
  Real y = der(2) * x + 2 * der(x);
```

In view of the above, I suggest this definition of `der` in 3.7.2:
> The time derivative of `expr`. The expression `expr` and all its subexpressions must be differentiable.  For a scalar `expr`, the result is the Integer 0 when `expr` is a subtype of Integer, otherwise the scalar `expr` needs to be a subtype of Real and the result is a subtype of Real derived from the type of `expr`.  If `expr` is an array…

When we are at it, do we really mean that this model is invalid?
```
model DerOfNonDifferentiable
  Real x = abs(time);
  Real y = der(x);
end DerOfNonDifferentiable;
```

**Comment by HansOlsson** [comment]
We first need to differentiate [sic!] between integer literals (actually integer expressions with parameter variability) that has 0 derivative and integer variables that cannot be differentiated, such as "Integer J=integer(time);"

Additionally I don't consider the case `der(2)` useful, but I agree that `der(2*x)` as good in some cases.

Thus one possibility would be to require that the argument to der must be a real, but allow integer sub-expressions with at most parameter-variability. (I believe that is the rule we use in Dymola.)

And I agree that DerOfNonDifferentiable should likely be legal, even though x has a discontinuity.

**Comment by henrikt-ma** [comment]
The thing with `DerOfNonDifferentiable ` is that that if we make it legal (which I think we should), then I don't see what the problem is with `DerOfInteger`:
```
model DerOfInteger
  Integer x = integer(time);
  Real y = der(x);
end DerOfInteger;
```

Compare with (regarding the workaround with `y`, see 4.4.4 _Component Variability Prefixes discrete, parameter, constant_):
```
model DerOfDiscreteReal
  discrete Real x(start = 0.0, fixed = true);
  Real y = x; /* Workaround for der(x) not being allowed. */
  Real z = der(y);
equation
  when sample(0.0, 1.0) then
    x = pre(x) + 1.0;
  end when;
end DerOfDiscreteReal;
```

Then, of course, if we would allow `DerOfInteger`, then `DerOfDiscreteReal` should also work even without the workaround with `y`.

**Comment by HansOlsson** [comment]
I don't think we should allow these as they break the assumption of integration, i.e.  that we can construct x from the initial value and der(x). The work-around for der(x)  not being allowed doesn't really fix the problem above - it only shifts it from a simple check (der(x) for a discrete real) to an issue detected during index reduction (need der(x) for a discrete real).

The assumption is that if we have:
```
  Real x,y;
initial equation
  x=y;
equation
 der(x)=der(y);
```
then x and y will be numerically almost the same (regardless of the equations for x and y).

**Comment by henrikt-ma** [comment]
SystemModeler sees no reason to complain about `DerOfDiscreteReal`, and is happy to translate it.  Is that illegal?

**Comment by HansOlsson** [comment]
> SystemModeler sees no reason to complain about DerOfDiscreteReal, and is happy to translate it.  Is that illegal?

To me it is clear that it should be illegal due to breaking the integration assumption; so the question is whether the specification says this in 4.4.4 "Component Variability Preﬁxes discrete, parameter, constant

- A discrete-time variable vd has a vanishing time derivative (informally der(vd)=0, **but it is not legal to apply the der() operator to discrete-time variables)** and can change its values only at event instants during transient analysis (see section 8.5). 
- A continuous-time variable vn may have a non-vanishing time derivative (der(vn)<>0 possible) and may also change its value discontinuously at any time during transient analysis (see section 8.5). **If there are any discontinuities the variable is not diﬀerentiable.**

So, assuming that differentiable has its usual meaning I believe it is specified. (Section 8.6 mentions that index reduction may require a tool to differentiate equations, but only in non-normative text.)

However,
- We could likely make that clearer.
- Instead of just saying that der(vd) is illegal, we could say that it is illegal since it has discontinuities and therefore is not differentiable.

**Comment by henrikt-ma** [comment]
But clearly, `x` isn't differentiable here either:
```
model IntegratorWithReset
  Real x(start = 0.0, fixed = true);
equation
  der(x) = 1.0; /* Illegal, since x is not differentiable? */
  when sample(0.0, 1.0) then
    reinit(x, 0.0);
  end when;
end IntegratorWithReset;
```

I guess there is an exception somewhere that makes this legal nevertheless…  Wouldn't it be better to relax things to avoid the need for such an exception?

**Comment by HansOlsson** [comment]
True, reinit is an exception to this and it should likely be formulated in a better way. It has always been sort of a hack to deal with impulses - with known issues, but we haven't found anything better yet. 

However, relaxing the general rule about only time-differentiating continuous variables would be really problematic, as it breaks the integration-assumption. For reinit we (mostly?) avoid the issues by requiring that it is applied to a state.

(Just to be clear: even if we have standardized anything better, we do have prototypes in Dymola that replace reinit by impulses, which can handle the case that it is applied to a non-state and propagated through the system. That generalizes "differentiable" to "differentiable in the distribution sense".)

**Comment by henrikt-ma** [comment]
What about only requiring differentiability between events?

**Comment by HansOlsson** [comment]
> What about only requiring differentiability between events?

Well, it is better than allowing non-differentiability everywhere. However, it will still messes with index reduction and integration assumptions. It might work if we handle the events-discontinuities using distribution theory, but I haven't fully investigated it. To me that seems like a fairly impacting change, and should be combined with even larger changes to make it a useful extension.

**Comment by henrikt-ma** [comment]
With the requirement that `der(x)` requires `x` to be differentiable between events, I don't see how this would be a problem for the integration assumptions.

To support the case that only requiring this would have substantial implications on the DAE index, and not being just a quality of implementation concern, I think an example is needed.

If we can't come up with such examples, and this is just about quality of implementation, I think the gain in mathematical consistency and better match with general expectations on a derivation operator are two very good reasons for change.

**Comment by HansOlsson** [comment]
> With the requirement that der(x) requires x to be differentiable between events, I don't see how this would be a problem for the integration assumptions.

But the actual requirement is that der(x) requires x to be differentiable (one time).

Reducing that to "between events" would be a major breaking change, that would invalidate the index-reduction. Additionally der(x) should be continuous "between events", (ideally several times continuously differentiable) to match the requirements of the solvers.

**Comment by HansOlsson** [comment]
To give a concrete example of the problem (and hopefully close this discussion).
Consider the following model (the variable is not "discrete" - but it has the same kind of discontinuity):

```
model Unnamed
  Modelica.Electrical.Analog.Basic.Capacitor capacitor(C=1)
    annotation (Placement(transformation(extent={{-30,8},{-10,28}})));
  Modelica.Electrical.Analog.Basic.Resistor resistor(R=1)
    annotation (Placement(transformation(extent={{10,8},{30,28}})));
  Modelica.Electrical.Analog.Basic.Ground ground
    annotation (Placement(transformation(extent={{-34,-32},{-14,-12}})));
  Modelica.Electrical.Analog.Sources.SignalCurrent signalCurrent
    annotation (Placement(transformation(extent={{-58,6},{-38,26}})));
  Modelica.Blocks.Sources.Ramp ramp(
    height=1,
    duration=0,
    startTime=0.5)
    annotation (Placement(transformation(extent={{-90,62},{-70,82}})));
  Modelica.Blocks.Continuous.Der der1
    annotation (Placement(transformation(extent={{-58,62},{-38,82}})));
equation 
  connect(capacitor.n, resistor.p)
    annotation (Line(points={{-10,18},{10,18}}, color={0,0,255}));
  connect(ground.p, resistor.n)
    annotation (Line(points={{-24,-12},{30,-12},{30,18}}, color={0,0,255}));
  connect(capacitor.p, signalCurrent.n) annotation (Line(points={{-30,18},{-34,18},
          {-34,16},{-38,16}}, color={0,0,255}));
  connect(signalCurrent.p, ground.p) annotation (Line(points={{-58,16},{-80,16},
          {-80,-10},{-24,-10},{-24,-12}}, color={0,0,255}));
  connect(ramp.y, der1.u)
    annotation (Line(points={{-69,72},{-60,72}}, color={0,0,127}));
  connect(signalCurrent.i, der1.y) annotation (Line(points={{-48,28},{-42,28},{-42,
          72},{-37,72}}, color={0,0,127}));
  annotation (uses(Modelica(version="3.2.3")));
end Unnamed;
```
In this context the "ramp" could be replaced by integer(x) or a discrete variable.
If you just differentiate the discontinuity and simulate ignoring errors the capacitor stays at 0V. 
If you use a very short ramp.duration you get 1V; so this assumption matters.

Apart from forbidding differentation of discrete variables, what are the options:

- Generate incorrect results. Not good.
- Don't generate an error for differentiating, but only in combination with integration. It will be a lot harder to generate good diagnostics, and the main benefit seems to be that we can handle toy examples.
- Handle it correctly using impulses/distributions. More work needed.

A side-note that isn't relevant for discrete-time expressions:
Note that for the example above Dymola (as default) generates the error durng the simulation - not during translation. 

The reason is that it is in general too difficult to statically determine that there will be a discontinuity (as it depends on the values at the switch); the if-statement if only a potential discontinuity.

However, that isn't a problem for "integer(x)" or a variable given by a when-statement (unless it never changes).

**Comment by henrikt-ma** [comment]
Thanks for providing an example for the sake of the discussion!

To me, trying to handle a ramp with zero duration as the limit when the duration tends to zero appears as an esoteric problem compared to not being allowed to take the derivative of a variable that is smooth between events.

**Comment by HansOlsson** [comment]
> Thanks for providing an example for the sake of the discussion!
> To me, trying to handle a ramp with zero duration as the limit when the duration tends to zero appears as an esoteric problem compared to not being allowed to take the derivative of a variable that is smooth between events.

You are focusing on the wrong thing:

I started with a step-source, which is not esoteric at all; and in general the problem applies to any differentiated discontinuous function as indicated above. Thus the three options above are still the only alternatives to the current semantics.

I only changed it to a ramp to simplify comparison between the limit as duration goes to zero and the result for zero duration (when ignoring all diagnostics).

**Comment by henrikt-ma** [comment]
OK, I think I see the difference now.  You want the integration assumption to hold across events, which is messy when variables have discontinuities due to `reinit` etc.  I'm satisfied with an integration assumption that is only concerned with what happens between events, and then a lot of problems disappear.  :)

**Comment by HansOlsson** [comment]
I would say I want correct integration results - and we get that as long as reinit and similar hacks aren't used. If reinit is used more analysis is needed, but I believe there are only about two models where reinit is used in a potentially problematic way in MSL. (The uses in Integrator and Mean are internal to the components and unproblematic.)

I would be happier if we could focus on finding a better solution for them.

**Comment by henrikt-ma** [comment]
I can see that you are fighting for a good cause here.  I'm not too found of `reinit` either.

Perhaps we could do both:
1. Relax requirements on differentiated expressions so that one can write `der(x)` without having to worry about whether it is legal or not depending on how `x` behaves at events.
1. Find a better replacement for `reinit`.

To me, it just seems that there must be so many good uses of hybrid modeling where the derivative is taken of something which isn't differentiable in the classical sense at events, and that we shouldn't delay taking this first small step to address that now, instead of waiting for a major redesign based on distribution theory.  It would be interesting to know the number of models in the MSL that break the differentiability rule.

Speaking of testing it, which of the following two variables are you allowed to differentiate?  Are the to variables identical or not?
```
model Subtle
  Real x(start = 5.0, fixed = true);
  Real y = abs(time - 5.0);
equation
  der(x) = if time < 5.0 then -1.0 else 1.0;
end Subtle;
```

**Comment by HansOlsson** [comment]
> To me, it just seems that there must be so many good uses of hybrid modeling where the derivative is taken of something which isn't differentiable in the classical sense at events, and that we shouldn't delay taking this first small step to address that now, instead of waiting for a major redesign based on distribution theory.  It would be interesting to know the number of models in the MSL that break the differentiability rule.

As far as I can tell **zero** models in MSL break the continuity rule for differentiation, since Dymola does check it during simulations (unless someone uses clever tricks to circumvent this).

Thus I don't see the good uses of hybrid modeling that break this. (And treating events specially is also problematic as we want to reduce the impact of events for efficient simulations.)

> Speaking of testing it, which of the following two variables are you allowed to differentiate?  Are the to variables identical or not?

You can differentiate both x and y, since they are continuous - but not continuously differentiable. The problems occur when differentiating variables that are discontinuous.

**Comment by henrikt-ma** [comment]
> You can differentiate both x and y, since they are continuous - but not continuously differentiable. The problems occur when differentiating variables that are discontinuous.

I was asking in view of 3.7.2 that says:
> The expression and all its subexpressions must be differentiable.

Which definition of _differentiable_ are we using that makes `abs(time - 5.0)` differentiable at 5.0?
