### ISSUE TITLE
annotation-comment is not a good name for the grammar rule

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaSpecification#2435]
Due to formatting issues (to avoid confusing a keyword with a grammar rule name), the `annotation` rule was changed to `annotation-comment`. The problem with this is that an annotation is nowhere referred to as any sort of "comment" in the specification, and an annotation really isn't a comment.

**Comment by HansOlsson** [comment]
We might also coordinate with #2371

**Comment by svorkoetter** [comment]
Unfortunately, the best I can come up with is "annotation", but some alternatives include:

- "annotation-modification" since annotations are syntactically identical to modifications, and one can think of the annotation itself as being a modification of the annotation keyword
- "annotation-expression"
- "annotation-clause"

Also, again in conjunction with #2371, we should change the name of the "comment" rule, since neither part of it would be considered a comment any more. Probably "description" would be a better name.

**Comment by HansOlsson** [comment]
Can we have an online poll for this in the next two weeks (ending 2019-12-19):

The alternatives are:
- "annotation-modification": Heart
- "annotation-expression": Rocket
- "annotation-clause": Eyes

The simple way to make a poll among different alternatives on GitHub seems to be go to the right-corner of this post and select one (or more) of the reactions as follows:

![Reactions](https://user-images.githubusercontent.com/13217430/70221051-dd3b7680-1747-11ea-8ca9-bcf91f1acff3.png)

(Will send out separate reminder etc.)

**Comment by HansOlsson** [comment]
Results are in:
annotation-modification: 2
annotation-expression: 1
annotation-clause: 4
Clear that annotation-clause is the winner.
