### ISSUE TITLE
Example in 3.3.1 is not helpful

### ISSUE THREAD

**Issue by svorkoetter** [modelica/ModelicaSpecification#2442]
The non-normative text of 3.3.1 is trying to make the point that one cannot rely on short-circuiting of Boolean operators. The following example is given:
```
  Boolean v[n]; 
  Boolean b; 
  Integer I; 
equation 
  x=v[I] and (I>=1 and I<=n); // Invalid 
  x=if (I>=1 and I<=n) then v[I] else false; // Correct 
```
The problem with the "invalid" example is that it's invalid in any language, even those that guarantee short-circuiting of Boolean expressions, since it doesn't test for `I` being in range until after already using it to index `v`, so it doesn't actually make the point. That line should be rewritten as,
```
    x = (I>=1 and I<=n) and v[I]; // Invalid
```
since a user might expect that this is safe (but it isn't).

Also, `x` was probably meant to be `b` in both equations.

**Comment by beutlich** [comment]
Parentheses aren't necessary in both lines, i.e.

```mo
  b = I>=1 and I<=n and v[I]; // Invalid
  b = if I>=1 and I<=n then v[I] else false; // Correct 
```

Maybe, `n` should be declared, too.

**Comment by svorkoetter** [comment]
It's true that parentheses aren't necessary, but they make it somewhat more clear that the first two conditions together are intended (but fail) to protect the last one. I have no issues with leaving them in, or leaving them out.
