### ISSUE TITLE
Function definition within record?

### ISSUE THREAD

**Issue by AHaumer** [modelica/ModelicaSpecification#2458]
Dear Language desingers, 
please tell whether it is legal Modelica to place a function definition within a (parameter) record?
E.g. the data that has to be interpolated together with the interpolation function. 
Thanks in advance, Toni

**Comment by HansOlsson** [comment]
A function definition can be placed within a record, but passing the record to a function does not pass "the value" of the function definition.

The only way to pass "functions" around is function partial evaluation as argument to functions https://specification.modelica.org/v3.4/Ch12.html#function-partial-application

It may be that you don't need the record as a separate entity - but only a functional partial evaluation (with the record as bound argument).

I believe that answers the questions.
