### ISSUE TITLE
New function like class

### ISSUE THREAD

**Issue by GarronFish** [modelica/ModelicaSpecification#2460]
A new class similar to the function class however it would contain an equation section instead of an algorithm section would be useful in some cases.  Using this class would be similar to using a model class however an instance of the class would not be required to be generated by the user before using the class.

example (I have called the new class sub):
```mo
sub circleEquationExample
  Real x;
  Real y;
  parameter Real r=1;
  Real x_der;
equation 
  r * r=x * x+y * y;
  x_der = der(x);
end circleEquationExample;

model useOfSubCircle
  Real xIn=sin(time);
  Real yOut;
equation 
  circleEquationExample(
    x=xIn,
    y=yOut,
    r=10);
end useOfSubCircle;
```
This would overcome a number of limitations with functions without having to resort to using Model classes instead.

This would allow improved symbolic manipulation and give the user the advantages of acausality and the ability to use implicit equations, while keeping the ease of use of functions.

This is an idea a colleague come up with while having to rewrite functions into Model classes to get around some the limitations of functions.

**Comment by HansOlsson** [comment]
This seems like a variant of MCP0012: calling a block as a function #1512; and could thus be closed as duplicated. The remaining work was related to handling this inside if-expressions.

**Comment by HansOlsson** [comment]
Consider together with MCP0012 in #1512
