### ISSUE TITLE
Default value "Parameters" for Dialog.group becomes misleading with non-parameters

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2476]
The pseudo-code definition for the `Dialog` annotation states that the default for `group` is `"Parameters"`.  Obviously, this only makes sense for parameters.  It would be better to leave the default empty, and allow tools to figure out a suitable dialog group depending on the kind of component.

**Comment by beutlich** [comment]
We had similar trouble in #2043. Its resolution was, that tool-specific worakrounds are possible.

**Comment by henrikt-ma** [comment]
For {{Dialog.tab}}, the default value {{"General"}} is less of a problem, as it seems like a default that could work regardless of the kind of component.

By the way, the code block with {{annotation(Dialog(…));}}­  preceding the paragraph starting with _The annotations **tab** and **group**…_ looks out of place where appears right after the {{unassignedMessage}} example.  It would probably be better to start the specification of {{Dialog}} with a paragraph with some text, and then come directly to the pseudo-code record definition.  The code block after the {{unassignedMessage}} could probably be dropped entirely, as there already exist examples of {{Dialog}} following its formative specification.

**Comment by henrikt-ma** [comment]
The only workaround I can see is to hard code the `Dialog.group` for every component, but that has several clear disadvantages:
1. The code is bloated with `Dialog` annotations everywhere, populated with an automatically generated `group` based on component variability, being `final`, etc.
2. When later changing the things that were used to automatically determine the `group`, it's no longer clear if `"Parameters"` was a manual decision or just an automatic choice that should be automatically updated.
3. When the library that's bloated with SystemModeler's automatically generated `group` names is used in a different tool, the `group` names are unlikely to match the defaults of the other tool.

(To suggest that tools should simply ignore the specification and provide a more intelligent default for `group` does not look like a resolution to this issue at all.)

**Comment by HansOlsson** [comment]
I agree that the best solution seems to be to remove that default from the specification.

**Comment by HansOlsson** [comment]
Proposal: Have as empty string in record, and specify that empty string means tool-specific tab and group.
Favor: 6
Against: 0
Abstain: 3

**Comment by henrikt-ma** [comment]
The fix that was once merged appears to have been lost since.

**Comment by beutlich** [comment]
> 
> 
> The fix that was once merged appears to have been lost since.

Changed the milestone.

**Comment by beutlich** [comment]
> 
> 
> The fix that was once merged appears to have been lost since.

What exactly do you miss? I actually cannot confirm.

**Comment by beutlich** [comment]
Actually I am rather confused. b119f40fa82a04d548962f1a732a93086abcfb3f (for #2618) added the comment "A component declaration or a short replaceable class definition may have the following annotation". Thus, the stated Dialog annotation can only be considered as an example and it no longer can be deduced that "Parameters" was the default group name and "General" is the default tab name.

**Comment by henrikt-ma** [comment]
> Actually I am rather confused.

Me to.  Sorry about the confusion.  Closing.

> [b119f40](https://github.com/modelica/ModelicaSpecification/commit/b119f40fa82a04d548962f1a732a93086abcfb3f) (for #2618) added the comment "A component declaration or a short replaceable class definition may have the following annotation". Thus, the stated Dialog annotation can only be considered as an example and it no longer can be deduced that "Parameters" was the default group name and "General" is the default tab name.

That was not the intended meaning of the added sentence  (and not what I think was understood by the phone meeting when accepted) – the intention was just to extend its use to more than just component declarations.

On the other hand, while most of the binding equations could be interpreted as defaults, there is at least one obvious exception for `groupImage`…

**Comment by beutlich** [comment]
> On the other hand, while most of the binding equations could be interpreted as defaults, there is at least one obvious exception for `groupImage`…

Yes, that is exactly my concern and does not look consistent.

**Comment by beutlich** [comment]
Maybe "A component declaration or a short replaceable class definition may have the following annotation" should be reformulated as "A component declaration or a short replaceable class definition may have a Dialog annotation".

**Comment by HansOlsson** [comment]
Good that this was resolved and that it had in fact been added (obviously we can still improve the texts further as indicated).

The reason is that:

- The current process for a release means that a new vote will take weeks - we cannot just modify a few lines and continue with the current release; and I don't think this issue alone should delay the rest of the specification.
- We already have a maint/3.5 branch so we can include any important post-release corrections in that.

**Comment by henrikt-ma** [comment]
> * The current process for a release means that a new vote will take weeks - we cannot just modify a few lines and continue with the current release; and I don't think this issue alone should delay the rest of the specification.

Right, it would be totally out of the question to fix such a thing if it would restart the voting procedure.  It was my other mistake (in addition to the two different checks I made to verify that the fix was actually missing) to somehow think that there was a loop hole for applying trivial hotfixes.

**Comment by henrikt-ma** [comment]
This is hilarious.  Find `Dialog` in the document index, and it takes you here:
https://specification.modelica.org/maint/3.5/annotations.html#S7.p40

We failed to implement the fix where it really matters, leaving the actual default as `"Parameters"`.  I am setting up a new PR to both fix the default and to reorganize the presentation to fix all of this confusion once and for all.

**Comment by beutlich** [comment]
That PR shoudl also go to 3.5, right?

**Comment by henrikt-ma** [comment]
> That PR should also go to 3.5, right?

Yes.  Is the normal procedure in such a case to open two PRs from start?  Isn't there a risk of spreading out discussion over the two simultaneously open PRs?  In the past, I've simply counted on Hans taking care of bringing the relevant changes over to 3.5. :)

**Comment by henrikt-ma** [comment]
> > That PR should also go to 3.5, right?
> 
> Yes. Is the normal procedure in such a case to open two PRs from start? Isn't there a risk of spreading out discussion over the two simultaneously open PRs? In the past, I've simply counted on Hans taking care of bringing the relevant changes over to 3.5. :)

Actually, on second thoughts, I think #2819 is too ambitious to suite the 3.5 maintenance branch.  For the maintenance branch, we should probably just replace `"Parameters"` by the empty string – just like the original fix for did issue did, but this time in the right place.  To this end, I made #2822.

**Comment by beutlich** [comment]
This issue is still open while targeting the closed milestone 3.5. I propose to first get it resolved before the MA approval of MLS 3.5.
