### ISSUE TITLE
Decide on how to use \textbf and \texttt in the specification sources

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2503]
In the LaTeX sources, some chapters make a lot of use of `\textbf` for what appears to be the job of `\lstinline`.  We need to agree on rules for when to use `\textbf`.

A related topic is that the use of colors in the syntax highlighting of `\lstinline` is quite disturbing when reading the PDF, so it could be that we need to use something more subtle if switching from `\textbf` to `\lstinline` shouldn't cause too much regression in terms of looks.

This issue is a follow-up to #2364.

**Comment by HansOlsson** [comment]
I agree that colored syntax highlighting - especially for inline code - can be distracting; so we might rethink that. As I recall some green color was changed for this reason.

And I also agree that we should use `\lstinline`, not `\textbf` for Modelica code.

**Comment by henrikt-ma** [comment]
There are also 33 occurrences of `\texttt` that I suggest we get rid of in favor of `\lstinline`.

**Comment by HansOlsson** [comment]
> There are also 33 occurrences of `\texttt` that I suggest we get rid of in favor of `\lstinline`.

Almost all of them and about 10% of the textbf cases are a bit more complicated.
Basically they use \textsubscript (due to indices) - and it would be nice to keep that.
It's possible to handle it for lstlisting, but I haven't tested it for the inline variant.

Proposals for changing color are kindly requested.

**Comment by henrikt-ma** [comment]
We now have experience of using `\lstinline` with `mathescape=true`, and it has been used successfully in other chapters to include subscripted symbolic variables inside of inline code.

**Comment by henrikt-ma** [comment]
Let's keep this issue for the actual decision on how to use `\textbf`.  I opened a separate #2562 for the overall cleanup of the chapter _Synchronous Language Elements_, which we can start fixing once the current issue has been settled.

**Comment by henrikt-ma** [comment]
Trying to draw attention to this so that we can start working on #2562, I'd like to make the following proposals:

Regarding `\textbf`:
- Don't use boldface for ad hoc syntax highlighting — use `\lstinline` instead.
- Never use directly in specification text — only through semantic macros defined in _preamble.tex_.

Regarding `\texttt`
- Never use for syntax highlighting of source code — use `\lstinline` instead.
- Never use directly in specification text (some things might not qualify as source code) — only through semantic macros defined in _preamble.tex_.

The use of semantic macros will help us minimizing inconsistent formatting, and make it easy to change formatting later based on semantic context.  As soon as we get a decision, I can take care of the implementation.

**Comment by HansOlsson** [comment]
I think those are good proposals.
And for syntax highlighting remember to consider the case that it's not-Modelica, but another programming language, we currently have Modelica, C, Fortran, and grammar as non-inline languages.
I'll see if I can change the start of chapters before this.

**Comment by henrikt-ma** [comment]
I assume that the left hand side of the last inequality of the paragraph
> Every solution of the implicit equation…

is a typo.  This will be fixed together with the rest of the `\texttt` cleanup.

**Comment by henrikt-ma** [comment]
Another issue I'm encountering is the unnecessary line breaks inside inline code due to redundant parentheses.  For example, in _streams.tex_ there is a lot of
> operator `inStream()`…

instead of just saying
> operator `inStream`…

In my opinion such empty parentheses are just clutter, and removing them would have the positive side effect of not risking line breaks between `inStream` and `()` (there are at least two such line breaks in the _Stream Connectors_ chapter).

**Comment by HansOlsson** [comment]
> I assume that the left hand side of the last inequality of the paragraph
> 
> > Every solution of the implicit equation…
> 
> is a typo. This will be fixed together with the rest of the `\texttt` cleanup.

If you mean that it looks odd with `m_1.c.m_flow`, `m_2.c.m_flow` and then `c_M.m_flow` (and abs and comparison with eps), it is actually odd but **correct**.
It could be clearer by writing `m_1.c.m_flow`, `m_2.c.m_flow`, .... `m_N.c.m_flow`, `c_1.m_flow` .... `c_M.m_flow`

**Comment by HansOlsson** [comment]
> Another issue I'm encountering is the unnecessary line breaks inside inline code due to redundant parentheses. For example, in _streams.tex_ there is a lot of
> 
> > operator `inStream()`…
> 
> instead of just saying
> 
> > operator `inStream`…
> 
> In my opinion such empty parentheses are just clutter, and removing them would have the positive side effect of not risking line breaks between `inStream` and `()` (there are at least two such line breaks in the _Stream Connectors_ chapter).

I agree that they are not needed, and it seems unnecessary to mark inStream as an operator in that way when we already use different font to mark it as code.
