### ISSUE TITLE
The semantics of convertClass() is ambiguous

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2514]
Functions for conversion scripts were introduced in [Modelica 3.4, sect. 18.8.2.1](https://specification.modelica.org/v3.4/Ch18.html#conversion-rules). They will be applied to the Modelica Standard Library for the first time in MSL 4.0.0, where they will play a major role, because an extensive, non-backwards compatible clean-up of the library was performed. Unfortunately, it seems that so far there is only one available implementation of this feature. So, I am worried that the specification is actually too ambiguous to make sure that other tools implementing it will produce the same results that current MSL developers got with today's only implementation, when converting existing libraries from MSL 3.2.3 to MSL 4.0.0. 

I discussed this issue with OpenModelica developers in this [ticket](https://trac.openmodelica.org/OpenModelica/ticket/5297), and I got the clear feeling that one could have naive implementations that only work in some cases, or much more involved implementations that work in all possible cases, and that the specification is too ambiguous in this regard. 

Given the crucial role of conversion scripts for the success of MSL 4.0.0 and of all future versions of MSL, I think we should refine the specification to explain in a clearer way what is the intended result in non-trivial cases. 

I also think there is a broad consensus that this feature should be implemented in at least two tools, producing the same results in a sufficient number of test cases, before we can be reasonably sure that the specification is sound and will allow all tool vendors to implement it without the need to reverse-engineer existing implementations. Having a clearer and agreed-upon specification will help getting the required second implementation soon without any unnecessary guesswork. It will also make further implementations that are consistent with these first two ones straightforward.

I am specifically concerned by the` convertClass()` function. The specification is very terse:

> convertClass(”OldClass”,”NewClass”)
> Match longer path first, so if converting both A to C and A.B to D then A.F is converted to C.F and A.B.E to D.E. This is considered before convertMessage for the same OldClass

Now, consider the following test case
```
package MyPackage
  import SI = Modelica.SIunits;
  model M1
    SI.Pressure p = 1e6;
    function f = SI.Conversions.to_degC;
    Modelica.Blocks.OldBlock b;
  end M1;
  model M2
    replaceable package Medium = Modelica.Media.Interfaces.PartialMedium;
    Medium.BaseProperties baseProperties; 
  end M2;
end MyPackage;
```
suppose you apply the following conversion script
```
convertClass("Modelica.Blocks.OldBlock", "Modelica.Blocks.NewBlock");
convertClass("Modelica.SIunits", "Modelica.Units.SI");
convertClass("Modelica.SIunits.Conversions", "Modelica.Units.Conversions");
convertClass("Modelica.Media.Interfaces.PartialMedium.BaseProperties", "Modelica.Media.Interfaces.PartialMedium.BasicProperties");
```
The first conversion function turns
```
    Modelica.Blocks.OldBlock b;
```
into
```
    Modelica.Blocks.NewBlock b;
```
and that is pretty straightforward, basically find&replace string. The second should also obviously turn
```
      import SI = Modelica.SIunits;
```
into
```
      import SI = Modelica.Units.SI;
```
From this point onwards, I have several doubts. Should
```
     SI.Pressure p = 1e6;
```
remain as it is, or should it be turned to
```
     Modelica.Units.SI.Pressure p = 1e6;
```
Both versions are valid, but as a library developer, I would definitely require imports to be maintained as much as possible, to keep the same readability of the original code also in the converted code. IMHO this cannot be simply dismissed as a "quality of implementation issue". As a library developer, _my_ requirement is that when I write a conversion script it should be clear to me what is the expected outcome, and I need to be confident that if a tool claims to support this feature, users of my upgraded library would get my expected result when they convert their own library, not something else.

Regarding the function declaration
```
    function f = SI.Conversions.to_degC;
```
as a human I would say it should be converted to 
```
    function f = Modelica.Units.Conversions.to_degC;
```
because obviously that is where the function is found after conversion, but how can a tool figure this out automatically? I guess the answer is, through lookup, but I'll leave this to the experts. In this case, the import statement cannot be reused, so you have to use a fully specified qualifier, but in the former case you actually can, what is the general rule to follow? Again, as a library developer I'd say that if the original model had an import for readability purposes, it should be preferably kept, unless (as in this case) it really can't.

Last, but not least, as a seasoned fluid modeller with a human brain, I would expect that
```
    Medium.BaseProperties baseProperties; 
```
is turned into
```
    Medium.BasicProperties baseProperties; 
```
because of the last `convertClass()` call. However, is this actually the expected behaviour according to the current specification? I can hardly say. Furthermore, is it actually conceivable that an automatic conversion function figures this out? If so, should we require that this is indeed done, even though it may be quite complicated, or should we rule this case out, to keep things simple, so that the last `convertClass()` call is illegal and triggers an error?

@adrpo, @perost, @sjoelund, please add your comments here, and possibly more issues and/or use cases that you think are unclear.

@HansOlsson, I think it's best if you put your arguments in this PR yourself.

Thank you!

**Comment by HansOlsson** [comment]
> 
> @HansOlsson, I think it's best if you put your arguments in this PR yourself.

This is not a PR; this is a ticket combining multiple separate issues (which will make it difficult to keep track of them):
- [ ] Should the result merely be correct after conversion, or should the exact result be specified (and if so how)? That is a possible enhancement.
- [x] `Whether SI.Conversions.to_degC` should be converted? I don't see that there is any issue here, since that clearly referred to `Modelica.SIunits.Conversions.to_degC` before conversion and that has the best match given by convertClass("Modelica.SIunits.Conversions", "Modelica.Units.Conversions"); leading to `Modelica.Units.Conversions.to_degC`
 -[ ] The possible conversion of Modelica.Media.Interfaces.PartialMedium.BaseProperties. I don't see any argument for not converting that class. Anyway that conversion isn't present in MSL 4.0.0. Note:   an alternative for specifying this possible conversion would be to use convertElement.

**Comment by casella** [comment]
Sorry, my mistake, of course it was an issue and not a PR 😃 

I also understand it combines multiple separate issues. I'd like to get a feeling whether or not the community considers them an issue at all. If it does, then we can categorize them and open several different issues, which will be linked from this one. If it doesn't, there is no point.

**Comment by HansOlsson** [comment]
The remaining issue is now:

Should the specification merely say that the model should be correctly converted, or should it also define the exact results of the conversion (in the latter case the details must also be specified).

**Comment by HansOlsson** [comment]
Proposal at phone-meeting, 

The conversion should generate correct Modelica models using the new version of the library corresponding to the old version.

Non-normative text:
Whenever possible tools should preserve the original style of the model, e.g. use of imports.
Agreement.
