### ISSUE TITLE
Arrow aspect ratio

### ISSUE THREAD

**Issue by max-privato** [modelica/ModelicaSpecification#2515]
MS in its section 18.6.5.1 states that:
"The arrow is drawn with an aspect ratio of 1/3 for each arrow part."
For me, it is not very clear. This should not very clear for developers of tools as well since they interpret it in different ways.
For instance, Dymola creates arrows having a width roughly one half the length, while OMEdit uses equilateral triangles. See the pictures (taken from a PowerGrids library) in the attached [pictures.pdf](https://github.com/modelica/ModelicaSpecification/files/4270934/pictures.pdf).

In that file the arrowed line is created using the following annotation:
```
annotation (
    Icon(graphics={  Line(origin={-2.98,0},
    points = {{-3.01972, 29.9973}, {18.9803, 9.99729}, {-19.0197, -12.0027}, {2.98028, -30.0027}},
    thickness = 1, arrow = {Arrow.None, Arrow.Filled}, arrowSize = 6)}));
```
Maybe the above-quoted MS sentence should be revised do be made clearer? I hope it will not request arrows having width 1/3 the length, since in this case, for me, they would be too slim.

**Comment by maltelenz** [comment]
It looks like Wolfram System Modeler is making the same interpretation as Dymola (except for some nicer rounding):

![image](https://user-images.githubusercontent.com/329963/75665764-f8e5e880-5c74-11ea-8cca-93b936f53b3c.png)

I don't immediately see how you would end up at the OpenModelica rendering, but I agree the specification could be clearer.

**Comment by HansOlsson** [comment]
The discussion in #1894 explain the decision. 
Thus "aspect ratio of 1/3" mean that the angle between line and each outer part for the arrow is atan(1/3)

**Comment by HansOlsson** [comment]
> 
> Maybe the above-quoted MS sentence should be revised do be made clearer? I hope it will not request arrows having width 1/3 the length, since in this case, for me, they would be too slim.

It is 1/3 for each arrow "part", and the idea is that a normal non-Bond-graph arrows have two parts, so in total a width 2/3 of the length.

So, the problem seems to be that "part" is unclear and should be clarified.

**Comment by max-privato** [comment]
> 
> It is 1/3 for each arrow "part", and the idea is that a normal non-Bond-graph arrows have two parts, so in total a width 2/3 of the length.
> 
> So, the problem seems to be that "part" is unclear and should be clarified.
Very good. a total 2/3 for me is the best choice. I will open a ticket on OpenModelica to ask for a fix there.
