### ISSUE TITLE
Something like convertMessage for components

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2516]
Currently convertMessage can be used for classes that cannot be converted.

However, the same issue can occur for components - and it would be good to have something similar for that case, e.g. convertMessageElement

https://github.com/modelica/ModelicaStandardLibrary/issues/3455#issuecomment-593391633_

The benefits are:

- Users will get better diagnostics when converting their libraries
- Better check of conversions beforehand

**Comment by christiankral** [comment]
@beutlich What milestone does make sense here? Shall we include the convertMessageElement for all non-backwards compatible changes for the upcoming 4.0.0 version?

**Comment by beutlich** [comment]
This is a specification issue. convertMessageElement is not yet available.

**Comment by christiankral** [comment]
OK, I was not aware of that.

**Comment by casella** [comment]
MSL 4.0.0 was meant to be compatible with Modelica 3.4.

**Comment by HansOlsson** [comment]
> MSL 4.0.0 was meant to be compatible with Modelica 3.4.

MSL 4.0.0 is planned to be compatible with Modelica 3.4; but we are still improving the Modelica specification for the future.

**Comment by HansOlsson** [comment]
I can see three possibilities here (in addition to the existing convertMessage):

- convertMessageElement("OldClass", "oldElement", "Message")
For any use of oldElement in OldClass report that conversion could not be applied with the given
message. 
- convertMessage("OldClass.oldElement", "Message")
For any use of oldElement in OldClass report that conversion could not be applied with the given
message.
- convertMessage("OldClass", "Message", "oldElement")
For any use of oldElement in OldClass report that conversion could not be applied with the given
message.

All solve the problem, the disadvantage with the first proposal is that we introduce yet another special function, the disadvantage with the second proposal is that it is not clear what is missing class and what is missing element in a class, and the last one has a bit unusual order of arguments (to preserve compatibility).
It should be straightforward to vote on, and then pick one.

**Comment by HansOlsson** [comment]
Poll:
1. 1
2. 4
3. 8
--
Go with variant 3.
