### ISSUE TITLE
The syntax of old modifier values in convertModifiers() is unclear

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2517]
Section [18.8.2.1](https://specification.modelica.org/v3.4/Ch18.html#conversion-rules) of the specification contains the following definition:

>  convertModifiers("OldClass",
{"OldModifier1=default1", "OldModifier2=default2", ...},
{"NewModifier1=...%OldModifier1\%"} [, simplify=true] )
>
>Normal case; if any modifier among OldModifier exist then replace all of them with the NewModifiers. The defaults (if present) are used if there are multiple OldModifier and not all are set in the component instance.

The MSL 3.2.3->4.0.0 conversion script, [line 406](https://github.com/modelica/ModelicaStandardLibrary/blob/beaa518c6586308eba39b6aab649d529e457befa/Modelica/Resources/Scripts/Conversion/ConvertModelica_from_3.2.3_to_4.0.0.mos#L406), contains the following call:

> convertModifiers("Modelica.StateGraph.Temporary.NumericValue",
                  {"precision"}, {"significantDigits=%precision%"})

According to the specification, I would expect the second input to contain an array of strings with "OldModiferX=defaultX". However, the "=defaultX" part here is missing. So, what is the syntax of the old modifier list is not clear. In particular, is "=defaultX" mandatory or optional, and under which conditions?

Please clarify.

**Comment by HansOlsson** [comment]
According to the specification, I would expect the second input to contain an array of strings with "OldModiferX=defaultX". 

The quoted text states:

> The defaults (if present) are used if there are multiple OldModifier and not all are set in the component instance.

That could be clearer, but "if present" implies that defaults can be missing (and also that defaults are not used if there is at most one modifier, as in this case).

The problematic situation would be if there are multiple old modifiers and at least one lacks defaults in convertModifiers, and a component have old modifiers for the other ones.

That does not occur in MSL 4.0.0 conversion as far I recall.
One possibility would be to require defaults if there are more than one old modifier.
