### ISSUE TITLE
The semantics of convertModifiers() is unclear

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2518]
Section [18.8.2.1](https://specification.modelica.org/v3.4/Ch18.html#conversion-rules) of the specification contains the following definition:

>  convertModifiers("OldClass",
{"OldModifier1=default1", "OldModifier2=default2", ...},
{"NewModifier1=...%OldModifier1\%"} [, simplify=true] )
>
>Normal case; if any modifier among OldModifier exist then replace all of them with the NewModifiers. The defaults (if present) are used if there are multiple OldModifier and not all are set in the component instance.

Consider the following use case:
```
//Old library
model M
  parameter Boolean p = false;
end M;

//New library
model M
  parameter Boolean p = true;
end M;

//Old user model
model MyModel
  M m;
end MyModel;

//Expected new user model after conversion
model MyModel
  M m(p = false)
end MyModel;
```
Obviously, if I want `MyModel` to keep the same behaviour it had with the old library, the conversion should use the old default (p = false) to set explicitly the modifier `p = false` in models that relied on the default value in the old library.

How is one expected to call convertModifiers() to get this behaviour? I tried to figure this out from the specification text together with my colleague @AndreaBartolini, but after one hour of discussion we still had no clue.

Furthermore, the specification text mentions "multiple `OldModifier`", but what if, as in this specific use case, there is only one?

**Comment by HansOlsson** [comment]
This was handled in #2409, which originated in a case in MSL discussed in
https://github.com/modelica/ModelicaStandardLibrary/pull/3086#pullrequestreview-278443918

**Comment by casella** [comment]
Does this mean we have to wait for Modelica 3.5 to be rolled out?

**Comment by HansOlsson** [comment]
> Does this mean we have to wait for Modelica 3.5 to be rolled out?

No, it seems you haven't been following the process in MAP-Lang.

For clarifications/corrections of flaws in Modelica 3.4 tools can use the updated semantics according to  https://github.com/modelica/ModelicaSpecification/blob/master/RationaleMCP/DevelopmentProcess.md
