### ISSUE TITLE
The syntax of new modifier values in convertModifiers() is unclear

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2519]
Section [18.8.2.1](https://specification.modelica.org/v3.4/Ch18.html#conversion-rules) of the specification contains the following definition:

>  convertModifiers("OldClass",
{"OldModifier1=default1", "OldModifier2=default2", ...},
{"NewModifier1=...%OldModifier1\%"} [, simplify=true] )

It is not clear to me exactly what `...%OldModifier1\%` means. I guess (but this should be said explicitly, IMHO) that %OldModifier1% means the value that the corresponding old modifier had prior to conversion. 

What is really not clear to me is what "..." mean. Can we please explain it clearly?

**Comment by adrpo** [comment]
Having a look at the conversion scripts gives some info on this:
For example using the convertModifiers below:
```
convertModifiers("Modelica.Blocks.Math.LinearDependency",
                 {"y0", "k1", "k2"}, {"y0=%y0%", "k1=%y0%*%k1%", "k2=%y0%*%k2%"}, true)
```
You get to this result:
https://github.com/beutlich/ModelicaStandardLibrary/commit/851b882f4e4cb8331ec377dce0bc2fa4b9ffc0ee#diff-cf79383a2906b946f55eba6294b959aeL66

So in this case `...%OldModifier1%` is an expression based on the values of the old modifiers.

What I find odd in this conversion is that the modifiers are changing their order:
Before:
```
      Modelica.Blocks.Math.LinearDependency linearDependency(
        y0=10,
        k1=100,
        k2=1000)
```
After:
```
      Modelica.Blocks.Math.LinearDependency linearDependency(
        k1=1000,
        k2=10000,
        y0=10)
```

**Comment by HansOlsson** [comment]
As @adrpo states it is intended as an expression involving the values of the old modifiers. The order-part I view as similar to the issue of exact results given as first issue in #2514.

**Comment by casella** [comment]
I agree that people wanting to learn how to use these scripts could have a look at the MSL 3.2.3->4.0.0 to figure out how it works by example. However, that script is not a substitute for proper specification of the semantics of these functions, nor is the result obtained when running the script with Dymola. 

This applies both to `%OldModifier1%` and to `...`

Could we try to come up with a proposal for a clearer specification text?
