### ISSUE TITLE
Discrete-time variability and arrays

### ISSUE THREAD

**Issue by Daiwen** [modelica/ModelicaSpecification#2521]
Is this model valid?

    model Test
      function f
           input Integer i;
           output Integer o;

           external "C" randomInt(i);
      end f;

      Real[2] x;
      Integer i = mod(f(time), 2)+1;
      Integer j = mod(i+1, 2)+1;
    equation
      der(x[i]) = 1-x[i];
      when time > 1.0 then
        x[j] = 0;
       end when;

    end Test;

In particular, is it possible for arrays to contain both discrete-time and non-discrete-time variables?

**Comment by dietmarw** [comment]
This issue tracker is for tracking issues of the MSL itself. For modelling questions, please head over to https://stackoverflow.com/tags/modelica
Thank you.

**Comment by Daiwen** [comment]
This is not a MSL question, this is a language definition problem. The specification does not seem to address this issue. And if it doesn't the specs should as it as implications on how to check the variability of expressions.

**Comment by dietmarw** [comment]
Sorry my bad.  I confused it with MSL issue tracker her.

**Comment by HansOlsson** [comment]
This is similar to #1190 and it seems it should be handled in the same way, i.e. the entire `x`-array is seen as discrete if `x[j]` appears as the left-hand-side inside a when-clause.

**Comment by Daiwen** [comment]
ok, but I don't understand why it is not required to declare them as such, as that would lift any ambiguity.

**Comment by HansOlsson** [comment]
> ok, but then I don't understand why it is not required to declare them as such, as that would lift any ambiguity and it would behave exactly the same way.

To be clear: I meant that we should update the specification based on my previous statement (assuming we agree) to remove that ambiguity.

Requiring that discrete variables should be declared as `discrete `have the following issues:

- It is complicated when you inherit variable-declarations from base-classes
- The keyword `discrete `currently mean "assigned in when-clause", and there are other variables that behave similarly, but aren't assigned in a when-clause and thus cannot be declared as `discrete`. Therefore if we add `discrete` the new question would be "why cannot X be declared as discrete"?

Note: clocked variables are different: no keyword and all "clocked" variables are "clocked"; not only the ones assigned in clocked when-clauses; it may be that this propagation is a better idea and we should redesign "discrete" as well, but that will take a lot more design; and I don't view it as urgent.

**Comment by HansOlsson** [comment]
Actually reading further the example is already illegal!

https://specification.modelica.org/v3.4/Ch8.html#restrictions-on-equations-within-when-equations

"Any left hand side reference, (v, out1, …), in a when-clause must be a component reference, and any _indices must be parameter expressions_."

**Comment by Daiwen** [comment]
Fair enough, but I think the problem still remains in the sense that we would like to avoid waiting until initialization to report variability issue it would be easy enough to replace `time` with a parameter.

**Comment by Daiwen** [comment]
I agree that we should resolve my problem in the way you suggest. The question may well change but it would avoid us having to write a significant caveat to the  "`discrete` means 'assigned in when-clause'", namely that it propagates to all variables of an array.

**Comment by henrikt-ma** [comment]
I think the following example sheds some more light on the problem:
```
model MyDiscreteNeighbor
  Real[2] x(each start = 0.0, fixed = {true, false}); /* Not explicitly declared discrete. */
equation
  when false then
    x[1] = pre(x[1]); /* Makes not just x[1], but all of x discrete-time. */
  end when;
algorithm
  x[2] := floor(time); /* Valid equation for discrete-time x[2], but not a when-clause assignment. */
end MyDiscreteNeighbor;
```
I would expect this model to be valid, even though `x[2]` isn't treated as if it were declared `discrete`, or am I hoping for too much?

**Comment by HansOlsson** [comment]
The model above is structurally overdetermined since we decided that the entire array is assigned if any element is assigned to in an algorithm (so x[1] is also "assigned to" in the array and thus assigned to twice).

If we change it to an equation it should be valid, and the more interesting case would be `x[2]=time;` as far as I can see that is also legal - and `x` will have some discrete and some continuous-time elements. As far as I recall we have a similar status for clocked variables, i.e. that different array elements can be on different clocks.

**Comment by henrikt-ma** [comment]
Of course!  My bad.  The alternative with an equation is what I had in mind originally, which I then thought was simplified by the use of an algorithm with verified variability in the assignment.  For sake of reference, I include the corrected example here:
```
model MyDiscreteNeighborEq
  Real[2] x(each start = 0.0, fixed = {true, false}); /* Not explicitly declared discrete. */
equation
  when false then
    x[1] = pre(x[1]); /* Makes not just x[1], but all of x discrete-time. */
  end when;
algorithm
  x[2] + floor(time) = 0; /* Valid equation for discrete-time x[2], but not a when-clause assignment. */
end MyDiscreteNeighborEq;
```
We seem to agree that this should also be considered consistent with `x[2]` being discrete-time.

But what you say regarding `x[2] = time;` doesn't make sense to me in view of the generalization of #1190, that the entire array `x` should be discrete-time as soon as any component of `x` is assigned in a when-clause.  What did I miss?

**Comment by henrikt-ma** [comment]
The whole situation would be so much more clear if `x` would only be considered a discrete-time variable if explicitly declared `discrete`, but then allow also continuous-time variables to be assigned in when-clauses.  A continuous-time variable assigned in a when-clause shouldn't be more strange than a continuous-time variable being equal to an `Integer` (or solved in some other fashion that only gives a new solution at events).  Then `x[2] = time;` would only be a problem if `x` was explicitly declared `discrete`.

**Comment by HansOlsson** [comment]
> Of course! My bad. The alternative with an equation is what I had in mind originally, which I then thought was simplified by the use of an algorithm with verified variability in the assignment. For sake of reference, I include the corrected example here:
> 
> ```
> model MyDiscreteNeighborEq
>   Real[2] x(each start = 0.0, fixed = {true, false}); /* Not explicitly declared discrete. */
> equation
>   when false then
>     x[1] = pre(x[1]); /* Makes not just x[1], but all of x discrete-time. */
>   end when;
> equation
>   x[2] + floor(time) = 0; /* Valid equation for discrete-time x[2], but not a when-clause assignment. */
> end MyDiscreteNeighborEq;
> ```
> 
> We seem to agree that this should also be considered consistent with `x[2]` being discrete-time.
> 
> But what you say regarding `x[2] = time;` doesn't make sense to me in view of the generalization of #1190, that the entire array `x` should be discrete-time as soon as any component of `x` is assigned in a when-clause. What did I miss?

That I changed my opinion on that! I'm not saying that it is a bad idea - but that we already have something else that avoids the problem in another way.

> The whole situation would be so much more clear if x would only be considered a discrete-time variable if explicitly declared discrete, but then allow also continuous-time variables to be assigned in when-clauses.

That could also be a possibility. The obvious issue would be that people use "pre" for real variables assigned in when-clauses, but often that occurs inside the when-clause, and is thus not an issue. However, there are cases in Modelica.Blocks.Discrete - and even if we could change them it's likely that users have similar models.

A larger change would be to use the inspiration from synchronous (specifically the base-clock partition): _change so that everything deduced to be discrete is actually discrete_ and possibly drop 'discrete' altogether. We already two parts in place for that: tools support synchronous, and including reasonable diagnostics for errors; but it would require quite a lot of changes in the specification.

**Comment by eshmoylova** [comment]
The problem I see with requiring discrete variable to be declared discrete is when the declaration is inherited from a base class, and the base class does not know that the variable maybe used in a when-clause. For example:
```
partial model A
    Real x, y;
end A;

model B
    extends A;
equation
    x = time;
    when x > 0.5 then
        y = pre(y) + 1;
    end when;
end B;
```
`A` does not have knowledge how `x` and `y` are going to be used.  Right now there are a lot of models like `A` which define the interface. Requiring that `y` is declared discrete would make `B` illegal. @HansOlsson, is that what you meant by "It is complicated when you inherit variable-declarations from base-classes" in [this comment](https://github.com/modelica/ModelicaSpecification/issues/2521#issuecomment-595753262)?

**Comment by henrikt-ma** [comment]
First, note that `B` would still be legal in my proposal.  The difference is that `y` would be a non-disctete-time expression for purposes of variability analysis.

I see the point of the current practice with a base classes defining an interface that should work with both discrete-time and non-discrete-time inputs and outputs.  On the other hand, aren't the most important use cases for interfaces that should work with both discrete-time and non-discrete-time signals those of blocks that are just wrappers around functions, that is, blocks behaving as functions?  For these, I think Modelica is lacking a quite important class specialization, and it makes me wonder why `function` isn't the perfect match here…

A `function` already has the property of preserving variability from inputs to outputs, and it seems that all one would need is to allow causal connectors to be used in the interface.  For example, a `RealOutput` would be a discrete-time `Real` as long as none of the inputs have higher variability.  Is there any well known difficulty of doing this that I'm missing?

With interfaces to function-like blocks treated as suggested above, I suspect that the remaining cases where one may depend on the discrete-time variability of a computed interface variable are actually not very nice uses of a base classes as interfaces.  When the discrete-time aspect is that important, I'm suspecting that it would make good sense to have the variable declared `discrete` in the interface, and not share interface with other implementations that produce non-discrete-time results.

**Comment by henrikt-ma** [comment]
> The obvious issue would be that people use "pre" for real variables assigned in when-clauses, but often that occurs inside the when-clause, and is thus not an issue. However, there are cases in Modelica.Blocks.Discrete - and even if we could change them it's likely that users have similar models.

True, one might need to relax the discrete-time restriction on `pre`, but define it to be an identity operator between events.

**Comment by henrikt-ma** [comment]
> A larger change would be to use the inspiration from synchronous (specifically the base-clock partition): change so that everything deduced to be discrete is actually discrete and possibly drop 'discrete' altogether. We already two parts in place for that: tools support synchronous, and including reasonable diagnostics for errors; but it would require quite a lot of changes in the specification.

In the same spirit, I don't think it would be too hard to get rid of variability rules all together.  The reason for not doing this is that variability rules help creation of correct models that are easy to reason about.

**Comment by HansOlsson** [comment]
> True, one might need to relax the discrete-time restriction on `pre`, but define it to be an identity operator between events.

I don't think that "between events" would be a good idea, since it would imply that events have a global impact, which would be problematic for models (your sampled system works fine, and then you add a clutch in a different part causing an event messing up that sampled system) - and also for some optimizations we currently do in Dymola.

**Comment by HansOlsson** [comment]
> In the same spirit, I don't think it would be too hard to get rid of variability rules all together. The reason for not doing this is that variability rules help creation of correct models that are easy to reason about.

Note that I wasn't removing _variability rules_, but removing the discrete keyword and reformulating normal when-clauses and discrete variables in terms of a new clock partitioning.
However, that would take more work, and exactly how isn't clear.

**Comment by henrikt-ma** [comment]
> > True, one might need to relax the discrete-time restriction on `pre`, but define it to be an identity operator between events.
> 
> I don't think that "between events" would be a good idea, since it would imply that events have a global impact, which would be problematic for models (your sampled system works fine, and then you add a clutch in a different part causing an event messing up that sampled system) - and also for some optimizations we currently do in Dymola.

I can't say I understand this argument, but what I can see is that this subtopic is becoming too technical to continue in the scope of this issue.

**Comment by HansOlsson** [comment]
Phone meeting: 
Leave as currently specified, and ignore that it differs from array elements in algorithms.
Agreement.
