### ISSUE TITLE
What does it mean to have internal memory 'reported' between function calls?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2524]
Regarding external objects, it is said that:
> External functions may have internal memory reported between function calls.

What does it mean for memory to be _reported_?

**Comment by HansOlsson** [comment]
It must be a typo for something else.

The complete paragraph is (added in 2.0):

> External functions may have internal memory reported between function calls. Within Modelica this memory is defined as instance of the predefined class ExternalObject according to the following rules

My first variant would be: "External functions may need to store their internal memory between function calls."

**Comment by svorkoetter** [comment]
Perhaps "restored" instead of "reported"? Probably a case of <strike>autoconnect</strike> autocorrect.

**Comment by HansOlsson** [comment]
> Perhaps "restored" instead of "reported"?

Yes, that seems likely.

However, I still think that it makes sense to rewrite the sentence completely, since "External functions may have internal memory restored between function calls." doesn't explain the entire issue.

**Comment by henrikt-ma** [comment]
I'd be fine with that _first variant_.
