### ISSUE TITLE
Don't mix normative and non-normative text in the same paragraph

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2536]
The current practice of inserting non-normative content anywhere in the specification text by just wrapping it in square brackets and styling with `\emph` is problematic for two reasons:
- The possibility to appear mixed with normative content in the same paragraph makes it difficult to apply many styling alternatives that would improve the visual separation of normative and non-normative content (such as using an indented box with smaller text and different background, for example).
- The LaTeX source code is severely messed up because of the `\emph` often being interleaved with lots of `\lstinline`, resulting in sources that are hard to read, very error prone (missing punctuation, bad spacing, etc), and hard to maintain.  This is also part of the reason why more appealing styling is impossible.

To remedy this situation, no non-normative content should be encoded using the square brackets and `\emph` in the LaTeX sources.  Instead, all non-normative content should be formulated as separate paragraphs and wrapped in the `nonnormative` environment (except for chapter introductions, etc).

In some cases, to avoid too many tiny non-normative paragraphs, this change may involve changing small pieces of currently non-normative content into normative content within parentheses.  Decisions will have to be made case by case.

This is a replacement for #2368, focusing on the most important part of what is left after closing #2364.

**Comment by HansOlsson** [comment]
Agreement by acclamation -> Henrik will start.
