### ISSUE TITLE
Restriction of the default values of function inputs and outputs

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#2538]
I can't find any restriction on the variability of function inputs and outputs, is there any?
Is the following a valid model:

    model TestModel
      function f
        input Real i;
        output Real o = i;
      end f;

      Real x;
      Real y;
      function g = f(i=x);

      constant Real c = g();
    equation
      der(x) = 1-x;
      y = g();
    end TestModel;

**Comment by HansOlsson** [comment]
> I can't find any restriction on the variability of function inputs and outputs, is there any?

As far as I recall, there are none - but instead the outputs for a call automatically gets the variability of the most variable input; and if the function is pure a low variability of inputs also mean that it can be called less.

I know that some languages go further with related concepts, e.g. constexpr in recent C++ - but since it has taken them several years for something that _seemed_ trivial I assume it isn't trivial.

**Comment by Daiwen** [comment]
So, in my current case, it is allowed to initialise a constant `c` with a non-discrete-time variable `x` as long as you do it by hiding it behind a function call.

**Comment by HansOlsson** [comment]
> So, in my current case, it is allowed to initialise a constant `c` with a non-discrete-time variable `x` as long as you do it by hiding it behind a function call and a default-value.

No, g() should be seen as f(x) and thus have continuous-time variability and you shouldn't be allowed to use that to initialize c.

Checking with Dymola after writing that, hoping that I don't have to do correct it.

Ah, it agrees and says:
> The variability of the definition equation:
> c = g_Unique'""'(x);
> is higher than the declared variability of the variables
(Ignore the Unique part, and also the name of the function.)

**Comment by Daiwen** [comment]
Why should it? Does that mean that it is not possible to call `g(1)`?

**Comment by HansOlsson** [comment]
> Why should it? This is not a partial application, or does that mean that it is not possible to call `g(1)`?

I mean that `g()` should be treated as `f(x)` and thus have continuous-time variability - but `g(1)` should be allowed and treated as `f(1)` and thus be constant, i.e. input-handling including defaults and named arguments should be done before variability check.

**Comment by Daiwen** [comment]
Ok

**Comment by Daiwen** [comment]
model TestModel
      function f
        input Boolean c;
        input Real i = if c then g(c) else 1;
        output Real o = i;
      end f;

      function g
        input Boolean c;
        input Real i = if c then f(c) else 1;
        output Real o = i;
      end g;

      constant Real c = g(false);
    end TestModel;
What about that one?

**Comment by henrikt-ma** [comment]
The mutually recursive example is a really nice one.  I'd just formulate the solution slightly differently:
- Default arguments of a pure function must have constant variability.
- A call to an impure function is fundamentally a non-discrete-time expression, but the usual rules regarding when-clauses and initial sections of course apply on top of that.

For a more fine-grained solution, one needs to be able to declare the variability of an impure function, and then the default argument expressions must not have variability exceeding that of the function itself.

**Comment by HansOlsson** [comment]
@HansOlsson check if possible to specify variability in terms of function (with special case for short-class with defaults etc), and arguments.

**Comment by HansOlsson** [comment]
> The mutually recursive example is a really nice one. I'd just formulate the solution slightly differently:
> 
> * Default arguments of a pure function must have constant variability.

I don't understand this, and it would break existing libraries.

A common case is something like Modelica.Math.Matrices.balanceABC where some of the optional matrices depend on other input matrices. You could also think of something like a limiter-function where the default for lower bound was `-upper`.

The mutually depending recursive example is problematic in some aspects, but I don't see that it is related to this issue of variability.

**Comment by henrikt-ma** [comment]
> > The mutually recursive example is a really nice one. I'd just formulate the solution slightly differently:
> > 
> > * Default arguments of a pure function must have constant variability.
> 
> I don't understand this, and it would break existing libraries.
> 
> A common case is something like Modelica.Math.Matrices.balanceABC where some of the optional matrices depend on other input matrices. You could also think of something like a limiter-function where the default for lower bound was `-upper`.
> 
> The mutually depending recursive example is problematic in some aspects, but I don't see that it is related to this issue of variability.

Right, it's not that simple.  What I was trying rule out was to set non-constant defaults via modification, where the modifier's scope is outside the function.
