### ISSUE TITLE
Incorrect link to MLS 3.3 in https://specification.modelica.org

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2541]
In https://specification.modelica.org, the link to MLS 3.3 points to https://modelica.org/documents/ModelicaSpec33Revision1.pdf whereas it should be https://modelica.org/documents/ModelicaSpec33.pdf.

Sorry, if this is the wrong issue tracker, but I was not sure where to report or fix it.

**Comment by sjoelund** [comment]
It's generated from https://github.com/modelica/ModelicaSpecification/blob/master/README.md
