### ISSUE TITLE
Suggesting signed number range for integer literals is strange

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2552]
In _Integer Literals_, we first define the integer literals as being non-negative numbers, mentioning that negative numbers can be obtained by negation of a literal:
https://specification.modelica.org/master/lexical-structure.html

Given that the literals are non-negative, it is strange that the minimal recommended number range covers signed numbers.  I'm sure this can be written in a better way.

How about moving the recommended number range into the non-normative part together with the negation of literals?

Is it in our interest to formulate the recommendation so that -2147483648 can be expressed as the negation of an `Integer` literal?  That is, could `2147483648` be an integer (or even `Integer`) literal even when it can't be stored in an `Integer`?

**Comment by henrikt-ma** [comment]
For what it's worth, in SystemModeler we hit the limit when not being able to say `-9223372036854775808`, even though this number is in the range (64 bit signed) on which we can do constant arithmetic.  However, the range of an `Integer` is much smaller than that (limited by its runtime storage as a `double`), so expressing the extreme values of an `Integer` is no problem.

The question raised here would be more important the day our `Integer` range is also extended to 64 bit signed, as it would then require a trick to express the smallest `Integer` (unless you do it the proper way and take it from the built-in library with machine constants):
```
Integer x = -9223372036854775807 - 1;
```

In view of this, and to avoid spending too much time here, I'd actually suggest to not mention the number range at all when talking about the `Integer` literals.  Instead, I think we could add a non-normative statement in 4.8.2 _Integer Type_ that the `IntegerType` is recommended to have at least the range of 32 bit signed.

**Comment by henrikt-ma** [comment]
On the same theme, why is there a non-normative description of `RealType` and `IntegerType` under the section _Attributes start, fixed, nominal, and unbounded_?

**Comment by HansOlsson** [comment]
> On the same theme, why is there a non-normative description of `RealType` and `IntegerType` under the section _Attributes start, fixed, nominal, and unbounded_?

It should likely be split and moved to directly under the definition of Real and Integer. The text was introduced in Modelica 1.1 (whereas Real and Integer appeared in Modelica 1.0), and back then it was closer to the definition of Real of Integer and it sort of made sense - and later we have added more and more text between them, and introduced extra sections, - without noticing this.

Note that it differs from the external-function definition as the intent is to explain how Real works in Modelica, not how it works when calling an external function in Modelica.

**Comment by HansOlsson** [comment]
> Given that the literals are non-negative, it is strange that the minimal recommended number range covers signed numbers. I'm sure this can be written in a better way.

I would say that it would make more sense to move the ranges to 4.8.x; as the important part is not how large integer literals can be - but how large integer values can be. Obviously there is still an issue with -2147483648 for integer literals - but you can construct that value in other ways.

**Comment by henrikt-ma** [comment]
Good.  Then we totally agree (and yes, external functions is a different thing; no room to leave ranges non-normative there).

**Comment by HansOlsson** [comment]
Agreement.
