### ISSUE TITLE
What (variability?) property is being guaranteed?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2553]
In _Component Variability Prefixes discrete, parameter, constant_, there is a non-normative statement that:
> A Modelica translator is able to guarantee this property due to restrictions imposed on discrete expressions, see…

The preceding text doesn't speak of any property, it just says that one cannot declare a discrete-valued variable with continuous-time variability, so what is the non-normative statement trying to say?

**Comment by HansOlsson** [comment]
> The preceding text doesn't speak of any property, it just says that one cannot declare a discrete-valued variable with continuous-time variability, so what is the non-normative statement trying to say?

I believe it's trying to say that you cannot construct a Boolean, Integer, or String variable in a model that changes its value as though it were continuous-time variable.

**Comment by henrikt-ma** [comment]
OK, but then I think something like this would express that better:
> The restriction that discrete-valued variables (of type `Boolean`, etc) cannot be declared with continuous-time variability is one of the foundations of the expression variability rules that will ensure that any discrete-valued expression has at most discrete-time variability.
