### ISSUE TITLE
Missing square brackets around non-normative equation counting remark?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2554]
Based on emphasis on entire normative sentences being very rare, and the style of nearby items in the same list, the following emphasized sentence in _Definition 2: Local Equation Size_ appears to have been intended as non-normative:
> This includes the proper count for when-clauses…

Was it?

(This came up while working on #2551.)

**Comment by HansOlsson** [comment]
I agree that it is non-normative.

**Comment by henrikt-ma** [comment]
OK.  Will be fixed with the rest of #2551.
