### ISSUE TITLE
Hardcoded section title after \autoref

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2559]
At the top of the section 11.1.3 _Execution of the algorithm in a function_, there is a use of `\autoref` that is followed by the hardcoded name of the referenced section:
```
See \autoref{initialization-and-binding-equations-of-components-in-functions} \emph{Initialization and Binding Equations of
Components in Functions}.
```

I think hardcoding things this way is a bad habit, and I don't remember having seen it being done anywhere else, so I don't think we should do it here either.

**Comment by HansOlsson** [comment]
I agree. If we want such references we should just replace autoref by something that does this consistently for all references.

**Comment by henrikt-ma** [comment]
Yes.  There are a few more of these in _revisions.tex_.

**Comment by dietmarw** [comment]
If you want to include the section name dymaically then you can do so with [`\nameref`](https://en.wikibooks.org/wiki/LaTeX/Labels_and_Cross-referencing#nameref)

**Comment by henrikt-ma** [comment]
Yes, for the few occurrences we have, that looks like the right solution.  I'll include a fix with https://github.com/modelica/ModelicaSpecification/pull/2551.
