### ISSUE TITLE
Non-standard formatting throughout chapter "Synchronous Language Elements"

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2562]
The chapter _Synchronous Language Elements_ deviates significantly in style from the rest of the specification.  The formatting needs to be aligned with the other chapters.

A prerequisite to do this is to decide how `\textbf` should be used, which is the topic of #2503.

**Comment by HansOlsson** [comment]
Note that in addition to the style formatting there is also #2512 to rephrase the rationale-part in a positive way.

**Comment by HansOlsson** [comment]
To me it seems that #2656 #2660 have corrected the most obvious differences and that we can close this one.

**Comment by henrikt-ma** [comment]
Here are some things I still think should be fixed:
- Systematic use of `\lstinline`.  For instance, shouldn't _Clock_ (with upper case initial) always be `\lstinline` (and use space instead of dash in _Clock-variable_)?
- When making use of the definitions for argument restrictions (_component expression_ and _expression_), we shouldn't do so using just uppercase initials — I am not aware of other places where definitions are used this way.  Ideally, I think the definitions we introduce should introduce so good terminology that no special formatting at all is needed when using it.  When that's not enough, I think we should name some sort of (linked) `\nameref`, but with the same sort of case handling as with `\Cref` and `\cref`.
- Does the _Sorting of a simulation model_ really belong to the example?
- The _incidence(e)_ should not use `\lstinline`, but rather `\operatorname`, and the graph stuff in 16.7 should use more math in general.
- Other things I just added to #2686.
