### ISSUE TITLE
Add promote to Modelica

### ISSUE THREAD

**Issue by sjoelund** [modelica/ModelicaSpecification#2568]
https://github.com/modelica/ModelicaSpecification/blob/0f11faa48bf1bd1d2049d06fb6e10687ad95c68c/chapters/arrays.tex#L220-L223 suggests that the reason `promote` is not a builtin function in Modelica is because a variable can have an unknown number of dimensions. Restricting `n` itself to be constant should not be a problem, right?
However, I believe that all such holes in the specification are resolved. If-expressions, etc are required to have the same types in all branches and I cannot seem to construct any expression where the **number** of dimensions would be unknown.

The minimum change needed would be to remove this rationale, but I believe it is a useful operator to have in the language anyway since MCP 0031 (Flat Modelica) probably needs it anyway. It should be very straight forward to get test implementations of it and into ModelicaSpec 3.5 since all tools probably already use the operator internally.

**Comment by HansOlsson** [comment]
Well, if we don't restrict n to be a literla, then we get something like the following that will be a bit difficult to handle:
```
function foo
  input Real v[:];
  input Integer n,m;
  output Real A[:,];
algorithm
  A:=[promote(v,m)*Modelica.Math.cos(promote(v, n))];
end foo;
```
Is it matrix multiplication, or scalar product, or just an error?

And I'm not sure that all implementations have a general promote-operation internally. (We have sort of handled different cases separately in Dymola.)

**Comment by sjoelund** [comment]
It could be OK to not be a literal, if it was a constant. Using the wording for parameter, which includes function inputs is indeed problematic. `promote` only makes sense for constants anyway.

**Comment by henrikt-ma** [comment]
To me, a very good reason to include `promote` (with restriction to constant) is that it is just confusing that it appears in the specification as if it really was a Modelica function, but you need to read carefully to see that it is just specification pseudo-code at the moment.

**Comment by HansOlsson** [comment]
An important issue is to be clear regarding constant vs. structural parameter #588
When considering this in more detail I realized that the related operator ndims is already part of Modelica, and that seems less useful. (We don't have any variables with unknown number of dimensions, and I don't see how it is used - except possibly when passing arrays to external functions.)

**Comment by HansOlsson** [comment]
Need name for constant that can be evaluated to literal.
Poll:

- **Add promote**: Adrian, Filippo, Gerd, Henrik, Martin, Quentin, Stefan
- Don't add it (might solve specially for FlatModelica):
- Abstain: Axel, Christoff, Markus, Dag, Hans
