### ISSUE TITLE
Rephrase 'define optionally begin and end of content that is HTML encoded'

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2593]
There are two places where we use the following phrase, which should be rewritten in a better way:
> … `<html>` and `</html>` define optionally begin and end of content that is HTML encoded

This would be a better phrase:
> … `<html>` and `</html>` may optionally be used to define the beginning and end of content that is HTML encoded

Filing this as an issue instead of opening a pull request, since the changes would most likely conflict with #2482.

**Comment by HansOlsson** [comment]
I agree that the new text looks better, and should be trivial to make the PR after #2482 to avoid any merge conflict.

**Comment by maltelenz** [comment]
I agree that the proposed change is good, but there is still room for improvement. Which of these alternatives is the intented behavior?
1. You can wrap with `<html>` if you want to, the content will be considered HTML encoded either way
2. If it is wrapped with `<html>` it is considered HTML encoded, if not, it is considered raw text and rendered as such
3. Some other interpretation (at least SystemModeler is in this category today)

**Comment by HansOlsson** [comment]
> I agree that the proposed change is good, but there is still room for improvement. Which of these alternatives is the intented behavior?
> 
> 1. You can wrap with `<html>` if you want to, the content will be considered HTML encoded either way
> 2. If it is wrapped with `<html>` it is considered HTML encoded, if not, it is considered raw text and rendered as such
> 3. Some other interpretation (at least SystemModeler is in this category today)

I would say '2' is the reasonable option, since in contrast to '1' that allows people to write "This block generates an assertion if x<0" without worrying about html-encoding characters such as <. Alternative '3' might also be ok, but that would need more information.

Thus one option would be to just write:
>  `<html>` and `</html>` define the beginning and end of content that is HTML encoded. 
or the slightly longer:
>  `<html>` and `</html>` define the beginning and end of content that is HTML encoded. Any text outside of those tags is rendered as is, and it is optional to have HTML encoded part(s).

**Comment by maltelenz** [comment]
I also think option 2 is the reasonable option. My worry is that there are libraries out there that assumed option 1, which would break badly if we change the interpretation to 2. I know for a fact we have multiple such cases in our testsuite of libraries.

SystemModeler currently applies heuristics to guess whether the string is HTML (basically looking for tags), and renders accordingly.

**Comment by HansOlsson** [comment]
> I also think option 2 is the reasonable option. My worry is that there are libraries out there that assumed option 1, which would break badly if we change the interpretation to 2. I know for a fact we have multiple such cases in our testsuite of libraries.
> 
> SystemModeler currently applies heuristics to guess whether the string is HTML (basically looking for tags), and renders accordingly.

That is always an issue with standardizing behaviour instead of having heuristics that may differ between tools.

What we have implemented in Dymola is a function, updateModelicaAnnotations (with multiple options), that goes through all of the classes in a package and updates them automatically to preserve the old meaning with the new standard.

**Comment by maltelenz** [comment]
> That is always an issue with standardizing behaviour instead of having heuristics that may differ between tools.

Indeed, and it is unavoidable.

A colleague suggested that we prevent `<html>` wrappers in the middle of strings, to avoid having to support complex things like:
```
"<HTML><B>X</B></HTML> is > than <HTML><B>Y</B></HTML>"
```
since such things can trivially be written with a single wrapper:
```
"<HTML><B>X</B> is &gt; than <B>Y</B></HTML>"
```

So how about something like:

> A string in the `Documentation` annotation can optionally be wrapped with `<HTML>` and `</HTML>` or `<html>` and `</html>`, in which case the string is considered HTML encoded.

If we want to be extra explicit, we could add more (possibly non-normative?):

> [HTML encoding can only be indicated for a complete string. If no wrapping is present, the text should be rendered verbatim.]

**Comment by HansOlsson** [comment]
> > That is always an issue with standardizing behaviour instead of having heuristics that may differ between tools.
> 
> Indeed, and it is unavoidable.
> 
> A colleague suggested that we prevent `<html>` wrappers in the middle of strings, to avoid having to support complex things like:
> 
> ```
> "<HTML><B>X</B></HTML> is > than <HTML><B>Y</B></HTML>"
> ```

To me that isn't difficult to support (I don't see that we have anything special for it in our code), but obviously it depends on how the functionality is implemented. I could imagine that it is used in some libraries, but I don't recall seeing it.

However, on the other hand I don't view it as good style, and would thus propose a non-normative text like:
[_It is recommended that the HTML encoding is only for the complete string._]

> > [_HTML encoding can only be indicated for a complete string. If no wrapping is present, the text should be rendered verbatim._]

**Comment by maltelenz** [comment]
> To me that isn't difficult to support

The straightforward implementation (as I see it) strips the wrapping `<html>` tags, adds a `<html><body>` wrapper, and dumps it in a third-party HTML viewer.

If you want inline `<html>` tags, don't you suddenly need to parse the string? If there multiple choices of matching start and end tags (uneven number), don't you get undefined behaviors?

**Comment by HansOlsson** [comment]
> > To me that isn't difficult to support
> 
> The straightforward implementation (as I see it) strips the wrapping `<html>` tags, adds a `<html><body>` wrapper, and dumps it in a third-party HTML viewer.

Yes, but:

> If you want inline `<html>` tags, don't you suddenly need to parse the string? 

"Parse" makes it seem a bit more than it is. However, since we want to html-render the things outside of html as well we need that anyway.

> If there multiple choices of matching start and end tags (uneven number), don't you get undefined behaviors?

Obviously if there is such an error we need to handle it in some safe way.

**Comment by maltelenz** [comment]
I see little point in adding the burden of supporting multiple inline `<html>` wrappers. I have never seen it used, and as I said above, the alternative solution from the user point of view is straightforward.

If anything, it would be nice if we could move more towards a proper HTML handling, where you can also specify things that go into `<head>`, so you could also style things and add javascript to your page. But that is obviously a much larger thing and would need more careful thought.

**Comment by henrikt-ma** [comment]
I (and I'm not the aforementioned colleague of @maltelenz) am also in favor of only giving special meaning to `<html>…</html>` surrounding the entire string.  If one really wants to write documentation as raw text, I find it more predictable to not have any interpretation at all of the contents.

While we seem to have a fairly mature interpretation of the HTML encoded documentation, I think there might be a need for more standardization of the raw text variant.  For example, can one assume that it will be rendered using a fixed-width font?  Can one assume that the long lines will be wrapped to the window width (considered nice by some, an impurity by others)?  What about the size of a tab character?

Would it be possible to make HTML encoding the only standardized way of writing documentation?!  It would solve so many problems.

**Comment by HansOlsson** [comment]
Phone meeting:

- Agreed that all info-strings only use format.
- Agreed that if the string starts with `<html>` it is html-encoded. Whether ending with `</html>` is required or not wasn't clear. The need for `</html>` in HTML 5 was discussed.
- Agreed that if the string doesn't start with `<html>` it is rendered as is (until we add a new format).

**Comment by henrikt-ma** [comment]
> * Agreed that all info-strings only use format.

Should be:
> … only use one format for the entire string.

**Comment by HansOlsson** [comment]
Will add the above. 
I'm not 100% sure that `</html>` is required in HTML 5, but the 5.2 specification uses it and thus I think we should follow that
https://www.w3.org/TR/html52/semantics.html#the-html-element

**Comment by sjoelund** [comment]
> I'm not 100% sure that </html> is required in HTML 5, but the 5.2 specification uses it and thus I think we should follow that
https://www.w3.org/TR/html52/semantics.html#the-html-element

That link says (almost right where the anchor is):
> An html element’s end tag can be omitted if the html element is not immediately followed by a comment.

**Comment by HansOlsson** [comment]
> > I'm not 100% sure that  is required in HTML 5, but the 5.2 specification uses it and thus I think we should follow that
> > https://www.w3.org/TR/html52/semantics.html#the-html-element
> 
> That link says (almost right where the anchor is):
> 
> > An html element’s end tag can be omitted if the html element is not immediately followed by a comment.

Ah, and I missed it. 

And then I tried to figure out what it means (note that the start-tag has a similar statement), which made me more confused - because it has a heading "Tag omission in text/html", which makes it a bit complicated (including the fact that it is supposedly non-normative - and the real text should be somewhere else).

As far as I understand the idea is that you logically still have the omitted tags, but you can omit writing them under some conditions in the normal text-format (but not in the XML-format).

The simple solution is to write that if the documentation starts with `<html>` it means the entire documentation-string shall be one html-element. And then everything about end-tag follows from the html-specification.

**Comment by maltelenz** [comment]
> The simple solution is to write that if the documentation starts with `<html>` it means the entire documentation-string shall be one html-element.

Should we be careful about mentioning "html element"? That formulation could lead to the interpretation that the content can be a full HTML document with `<head>` and `<body>` tags, since that is usually what goes into a `<html>` element. Should we allow that? I haven't seen any such uses in libraries, but it would be much more powerful.

**Comment by HansOlsson** [comment]
A side-note: @maltelenz I believe you should apply to be member of MAP-Lang.

**Comment by henrikt-ma** [comment]
> > The simple solution is to write that if the documentation starts with `<html>` it means the entire documentation-string shall be one html-element.
> 
> Should we be careful about mentioning "html element"? That formulation could lead to the interpretation that the content can be a full HTML document with `<head>` and `<body>` tags, since that is usually what goes into a `<html>` element. Should we allow that? I haven't seen any such uses in libraries, but it would be much more powerful.

Yes. I'd like to see choice a choice between the following alternatives, and I'm afraid we shouldn't try allowing both:
- Full-blown `<html>` tag — follow relevant specification such as https://www.w3.org/TR/html52/semantics.html#the-html-element
- Just HTML body contents indicated by a leading `<html>` — doesn't follow any other relevant specification, and we might as well allow omission of the closing tag, since the opening `<html>` is just a Modelica specification marker to indicated that this is an `info` string providing HTML body contents.

**Comment by HansOlsson** [comment]
For the html-contents we also have #2395 - so I believe we can close this issue by improving the general description of html as in PR, and then handle the html-version-part for that one. (To keep closing issues one by one to move forward.)
