### ISSUE TITLE
Changes agreed and merged in #2416 no longer present on master

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#2597]
The changes agreed upon in #2416, which were incorporated in #2453, no longer exist on `master`.

I assume this was unintentional?

It looks like the changes were reverted by @HansOlsson in af4348584693f4772717e89deb6e1a8da22a57ba in some involved merge/revert sequence?

**Comment by HansOlsson** [comment]
> The changes agreed upon in #2416, which were incorporated in #2453, no longer exist on `master`.
> It looks like the changes were reverted by @HansOlsson in [af43485](https://github.com/modelica/ModelicaSpecification/commit/af4348584693f4772717e89deb6e1a8da22a57ba) in some involved merge/revert sequence?

Not simply merge/revert - but unintended and more complicated. I will look into it again.
