### ISSUE TITLE
Inconsistency in how Q-IDENTs are specified

### ISSUE THREAD

**Issue by tobias-gutzmann-modelon** [modelica/ModelicaSpecification#2612]
There's an inconsistency in the spec in how Q-IDENTs are specified.

lexicalstructure.tex (Section 2.3.1):
Q-IDENT = "'" { Q-CHAR | S-ESCAPE | """ } "'"

syntax.tex (Appendix B):
Q-IDENT = "'" ( Q-CHAR | S-ESCAPE ) { Q-CHAR | S-ESCAPE | """ } "'"

The former definition allows '' and '"' as Q-IDENTs, the latter does not.

My proposal is to allow '' and '"', I cannot think of a reason to forbid them as the enclosing single quotes are part of the identifier anyway.

Suggested fix:
- include quotation mark " in Q-CHAR
- Change both places to   Q-IDENT = "'" { Q-CHAR | S-ESCAPE } "'"
- (optional) S-ESCAPE and Q-CHAR could be joined as well, as S-ESCAPE is not used anywhere else, but it may be desirable to keep them separated anyway.

I found that this was already mentioned in https://github.com/modelica/ModelicaSpecification/issues/2408 but neither discussed nor resolved as part of that issue.

**Comment by HansOlsson** [comment]
Obviously `'"'` should be allowed.
It seems `"` as part of quoted identifier was introduced in Modelica 3.4 together with the rule that `\"` and `"` are the same as part of #1176.
And the lexical variant was introduced in Modelica 3.0; and I believe it is just sloppy copying that led it to allow the empty quoted identifier.

I thus agree that it is simplest to extend Q-CHAR with " and simplify the rules. Having S-ESCAPE separate makes sense to me.
Obviously both variants of the rule should be identical.
Allowing the empty quoted identifier is less clear, but we might as well allow it. It would make the grammar slightly simpler; and if people find it unclear the obvious solution is to not use it, similarly as not mixing `'1'`, `'I'`, `'l'`, `'0'`, `'O'`.

BTW: Dymola seems to support `''`

**Comment by henrikt-ma** [comment]
I agree that there doesn't seem to be a compelling reason why the identifiers `''` and `'"'` shouldn't be allowed.  I can see how things could get confusing in an environment where only quoted identifiers are used, so that the enclosing apostrophes don't have to be displayed in a GUI, but I hope no such environments exist.
