### ISSUE TITLE
Dialog annotation for replaceable classes

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#2617]
As a user, I want to control where the selection of replaceable classes ends up.

A natural attempt would be to use the `Dialog` annotation, as here in `P.M`:

```
package P
  type base = Real;
  type a = base(unit = "a");
  type b = base(unit = "b");

  model M
    replaceable type myType = base annotation(Dialog(group = "My configuration", tab = "My tab"));
    myType x = sin(time);
  end M;
end P;
```
but the `Dialog` annotation is only for `components and variables`:
https://github.com/modelica/ModelicaSpecification/blob/333231b7e8d59511d4af5c94b42260a1bbd167c2/chapters/annotations.tex#L1200-L1202

Not all pieces of the `Dialog` annotation makes sense for replaceable classes, but at least `group` and `tab` might.

**Comment by HansOlsson** [comment]
I believe it will be a good idea to add this.

Specifically I would say that `tab`, `group`, `enable`, `groupImage `make sense.
Whereas `showStartAttribute`, `colorSelector`, `loadSelector`, `saveSelector `, and `connectorSizing `does not.

(And it seems Dymola already supports this.)
