### ISSUE TITLE
HTML version is missing 0

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2619]
In the chapter 4.4.4, there is the following line saying "der(vd)=0":
https://github.com/modelica/ModelicaSpecification/blob/333231b7e8d59511d4af5c94b42260a1bbd167c2/chapters/classes.tex#L379

"0" appears in the source code (as above) and in the pdf version. But I am not seeing it when I open the HTML version in my browser:
![image](https://user-images.githubusercontent.com/20460714/87953882-98b3df80-ca79-11ea-8470-cb2f3584d00f.png)
https://specification.modelica.org/master/class-predefined-types-and-declarations.html#component-variability-prefixes-discrete-parameter-constant

The same is true for the 3.4 branch:
https://github.com/modelica/ModelicaSpecification/blob/828346ea217d72a1be3e351738943b0a7f476991/chapters/classes.tex#L368
![image](https://user-images.githubusercontent.com/20460714/87954057-d7e23080-ca79-11ea-8db8-e06ffd922c53.png)
https://specification.modelica.org/v3.4/Ch4.html#component-variability-prefixes-discrete-parameter-constant

I am using Google Chrome. Does anyone else have the same issue?

**Comment by HansOlsson** [comment]
I can confirm this issue, and I can see that the error occurs in the html itself. I also see another similar case.

**Comment by henrikt-ma** [comment]
I filed a LaTeXML bug for this: https://github.com/brucemiller/LaTeXML/issues/1312

**Comment by HansOlsson** [comment]
Corrected by upgrade to latexml 0.8.5.
