### ISSUE TITLE
Problem with subequations in generated HTML

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2629]
The page
https://specification.modelica.org/master/modelica-dae-representation.html contains the text " \cref@addtoresetequationparentequation"
and similarly: https://specification.modelica.org/master/derivation-of-stream-equations.html#eq:D2

Filed as:
https://github.com/brucemiller/LaTeXML/issues/1319

Ideally we shouldn't have to change anything, but rely on a new version of LaTeXML.
However, since there are only three sub-equations we could work around it.

**Comment by henrikt-ma** [comment]
Sure, I can split the equations and leave a comment pointing to the LaTeXML issue.  Should I?

**Comment by HansOlsson** [comment]
> Sure, I can split the equations and leave a comment pointing to the LaTeXML issue. Should I?

I was contemplating doing it myself as well, but I think it's best to just wait for now.

**Comment by henrikt-ma** [comment]
OK.

**Comment by HansOlsson** [comment]
Corrected by upgrade to latexml 0.8.5.
