### ISSUE TITLE
Does initial() have to be in the condition of the first when-clause?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2636]
This might seem silly, but with so many requests for clarification on the role of `initial()` for enabling when-clauses during initialization, I think we should really go to the bottom with this.  Does this when-statement initialize `x` to 3?
```
model ElsewhenInitial
  Integer x(start = 1);
equation
  when time > 1 then
    x = 2;
  elsewhen initial() then
    x = 3;
  end when;
end ElsewhenInitial;
```

A strict interpretation of 8.6 _Initialization, initial equation, and initial algorithm_ suggests that it doesn't, since the clause condition is neither in the form `when initial() then` nor `when {…, initial(), …} then`, but I believe the intention was to also allow the `elsewhen` forms?

**Comment by sjoelund** [comment]
Can you really transform the `elsewhen` into an initial equation though? Maybe since even if `startTime=2`, the first `when` will not trigger at the initial step?

**Comment by henrikt-ma** [comment]
Right, I wouldn't like the first clause to trigger no matter what `startTime` is.  I'd just like the first when-clause with condition `initial()` or `{…, initial(), …}` to be active during initialization.

**Comment by HansOlsson** [comment]
> Right, I wouldn't like the first clause to trigger no matter what `startTime` is. I'd just like the first when-clause with condition `initial()` or `{…, initial(), …}` to be active during initialization.

I agree that this seems like a good idea.

**Comment by sjoelund** [comment]
I guess there should be a limitation of at most one clause with `initial()` in it? There is no use to have a second `initial()` that can never trigger after all.

**Comment by HansOlsson** [comment]
> I guess there should be a limitation of at most one clause with `initial()` in it? There is no use to have a second `initial()` that can never trigger after all.

Yes.

**Comment by henrikt-ma** [comment]
> I guess there should be a limitation of at most one clause with `initial()` in it? There is no use to have a second `initial()` that can never trigger after all.

For me, it would be cleaner to just explain this in a piece of non-normative text.

**Comment by HansOlsson** [comment]
> > I guess there should be a limitation of at most one clause with `initial()` in it? There is no use to have a second `initial()` that can never trigger after all.
> 
> For me, it would be cleaner to just explain this in a piece of non-normative text.

You mean non-normative text saying it's formally allowed - but practically useless, since the second clause will not trigger. Yes, that would work as well - and closer to how we have handled similar cases.

**Comment by henrikt-ma** [comment]
> You mean non-normative text saying it's formally allowed - but practically useless, since the second clause will not trigger. Yes, that would work as well - and closer to how we have handled similar cases.

Exactly.
