### ISSUE TITLE
Making invalid model valid by redeclare?

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#2638]
Would you consider `PossibleOutputTypes.Example` a valid model?

```
package PossibleOutputTypes
  package BaseType
  end BaseType;

  package Rate
    extends BaseType;
    type TheType = Real(final quantity = "Rate", final unit = "1/s");
    connector TheOutput = Modelica.Blocks.Interfaces.RealOutput(unit = "1/s");
  end Rate;

  package Time
    extends BaseType;
    type TheType = Real(final quantity = "Time", final unit = "s");
    connector TheOutput = Modelica.Blocks.Interfaces.RealOutput(unit = "s");
  end Time;

  package RType
    extends BaseType;
    type TheType = Real(unit = "1");
    connector TheOutput = Modelica.Blocks.Interfaces.RealOutput(unit = "1");
  end RType;

  block ConstantInput
    replaceable package TypePackage = PossibleOutputTypes.BaseType constrainedby PossibleOutputTypes.BaseType;
    parameter TypePackage.TheType value = 0;
    TypePackage.TheOutput y;
  equation
    y = value;
  end ConstantInput;

  model Example
    ConstantInput constantInput1(value = 1, redeclare replaceable package TypePackage = RType);
    ConstantInput constantInput2(value = 2, redeclare replaceable package TypePackage = Time);
    ConstantInput constantInput3(value = 2, redeclare replaceable package TypePackage = Rate);
  end Example;
end PossibleOutputTypes;
```
If the redeclares of `TypePackage` are applied, the types for `TypePackage.TheType` and `TypePackage.TheOutput` in `ConstantInput` exist. This would be the argument for `Example` being valid.

However, `ConstantInput` as it is declared has broken lookups for these two types, which could be the argument for `Example` being invalid by using it.

**Comment by eshmoylova** [comment]
I would consider the `Example` model legal. I think for clarity it would be good to declare the `BaseType` package as `partial`. I think it falls under [5.6.1 of the specification](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#instantiation):
> An implementation may delay and/or omit building parts of these trees, which means that the different steps can be interleaved. If an error occurs in a part of the tree that is not used for the model to be instantiated the corresponding diagnostics can be omitted (or be given). However, errors that should only be reported in a simulation model must be omitted there, since they are not part of the simulation model.

**Comment by HansOlsson** [comment]
To me `ConstantInput `is illegal, and thus `Example `as well.
However, @eshmoylova brings up an interesting point in that the error for `Example `_can be_ omitted (but it is not necessary to omit it as it's not an error restricted to 'simulation model').

**Comment by HansOlsson** [comment]
So to summarize my new position, which is similar to the one @eshmoylova has

- PossibleOutputTypes.ConstantInput is illegal; and should give an error.
- PossibleOutputTypes.Example uses the illegal model, but is not illegal in itself.
- The illegal parts can be omitted during instantiation of PossibleOutputTypes.Example and thus no diagnostics is needed for PossibleOutputTypes.Example.

**Comment by HansOlsson** [comment]
I would believe that this answers the question, and we can close this.

**Comment by maltelenz** [comment]
Thank you for the insight. Closing.
