### ISSUE TITLE
Stray extra 'q' in subscripts of figure 15.1

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2641]
In figure 15.1 at the beginning of section 15.2 _Stream Operator inStream and Connection Equations_, the labels on the outside connector symbols have a 'q' in the subscripts before the index.  I can't see what that letter corresponds to in the text; should it be there at all?

**Comment by HansOlsson** [comment]
I cannot see that the "q," should be there either. It was introduced in version 3.1 and I cannot see any explanation for it any underlying document. (Powerpoint etc.)

**Comment by henrikt-ma** [comment]
OK, then I'll remove it together with the other work on figures in #2609.
