### ISSUE TITLE
Unexpected mention of Modelica.Math in chapter 'Operators and Expressions'

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2662]
It is unexpected that chapter _Operators and Expressions_ mentions some `Modelica.Math` functions in section 3.7.1.2 _Built-in Mathematical Functions and External Built-in Functions_:
> They are also available as external built-in functions in the `Modelica.Math` library.

At least, the part related to the MSL should be removed from the section title, as the definition of these functions in the Modelica specification is really something separate from the external functions of the MSL.

The connection to the MSL still has some relevance, but doesn't belong to the normative parts of the Modelica specification.

**Comment by HansOlsson** [comment]
> It is unexpected that chapter _Operators and Expressions_ mentions some `Modelica.Math` functions in section 3.7.1.2 _Built-in Mathematical Functions and External Built-in Functions_:
> 
> > They are also available as external built-in functions in the `Modelica.Math` library.
> 
> At least, the part related to the MSL should be removed from the section title, as the definition of these functions in the Modelica specification is really something separate from the external functions of the MSL.

I partially disagree. I agree that the existence in Modelica.Math isn't important (and shouldn't be normative). 

However, these functions in MSL are declared as `external "builtin"` (not `external "C"`), and the functions that a tool must recognize as a builtin-function is something that should be part of the specification. That is what the section heading is discussing.

> The connection to the MSL still has some relevance, but doesn't belong to the normative parts of the Modelica specification.

Agreed.

**Comment by henrikt-ma** [comment]
> However, these functions in MSL are declared as `external "builtin"` (not `external "C"`), and the functions that a tool must recognize as a builtin-function is something that should be part of the specification. That is what the section heading is discussing.

Right, I missed that.  To some degree, I blame this on the use of natural language _built-in_ here, which just looks meaningless to me considering that any function described in the specification could be considered built in.  Don't we need a more clear way of pointing out the functions that can be called as `external "builtin"`?  How about simply naming the section _Mathematical functions_, and add to the normative presentation of the functions in this sections that they can be called via `external "builtin"`?

A search for `external "builtin"` in MSL reveals that these are the only functions currently called this way.  How about adding a link to this section from the place where `external "builtin"` is described?

**Comment by henrikt-ma** [comment]
By the way, what's the reason we have `external "builtin"` at all?  Doesn't it deserve an explanation where it is defined in the specification?

For example, why wouldn't this be a just as good implementation?
```
package Modelica
  package Math
    function sin
      input Real x;
      output Real y = .sin(x);
    end sin;
  end Math;
end Modelica;
```

Was it because one couldn't say `.sin` at the time `external "builtin"` was introduced?

**Comment by eshmoylova** [comment]
> How about simply naming the section _Mathematical functions_, and add to the normative presentation of the functions in this sections that they can be called via `external "builtin"`?

I think it is important to specify in the name what makes these mathematical functions different from mathematical functions in other (sub)sections. 'abs', 'sqrt', 'ceil', 'floor', etc,  are all mathematical functions too. But they are in separate tables. They are also built-in. So distinction as far as I can see is that the function in the section 3.7.1.2 have external builtin functions.

As far as I understand from reading the specification about "builtin" (section 12.9), it is supposed to be for functions that are Modelica builtin and that are, typically, in a standard C-library. But it is not required that a tool uses the C-library version and may choose a different one. So in a way they are builtin for Modelica and C.

**Comment by HansOlsson** [comment]
Minimal change of removing the normative text about Modelica.Math:

Replace:

They are also available as external built-in functions in the Modelica.Math library

by:

These names are also recognized as external "builtin" functions.
Non-normative: This allows them to be declared in the Modelica.Math library.

**Comment by henrikt-ma** [comment]
To me, the important question is why they need to be recognized as `external "builtin"`, unless we really intend to get rid of them in the "normal" Modelica language.

**Comment by HansOlsson** [comment]
Agreement on 
> "These names are also recognized as external "builtin" functions.
> Non-normative: This allows them to be declared in the Modelica.Math library."

Poll for deprecating external "builtin" for these functions:
* Keep as now. Hans, Axel, Gerd
* Deprecate. Stephan, Filippo, Henrik, Markus, Quentin
Abstain: Christoff, Leo, Martin
Deprecate for now.
