### ISSUE TITLE
final or not final?

### ISSUE THREAD

**Issue by d-hedberg** [modelica/ModelicaSpecification#2676]
In `MyPackage.MyModel` below, is the modification of `a(x=4)` legal (considering that the model A has a `final` prefix to it)?

```
package MyPackage
  model B
    parameter Real x;
  end B;

  final model A = B(x = 3); // Model A is made final here.

  model MyModel
    A a(x=4); // Legal?
  end MyModel;
end MyPackage;
```

**Comment by HansOlsson** [comment]
I would prefer it is legal, and think that it is easier to understand for replaceable.
The reason is that I would assume some people use 'final redeclare' to say that the class is choice, but still works as a normal class.

I would actually see three possibilities:

1. It's only the choice of class `A` that is `final`; this prevents some modifications that are a bit odd.
2. The entire class `A` is `final`, so even for 'final model A=B;' then `MyModel` would be illegal.
3. Only the modified elements "inherit" `final`; the example suggests this.

I prefer 1, but https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#final-element-modification-prevention indicates 2.

**Comment by henrikt-ma** [comment]
Alternative 2 corresponds to my intuition about `final`, which I suppose I got from the cited 7.2.6 _Final Element Modification Prevention_ one way or another.

**Comment by d-hedberg** [comment]
I'd have to agree that alternative 2 is the only alternative that makes sense to me. I'd have a really hard time trying to convince Modelica users that if they declare a class `final `, parts of it can still be modified. That's confusing, and I'm pretty sure that the follow-up question would be: "How do I **really** make the class final then?".

**Comment by HansOlsson** [comment]
> I'd have to agree that alternative 2 is the only alternative that makes sense to me. I'd have a really hard time trying to convince Modelica users that if they declare a class `final `, parts of it can still be modified. That's confusing, and I'm pretty sure that the follow-up question would be: "How do I **really** make the class final then?".

Agreed on second thought, and thus it seems this is just a question that has been answered and can be closed.
(If people just want to prohibit redeclare the solution is to use "redeclare" without final.)

**Comment by henrikt-ma** [comment]
> Agreed on second thought, and thus it seems this is just a question that has been answered and can be closed.
> (If people just want to prohibit redeclare the solution is to use "redeclare" without final.)

Perhaps we should still clarify that a `final` element doesn't have to be a component, and give an example of what it means for a type to be final?

**Comment by HansOlsson** [comment]
However, there are a number of modifiers for `final `classes (mostly/entirely `final redeclare`, of course) in MSL.

One example is in Modelica.Fluid.Examples.HeatExchanger.BaseClasses.BasicHX:
```
model BasicHX "Simple heat exchanger model"
 ...
Pipes.DynamicPipe pipe_1(
    redeclare final package Medium = Medium_1,
    ...
    redeclare final model HeatTransfer = HeatTransfer_1,
    ...
    redeclare final model FlowModel = FlowModel_1,

```
with Modelica.Fluid.Pipes.DynamicPipe:
```
model DynamicPipe "Dynamic pipe model with storage of mass and energy"
   ...
   HeatTransfer heatTransfer(
    redeclare final package Medium = Medium,
    final n=n,
```
(and similarly for the inherited `FlowModel`).

**Comment by d-hedberg** [comment]
Are you saying that the final prefix for a class if occurring in a modification should be interpreted differently? That it should be allowed to change a parameter inside a redeclared final class? See example below.

```
package MyPackage
  model B
  end B;

  model C
    parameter Real x;
  end C;

  replaceable model A = B constrainedby B;
end MyPackage;

model MyModel
  package P = MyPackage(redeclare final model A = MyPackage.C(x=3)); // Model A is made final here.
  P.A a(x=4); // Legal?
end MyModel;
```

**Comment by HansOlsson** [comment]
> Are you saying that the final prefix for a class if occurring in a modification should be interpreted differently? 

No, it was just an observation that some had that idea - and we need to correct MSL to be consistent with this.
I'll make a PR.

**Comment by HansOlsson** [comment]
> > Agreed on second thought, and thus it seems this is just a question that has been answered and can be closed.
> > (If people just want to prohibit redeclare the solution is to use "redeclare" without final.)
> 
> Perhaps we should still clarify that a `final` element doesn't have to be a component, and give an example of what it means for a type to be final?

Clarifying that and adding an example makes sense.
