### ISSUE TITLE
Clarification on the definition of choicesAllMatching

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2693]
@HansOlsson, please consider this test package. 
```
package A
  model B
    package C
      extends Base;
      constant Real q = 10;
    end C;
  end B;

  partial package Base
    function f
      input Real x;
      output Real y;
    algorithm 
      y := 2*x;
    end f;
  end Base;

  partial package BaseAdvanced
    extends Base;
    constant Real p = 2;
  end BaseAdvanced;

  package Regular
    extends Base;
    constant Real w = 0;
  end Regular;

  model M
    replaceable package P = Base annotation(choicesAllMatching = true);
    Real x = P.f(time);
  end M;

  model S1
    A.M m annotation (
      Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end S1;

  model S2
    A.M m(redeclare package P = A.B.C) annotation (
      Placement(visible = true, transformation(origin = {0, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  end S2;
end A;
```

According to [Section 7.3.4](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#annotation-choices-for-suggested-redeclarations-and-modifications) of the Specification, the choices menu of `M.P` should show "_the names of all classes that are either directly or indirectly derived by inheritance from the constraining class of the declaration_".

Since the constraining class of `A.M.P` is `A.Base`, according to that definition of `choicesAllMatching` I would expect to see

1. `A.Base`
2. `A.BaseAdvanced`
3. `A.B.C`, which can be looked up according to [Section 5.3.2](https://specification.modelica.org/v3.4/Ch5.html#composite-name-lookup) of the Specification, and that in fact works just fine in `A.S2` when using Dymola 2021
4. `A.Regular`

However, if I open `A.S1` with Dymola 2021 and double-click on `m`, I only see the fourth class in the replaceable class drop-down menu, not the other three ones.

With reference to `Modelica.Media` replaceable packages, Dymola's behaviour indeed makes a lot of sense to me: in the drop-down menu I don't want to see any partial package (which won't work), nor I want to use media models that are defined inside some components of `Modelica.Fluid`, because using them is probably not such a good idea, even though it is legal according to the lookup rules.

It seems to me that the choices shown by Dymola (which I am actually fine with) correspond to this description: "_the names of all classes A.B...X.Z that are either directly or indirectly derived by inheritance from the constraining class of the declaration, **such that all classes A to X are non-partial packages and Z is non-partial**_"

Should we update Section 7.3.4 along these lines?

**Comment by HansOlsson** [comment]
I agree that we should update it, but would prefer to not specify it too much.

There are situations when partial classes (e.g.,  building a template model and switching to PartialMixtureMedium) or local classes may make sense.

Proposal, something like:
the names of all classes A.B...X.Z that are either directly or indirectly derived by inheritance from the constraining class of the declaration, possibly excluding choices that are not fully useable.
Non-normative: For instance partial classes and classes in partial classes.

**Comment by eshmoylova** [comment]
I feel like @HansOlsson's proposal doesn't make it very clear what is meant by useable and the non-normative text does not mention the case of A.B.C. Also as a developer I wouldn't know how to interpret "possibly excluding"? It would create inconsistency among tools and discontent among users. I would prefer @casella's proposal.

**Comment by HansOlsson** [comment]
Some discussion about other possibilities, like SimulationX having the possibility to use structural instead.

Conclusion something like:

at least it should be possible to ... the names of all classes A.B...X.Z that are either directly or indirectly derived by inheritance from the constraining class of the declaration, such that all classes A to X are non-partial packages and Z is non-partial

(Note: Not saying 'default' as that would overspecify tools.)
Agreement.
