### ISSUE TITLE
Typo/language in discrete variable initialization

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#2699]
https://github.com/modelica/ModelicaSpecification/blob/de55f8b69389d5699c2a0e82e652095cbe7211fe/chapters/equations.tex#L801

This should probably say either of these?

> For a discrete-time variable vd

> For discrete-time variables vd

**Comment by henrikt-ma** [comment]
I thought this was already fixed.

**Comment by henrikt-ma** [comment]
I gave up searching.  Fixing it right away was faster.
