### ISSUE TITLE
URIs in Documentation annotation

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#2701]
Section 13.5 has:

> In  order  to  reference  external  resources  from  documentation  (such  as  links  and  images  in  html-text) and/or to reference images in the Bitmap annotation (see section 18.6.5.6).  URIs should be used...

I would like clarification which of these is true:
A: It is restricted to the full-blown URI (always starting with the _scheme_ like `modelica`, `file`, or similar)

B: URI is used in the wider sense of an _URI reference_, which can be either the thing that starts with a _scheme_ (`modelica`, `file`, ...), or it is a _relative reference_ (and if so, the natural base URI it is relative to would presumably be the (file) location of the class?)

In particular, with a file structure like this:
```
MyPackage/
-- package.mo
-- image.png
```
Is this expected to work?
```
package MyPackage
  annotation(Documentation(info = "<html>
<img src=\"./image.png\"/>
</html>"));
end MyPackage;
```

**Comment by henrikt-ma** [comment]
This is highly related to the MCP on _Generalized Modelica URIs_, #2663.  I would therefore suggest that we are very careful here to not build more dependencies than necessary on the current Modelica URIs.

That said, I like the general spirit of option B above (to allow relative references), but I don't think that we should give a base URI that refers to a file location.  To illustrate, the base URI in the example above would then be something like _modelica://MyPackage/package.mo_, but I don't think we want to make assumptions about how a package is stored in a file system when defining the base URI.

I find it more realistic to make the base URI just point to the current class.  That is, for the a `Documentation` annotation in class `A.B.C`, the base URI would be _modelica://A.B.C/_.

(To show in some more detail why I think it might be a good to wait for the new Modelica URIs here, this is how things  _might_ change if the MCP gets accepted.  The base URI might change into _modelica:/A/B/C/_, and the relative reference might change into _?resource=image.png_, as the generalized Modelica URIs have many more uses than just referencing external resources.)

**Comment by maltelenz** [comment]
Even if a new kind of relative reference is introduced with the MCP, it could be useful to allow something like option B above. It uses a format users will be used to and expect when writing HTML, which does not seem to necessarily be the case with the MCP.

**Comment by henrikt-ma** [comment]
> Even if a new kind of relative reference is introduced with the MCP, it could be useful to allow something like option B above. It uses a format users will be used to and expect when writing HTML, which does not seem to necessarily be the case with the MCP.

I suppose it would be possible to get this behavior by introducing another scheme, say _documentation_, that would essentially restore the behavior of the current Modelica URIs, only useable to reference external resources. Changing the base URI to _documentation:/A.B.C/_ would then make linking to images more convenient, but come at the very high price of not being able to use relative references for other things, such as linking to figures belonging to the current model.

**Comment by HansOlsson** [comment]
> Section 13.5 has:
> 
> > In  order  to  reference  external  resources  from  documentation  (such  as  links  and  images  in  html-text) and/or to reference images in the Bitmap annotation (see section 18.6.5.6).  URIs should be used...
> 
> I would like clarification which of these is true:
> A: It is restricted to the full-blown URI (always starting with the _scheme_ like `modelica`, `file`, or similar)
> 
> B: URI is used in the wider sense of an _URI reference_, which can be either the thing that starts with a _scheme_ (`modelica`, `file`, ...), or it is a _relative reference_ (and if so, the natural base URI it is relative to would presumably be the (file) location of the class?)

No to B for two reasons:

- A relative URI reference is relative to another URI reference; and there is no natural file-based URI reference to start from. (We start from a Modelica class - not a file; and thus presumably a modelica URI reference.)
- The modelica-URIs are designed to avoid file-based references, as not all store Modelica classes on files. (The early design treated data-bases as sort of files; that doesn't work at all.) Additionally the early file-relative references didn't work well in practice - the current modelica-URI were designed to avoid repeating those mistakes.

Leaving only A.

**Comment by maltelenz** [comment]
>  * A relative URI reference is relative to another URI reference; and there is no natural file-based URI reference to start from. (We start from a Modelica class - not a file; and thus presumably a modelica URI reference.)

I should have said "and if so, the natural base URI it is relative to would presumably be the modelica URI for the class". I just mentally skipped the step of resolving the modelica URI to, in the world I'm exposed to, the natural `file` reference.
So, let's add:

C: URI is used in the wider sense of an URI reference, which can be either the thing that starts with a scheme (modelica, file, ...), or it is a relative reference (with the natural base URI it is relative to being `modelica://TheClassWhereinItIsContained/`)

**Comment by henrikt-ma** [comment]
> C: URI is used in the wider sense of an URI reference, which can be either the thing that starts with a scheme (modelica, file, ...), or it is a relative reference (with the natural base URI it is relative to being `modelica://TheClassWhereinItIsContained/`)

Even better: make the base URI point to the _info_ view.  While the difference may not be significant with the current Modelica URIs, a formulation that points to the _info_ view would work better if we get improved Modelica URIs one day where selection of view doesn't conflict with the use of fragment specifier to point to a specific element in the documentation.

**Comment by HansOlsson** [comment]
Currently expect full-blown - Hans to formulate PR, revisit as part of MCP-0037.
