### ISSUE TITLE
Recommended restriction for class extending ExternalObject

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2705]
In #1719, it was mentioned that we might consider deprecating the use of class restriction `class`, but this is the restriction used by the only example of a class extending from `ExternalObject`.  Is there anything preventing use of restrictions such as `model` or `block`?

It seems like an unnecessary degree of freedom to have more than one specialization to choose from, and it would be good if we could at least state a recommendation for which one to use.

**Comment by HansOlsson** [comment]
Currently the recommendation is `class`. Having an externalObject as either block or model would be odd to, but if we had to choose I would say 'model' as it's the most restrictive.

**Comment by henrikt-ma** [comment]
Is this recommendation expressed more clearly than by means of usage the one and only example?

**Comment by HansOlsson** [comment]
We can in the itemized list add:

- An external object class shall be of the specialized type class \nonnormative{This is the only use of class}.

**Comment by henrikt-ma** [comment]
> We can in the itemized list add:
> 
> * An external object class shall be of the specialized type class \nonnormative{This is the only use of class}.

Fine by me (except that we write non-normative text as separate paragraphs nowadays).  While it makes you wonder why we have both `class` and `ExternalObject`, that's of course a subject for possible cleanup that we can save for the future.

If we make this change, however, we need to be aware that it's a backward incompatible change, since `class` wasn't the only option in the past.

**Comment by HansOlsson** [comment]
Agreement.
