### ISSUE TITLE
Clarification on conditional components

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2715]
Consider the following MWE
```
package TestConditional
  model A
    parameter Real p;
  end A;
  
  model B
    A a if n > 0;
    parameter Integer n;
  end B;
  
  model C
    B b(n = 0, a(p = 3));
  end C;
end TestConditional;
```
According to what myself and @AndreaBartolini understand from [Section 5.6.2](https://specification.modelica.org/v3.4/Ch5.html#generation-of-the-flat-equation-system), model `C` is legal, because the component `C.b` is first flattened, modifications and all, and later removed. In fact, both Dymola and OpenModelica accept it.

Can you confirm that?

**Comment by perost** [comment]
From [section 4.4.5](https://specification.modelica.org/v3.4/Ch4.html#component-declarations):
>A component declared with a condition-attribute can only be modified and/or used in connections

So yes, that's legal.

**Comment by HansOlsson** [comment]
> From [section 4.4.5](https://specification.modelica.org/v3.4/Ch4.html#component-declarations):
> 
> > A component declared with a condition-attribute can only be modified and/or used in connections
> 
> So yes, that's legal.

I agree, and I don't see that there's any remaining issue.
