### ISSUE TITLE
Upgrade to LaTeXML 0.8.5

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2723]
LaTeXML released version 0.8.5 a few days ago, and we should start using it as soon as possible, so that we have a chance to detect and work around any new issues well in advance of the upcoming release of MLS 3.5.

**Comment by henrikt-ma** [comment]
I haven't checked availability in package managers yet, but as far as I can tell, LaTeXML is really easy to build form source.

**Comment by sjoelund** [comment]
It's available in CPAN, which is how we installed the previous version. It will take a while, but I will update a docker image.

**Comment by HansOlsson** [comment]
> LaTeXML released version 0.8.5 a few days ago, and we should start using it as soon as possible, so that we have a chance to detect and work around any new issues well in advance of the upcoming release of MLS 3.5.

Good idea. I thought I had checked this earlier in the week and it wasn't available then; and I have been busy since.
Looking more closely the release was made two days ago (2020-11-17 I believe) and the milestone closed yesterday (2020-11-18).

**Comment by henrikt-ma** [comment]
> Good idea. I thought I had checked this earlier in the week and it wasn't available then; and I have been busy since.
> Looking more closely the release was made two days ago (2020-11-17 I believe) and the milestone closed yesterday (2020-11-18).

I just stumbled upon it when looking for the date of the 0.8.4 release, and was pleasantly surprised when 0.8.5 had been released just 3 hours earlier.
