### ISSUE TITLE
public variable in function without input/output

### ISSUE THREAD

**Issue by thorade** [modelica/ModelicaSpecification#2730]
Dymola check complains about this code:
```modelica
function myFun1
  input Real x;
  output Real y;
  Real z = 4;
algorithm 
  y := x*z;
end myFun1;
```
but not about this:
```modelica
function myFun2
  input Real x;
  output Real y;
  constant Real z = 4;
algorithm 
  y := x*z;
end myFun2;
```
and also not about this:
```modelica
function myFun2
  input Real x;
  output Real y;
  parameter Real z = 4;
algorithm 
  y := x*z;
end myFun2;
```

Is it allowed to have any variable without input/output in the public section? Why would it be allowed if variability is reduced to constant or parameter? For another discussion about parameters in functions, see #1594.

**Comment by henrikt-ma** [comment]
While not crystal clear, this restriction from [12.2](https://specification.modelica.org/master/functions.html#function-as-a-specialized-class) _seems_ to imply that all of the functions above are illegal:
> Each input formal parameter of the function must be prefixed by the keyword `input`, and each result formal parameter by the keyword `output`. All public variables are formal parameters.

I'd find it more clear if it was written like this instead:
> … Only input and output formal parameters are allowed in the function's public variable section.

**Comment by qlambert-pro** [comment]
The implication of the beginning of section 12.4.4 leads me to the same conclusion as Henrik.
> Components in a function can be divided into three groups:
>   - Public components which are input formal parameters.
>   - Public components which are output formal parameters.
>   - Protected components which are local variables, parameters, or constants.

**Comment by henrikt-ma** [comment]
The following statement in [12.9](https://specification.modelica.org/master/functions.html#external-function-interface) also confirms the current intention:
> Components in the public part of an external function declaration shall be declared either as `input` or `output`.
> [This is just as for any other function.  The components in the protected part allow local variables for temporary storage to be declared.]

**Comment by HansOlsson** [comment]
Function public components must be input or output, check MSL.

Agreement.

**Comment by henrikt-ma** [comment]
This wasn't only a tool issue; had the could actually also have been more clear, see https://github.com/modelica/ModelicaSpecification/issues/2730#issuecomment-731843984.  Should I prepare a PR?

**Comment by HansOlsson** [comment]
> This wasn't only a tool issue; had the could actually also have been more clear, see [#2730 (comment)](https://github.com/modelica/ModelicaSpecification/issues/2730#issuecomment-731843984). Should I prepare a PR?

I prepared one.
