### ISSUE TITLE
Array as index and assignment

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#2732]
Does the following have a semantics:
```
v[{1,1,1}] := {1,2,3};
```

I suspect it  should be equivalent to:
```
v[1]:=3;
```
If it is specified somewhere we should probably add a link in Section 10.6.1.

**Comment by qlambert-pro** [comment]
It is specified in Section 10.5.
I suggest we add a link to that section in 10.6.1 and 11.2.1.

**Comment by HansOlsson** [comment]
Makes sense.
