### ISSUE TITLE
Figure 9.2 should not include Adobe Acrobat window elements

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2733]
Figure 9.2 in [Section 9.4.3](https://specification.modelica.org/v3.4/Ch9.html#examples-of-overconstrained-connection-graphs) of the Modelica 3.5 draft specification shows an example of connection graph. I guess the idea was to get the picture as a bitmap from earlier specifications PDF. This is fine for me, as long as the resolution is adequate and only a cropped image of the graph is included. 

The currently available html version of the specification shows the entire window of the Adobe Acrobat tool, that was used to capture the image. This is kind of weird and probably inappropriate from an IP point of view - why should we implicitly endorse Adobe products in the Modelica Specification?

**Comment by sjoelund** [comment]
Yeah, it would make more sense to open the PDF in inkscape and save only that picture as SVG and convert it to PDF. Actually, it only takes a minute so I'll attach it :)

[Fig9.2.pdf](https://github.com/modelica/ModelicaSpecification/files/5589763/Fig9.2.pdf)

**Comment by sjoelund** [comment]
Actually, it is a file called overdetermined.pdf so why was it not added to the spec instead of a screenshot of it? It's an extra step that reduces quality.

**Comment by sjoelund** [comment]
And it's not present in the 3.5 draft, only the 3.4 version

**Comment by HansOlsson** [comment]
> And it's not present in the 3.5 draft, only the 3.4 version

I also noticed that, and thus removed the milestone.

**Comment by HansOlsson** [comment]
> Actually, it is a file called overdetermined.pdf so why was it not added to the spec instead of a screenshot of it? It's an extra step that reduces quality.

For Modelica 3.4 I didn't want to rely on embedded pdf for the html-variant - so I generated both pdf and png and messed around with priorities so that pdf-file used pdf and html used png. 
That has been improved on master (and most images regenerated I believe) - but I see no need to do it for the maintenance version.
