### ISSUE TITLE
Array constructor with several iterators are ambiguous

### ISSUE THREAD

**Issue by perost** [modelica/ModelicaSpecification#2749]
The specification says in [section 10.4.1.2](https://specification.modelica.org/master/arrays.html#array-constructor-with-several-iterators) that array constructors with several iterators can be expanded by "replacing each ’,’ by ’} for’ and prepending the array constructor with a ’{’". Then it shows an example:
```Modelica
Real hilb[:,:]= { 1/(i+j-1) for  i in 1:n, j in 1:n};
Real hilb2[:,:]={{ 1/(i+j-1) for  j in 1:n} for i in 1:n}; 
```
However, doing what the text says on `hilb` would produce `{{ 1/(i+j-1) for  i in 1:n} for j in 1:n}`, while in `hilb2` the order of the iterators has also been reversed. So the text and the example does not agree in this case.

**Comment by HansOlsson** [comment]
As far as I can see:

- The example is incorrect; and has been that way since Modelica 2.1.
- It's not a good example as the two variants give the same result even with this error.

A simple form of a Toeplitz matrix avoid the latter:
```
   Real toeplitz[:,:]={i-j for i in 1:n, j in 1:n];
   Real toeplitz2[:,:]={i-j for i in 1:n} for j in 1:n]
```

**Comment by perost** [comment]
Yes, it seems both OpenModelica and Dymola follows the text rather than the example in this case. And I agree that the example you suggest is better.

**Comment by mahge** [comment]
It might also be a good idea to pick a non-square matrix as an example. Then specify the expected dimensions after construction.
