### ISSUE TITLE
Add two-dimensional example for scalar function to 12.4.6 Scalar Functions Applied to Array Arguments

### ISSUE THREAD

**Issue by AnHeuermann** [modelica/ModelicaSpecification#2751]
The example using `atan` in [12.4.6 Scalar Functions Applied to Array Arguments](https://specification.modelica.org/master/functions.html#scalar-functions-applied-to-array-arguments) is wrong and https://github.com/modelica/ModelicaSpecification/pull/2750 fixes this.
[atan](https://build.openmodelica.org/Documentation/Modelica.Math.atan.html) is only accepting one argument, it should probably be [atan2](https://build.openmodelica.org/Documentation/Modelica.Math.atan2.html) for that example which accepts two arguments.

But can an example with a multi-dimensional array be added as well?
I hope I understood [12.4.6 Scalar Functions Applied to Array Arguments](https://specification.modelica.org/master/functions.html#scalar-functions-applied-to-array-arguments) correct and the following example is correct:
```
cos({{a,b,c},{d,e,f}}) = {{cos(a), cos(b), cos(c)}, {cos(d), cos(e), cos(f)}}
```

**Comment by HansOlsson** [comment]
We already have a matrix example, and since a matrix is the same as an array of arrays - I don't see how this adds anything.
Having an array of matrices example would add something, but it doesn't seem natural.

**Comment by AnHeuermann** [comment]
Oh, you are correct, my example is more or less the same as
```
sin([1,2;3,4]) = [sin({1,2}); sin({3,4})]
  = [sin(1), sin(2); sin(3), sin(4)]
```
