### ISSUE TITLE
impure function input prefix not present in grammar

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#2756]
This says that a function formal parameter can be marked as `impure`:
https://github.com/modelica/ModelicaSpecification/blob/fffa303febe088b350fba3eee96bcb3f362d05c1/chapters/functions.tex#L326-L329

I'm assuming this tries to say something like this is OK?
```
impure function Fun
  impure input Otherfun f;
  input Real u;
  output Real y;
algorithm
  y := f(u);
end Fun;
```

I don't see where this fits into the grammar, since the only occurrence of `impure` in the grammar seems to be in the `class-prefixes`?

**Comment by HansOlsson** [comment]
Good point. One can write:
```
impure function Fun
  input Otherfun f;
  input Real u;
  output Real y;
algorithm
  y := f(u);
end Fun;
partial impure function Otherfun
   input Real u;
  output Real y;
end Otherfun;
```
It sort of matches the description, but just "sort of". However, it is legal - and I would expect that if the partial function is impure so should the passed functions.

**Comment by maltelenz** [comment]
That sounds like a possible different way to encode the information the linked text is trying to establish.

The situation you exemplify should probably be clarified (explicitly say that if the partial function is impure, so should the passed functions, and the requirements that puts on the declaration of purity of `Fun` in your example).

If we have that, maybe the prefix I assumed from the current text is unnecessary? Has anyone actually implemented these things, or could we get away with just the partial function impurity you exemplify? It seems pretty clean to me (but admittedly, I have little practical experience with pure/impure functions).

**Comment by HansOlsson** [comment]
Proposal:

As indicated above we could replace the two first sentences by:

It is possible to have a function declared as \lstinline!impure! as a function formal parameter. 
Only if the function formal parameter is declared as \lstinline!impure!, it is allowed to pass an \lstinline!impure! function to it.

The other option would be to change the grammar, but I'm not sure exactly how - and I feel that it might cause confusion as function formal parameters are syntactically similar to non-function formal parameters, and thus impure might appear in odd places.

**Comment by eshmoylova** [comment]
The example above raises a question for me how impure functions are inherited. If the base function is impure and the derived function declaration does not include "impure" explicitly what is the result?

**Comment by HansOlsson** [comment]
> The example above raises a question for me how impure functions are inherited. If the base function is impure and the derived function declaration does not include "impure" explicitly what is the result?

I would analyze this as two parts:

- Short function definitions. To me they have to inherit impure since `function foo=bar` shouldn't create an impure function `foo `from an impure function `bar`.
- Normal inheritance. But since you cannot have multiple algorithms in a function the inheritance either adds nothing of importance, or the original impure function was just an interface without algorithm. If you specify `impure `in an interface assumedly the function implementing it should be impure.

I would thus propose that they inherit `impure`. 
The other option would be that they have to declared as `impure`, but that seems like requiring users to write more for no good reason.

**Comment by maltelenz** [comment]
Inheriting `impure` seems reasonable to me as well.

The followup question becomes, are you allowed to make an `impure` function `pure` by extending it with the `pure` keyword?

**Comment by henrikt-ma** [comment]
> Inheriting `impure` seems reasonable to me as well.
> 
> The followup question becomes, are you allowed to make an `impure` function `pure` by extending it with the `pure` keyword?

I'd prefer having `pure(…)` as the one and only way to bypass the purity checks.

**Comment by henrikt-ma** [comment]
> * Short function definitions. To me they have to inherit impure since `function foo=bar` shouldn't create an impure function `foo `from an impure function `bar`.

Did you really write what you meant?  (To say "shouldn't create a pure function" would sound more sensible to me.)

**Comment by henrikt-ma** [comment]
> The other option would be that they have to declared as `impure`, but that seems like requiring users to write more for no good reason.

It wouldn't be without good reason: it lets users of the functions see that the function is impure without having to go through its chain of ancestors.

**Comment by HansOlsson** [comment]
> > * Short function definitions. To me they have to inherit impure since `function foo=bar` shouldn't create an impure function `foo `from an impure function `bar`.
> 
> Did you really write what you meant? (To say "shouldn't create a pure function" would sound more sensible to me.)

Oops. Yes, I mean that.

**Comment by HansOlsson** [comment]
> > The other option would be that they have to declared as `impure`, but that seems like requiring users to write more for no good reason.
> 
> It wouldn't be without good reason: it lets users of the functions see that the function is impure without having to go through its chain of ancestors.

True, so it makes sense that it is allowed (and pure inheriting from impure should be illegal).

But if impure is missing it should at least be inherited for short classes, and thus a non-short function definition inheriting from impure without specifying impure could:
* Illegal
* Legal and implicitly impure.

**Comment by HansOlsson** [comment]
Do off-line:
* Not legal to pass impure function as function argument, remove rest
* Proposal above.
And extend-part.
Dead-line this week.

**Comment by HansOlsson** [comment]
The poll will be in two parts, and run for one week starting at 10.00 CET tomorrow. Preferably react to both.
If there is anything unclear add comments etc. (Preferably before the poll starts so it can be clarified before.)

Proposal A ( +1 if ok, -1 if not):
If a function is declared as \lstinline!impure! any function extending from it shall be declared as \lstinline!impure!.

(I did as we discussed consider having this implicit etc, but in the end I realized that implicit was primarily important for redeclarations of short impure function and that is esoteric enough that we don't need something special for it.)

**Comment by HansOlsson** [comment]
Current text:

It is possible to mark a function formal parameter as \lstinline!impure!. 
Only if the function formal parameter is marked \lstinline!impure!, it is allowed to pass an \lstinline!impure! function to it. 
A function having a formal function parameter marked \lstinline!impure! must be marked \lstinline!pure! or \lstinline!impure!. 

Proposal B1 (Rocket): (Retain current functionality.)
Replace current text in spec with:

Only if the function formal parameter is \lstinline!impure!, it is allowed to pass an \lstinline!impure! function to it. 
A function having a formal function parameter that is \lstinline!impure! must be marked \lstinline!pure! or \lstinline!impure!.

Proposal B2  (Eyes): (Simpler, but we lose functionality.)
Replace current text in spec with: 
It is not legal to pass an \lstinline!impure! function as a function argument.

**Comment by maltelenz** [comment]
> A function having a formal function parameter that is `impure` must be marked `impure` or `impure`.

I assume that should end in `pure`?

**Comment by HansOlsson** [comment]
> > A function having a formal function parameter that is `impure` must be marked `impure` or `impure`.
> 
> I assume that should end in `pure`?

Yes, (or actually pure or impure as before).

**Comment by henrikt-ma** [comment]
In poll B, it would be good to also have an option for no change for now, that is, delaying the fix until we have time to do it properly.  To be, this is a much better alternative compared to B1, as the only real problem with the current formulation is that the grammar hasn't been updated accordingly.

**Comment by HansOlsson** [comment]
> In poll B, it would be good to also have an option for no change for now, that is, delaying the fix until we have time to do it properly. To be, this is a much better alternative compared to B1, as the only real problem with the current formulation is that the grammar hasn't been updated accordingly.

I see a problem with updating the grammar; as we currently have function inputs declared as normal components as for any class - that sort of works, but isn't ideal. However, if we add impure that would mean that the keyword `impure `would be allowed for all component declarations. I know that it can be handled in the parser, but it doesn't look like a good design.

**However**, if we later decide on something like that change (or only for function arguments in some way) and we _now_ decide on A and B1 one possibility would be to require impure on the function component if the function used as formal argument is impure; since it seems in line with those decisions - giving the result you desire.

**Comment by henrikt-ma** [comment]
> I see a problem with updating the grammar; as we currently have function inputs declared as normal components as for any class - that sort of works, but isn't ideal. However, if we add impure that would mean that the keyword `impure` would be allowed for all component declarations. I know that it can be handled in the parser, but it doesn't look like a good design.

It's a design principle we're already applying: the grammar already has `flow` and `stream` in the `type-prefix` rule.  In my opinion, defining a more permitting grammar in this way is even the right way to do it if you want to give high quality error messages for invalid uses.

**Comment by henrikt-ma** [comment]
> **However**, if we later decide on something like that change (or only for function arguments in some way) and we _now_ decide on A and B1 one possibility would be to require impure on the function component if the function used as formal argument is impure; since it seems in line with those decisions - giving the result you desire.

My point is that I find no change a better alternative in the meantime.  We have once decided on a good design, but only implemented it partly in the specification.  As I read the current inconsistent specification, the `type-prefix` rule is simply out-of-date because it fails to mention `impure`.

**Comment by HansOlsson** [comment]
> > I see a problem with updating the grammar; as we currently have function inputs declared as normal components as for any class - that sort of works, but isn't ideal. However, if we add impure that would mean that the keyword `impure` would be allowed for all component declarations. I know that it can be handled in the parser, but it doesn't look like a good design.
> 
> It's a design principle we're already applying: the grammar already has `flow` and `stream` in the `type-prefix` rule. In my opinion, defining a more permitting grammar in this way is even the right way to do it if you want to give high quality error messages for invalid uses.

In my opinion these cases are different.

However, my point is that if you use a base-function as your interface it will anyway (based on proposal A, inheritance, and B1 or current idea) be:
```
partial impure function MyImpureInterface
  input Real x;
end MyImpureInterface;

impure function MyImpureImplementation
  extends MyImpureInterface;
external "C";
end MyImpureImplementation;

impure function foo CallN
  input MyImpureInterface f;
  input Integer n;
  input Real x;
algorithm
  for i in 1:n loop
      f(x);
  end for;
end CallN;
CallN(MyImpureImplementation, 4, 4.0);
```
And the discussion is whether there should also be `impure `on the line with f, but no other changes.

**Comment by henrikt-ma** [comment]
But doesn't our type system allow passing an impure function as argument to an input of a pure function interface type?

More generally, does rules about inheritance really help in any way here, considering that we have a structural type system?

**Comment by henrikt-ma** [comment]
When we're at it, shouldn't proposal A also be extended to not allow an impure function to extend a pure function?

**Comment by HansOlsson** [comment]
> When we're at it, shouldn't proposal A also be extended to not allow an impure function to extend a pure function?

I'm not sure if that is necessarily a problem. I think we need more experience with pure/impure.

**Comment by henrikt-ma** [comment]
> > When we're at it, shouldn't proposal A also be extended to not allow an impure function to extend a pure function?
> 
> I'm not sure if that is necessarily a problem. I think we need more experience with pure/impure.

It isn't a problem since the typing is structural anyway, just like proposal A doesn't fix any real problem.

I just mean that if we add rules for extends just to better match common intuition, then it would make sense to also cover this other aspect.

**Comment by qlambert-pro** [comment]
For the second poll, it seems like, the following would be valid with B1:
```
model Test
  impure function bar
    input Real i;
  algorithm
    assert(i > 0, "");
  end bar;

  pure function foo
    input MyImpureInterface f;
  algorithm
    f(x);
  end foo;
equation
  foo(bar);
end Test;
```
B2 would make it invalid, which I would prefer, but I don't see the need of forbidding passing impure function as argument entirely, I would only restrict the function to which it is an argument to being impure itself.
What was the reasoning not to do that?

**Comment by henrikt-ma** [comment]
> What was the reasoning not to do that?

It gives the function a chance of overriding purity checks by means of `pure(…)` expressions, so that it can declare itself `pure` despite taking impure function arguments.

**Comment by HansOlsson** [comment]
> > What was the reasoning not to do that?
> 
> It gives the function a chance of overriding purity checks by means of `pure(…)` expressions, so that it can declare itself `pure` despite taking impure function arguments.

I was also going to write that.
I don't know how much use it will see in practice, though.

**Comment by henrikt-ma** [comment]
Having given some more thought to B2, I've come to the conclusion that it could be a good alternative if formulated in terms of function-compatibility (definition 6.8).  This would also prohibit extending a pure function with an impure one.

**Comment by henrikt-ma** [comment]
> For the second poll, it seems like, the following would be valid with B1:

You forgot to wrap the call to `f` with `pure(…)`:
```
  pure function foo
    input MyImpureInterface f;
  algorithm
    pure(f(x));
  end foo;
```

**Comment by HansOlsson** [comment]
> Having given some more thought to B2, I've come to the conclusion that it could be a good alternative if formulated in terms of function-compatibility (definition 6.8). This would also prohibit extending a pure function with an impure one.
> 
> It took me some time (sorry for that), to realize that B2 is able to reject this:
> 
> ```
> model Test
>   partial pure function PureInterface
>     input Real i;
>   end PureInterface;
> 
>   impure function bar
>     extends PureInterface; /* B2 fails to reject this... */
>     input Real i;
>   algorithm
>     assert(i > 0, "");
>   end bar;
> 
>   pure function foo
>     input PureInterface f;
>   algorithm
>     f(x); /* (Note: not wrapped in pure this time.) */
>   end foo;
> 
> equation
>   foo(bar); /* ... but B2 is still able to reject this! */
> end Test;
> ```

Ok, so you are saying that the function argument must be function-compatible with the interface (as already stated), and an impure function isn't function-compatible with a pure one (which makes sense - and consistent with proposal A, and I agree could be added to the function-compatibility part).

But then you seem to be in favor of B1 - not B2; but just having the restriction in another place?
(Since B2 prohibits sending impure functions as function arguments it clearly prohibits foo(bar).)

**Comment by henrikt-ma** [comment]
> But then you seem to be in favor of B1 - not B2; but just having the restriction in another place?

Yes, my bad.  I'll fix my comment.

**Comment by HansOlsson** [comment]
> > But then you seem to be in favor of B1 - not B2; but just having the restriction in another place?
> 
> Yes, my bad. I'll fix my comment, and I'm ready to jump from B2 to an improved B1.

Can you clarify the exact improvement needed?

Note that for my it makes sense that subtyping here is asymmetric so that an impure function can inherit a pure one, but not vice-versa.

The reason is both that all functions as default are pure - so it will introduce less problems, and also more generally that adding something can introduce impurity. (Even though it doesn't make that much sense in Modelica for other reasons.)

**Comment by henrikt-ma** [comment]
> > Yes, my bad. I'll fix my comment, and I'm ready to jump from B2 to an improved B1.
> 
> Can you clarify the exact improvement needed?

I could try, but I've got a feeling I won't succeed on first attempt.

> Note that for my it makes sense that subtyping here is asymmetric so that an impure function can inherit a pure one, but not vice-versa.

My starting point is that function subtyping is the relation defining when a function can be passed as argument to another function:
> In all cases the provided function must be function-compatible (\cref{function-compatibility}) with the corresponding formal parameter of function type.

Seen this way, I come to the opposite conclusion regarding the asymmetric relation.  Since passing a pure function for an impure formal parameter is the safe direction, this shows that the subtype relation should go in the direction of the pure being be a subtype of the impure.

> The reason is both that all functions as default are pure - so it will introduce less problems, and also more generally that adding something can introduce impurity. (Even though it doesn't make that much sense in Modelica for other reasons.)

Sure, extending a a pure function and adding things to it can result in something impure, but this is just an example of inheritance in Modelica not having anything to do with subtyping.  Adding additional constraints for marking extending functions as either pure or impure can help align language concepts with intuition.  (Not allowing a pure function to be extended by an impure function makes intuition about inheritance more aligned with subtyping, while not allowing an impure function to be extended by a pure function is necessary to avoid bypassing purity checks.)

**Comment by beutlich** [comment]
This is very long to read and hard to grasp. Could you please provide some example for what is allowed and what's not allowed such that I can make my mind for the vote?

**Comment by HansOlsson** [comment]
> This is very long to read and hard to grasp. Could you please provide some example for what is allowed and what's not allowed such that I can make my mind for the vote? Thanks.

There are two parts:
"A" means that you can declare a function interface as impure, and anything inheriting from it should be impure.
"B1" mean that you if a function is defined as taking an impure function interface you need to pass an impure function to it (and the function itself must be impure or pure). 

The comment indicate that it should be included in the function subtyping as well.

So:
```
impure partial function MyImpureInterface
  input Real x;
end MyImpureInterface;
partial function MyNormalInterface
  input Real x;
end MyNormalnterface;

function IllegalExtend "Should be declared as impure since extending from impure function"
   extends MyImpureInterface;
...
end IllegalExtend;

function F "Legal function, but not function compatible subtype of MyImpureInterface"
  extends MyNormalnterface;
end F;

impure function FImpure"Legal function, and function compatible subtype of MyImpureInterface"
  input Real x;
end FImpure;

impure function fooImpure "Note, must be declared pure or impure due to MyImpureInterface"
  input MyImpureInterface bar=...;
...
end foo;
function foo "Note, implicitly pure as all functions"
  input MyNormalInterface bar=...;
  input Real x;
  output Real y;
algorithm // See below
  y:=0;
  if bar(x)>0 then
    y:=bar(x);
  end if;
end foo;
equation
when sample(1,1) then
  x1=foo(MyNormalInterface=F); / Legal, nothing impure
  x2=fooImpure(MyImpureInterface=FImpure); // Legal since MyFunction is impure
  x3=foo(MyNormalInterface=FImpure); // Illegal, since passing impure function to function not expecting it
end when;
x4=foo(MyNormalInterface=FImpure); // Illegal, since passing impure function to function not expecting it
```
The last example shows that users cannot circumvent the restrictions on calling impure function by having a pure function with an impure function argument.

The implication for implementers is that they can optimize functions declared as taking function arguments under the assumption that repeated call of the function can be optimized away - unless the function argument is declared as an impure function.

Thus inside `foo` we can see that the two calls of `bar` are the same and you only need to call `bar(x)` once, but if `fooImpure` contained the same algorithm we couldn't do the same optimization inside it (since `fooImpure` has to be declared as impure there are also other reasons to not optimize it).

Obviously since function arguments are known statically one could do the same based on the actual arguments, but that seems messier (in terms of specifying, explaining, implementing, etc) to me.

**Comment by henrikt-ma** [comment]
I think you mixed up the formal parameter types with the formal parameter names here, didn't you?
```
when sample(1,1) then
  x1=foo(MyNormalInterface=F); / Legal, nothing impure
  x2=fooImpure(MyImpureInterface=FImpure); // Legal since MyFunction is impure
  x3=foo(MyNormalInterface=FImpure); // Illegal, since passing impure function to function not expecting it
end when;
x4=foo(MyNormalInterface=FImpure); // Illegal, since passing impure function to function not expecting it
```

**Comment by HansOlsson** [comment]
> > So:
> > ```
> > when sample(1,1) then
> >   x1=foo(MyNormalInterface=F); / Legal, nothing impure
> >   x2=fooImpure(MyImpureInterface=FImpure); // Legal since MyFunction is impure
> >   x3=foo(MyNormalInterface=FImpure); // Illegal, since passing impure function to function not expecting it
> > end when;
> > x4=foo(MyNormalInterface=FImpure); // Illegal, since passing impure function to function not expecting it
> > ```
> 
> I think you mixed up the formal parameter types with the formal parameter names here, didn't you? And `MyFunction` in the comment should probably be `MyImpureInterface`.

Seems so. Good that it was only in text here and not in the specification text yet.

**Comment by HansOlsson** [comment]
Poll results:
Proposal A: 6 votes in favor, none against: eshmoylova, HansOlsson, maltelenz, henrikt-ma, qlambert-pro, and hubertus65.
Proposal B:
B1. Retain current (rocket) 3 votes: HansOlsson eshmoylova casella 
B2. Remove (eyes) 2 votes: henrikt-ma qlambert-pro 

So a clear win for proposal A, and slight win for B1. It seems we will need to later revisit impure functions; as we in general (not only for this specific topic) need more experience both with the optimizations allowed by pure functions and the restrictions imposed by impure functions.

In particular it is problematic that many (most?) functions in practice rely on "A deprecated semantics is that..."
