### ISSUE TITLE
What to do with 'partial flattening' from old glossary?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2787]
In the source file _scoping.tex_, this comment was left after migration of the old glossary to the new document index:
```LaTeX
% henrikt-ma: The old glossary defined 'partial flattening' as follows -- does it belong here?
%First find the names of declared local classes and components.
%Modifiers, if present, are merged to the local elements and redeclarations are performed.
%Then base-classes are looked up, flattened and inserted into the class.
%See also flattening, which additionally flattens local elements and performs modifications.
```

Should the text be integrated in the document, or the comment be removed?

**Comment by HansOlsson** [comment]
It is similar to https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#steps-of-instantiation - excluding the "Recursive instantiation of components".

However, after the instantiation was redone in #1829 the terminology no longer is relevant.
Thus I don't see a problem with removing it.

**Comment by henrikt-ma** [comment]
OK, now people have had 5 days to fight for the text about to be removed.  I'm now going to prepare a PR for getting it done.
