### ISSUE TITLE
MLS 3.5 RC1: MLS.pdf misses PDF attributes title and author

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2795]
The current MLS 3.5 RC1 from https://specification.modelica.org/maint/3.5/MLS.pdf misses the PDF tags title and author.

![grafik](https://user-images.githubusercontent.com/14896695/103700251-820c3100-4fa4-11eb-93fd-9ba8fdf0d982.png)

See MLS 3.4 for comparison:

![grafik](https://user-images.githubusercontent.com/14896695/103700191-686ae980-4fa4-11eb-9990-05ccc3e57391.png)

**Comment by henrikt-ma** [comment]
Thanks for reporting.  I'll prepare a fix for _master_ that we can then cherry-pick to 3.5.

**Comment by HansOlsson** [comment]
> Thanks for reporting. I'll prepare a fix for _master_ that we can then cherry-pick to 3.5.

Oh, I was only starting on it.

**Comment by HansOlsson** [comment]
> > Thanks for reporting. I'll prepare a fix for _master_ that we can then cherry-pick to 3.5.
> 
> Oh, I was only starting on it.

But failed - seems that \pdfinfo didn't work as expected.

**Comment by beutlich** [comment]
> Oh, I was only starting on it.

You can make use of the assignee feature of GitHub issues to avoid accidental double work. 🧑‍💼

**Comment by henrikt-ma** [comment]
> > Oh, I was only starting on it.
> 
> You can make use of the assignee feature of GitHub issues to avoid accidental double work. 🧑‍💼

Yes, this is something we should learn to make use of.
