### ISSUE TITLE
Conversion scripts not defined

### ISSUE THREAD

**Issue by gkurzbach** [modelica/ModelicaSpecification#2801]
Conversion scripts as such are not defined in the specification. In chapter 18.8.2 it is only mentioned that there may be a reference (script="convertTo3.mos") to such a script and that there are some functions which perform some operation.
But what is allowed inside such a script and especially whether the calls to these functions are separated by a semicolon or just by spaces is not specified (there are no semicolons in the current MSL 4.0 conversion scripts).  Someone might get the idea that the syntax is the same as in algorithm sections, but it is not. 

In the listing of the conversion functions they are mostly define without trailing semicolon, but the two possible calls of convertMessage have a trailing semicolon. That is odd.

**Comment by HansOlsson** [comment]
On one hand it would be natural for me to require trailing semi-colon, but as noticed since it is missing in MSL 4 (and assumedly other libraries) I think it's best to just say that separated by white-space.

**Comment by HansOlsson** [comment]
Proposal: Optional (but recommended) semi-colon terminating the function calls in the scripts.
And add in examples.
Poll: 
Just space: Hans, Henrik, Elena
Optional semi-colon (but recommended): Hans, Axel, Gerd, Leo, Elena, Markus
Deprecate space: Henrik, Gerd, Leo, Markus, Quentin
Conclusion: slight advantage for "Optional semi-colon (but recommended)".
