### ISSUE TITLE
Inaccurate statement about solving equations

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2814]
In Chapter 8 Equations in the introductory paragraph, there the following statement:
> In contrast to a statement in an algorithm section, an equation does not define for which of its variable it is to be solved. 

It is not an accurate statement. For example, in when-equations the left-hand side determines which variable the equation should be solved for. Similarly, the declaration equations should be solved for the variable that is declared by the declaration.

I noticed that while reviewing #2788.

**Comment by henrikt-ma** [comment]
Without entering the debate regarding declaration equations, I also react against the statement that an algorithm would define with respect to which variables it will be solved.

**Comment by henrikt-ma** [comment]
I find the words _compute_ and _solve_ too close to be a useful distinction here.  If the text would say _compute_ regarding a variable in an equation, I'd probably read that as solving for that variable, and then the reading becomes dangerously close to what we currently have.  I'm not sure there is any intent here really worth preserving.

**Comment by eshmoylova** [comment]
I agree with @henrikt-ma that _compute_ and _solve_ are too close. I am not sure if it is easy to express the difference between the equations and algorithms concisely without adding a whole bunch of except.... One clear difference is that algorithm determines the order in which statements are executed. The order of equations can be changed in order to solve them. The problematic sentence was not there in 3.4. So maybe it would be fine to omit it.
