### ISSUE TITLE
Algorithm in state-machines?

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2817]
https://specification.modelica.org/master/state-machines.html#transitions says:

> Any Modelica block instance without continuous-time equations or algorithms can potentially be a state of a state machine.

Does this mean "(continuous-time equations) or (algorithms)" or "continuous-time (equations or algorithms)"?
For some reason Dymola 2021x (and earlier) seems to have selected the first interpretation (but only gives a warning), but to me the second one would be slightly more natural.

Found when looking at #2816 and if we allow algorithms in state-machines we have to be more careful about how we reset it.

**Comment by eshmoylova** [comment]
Since clocked algorithms are allowed in general, I agree that it would make sense to allow them to be included here as well.
