### ISSUE TITLE
Missing explicit ban on providing inconsistent derivatives or inverses

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2837]
For a model to be portable between tools and even different versions of the same tool, it is necessary that tools can rely on provided derivatives and inverses being defined in a mathematically consistent manner.  Hence, there should probably be an explicit ban on providing inconsistent derivatives or inverses of functions.  Otherwise, users might think it's fine to provide things that will trick the symbolic processing of a particular version of a particular tool into computing some crazy stuff.

**Comment by HansOlsson** [comment]
> For a model to be portable between tools and even different versions of the same tool, it is necessary that tools can rely on provided derivatives and inverses being defined in a mathematically consistent manner. Hence, there should probably be an explicit ban on providing inconsistent derivatives or inverses of functions. Otherwise, users might think it's fine to provide things that will trick the symbolic processing of a particular version of a particular tool into computing some crazy stuff.

I wouldn't want to formulate it as ban on providing inconsistent annotations, but as a requirement that the derivative/inverse (when provided) is correct.
This is already sort of specified but can be made clearer.

For inverse it is part of non-normative explanation (to me it seems that it is non-normative since it explains "inverse", not because inverses don't have to follow it):
https://specification.modelica.org/master/functions.html#declaring-inverses-of-functions

For derivatives it is sort of implicitly assumed, since there are derivatives that are only valid under certain conditions:
https://specification.modelica.org/master/functions.html#using-the-derivative-annotation
However, this also highlights an issue - exactly how to define the noDerivative case.

**Comment by henrikt-ma** [comment]
> For inverse it is part of non-normative explanation (to me it seems that it is non-normative since it explains "inverse", not because inverses don't have to follow it):
> https://specification.modelica.org/master/functions.html#declaring-inverses-of-functions

Yes, so we could probably solve this case by shifting the focus of this sentence to what it is that we require.

**Comment by henrikt-ma** [comment]
> For derivatives it is sort of implicitly assumed, since there are derivatives that are only valid under certain conditions:
> https://specification.modelica.org/master/functions.html#using-the-derivative-annotation

This issue is about the implicitness leaving too much room for interpretation.

> However, this also highlights an issue - exactly how to define the noDerivative case.

To me, that sounds like an issue in its own right.

**Comment by eshmoylova** [comment]
@henrikt-ma  what do you mean exactly by *inconsistent* derivatives or inverses? Inconsistent in the mathematical sense or in the sense of the arguments should be the way they are described in the specification? Or something else entirely?

**Comment by henrikt-ma** [comment]
> @henrikt-ma what do you mean exactly by _inconsistent_ derivatives or inverses? Inconsistent in the mathematical sense or in the sense of the arguments should be the way they are described in the specification? Or something else entirely?

In the mathematical sense, whatever that is – I can see that there are technical details that can make this topic very complicate if you want to:
- Choice of derivative definition (I don't think we have made that choice yet).
- Requirements for points where the original function isn't differentiable (of the order at hand).
- Definition of consistency where the derivative is defined, accounting for errors due to finite precision representation of `Real`.

Instead of going into these details, I was hoping that we could find fluffy – yet normative – statements that make the intention clear.

For inverses (as noted above), we have this sort of statement, although non-normatively.  Note the use of the fluffy _up to a certain precision_.

For derivatives, we have an example of providing consistent derivative functions.  I think we should simply turn that into a normative statement that they must be consistent: using the provided derivative shall give the same result as symbolic-numerical differentiation of the original function, "up to a certain precision".  Perhaps we should then change the example into something concrete, with an actual expression that we can differentiate twice.  Depending on the choice of expression and how its derivatives are expressed, we would be able to illustrate various aspects of the required consistency.

For completeness, we would also need to say something similar about the partial derivatives.

**Comment by henrikt-ma** [comment]
Having thought some more, I think that the most important fix might be to provide a couple of more illustrative examples:
- An incorrect inverse function (an error that tools are generally not expected to detect).
- The use of function inverses for functions that are not injective (for example, using the (negative) square root as an inverse for squaring).
- An incorrect derivative function (an error that tools are generally not expected to detect).
- Something about providing a derivative of an `abs`-like function – subtle error or legal?

**Comment by eshmoylova** [comment]
This is something that I find very unclear: should the derivatives and inverses be actual mathematical derivatives and inverses? In the description of 'LateInline' 'Modelica.Media.Water.IF97_Utilities.T_props_ph' is given as an example.  It is defined as:
```
  function T_props_ph
    "Temperature as function of pressure and specific enthalpy"
    extends Modelica.Icons.Function;
    input SI.Pressure p "Pressure";
    input SI.SpecificEnthalpy h "Specific enthalpy";
    input Common.IF97BaseTwoPhase properties "Auxiliary record";
    output SI.Temperature T "Temperature";
  algorithm
    T := properties.T;
    annotation (
      derivative(noDerivative=properties) = T_ph_der,
      Inline=false,
      LateInline=true);
  end T_props_ph;
```
The derivative of function is given as:
```
  function T_ph_der "Derivative function of T_ph"
    extends Modelica.Icons.Function;
    input SI.Pressure p "Pressure";
    input SI.SpecificEnthalpy h "Specific enthalpy";
    input Common.IF97BaseTwoPhase properties "Auxiliary record";
    input Real p_der "Derivative of pressure";
    input Real h_der "Derivative of specific enthalpy";
    output Real T_der "Derivative of temperature";
  algorithm
    if (properties.region == 4) then
      T_der := 1/properties.dpT*p_der;
    elseif (properties.region == 3) then
      T_der := ((-properties.rho*properties.pd + properties.T*properties.pt)/(properties.rho*properties.rho*properties.pd*properties.cv
         + properties.T*properties.pt*properties.pt))*p_der + ((properties.rho*properties.rho*properties.pd)/(properties.rho*properties.rho
        *properties.pd*properties.cv + properties.T*properties.pt*properties.pt))*h_der;
    else
      //regions 1,2 or 5
      T_der := ((-1/properties.rho + properties.T*properties.vt)/properties.cp)*p_der + (1/properties.cp)*h_der;
    end if;
  end T_ph_der;
```
From the mathematical point of view, the way I see it:
```
T_props_ph = f(p,h,properties.T,properties.rho,properties.cp,...) = properties.T
```
I do not see how you can differentiate `T_props_ph` and arrive at `T_ph_der`.  Is there some magic involved in saying `noDerivate = properties`? Still differentiating T_props_ph with respect to anything other than `properties.T` should give 0 and not that highly complex function I wanted to post that question on MAP-LIB github but then I saw that it was explicitly mentioned in the explanation of the `LateInline` annotation and that meant to me that it was clearly intended that way regardless of the mathematical sense. So I would say that currently the specification endorses the use of mathematically inconsistent derivatives as derivatives of functions.

**Comment by HansOlsson** [comment]
> I do not see how you can differentiate `T_props_ph` and arrive at `T_ph_der`. Is there some magic involved in saying `noDerivate = properties`? 

Yes, the noDerivative case is special because we only consider the case `T_props(p,h,properties(p,h)) ` for one special function `properties(p,h)` that does all the heavy work, and actually computes several of the partial derivatives as well. So, in that special case it works, but not in other cases.

Exactly how to describe this restriction is still unclear.

**Comment by eshmoylova** [comment]
I feel like I really do not understand how `noDerivatives` should work.  I thought it meant we would not differentiate with respect to properties. Filed #2840 in hopes of clarifying.
