### ISSUE TITLE
Issues with connectorSizing description

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2839]
There are a couple of issues that I see in the description of 'connectorSizing' attribute in the Dialog annotation in the non-normative part starting [here](https://github.com/modelica/ModelicaSpecification/blob/3803e4beee60c1bb08ac6336e9a5e063f68c9b12/chapters/annotations.tex#L1477).

It says: ["The recommended rules are clarified at hand of the following example which represents a connector and a model from the \lstinline!Modelica.StateGraph! library:"](https://github.com/modelica/ModelicaSpecification/blob/3803e4beee60c1bb08ac6336e9a5e063f68c9b12/chapters/annotations.tex#L1480) In Modelica.StateGraph in 4.0.0 the connector is called 'Step_in'. There is no model 'Step', but there is a block 'Step'. Those are minor differences but they do make it hard to find the example in the MSL. Perhaps it is better not to mention the MSL given that the library can change. Or mention that other examples can be found there.

In item 2 it says: [Assume the connection line in (3) is removed.](https://github.com/modelica/ModelicaSpecification/blob/3803e4beee60c1bb08ac6336e9a5e063f68c9b12/chapters/annotations.tex#L1527) Should it be in (1) instead? Is there a better way to reference what is meant without hard-coding link?

Items 3 and 4 refer to previous cases and case 1 and case 2. Maybe item 2 should also use the same language instead of using "(3)" format?

**Comment by HansOlsson** [comment]
> There are a couple of issues that I see in the description of 'connectorSizing' attribute in the Dialog annotation in the non-normative part starting [here](https://github.com/modelica/ModelicaSpecification/blob/3803e4beee60c1bb08ac6336e9a5e063f68c9b12/chapters/annotations.tex#L1477).
> 
> It says: ["The recommended rules are clarified at hand of the following example which represents a connector and a model from the \lstinline!Modelica.StateGraph! library:"](https://github.com/modelica/ModelicaSpecification/blob/3803e4beee60c1bb08ac6336e9a5e063f68c9b12/chapters/annotations.tex#L1480) In Modelica.StateGraph in 4.0.0 the connector is called 'Step_in'. There is no model 'Step', but there is a block 'Step'. Those are minor differences but they do make it hard to find the example in the MSL. Perhaps it is better not to mention the MSL given that the library can change. Or mention that other examples can be found there.
> 
> In item 2 it says: [Assume the connection line in (3) is removed.](https://github.com/modelica/ModelicaSpecification/blob/3803e4beee60c1bb08ac6336e9a5e063f68c9b12/chapters/annotations.tex#L1527) Should it be in (1) instead? 

Yes, it's the result model in (1) that is intended.

> Is there a better way to reference what is meant without hard-coding link?
> 
> Items 3 and 4 refer to previous cases and case 1 and case 2. Maybe item 2 should also use the same language instead of using "(3)" format?

I agree that it shouldn't be hardcoded and it should use a more consistent style.
