### ISSUE TITLE
Mathematical formulae for noDerivative and zeroDerivative

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2840]
Would it be possible to include mathematical formulae describing the meaning of `noDerivative` and `zeroDerivative` annotations for the derivative? The chain rule for a multivariate function is:
![image](https://user-images.githubusercontent.com/20460714/106633521-ecd16d80-654c-11eb-8ded-cc5f417074d4.png)

If we specifying in `f` annotation `derivative(noDerivative = x) = f_der1` what would be the formula for `f_der1`? What would it be if you say `derivative(zeroDerivative = x) = f_der2`?

**Comment by HansOlsson** [comment]
For zero-derivative it would be that dx/dt=0 so we can ignore \partial f/\partial x as it would be multiplied by 0.
For no-derivative it would be that we assume x=g(y(t)) and d/dt f(g(y(t)), y(t))=(\partial f/partial x*\partial g/\partial y+\partial f/\partial y)*dy/dt and the given derivative is (\partial f/partial x*\partial g/\partial y+\partial f/\partial y) and expressed using g(y(t))

**Comment by eshmoylova** [comment]
Can we include it into the specification? That to me explained it way better than all the current text in the specification.

**Comment by beutlich** [comment]
Here's @HansOlsson reply again, but rendered with inline Latex.

For zero-derivative it would be that <img src="https://render.githubusercontent.com/render/math?math=\frac{dx}{dt}=0"> so we can ignore <img src="https://render.githubusercontent.com/render/math?math=\frac{\partial f}{\partial x}"> as it would be multiplied by 0.
For no-derivative it would be that we assume <img src="https://render.githubusercontent.com/render/math?math=x=g(y(t))"> and <img src="https://render.githubusercontent.com/render/math?math=\frac{d}{dt} f(g(y(t)), y(t))=\left(\frac{\partial f}{\partial x}\frac{\partial g}{\partial y}  %2B\frac{\partial f}{\partial y}\right)*\frac{dy}{dt}"> and the given derivative is <img src="https://render.githubusercontent.com/render/math?math=\left(\frac{\partial f}{\partial x}\frac{\partial g}{\partial y}  %2B\frac{\partial f}{\partial y}\right)"> and expressed using <img src="https://render.githubusercontent.com/render/math?math=g(y(t))">.

**Comment by HansOlsson** [comment]
> Can we include it into the specification? That to me explained it way better than all the current text in the specification.

Yes. That seems like a good idea.

**Comment by HansOlsson** [comment]
Agreement to add.
