### ISSUE TITLE
promote still marked as not available in Modelica

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#2843]
This says `promote` is not available in Modelica:
https://github.com/modelica/ModelicaSpecification/blob/8c8052a575b72dc48d0479f8c61db9d4b82c5ec7/chapters/arrays.tex#L220
but I think since https://github.com/modelica/ModelicaSpecification/pull/2590 and https://github.com/modelica/ModelicaSpecification/issues/2568 it is?

**Comment by henrikt-ma** [comment]
Good observation.  We did a terrible job at implementing the decision to make it a Modelica function.

**Comment by henrikt-ma** [comment]
So what does this mean regarding the status of `promote` in Modelica 3.5?  According to decision or according to specification?
