### ISSUE TITLE
Defaults and conflicts in Dialog selectors

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2854]
The description of the `Dialog` annotation doesn't forbid setting more than one of:
- `colorSelector = true`
- `loadSelector = Selector(…)`
- `saveSelector = Selector(…)`

Further, the default meaning of not specifying `loadSelector` or `saveSelector` is not defined.  (Certainly, it does not correspond to setting them equal to `Selector()`, compare #2852.)

**Comment by HansOlsson** [comment]
I would add `showStartAttribute `and `connectorSizing `to that list, and propose:

A load or save dialog is activated by setting `loadSelector `or `saveSelector`.
A variable shall have at most one of `showStartAttribute=true`, `colorSelector=true`, `loadSelector=...`, `saveSelector=...` and `connectorSizing=true`.
