### ISSUE TITLE
Lack of symmetry between ModelicaAllocateString and ModelicaDuplicateString

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2858]
This is a follow-up to #2450.

First a sidenote about readability of _Utility Functions for Allocating Strings_: I think it would be easier to note the important general details regarding external function memory allocation if the function definitions were placed at the end of the section.

Main point of this issue: The text doesn't fully treat `ModelicaDuplicateString` as an alternative way of making the same kind of memory allocation as `ModelicaAllocateString`:
- Only `ModelicaAllocateString` has the phrase _which is used as a return argument of an external Modelica function_.
- In the general details, we only say _e.g._ before `ModelicaAllocateString` in one place.  It would be more clear if we (informally) introduced a common term for these (_string allocation function_), and then used this term in stead of `ModelicaAllocateString`:
  > Thus if an external function wants to create a non-literal string it must be allocated with one of the string allocation functions in this section, e.g., `ModelicaAllocateString`.  After return of the external function, the Modelica environment is responsible for the allocated memory (e.g., to free this memory, when appropriate). It is not allowed to access memory that was allocated with one of these string allocation functions in a previous call of this external function.

Finally, maybe we should provide a reason for requiring that a string allocated with `ModelicaAllocateString` shall be returned from the external Modelica function?  In other words, extend the non-normative paragraph on when one should use the standard C mechanisms instead, giving a reason.  (After all, it's easy to imagine an implementation where ownership of all strings allocated using string allocation functions would be transferred to the Modelica simulation environment, and that it wouldn't be a problem in case some of them didn't show up as return values from the external function.)

**Comment by HansOlsson** [comment]
Making the texts more similar would be good.

> Finally, maybe we should provide a reason for requiring that a string allocated with ModelicaAllocateString shall be returned from the external Modelica function?

That statement can be interpreted in multiple ways, and only one is correct.

The reason users should use ModelicaAllocateString to allocate such strings is that it would be difficult to construct an alternative that is safe, efficient and free of memory leaks. (The obvious alternatives would be malloc or fixed-length strengths allocated by the caller.)

However, a string returned by ModelicaAllocateString does not have to be returned from the external function, it could be that the function fails after allocating one string - or there might be other reasons. The implementation should also handle those cases as well.

**Comment by henrikt-ma** [comment]
> However, a string returned by ModelicaAllocateString does not have to be returned from the external function, it could be that the function fails after allocating one string - or there might be other reasons. The implementation should also handle those cases as well.

I agree that this sounds like the intended meaning, but do we need a meeting discussion to support a decision to update the text accordingly?

**Comment by HansOlsson** [comment]
Proposal:

- Unify their texts
- It seems that the functions named are only used in this section, so the simple solution is to just not use their names in the general description; see below (1)
- Clarify the point above for ModelicaAllocateString (for all of them) (2)

Current text (1):
Thus if an external function wants to create a non-literal string it must be allocated with one of the functions in this section, e.g., ModelicaAllocateString. After return of the external function, the Modelica environment is responsible for the memory allocated with ModelicaAllocateString (e.g., to free this memory,
when appropriate). It is not allowed to access memory that was allocated with ModelicaAllocateString
in a previous call of this external function.

Proposal:

Thus if an external function wants to create a non-literal string it must be allocated with one of the functions in this section. After return of the external function, the Modelica environment is responsible for the memory allocated with these function (e.g., to free this memory, when appropriate). It is not allowed to access memory that was allocated with these function in a previous call of this external function.

For (2) we have:
[The reason why one should avoid, for instance, malloc for string allocation is that a Modelica simulation
environment may have its own allocation scheme, e.g., a special stack for local variables of a function.]
Propose to extend:
[The reason why one should avoid, for instance, malloc for string allocation is that it would require more details to avoid memory leaks, and thus a Modelica simulation environment may have its own allocation scheme, e.g., a special stack for local variables of a function.]

**Comment by henrikt-ma** [comment]
Apart from some minor grammar errors, I'm missing action on the part about the strings being returned from the external function.

For tomorrow's meeting, I think the most important question is whether there's general agreement that these things need reformulation, and then decide whether we need another meeting decision on accepting the (forthcoming) PR that resolves it, or if it can be left to the PR review process.

**Comment by HansOlsson** [comment]
Seems agreement that no need to return the value; and for other changes as well.
