### ISSUE TITLE
Clarification about discrete variables becoming clocked variables

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#2859]
Please consider the following test case
```
 model BasicClockedSynchronous
    extends Modelica.Icons.Example;
    Clock clk "A clock variable";
    discrete Real x "Clocked discrete-time variable";
    Real y "Unclocked discrete-time variable";
equation
    clk = Clock(0.2);
    x = sample(time, clk);
    y = hold(x) + 1;
end BasicClockedSynchronous;
```
from Peter Fritzson's book "Principles of Object-Oriented Modeling and Simulation with Modelica 3.3", page 382. Dymola accepts it. However, [Section 4.4.4](https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#component-variability-prefixes-discrete-parameter-constant) states:

>  If a Real variable is declared with the prefix discrete it must in a simulation model be assigned in a when-clause, either by an assignment or an equation.

Obviously the above example violates this rule, because a) `x` is declared with prefix discrete, and b) it is not assigned in a when clause.

I understand that Real variables and also other discrete variables such as Booleans and Integers can be used in clocked equations, and they get their clocked discrete-time variable status by clock inference. If the idea is to make this possible also for discrete Real variables, then the rule in Section 4.4.4 should be clarified. Alternatively, we should make it clear in Chapter 16 that discrete variables cannot be used in clocked equations.

I would also suggest to rewrite "it must in a simulation model be assigned" into "in a simulation model, it must be assigned", as the former syntax sounds very German to me. Maybe native speakers could comment on that.

**Comment by HansOlsson** [comment]
This seems like a simple tool-issue. The specification is clear that variables declared with the keyword `discrete `shall be assigned in a when-clause.

Restricting discrete variables in clocked equations is more complicated as we have the explicit goal that all models should work in clocked discretized continuous-time - and ideally that should include models with discrete variables.

**Comment by casella** [comment]
> This seems like a simple tool-issue. The specification is clear that variables declared with the keyword `discrete `shall be assigned in a when-clause.

So, according to your interpretation, the test case above is invalid?

> Restricting discrete variables in clocked equations is more complicated as we have the explicit goal that all models should work in clocked discretized continuous-time - and ideally that should include models with discrete variables.

But that is not the case here, right?

**Comment by HansOlsson** [comment]
> > This seems like a simple tool-issue. The specification is clear that variables declared with the keyword `discrete `shall be assigned in a when-clause.
> 
> So, according to your interpretation, the test case above is invalid?

Yes.

> > Restricting discrete variables in clocked equations is more complicated as we have the explicit goal that all models should work in clocked discretized continuous-time - and ideally that should include models with discrete variables.
> 
> But that is not the case here, right?

No, but it indicates that we need to be careful when adding restrictions.

**Comment by HansOlsson** [comment]
Since it is a tool-issue I think we can close it. Improving the formulations might be good, but less urgent.
