### ISSUE TITLE
Math input error in example in Function Declaration

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2867]
I am seeing "Math input error" in the example in [12.1 Function Declaration](https://specification.modelica.org/master/functions.html#function-declaration):
![image](https://user-images.githubusercontent.com/20460714/108526427-215c5d80-729f-11eb-9cce-d34cb7d653cf.png)

In [3.5](https://specification.modelica.org/maint/3.5/functions.html) it appears normal:
![image](https://user-images.githubusercontent.com/20460714/108526780-8adc6c00-729f-11eb-9451-a436acaa1b54.png)

**Comment by HansOlsson** [comment]
It's due to #2812 - I'll check the other changes from it.

**Comment by HansOlsson** [comment]
Same in 
https://specification.modelica.org/master/class-predefined-types-and-declarations.html#type-conversion-of-enumeration-values-to-string-or-integer
https://specification.modelica.org/master/connectors-and-connections.html#overconstrained-equation-operators-for-connection-graphs
https://specification.modelica.org/master/synchronous-language-elements.html#clocked-when-clause
But
https://specification.modelica.org/master/lexical-structure.html#comments 
https://specification.modelica.org/master/modelica-revision-history.html#main-changes-in-modelica-3-2-revision-1
https://specification.modelica.org/master/statements-and-algorithm-sections.html#assignments-from-called-functions-with-multiple-results
are ok.
