### ISSUE TITLE
Is the value of a basic type an attribute?

### ISSUE THREAD

**Issue by sjoelund** [modelica/ModelicaSpecification#2869]
In 4.8 Predefined Types and Classes, it is slightly unclear if `value` is an attribute or not. It says the attributes are described using Modelica syntax, that attributes may not be accessed using dot-notation, and that they can only be defined by modification.
The value can be defined by equation as well, so I think it's not an attribute. And since it's not an attribute, we have no text to say what you can do with the `value`.

There is at least one Modelica tool out there that allows:
```mo
model M
  partial model N
    Real r;
  end N;
  N n(r.value = 1.0);
end M;
```
OpenModelica does not allow modifying the value in this way (or any other way; only by modifying the Real variable itself).

A clarification would be appreciated.

#2786 might be related.

**Comment by HansOlsson** [comment]
I would say that it isn't allowed.

**Comment by eshmoylova** [comment]
There are comments next to the value specification in the type definitions for Real, Integer, Boolean, String, e.g.:
```
type Real // Note: Defined with Modelica syntax although predefined
  RealType value; // Accessed without dot-notation
```
But they do not forbid accessing it with dot-notation. I think it should not be allowed.

**Comment by henrikt-ma** [comment]
> There are comments next to the value specification in the type definitions for Real, Integer, Boolean, String, e.g.:
> 
> ```
> type Real // Note: Defined with Modelica syntax although predefined
>   RealType value; // Accessed without dot-notation
> ```
> 
> But they do not forbid accessing it with dot-notation. I think it should not be allowed.

I'd say it pretty-much forbids it already; it doesn't say _Also accessible without dot-notation_.  To make it more clear, it could be sufficient to just say this instead:
```
  RealType value; // Not accessible as attribute; only without dot-notation
```

**Comment by henrikt-ma** [comment]
Actually, even better:
```
  RealType value; // Not an attribute; only accessed without dot-notation
```

**Comment by sjoelund** [comment]
The weird part would be using:
```mo
Real r(value=3.0);
```
Which doesn't use dot-notation. Saying it's not an attribute would perhaps be enough. It's certainly better than before. Maybe `// Not an attribute; only accessed without dot-notation and modified without using the name`, but is too long and anyway not detailed enough.

**Comment by HansOlsson** [comment]
> The weird part would be using:
> 
> ```modelica
> Real r(value=3.0);
> ```
> 
> Which doesn't use dot-notation. Saying it's not an attribute would perhaps be enough. It's certainly better than before. Maybe `// Not an attribute; only accessed without dot-notation and modified without using the name`, but is too long and anyway not detailed enough.

Instead of being limited by having the explanation as an end-line comment we could add it after the entire definition and then explain it in more detail. Additionally we could rename it from `value `to something like _`<value>`_.

**Comment by HansOlsson** [comment]
Agreement, but modify existing value-attribute (if any) to another name.
