### ISSUE TITLE
When to use discrete variables?

### ISSUE THREAD

**Issue by dietmarw** [modelica/ModelicaSpecification#2878]
When working on https://github.com/modelica/ModelicaStandardLibrary/pull/3762 it was noted that the original implementation that assigns values inside a when clause to discrete helping variables is not really necessary. So now I wonder, if continuous variables can get assigned discrete values inside `when` in what cases do we actually need discrete variables. Is there any benefit nor necessity in using discrete over continuous in Modelica?

**Comment by HansOlsson** [comment]
They are still discrete - even if not declared with the discrete-prefix.

https://specification.modelica.org/master/class-predefined-types-and-declarations.html#component-variability-prefixes-discrete-parameter-constant

> A Real variable assigned in a when-clause is a discrete-time variable, even though it was not declared with the prefix discrete.

When connected with another variable this doesn't matter, which simplifies things.

As for the related question of whether there is any reason to use discrete when declaring variables, and I can only see some weak reasons: Documentation purposes, and possible declare it discrete in a base-class if you want to use 'pre' on it (even if the actual when-clause is in a derived class).

**Comment by dietmarw** [comment]
Thanks for the clarification. What made me also wondering is the presence of the discrete interface connectors. At first I though I probably have to use those but as it turned out there was no need.

**Comment by HansOlsson** [comment]
I propose that we can close this as an answered question.
