### ISSUE TITLE
Clarify known size in equalityConstraint

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2886]
In the definition of the `equalityConstraint` function in 9.4.1 [Overconstrained Equation Operators for Connection Graphs](https://specification.modelica.org/maint/3.5/connectors-and-connections.html#overconstrained-equation-operators-for-connection-graphs) it says:
> The residue output of the equalityConstraint function shall have known size, say constant .

What is "known size" in this case? In the discussion of #2882 it was mentioned [it would normally be replaced by a number](https://github.com/modelica/ModelicaSpecification/pull/2882#discussion_r586229575). I thought "known size" means it can be evaluated at the translation time. I believe it needs to be clarified.

**Comment by henrikt-ma** [comment]
The question that is nagging me is whether it should be an `Integer` or not.  I see no technical reasons to forbid `Boolean` or an enumeration type, but at the same time integers have a very strong position in my mental machinery for degrees of freedom and rank of constraints.

**Comment by HansOlsson** [comment]
> The question that is nagging me is whether it should be an `Integer` or not. I see no technical reasons to forbid `Boolean` or an enumeration type, but at the same time integers have a very strong position in my mental machinery for degrees of freedom and rank of constraints.

I agree, and I would prefer to restrict it to integers just to keep it simpler.

**Comment by HansOlsson** [comment]
I propose we state that it shall be an integer, normally literal but it can also be a structural parameter.

**Comment by henrikt-ma** [comment]
> I propose we state that it shall be an integer, normally literal but it can also be a structural parameter.

Isn't it better that we try to stick to the kinds of formulations that are already in use?  To me, a good candidate is the one we use for `promote`:
> The argument $n$ must be a constant that can be evaluated during translation, as it determines the number of dimensions of the returned array.

Later, I hope that #2754 will lead to even more alignment of things like this.

**Comment by eshmoylova** [comment]
I like @henrikt-ma's suggestion. From the point of view of a person who writes a Modelica compiler this is all I would like to see. I just want to double check that it also makes sense from the modeling point of view. This quantity is supposed to determine the number of non-redundant equations when connecting two instances of that type. Does it make sense to have that number parameteric? I don't think the role of the Specification is to ensure that modeling makes physical sense (we cannot guarantee that), so maybe my question is irrelevant.

**Comment by HansOlsson** [comment]
> > I propose we state that it shall be an integer, normally literal but it can also be a structural parameter.
> 
> Isn't it better that we try to stick to the kinds of formulations that are already in use? To me, a good candidate is the one we use for `promote`:

I checked and many of the other structural parameters use variants of the following:
"A parameter expression is required since it shall be evaluated at compile time."

> Does it make sense to have that number parameteric?

Good point, as having a parameter expression would be complicated as we connect two connectors and they should have the same number (when connecting connectors they will generate assertions). That means that one would have to set parameters for every instance - which is possibly - but messy.

One could imagine that it is a constant in a package; as that is somewhat easier to change consistently.

So, we have three possibilities:

1. Only literal
2. Constant (that can be evaluated during compile time)
3. Parameter (that can be evaluated during compile time)

**Comment by HansOlsson** [comment]
Poll:
1. Hans
2. Stefan, Henrik, Gerd, Filippo, Markus.
3. Hans, Gerd
Abstain: Axel
Go for (2).

**Comment by henrikt-ma** [comment]
I'll make a PR.
