### ISSUE TITLE
can "der" be overloaded?

### ISSUE THREAD

**Issue by AtiyahElsheikh** [modelica/ModelicaSpecification#2904]
According to the language specification document, to my understanding, there is nothing against or for overloading the function "der". See e.g. Ch 14, Operator Overloading.  

1. Is overloading of "der" theoretically prevented? 
2. What could speak against such realization? 

Thx

**Comment by henrikt-ma** [comment]
It's not possible to overload `der`, since it is a keyword.

Overloading could be rather involved, as it is acting on its operand as a function of time rather than pointwise in time.

Also, before thinking about overloading it, maybe we should start by just including some examples in the text of applying `der` to something that isn't a component reference?  For example:
```
model ChainRule
  Real x(start = 1.0, fixed = true);
  Real y;
equation
  der(1.5 * x + 0.5 * y) = 1.0;
  2 * x + 3 * y = 4.5;
end ChainRule;
```

Note also that there are ways to provided derivatives of a function call, so maybe it just needs to be clarified that it can be useful to provided derivatives for the overloaded operators?

**Comment by AtiyahElsheikh** [comment]
So here is a quick ad-hoc use case for straightforward computation of dynamic parameter sensitivities using operator overloading. The code can be found [here](https://github.com/AtiyahElsheikh/derxpoo). 

Say we have the following simple model:

```
within derxpoo.Examples;
model Simple1
  
   Real x(start = x0); 
   Real y;

   parameter Real x0 = 1.0; 
   parameter Real p  = -2.0; 
   parameter Real q  = 0.1; 
   
equation

  der(x) = p * y ; 
  y  = q + x;  

end Simple1;
```

- Say we enumerate model parameters from 1,2,3, .... 
- By associating an array gradient grad for each variable `x` of type Real, with `g[i]` corresponds to `dx / dp[i]` where `p[i] `is parameter number` i`.  
- By establishing a Gradient type for each variable of type Real, say `RealGrad,` and defining all operators over `RealGrad`, computation of parameter sensitivities is straightforward if overloading `der` is enabled: 

 Implementation of `RealGrad` may look as follows: 

within derxpoo;

```
operator record RealGradOO
  Real val "value of a real identity";
  parameter Integer NP = 0 "number of active parameters";
  Real grad[NP] "gradients";

  encapsulated operator function '*'
    import derxpoo.RealGradOO;
    input RealGradOO g1;
    input RealGradOO g2;
    output RealGradOO res;
  algorithm
    res.val := g1.val * g2.val;
    res.grad := g1.grad * g2.val + g1.val * g2.grad;
  end '*';

  encapsulated operator function '+'
    import derxpoo.RealGradOO;
    input RealGradOO g1;
    input RealGradOO g2;
    output RealGradOO res;
  algorithm
    res.val := g1.val + g2.val;
    res.grad := g1.grad + g2.grad;
  end '+';

  // Modelica language specification does not explicitly state that function der can be overloaded
 
 encapsulated operator function 'der' 
  
  input RealGrad g;
  input Integer i;
  output RealGrad dxp;
  
algorithm

  // unfortionately this der is not allowed in functions, may be to try with blocks instead 
  
  der(dxp.val)  := g.val; 
  der(dxp.grad) := g.grad[i];

end 'der';

```
 
If the above code is possible, dynamic parameter sensitivities of the example can be represented and described as follows:

within derxpoo.Examples;

```
partial model OOSimple
   
   import derxpoo.RealGradOO; 
   type MyGrad = RealGradOO(NP=3); 
   
   
   MyGrad x(val.start = x0.val); 
   MyGrad y;

   parameter MyGrad x0(val=1.0,grad={1,0,0}); 
   parameter MyGrad p(val=-2.0,grad={0,1,0}); 
   parameter MyGrad q(val=0.1,grad={0,0,1}); 
   
   MyGrad temp;
   
equation

   // der(x) = p * y ; does not work with OMC 1.17 
   // Instead 
   
   temp = p * y; 
   der(x.val)  = temp.val; 
   der(x.grad) = temp.grad; 
   y  = q + x;  

end OOSimple;
```

**Comment by henrikt-ma** [comment]
I'm not sure manual implementation of sensitivity equations is a really good use case, since this is something that one could argue would be better handled as a tool feature, but let's ignore that for now.

Another minor detail is that I don't see how the could would manage to compute the sensitivity with respect to `x0`.

My main reaction, however, is that your example of `'der'` demonstrates quite clearly that overloading of `der` is something very different from overloading of other operators, which was a point I was trying to make in my first comment above:  While other operators operate on the values of their operands, `der` operates on its argument as a function of time.  As such, it's natural that one should be able to apply `der` inside its "function" body.  To me, introducing custom operators acting on the entire solution trajectory seems like a very big extension of the language, certainly in need of an MCP (Modelica Change Proposal).

The MCP process is described here:
- https://github.com/modelica/ModelicaSpecification/blob/master/RationaleMCP/DevelopmentProcess.md#mcp

**Comment by AtiyahElsheikh** [comment]
Having the ability to perform algorithmic differentiation through operator overloading, let modelers be capable of straightforward computation of sensitivities at the model level. It makes Modelica a unique platform capable of performing sensitivity analysis of implicit DAEs of arbitrary differential index. If the operator overloading can work, the process of computing parameter sens. by the modeler won't be viewed as a manual implementation anymore. I see huge and unique advantages of having parameter sens. expressed at the model level and I agree that this desires enough justification. But Ok I won't speak about that since this desires series of papers, or even a book. 

[Here ](https://github.com/AtiyahElsheikh/derxpoo/blob/main/Examples/ADFDSimple.mo) is an explicit example showing the sensitivities w.r.t. a variable start value (which are expressed as a model parameter). Comparison is done against finite difference. How this works, this relies on the chain rule of calculus which guarantees that derivatives propagates to the gradients of state variables. To fully understand this process, one needs to consult a book in Algorithmic Differentiation.

**Comment by henrikt-ma** [comment]
> I see huge and unique advantages of having parameter sens. expressed at the model level and I agree that this desires enough justification.

I see mainly disadvantages compared to having sensitivity analysis integrated into the Modelica tool.

If it's in the tool, one doesn't need to manually bloat all Modelica code with instrumentation for computation of parameter sensitivities.

It is also not clear to me that there would be situations where a tool wouldn't be able to automatically compute the correct sensitivities, but a manual implementation by instrumentation of the code would be able to give better results in a reliable way.  Just think about dynamic state selection, fixed point iteration of mixed systems, and event iteration; would manual instrumentation be able to deal with these tough challenges?  Conversely, if we only look at quite restricted subset of models without these challenges, what could then make a tool's by-the-book implementation fail?

**Comment by HansOlsson** [comment]
> > I see huge and unique advantages of having parameter sens. expressed at the model level and I agree that this desires enough justification.
> 
> I see mainly disadvantages compared to having sensitivity analysis integrated into the Modelica tool.
> 
> If it's in the tool, one doesn't need to manually bloat all Modelica code with instrumentation for computation of parameter sensitivities.

Based on people attempting to manually write derivatives for functions I would also believe that the manual coding for parameter sensitivities will be error prone.

> What I'm trying to say here is that if parameter sensitivity analysis is what we want to give our users, then I think it would be better if tool vendors would spend their time implementing this in tools so that it just works without any need to modify Modelica models, than to work on a non-trivial language extension that would still require manual instrumentation of models to get the task done.

Agreed.

**Comment by AtiyahElsheikh** [comment]
With the OO approach, where derivative evaluations are all moved to one package / library, user should not modify mathematical formulas. I think with Modelica capabilities (e.g. replaceable types and packages, etc.), code modification can be kept at minimum level.

In the world of AD, we have all schools are present, tools that perform semantic transformation, e.g. ADIC, libraries that do OO, ADOL, compilers that perform automatic code generation, e.g. NAG and even compilers that evaluate derivatives at the assembly level. All approaches had their own + & - and I saw prof. belonging to each school criticizing each other. It seems that ADOL is the one that is most relevant for object-oriented C++ code.    

However, I see that your valid points necessitate the reasons why presence of parameter sensitivities at the model level should be strongly justified.

**Comment by HansOlsson** [comment]
As I see it the question has been answered, and a proposal to support parameter sensitivities would need more work.
