### ISSUE TITLE
Handling several external sections via inheritance

### ISSUE THREAD

**Issue by adrpo** [modelica/ModelicaSpecification#2921]
The spec says: https://specification.modelica.org/master/functions.html#function-as-a-specialized-class
- A function can have at most one algorithm section or one external function interface (not both), which, if present, is the body of the function.

but some unnamed tools seems to disregard that.

TilMedia is using this kind of inheritance:

```
 package TILMedia.Internals.VLEFluidObjectFunctions.PureComponentDerivatives
  function density_pTxi
    extends .TILMedia.BaseClasses.PartialVLEFluidObjectFunction;
    input SI.AbsolutePressure p "Pressure";
    input SI.Temperature T "Temperature";
    input SI.MassFraction[:] xi "Mass fractions of the first nc-1 components";
    input .TILMedia.Internals.TILMediaExternalObject vleFluidPointer;
    output SI.Density d "Density";
  external"C" d = TILMedia_VLEFluid_Cached_density_pTxi(
        p,
        T,
        xi,
        vleFluidPointer);
  end density_pTxi;
end TILMedia.Internals.VLEFluidObjectFunctions.PureComponentDerivatives;

package TILMedia.VLEFluidObjectFunctions
  redeclare replaceable function density_pTxi =
    .TILMedia.Internals.VLEFluidObjectFunctions.PureComponentDerivatives.density_pTxi;
end TILMedia.VLEFluidObjectFunctions;

package TILMedia.Internals.VLEFluidConfigurations.FullyMixtureCompatible.VLEFluidObjectFunctions
  redeclare replaceable function extends density_pTxi
  external "C" d = TILMedia_VLEFluidObjectFunctions_density_pTxi(p, T, xi, vleFluidPointer)
    annotation(__iti_dllNoExport = true,Include="double TILMedia_VLEFluidObjectFunctions_density_pTxi(double, double, double*, void*);",Library="TILMedia160ClaRa");
  end density_pTxi;
end TILMedia.Internals.VLEFluidConfigurations.FullyMixtureCompatible.VLEFluidObjectFunctions;
```

which will make `redeclare replaceable function extends density_pTxi` function to have two unique external declarations.
That is not Modelica Spec legal but is also not possible to fix this in the library, so this means we need to fix the specification.

As far as I can tell some of the tools allow the inherited class to replace the existing external declaration with a new one.
If this is the case we should write that in the specification.

**Comment by HansOlsson** [comment]
> That is not Modelica Spec legal but is also not possible to fix this in the library, so this means we need to fix the specification.

I don't see anything supporting the statement that it's impossible to fix in the library; and I can see at least one way of achieving it.

**Comment by adrpo** [comment]
Yeah, I wrote first that is not an easy fix, then I changed the text. Yes, is possible if you remove the external declaration from the base class and copy it to the leafs, but the question remains, what is a better solution?

**Comment by HansOlsson** [comment]
> Yeah, I wrote first that is not an easy fix, then I changed the text. Yes, is possible if you remove the external declaration from the base class and copy it to the leafs, but the question remains, what is a better solution?

You make a partial function with the interface and without the external and both functions inherit from it while adding different external declarations.

**Comment by CSchulzeTLK** [comment]
This structure was not intended. We`re going to change it.

The new plan is to:
1. Setup a new package called something like `MyBaseBaseClassPackage` with functions with the interface, but without `external` etc. (basically a duplicate of `TILMedia.BaseClasses.PartialVLEFluidObjectFunctions` but the keyword `replaceable` removed to avoid replaceable base classes)
2. All functions in the package `TILMedia.BaseClasses.PartialVLEFluidObjectFunctions` are declared as `replaceable partial function density_pTxi = MyBaseBaseClassPackage.density_pTxi;`
3. The code of `TILMedia.Internals.VLEFluidConfigurations.FullyMixtureCompatible.VLEFluidObjectFunctions.density_pTxi` starts with `redeclare replaceable function density_pTxi extends MyBaseBaseClassPackage.density_pTxi; ... end density_pTxi;`

So we separate the function interface definition from the package `PartialVLEFluidObjectFunctions` where these function are replaceable. The functions in `TILMedia.BaseClasses.PartialVLEFluidObjectFunctions` directly extend from the non-replaceable function interface definition.

If this is done, the pedantic check in Dymola works fine. @adrpo: Do you think this should work fine in OM?

**Comment by adrpo** [comment]
If it avoids having multiple external definitions then all should be fine, but if you have a branch someplace, let me know and I can give it a quick test with OM.

**Comment by CSchulzeTLK** [comment]
@adrpo, please check the changes in my fork.
https://github.com/CSchulzeTLK/TILMedia
