### ISSUE TITLE
Restore https://specification.modelica.org/v3.4 links

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2928]
Please restore the old MLS v3.4 links to not break its references: See https://github.com/modelica/ModelicaStandardLibrary/runs/2482790609?check_suite_focus=true for the current failures.

**Comment by sjoelund** [comment]
I can do that, but I guess it needs to be done manually since it's a tag and that will try to upload to a different location. I still have access to the originally generated files.

**Comment by beutlich** [comment]
Thank you. Confirmed.
