### ISSUE TITLE
String are ordered, but not supported by min/max

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2940]
Considering that all simple types are ordered and allowing comparison with the `<` and `>` operators,
https://specification.modelica.org/master/operators-and-expressions.html#equality-relational-and-logical-operators
and that the binary `min` and `max` operators are defined in terms of `<` and `>`,
https://specification.modelica.org/master/arrays.html#reduction-functions-and-operators
it is strange that `min` and `max` can operate on all simple types but `String` according to the table in
https://specification.modelica.org/master/arrays.html#reduction-expressions

I can see that `String` is a bit problematic for the non-binary forms (reduction expression and unary array function) of `min` as there is no greatest string to return as the minimum of no strings, but it is really odd that `String` isn't even supported by the binary operators.

I suggest that `min` and `max` are extended to apply simply based on availability of `<` and `>` operators, and of greatest and least elements:
- All three forms of `min` and `max` apply to all simple types.
- For `String`, the least value is the empty string, and it is an error to call `min` on an empty collection of strings (there is no greatest value).

**Comment by henrikt-ma** [comment]
> For Strings I currently don't see a need. I agree that you could define it, but I simply don't see good use cases in Modelica (I can, of course, construct use-cases - but I don't see them as realistic at the moment).

The issue is not driven current needs I am aware of, it's driven by the desire to remove unnecessary and surprising exceptions in the specification.  Why make exceptions for `String` that are neither semantically motivated or saving significant implementation effort?

> Compare this with symmetric, which now is defined to only operate on Real matrices (#2673). It would certainly be possible to define it for other matrices, including String-matrices - but we decided not to.

It's good you mention that, but `symmetric` can be regarded as belonging to a family of functions for numerical mathematics on matrices, and it adds simplicity that `symmetric`, `outerProduct`, `cross`, and `skew` operate on similar types.  (For more reasons, one can of course also study #2673.)  That `transpose` is more general can be excused by its wider applicability as a storage convention conversion function.

**Comment by HansOlsson** [comment]
> > For Strings I currently don't see a need. I agree that you could define it, but I simply don't see good use cases in Modelica (I can, of course, construct use-cases - but I don't see them as realistic at the moment).
> 
> The issue is not driven current needs I am aware of, it's driven by the desire to remove unnecessary and surprising exceptions in the specification. Why make exceptions for `String` that are neither semantically motivated or saving significant implementation effort?

Since strings are handled differently than numbers I would argue that it saves a significant implementation effort; and allows a simpler unified min/max-handling.

**Comment by HansOlsson** [comment]
Doesn't seem enough interest in it at the moment.
