### ISSUE TITLE
Remove constant!

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#2941]
This is a proposal to simplify the language. 

The issue is that constant has varied a bit over the times, and currently it does not seem clear what benefits it brings compared to just parameters, and thus we can first deprecate it and view it as an alias for `parameter`. This becomes messier when we introduce evaluable parameters that sits between parameters and constants in some way.

Removing `constant` from the language would simplify the language, and allow us to use "constant" informally.

Package constants should be then be parameters, either `final parameter` (for pi, e, etc) or just `parameter` (in Modelica.Media); with the restriction that the used package-parameters outside models may not have `fixed=false` or transitively depend on parameters with `fixed=false`.

**Comment by eshmoylova** [comment]
Defining actual constants like pi as parameters does not seem right.

**Comment by henrikt-ma** [comment]
I love having a declared variability (`constant`) for things that can (normally) be assumed evaluatable during translation, instead of hiding away stuff in the `Evaluate` annotation.  I also love the idea of having parameters that you declare as parameters, and that then end up being something that can be modified after translation, although I am fully aware that not all things declared `parameter` in Modelica fall into this category.

**Comment by henrikt-ma** [comment]
One more reason for keeping `constant` is alignment with FMI, where there is also a distinction between constant and "fixed" variability (corresponding to parameter variability in Modelica).  In FMI, the value of a constant can be accessed without even running the FMU, making constant very different from the other variabilities.  Being able to declare an FMU constant as a `constant` in a Modelica FMI import wrapper is an example of good alignment of the two standards.  Conversely, being able to control that a Modelica variable should become a constant in an exported FMU (allowing it to be accessed without running the FMU), by declaring it `constant` in the Modelica model, is another example of good alignment.

**Comment by HansOlsson** [comment]
Doesn't seem enough interest in it at the moment.
