### ISSUE TITLE
Don't start sentences with 'The' to avoid inline code lower case initial

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2943]
This is a follow-up to #2916, seeking more input from the language group on the style guide issue discussed in this comment: https://github.com/modelica/ModelicaSpecification/pull/2916#issuecomment-839209794

Which one is better – think of this as a general pattern for sentences that could start just with the inline code?

Variant 1:
> The `import`-clauses are _not_ inherited.

Variant 2:
> `import`-clauses are _not_ inherited.

For background: Before applying the new style guide we had it like this (no longer an option):
> Import-clauses are _not_ inherited.

Whatever comes out of this discussion should probably be formulated in the style guide one way or another.

**Comment by HansOlsson** [comment]
Variant 1 is often preferred over variant 2:

https://english.stackexchange.com/questions/21295/should-i-change-the-structure-of-a-sentence-add-filler-words-to-make-sure-that-t

https://en.wikipedia.org/wiki/Wikipedia:Manual_of_Style/Capital_letters#Initial_letters_in_sentences_and_list_items

Note that it's not just a matter of adding 'The' as in some cases a filler word is needed; like "The keyword `for `..."

**Comment by HansOlsson** [comment]
Poll:
Variant 1: "The import-clauses": Gerd, Daeoh, Filippo, Elena, Dietmar, Markus, Martin, Hans
Variant 2: "import-clauses": Quentin, Henrik, 
(1)
Henrik to update style-guide.
