### ISSUE TITLE
Misplaced rule that constants must have declaration equation

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2945]
This concerns to minor problems with this rule from https://specification.modelica.org/master/operators-and-expressions.html#constant-expressions:
> Components declared as constant shall have an associated declaration equation with a constant expression, if the constant is directly in the simulation model, or used in the simulation model.  The value…

Since this is about the declared variability of a component, the correct section ought to be this: https://specification.modelica.org/master/class-predefined-types-and-declarations.html#component-variability-prefixes-discrete-parameter-constant

Later, the rule isn't even mentioned in https://specification.modelica.org/master/equations.html#initialization-initial-equation-and-initial-algorithm, where it is just said that a constant doesn't get a default initial equation.  It would have been better to separate constants and parameters here, use the current formulation only for the parameters, and explain that there is never any need for a default initial equation for a constant considering that it must have a declaration equation.

**Comment by HansOlsson** [comment]
It seems the proposal is to:
1. Move "Components declared as constant shall have an associated declaration equation with a constant expression, if the constant is directly in the simulation model, or used in the simulation model. The value…" from https://specification.modelica.org/master/operators-and-expressions.html#constant-expressions to https://specification.modelica.org/master/class-predefined-types-and-declarations.html#component-variability-prefixes-discrete-parameter-constant
2. Link from https://specification.modelica.org/master/equations.html#initialization-initial-equation-and-initial-algorithm

**Comment by HansOlsson** [comment]
Agreement
