### ISSUE TITLE
OK to use type's default value for parameter and just notify?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2947]
While my gut feeling is that the specification never wants the default value of a type to be used for initialization of a parameter, the text can be read differently.

It is normative that the following is legal and should result in a diagnostic message when using `start` for initialization:
```
parameter Real p(start = 1.0);
```
System Modeler considers this bad style and interprets "diagnostic message" as warning in this case.

In case `start` wasn't present we could use the more general non-normative rule:
> A tool may add or remove initial equations automatically such that the resulting system is structurally nonsingular. In these cases diagnostics are appropriate since the result is not unique and not necessarily what the user expects.

In System Modeler, this is generally considered so normal that the diagnostics are only given in the form of notifications.  Is it the intention of the specification that this rule may also be applied to parameters?  (In case of a parameter, System Modeler considers it bad enough to warrant a special warning.)

More generally, I also think that much of the non-normative text in section 8.6 needs to be made normative, so that it is really clear what a tool really may do to obtain a balanced initialization problem.  If it shouldn't be normative, it should be clarified the other way: that the tricks that can make the initialization problem valid are simply tricks to deal with models that are in fact invalid.

**Comment by HansOlsson** [comment]
> In System Modeler, this is generally considered so normal that the diagnostics are only given in the form of notifications. Is it the intention of the specification that this rule may also be applied to parameters? (In case of a parameter, System Modeler considers it bad enough to warrant a special warning.)

I don't see that the rule should cover parameter-changes.

In general I would say that it should be clarified so that _adding_ initial equations can be added with message/warning, but changing initialization to violate initial equations is an error. However, removing _consistent_ initial equations are ok

**Comment by henrikt-ma** [comment]
This question is also coupled with #2952: If one allows introducing some sort of initial equation for a parameter, this would counteract the idea of requiring a value to be given by the user at initialization.

**Comment by HansOlsson** [comment]
> This question is also coupled with #2952: If one allows introducing some sort of initial equation for a parameter, this would counteract the idea of requiring a value to be given by the user at initialization.

I believe it should be clarified so that:

- (Non-fixed) start-values can be added with message/warning.
- Changing initialization to violate initial equations is an error. 
- Removing consistent initial equations and start-values are ok.

**Comment by henrikt-ma** [comment]
> * Changing initialization to violate initial equations is an error.

Just to clarify: Are you talking about some sort of user error here, or is this simply stating the obvious about what a tool must not do?

**Comment by HansOlsson** [comment]
> > * Changing initialization to violate initial equations is an error.
> 
> Just to clarify: Are you talking about some sort of user error here, or is this simply stating the obvious about what a tool must not do?

What tools must not do.

**Comment by henrikt-ma** [comment]
> What tools must not do.

Then I'm not sure we have to write anything about it, but overall it looks like there's a good basis for making some good decisions at tomorrow's meeting.
