### ISSUE TITLE
HTML Formatting of Language Specification 3.5 - 9.1.2 Inside and Outside Connectors

### ISSUE THREAD

**Issue by and-sang** [modelica/ModelicaSpecification#2950]
In the HTML version of the language specification 3.5, section [**9.1.2 Inside and Outside Connectors**](https://specification.modelica.org/maint/3.5/connectors-and-connections.html#inside-and-outside-connectors), the text formatting of the connect statements breaks the lines. 

- The content of `<div id="lstnumberx1767" class="ltx_listingline">` should belong to `<div id="lstnumberx1766" class="ltx_listingline">`
- The content of `<div id="lstnumberx1769" class="ltx_listingline">` should belong to `<div id="lstnumberx1767" class="ltx_listingline">`

As a result, comments in the code are rendered misleadingly into wrong Modelica code

**Comment by henrikt-ma** [comment]
This is already fixed on _master_.  Closing.
