### ISSUE TITLE
 `fixed=false` parameter with an `Evaluate=true` annotation

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#2951]
`Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic` has a  `fixed=false` parameter with an `Evaluate=true` annotation, namely `jointRRR1.n_b`. Does it mean that one should ignore the annotation or go and fetch the `initial equation`?

**Comment by HansOlsson** [comment]
> `Modelica.Mechanics.MultiBody.Examples.Loops.PlanarLoops_analytic` has a `fixed=false` parameter with an `Evaluate=true` annotation, namely `jointRRR1.n_b`. Does it mean that one should ignore the annotation or go and fetch the `initial equation`?

Ignore the annotation as it is only proposed to use it.
As noted both of these are in the declaration of `Modelica.Mechanics.MultiBody.Joints.Assemblies.JointRRR` for `n_b.`

In this case it would make sense to just remove the annotation. However, in some cases it is a bit messier - you have a parameter `n` with `Evaluate=true` in a component, and then you have a another parameter `n_b(fixed=false)` and propagate `n=n_b`. In that case you cannot do much.

**Comment by HansOlsson** [comment]
I see this as resolved now.
