### ISSUE TITLE
Redeclaration from false class in example

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaSpecification#2963]
In example listing _package MoistAir2_ (Sect. 7.3.1 The class extends Redeclaration Mechanism), the `model MoistAir_dynamicViscosity` extends from `PartialMedium.dynamicViscosity` which actually is a function. But this is prohibited according to Sect. 7.1.3 Restrictions on the Kind of Base Class.

**Comment by tobolar** [comment]
If `MoistAir_dynamicViscosity` is a function now, its name shall actually start with lower case.

**Comment by HansOlsson** [comment]
> If `MoistAir_dynamicViscosity` is a function now, its name shall actually start with lower case.

Normally yes, but people shouldn't be using this style so having a name suggesting MoistAir.dynamicViscosity seems clearer. I see that one could use dynamicViscosity_MoistAir - but it seems too odd.
