### ISSUE TITLE
Formatting is off when accessing ExternlObject via index

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#2967]
Go to index, ExternalObject. The entry for it appears as:
![image](https://user-images.githubusercontent.com/20460714/128021253-c229959f-3c00-4474-bffc-6d6c7ed3f6d6.png)
If you click on it, it takes you to: https://specification.modelica.org/master/functions.html#S9.I12.i1.p1. It appears as:
![image](https://user-images.githubusercontent.com/20460714/128021520-3ecfc9be-1e5d-4817-9f36-347a6a8d636a.png)
which is the middle of the item's text. To see the beginning, you need to scroll up and then there is an extra line break:
![image](https://user-images.githubusercontent.com/20460714/128021780-ce5fcbde-96bf-4e73-a4e9-2aa9cd325608.png)

I first thought there was an extra break in the text of that bullet item. But it looks clean in the code, and if you navigate to Section 12.9.7 through the menu it looks clean: https://specification.modelica.org/master/functions.html#external-objects

After a quick look through the index, I see there are at least two more items that appear as n-th item, for connector and conversion. If you click on them they also insert an extra line break in the formatting.

**Comment by HansOlsson** [comment]
This is really weird.

It seems related to the anchor-handling and css so that 
https://specification.modelica.org/master/functions.html#S9.I12.i2.p1
gives the same issue for the 2nd item in the list.

I had no idea that you could style the page based on which link was used to access it.

**Comment by HansOlsson** [comment]
It is a regression caused by #2841 
The correction for #2841 is rather subtle, it adds white-space before the target - but normally that is a section heading and you don't notice it.

Something like this instead might work:

```
:target:before {
  visibility: hidden;
  content: "X"; /* Hidden, but needs to be non-empty to work in Chrome. */
  display: inline-block;
  position: relative;
  padding-top: calc((3.5rem + 2px));
  top: calc(-(2.5rem + 2px)); /* Offset by total height of .ltx_page_header. */
}
```

**Comment by henrikt-ma** [comment]
Excellent preparations, but it still doesn't look great.  The screen shot is from Chrome, but it looks similar in Safari and Firefox:
![chrome](https://user-images.githubusercontent.com/25294143/128835077-e1ac912d-9056-43e2-b60a-d243d9c459b3.png)

**Comment by HansOlsson** [comment]
Either it has re-appeared or it wasn't solved. The following are the possibilities:

- Just skip the target-before hack, accept that you cannot see that you link to-- 
- Really investigate target-before in css
- Remove the banner with "Modelica Language Specification 3.7"
- Change the banner into a footer

Current goal is to investigate target-before, as removing banner or changing it into a footer was deemed less good.
Will re-open if there's progress.
