### ISSUE TITLE
Make GenerateEvents = true imply inlining

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#2986]
(**Background:** An ongoing discussion about `GenerateEvents` in #2895 was lost when the issue was closed (the discussion was beside the main point of the issue, so closing the issue wasn't wrong per se), so I'm bringing it to life here as a separate issue.)

Since implementing `GenerateEvents = true` seems like a rather challenging task unless the function is inlined, can't we specify `GenerateEvents` so that it cannot be combined with no inlining?

Here's a suggested poll that tries to summarize the original discussion:
- Do nothing.
- Make `Inline = true` implied, and don't allow combination with any other inlining annotation.
- When `GenerateEvents = true`, only allow other inlining annotations to be used with a setting of `true`, and make `Inline = true` implicit in case no inlining annotation is given.
- Just Deprecate.
- Make `Inline = true` implied as above, plus deprecation.

Regarding deprecation, see: https://github.com/modelica/ModelicaSpecification/issues/2895#issuecomment-829882774

**Comment by HansOlsson** [comment]
Language group:
If GenerateEvents=true then events shall be generated (this might imply that the function is inlined).

And poll: 
1 (nothing) Hans, Gerd
2 (Inline=true implied nothing else) Elena, Gerd, Henrik, Markus,
3 (Inline=true implied but can change)  Hans, Gerd, Henrik, Markus, Stephan
4 Deprecate: Henrik
5 (Inline=true implied deprecate) Elena, Henrik

3 is slight winner over 2. @henrikt-ma

**Comment by henrikt-ma** [comment]
Like I suspected, System Modeler cannot combine `GenerateEvents = true` with `LateInline`.  As input to this discussion, let's collect some observations about where different tools stand today, and then we can proceed to the question of which of the reported behaviors that make sense.

Please add comments with how different tools handle this model:
```
model LateInlineWithEvents
  function f
    input Real x;
    output Real y = if sin(x) > 0.5 then sqrt(0.5*sin(x)) else sin(x);
    annotation(GenerateEvents = true, LateInline = true);
  end f;
  Real x(start = 0.0, fixed = true);
  Real s = sin(x);
  Real y = f(x);
equation
  der(x) = 20 - x;
end LateInlineWithEvents;
```

**Comment by henrikt-ma** [comment]
Pinging people that I hope can contribute with reports for other tools: @HansOlsson, @gkurzbach, @sjoelund, @eshmoylova, @axelmartenssonmodelon

**Comment by gkurzbach** [comment]
In SimulationX the function is inlined at the same place as with Inline=true, so basically GenerateEvents = true implies Inline=true.

**Comment by MarkusOlssonModelon** [comment]
OPTIMICA Compiler Toolkit does not look at the GenerateEvents annotations today, but if we did I don't see why it wouldn't work with the model.

**Comment by sjoelund** [comment]
OpenModelica:

* GenerateEvents = true, LateInline = true: 4 state events (LateInline is done after sorting/matching but before some additional symbolic processing since inlining introduces new expressions that can be manipulated)
* GenerateEvents = true, Inline = true: 4 state events
* GenerateEvents = true: 0 state events
* Inline = true: 0 state events
* LateInline = true: 0 state events

**Comment by henrikt-ma** [comment]
It is an interesting diversity in the tool reports so far.

For background, in case someone doesn't remember the definition of `LateInline`, the specification says:
> Inline after all symbolic transformations

So let me try to describe the situation in view of this:
- SimulationX avoids the problem by ignoring `LateInline = true`.
- System Modeler tries to respect the definition of `LateInline`, but with the consequence that events are not generated (after all, `GenerateEvents = true` is only a suggestion – not a hard requirement – to generate events as of the current specification)
- OpenModelica doesn't respect the definition of `LateInline`, but is thereby able to generate the events.
- Dymola (as reported by @HansOlsson during the [meeting above](https://github.com/modelica/ModelicaSpecification/issues/2986#issuecomment-929284678)) generates the events, but no further details have been given.
- No actual report of tool behavior from OPTIMICA Compiler Toolkit or MapleSim.

A question to @gkurzbach: Can you see how `GenerateEvents = true` could be handled at either of the later inlining stages?

While Dymola could be the only tool that both respects the definition of `LateInline` and is able to generate the events, the other three tool reports indicate some kind of conflict between inlining after all symbolic processing and generating events.  Considering this, I see some alternatives for proceeding on this issue:
- Option 1: Agree on a clear picture of how event generation can be handled after all symbolic processing.
- Option 2: Change definition of `LateInline` to not get in the way of event generation (more in line with how `LateInline` is handled by OpenModelica, but without ending up being defined equivalently to `InlineAfterIndexReduction`).
- Option 3: Don't allow `LateInline = true` in combination with `GenerateEvents = true`.

**Comment by eshmoylova** [comment]
Sorry, it took me a while to respond. In MapleSim we ignore the `GenerateEvents = true` annotation, and we treat the `LateInline = true` annotation as `Inline = false`. We only support inlining at symbolic handling stage.

**Comment by HansOlsson** [comment]
> * Option 1: Agree on a clear picture of how event generation can be handled after all symbolic processing.
> * Option 2: Change definition of `LateInline` to not get in the way of event generation (more in line with how `LateInline` is handled by OpenModelica, but without ending up being defined equivalently to `InlineAfterIndexReduction`).

I believe the problem here is that LateInline has a too simple statement. 

The intent is to do LateInline:

- After symbolic simplifications including evaluating literals
- After differentiating for index-reduction
- After transforming systems of equations to a better variant (symbolic solution, generating analytic Jacobian, etc); since those steps need the original function.

And it was assumed that the list above are "all" the symbolic transformations, but event-generation and inlining itself can be done later, regardless of whether they are seen as symbolic transformations or something else.
