### ISSUE TITLE
Missing integer zero literal in section 2.4.2

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2991]
The integer literal `0` is not properly rendered in the generated HTML:

https://github.com/modelica/ModelicaSpecification/blob/80f268aa5f113830fd85c74568381b8542dd273e/chapters/lexicalstructure.tex#L156

https://specification.modelica.org/master/lexical-structure.html#integer-literals

![grafik](https://user-images.githubusercontent.com/14896695/132254020-45309f44-d48c-4801-9463-c385f7acccfc.png)

**Comment by henrikt-ma** [comment]
Thanks!  I opened an upstream issue: https://github.com/brucemiller/LaTeXML/issues/1651

**Comment by henrikt-ma** [comment]
There's one more occurrence in https://specification.modelica.org/master/connectors-and-connections.html#overconstrained-equation-operators-for-connection-graphs.

**Comment by beutlich** [comment]
Thanks. Fix confirmed.
