### ISSUE TITLE
Confusing syntax highlighting of comment variants

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#2992]
The syntax highlighting of the comment variants, particularily the illegal case of nested block comments, seems odd in the generated HTML of section 2.2, see https://specification.modelica.org/master/lexical-structure.html#comments.

**Comment by henrikt-ma** [comment]
Are you sure?  As far as I can see, it looks consistent with the PDF and meets my expectations.

**Comment by beutlich** [comment]
Yes, it meets the expectations, but it is confusing:
* `/* comment */ & Characters between /* and */ are ignored, including line terminators.` is no valid Modelica - so why highlighting?
* The nested block comments around `model interesting` is no valid Modelica - so why highlighting?
* `model interesting` could be `model Interesting`, i.e. with a capital `I`.

**Comment by henrikt-ma** [comment]
> Yes, it meets the expectations, but it is confusing:
> 
> * `/* comment */ & Characters between /* and */ are ignored, including line terminators.` is no valid Modelica - so why highlighting?

I find the highlighting helpful for conveying the message – the code is highlighted as if it were an attempt at writing valid code in a Modelica-aware text editor.  It is a very clear way of showing that the _& Characters between_ isn't included in the comment.

I wonder, though, if the point about line terminators could have been made more clear by actually having a line terminator inside one of the comments?

> * The nested block comments around `model interesting` is no valid Modelica - so why highlighting?

See above.

> * `model interesting` could be `model Interesting`, i.e. with a capital `I`.

Yes, this is a good idea (just slightly off-topic).

**Comment by HansOlsson** [comment]
As I see it:
The & seems due to some attempt at column-mode and the text following it wasn't originally Modelica code, see: https://modelica.org/documents/ModelicaSpec34.pdf

The special highlighting of /* and */ introduced by this conversion is more cute than helpful, and I would prefer to have something that is correct Modelica code (will write it down later).

The second (illegal) nesting just raises too many questions when you start looking. Is the model interesting, what is erroneous - just the commenting or wasn't it interesting?

**Comment by HansOlsson** [comment]
My proposed text for this part:

```
// Line-comment: Everything from // to the end of the line are ignored.
"Not part of comment"
/* Comment: Characters after /* are ignored,
  including line termination. The comment ends with */
```
And the second example:
```
/* Invalid nesting of comments, the comment ends just before end
 model Interesting
  /* To be done */
 end Interesting;
*/
```

**Comment by henrikt-ma** [comment]
A minor but related remark is that it doesn't seem right to say:
> Modelica comments do not nest

as this doesn't seem true regarding the rest-of-line comments.  To resolve this, we should make sure to have separate names for the two types of comments, such as _rest-of-line comments_ and _delimited comments_, and then say:
> Delimited comments do not nest

**Comment by henrikt-ma** [comment]
As a minor suggestion, I'd put the _end_ in quotes:
```
/* Invalid nesting of comments, the comment ends just before 'end'
```

As a bigger suggestion, I'd like to point of the usefulness of rest-of-line comments for commenting out blocks of code:
> Rest-of-line comments can safely be used to comment out blocks  of code without risk of conflict with comments inside. 
 For example, consider commenting out the entire model definition below, which contains both a rest-of-line comment and a delimited comment:
```
model Obsolete
//Real commentedOutVariable;
  /* To be done */
end Obsolete;
```
> Commenting it out is a simple matter of prefixing each line with `//`, which also has the benefit over wrapping the definition in `/* … */` that no syntax highlighter is needed to see that each of these lines is commented-out; in general the surrounding `/* … */` could be arbitrarily many lines above and below, outside the field of view of a human reader:
```
//model Obsolete
////Real commentedOutVariable;
//  /* To be done */
//end Obsolete;
```

**Comment by HansOlsson** [comment]
> As a minor suggestion, I'd put the _end_ in quotes:
> 
> ```
> /* Invalid nesting of comments, the comment ends just before 'end'
> ```
> 
> As a bigger suggestion, I'd like to point of the usefulness of rest-of-line comments for commenting out blocks of code:

True, and I had to search - seems that Dymola added comment command adding "// " (and de-comment) in May 2004.

**Comment by HansOlsson** [comment]
Language group: No-one has issues with using "// " to comment out lines (add as suggestion in PR).
