### ISSUE TITLE
Comments on MCP-0032

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3005]
@christoff-buerger, I have not tried to implement a prototype for MCP-0032 but I reviewed the proposed Syntax and semantic as well as the examples in 0.4.0 version. I have a couple of questions. 

In semantic rules, it says:
> 1. D is applied before any other, non selective model extension related, modifications of B via E;

I believe that the intention is that we should be able to set the inheritance modification on any component of B, whether defined explicitly in B or inherited from some extends clause in B. In order to resolve extends clauses we usually apply any modifications on B as specified by the extends clause. From [Section 5.6.1.4](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#steps-of-instantiation):
>**The inherited contents of the element** Classes of extends-clauses of the current class are looked up in the instance tree, modifiers (including redeclarations) are merged, the contents of these classes are partially instantiated using the new modification environment, and are inserted into an extends-clause node, which is an unnamed node in the current instance that only contains the inherited contents from that base class.

So without first processing other modifications we cannot get the inherited content of the class. Maybe it should be rephrased that any other modifications of B via E that contain deselected components should be ignored without the reference for in which order they should be performed.

Another interrelated issues I have is what type of components deselection can be applied to and what to do with any equations or modifications where the deselected component is referenced. The deselection can be applied only to components, not to classes, right? All the examples I have seen only involve instances of models, blocks or connectors being deselected. All those components only appeared in connect equations. I guess it is expected that any connect equation would be removed. I could not find the direct mention of it in **Syntax and semantic**. With connect equations it is pretty straight-forward to remove those that include the deselected component, and there is a  precedent for that with conditional components. But how should modifications or other equations be treated? Should there be a restriction like for conditional components that they can only be used in connect equations?

**Comment by christoff-buerger** [comment]
I think that a lot of these questions are already captured in the MCP. I will link your individual questions to quotes from the MCP's specification in the following in the hope that it becomes clear that these issues are already well-defined.

# Question 1

 > The deselection can be applied only to components, not to classes, right?
 > All the examples I have seen only involve instances of models, blocks or connectors being deselected.

Yes. You are right. We can not deselect record instances for example, we can not deselect equations except `connect`-equations (simply because we can not refer to equations by the provided syntax). But you can for example deselect an input component like `Modelica.Blocks.Interfaces.RealInput` (thus a connector as you correctly list).

MCP answer from the _Semantic rules_ Section:

> i. A component deselection matches all equally named components of B.
> ii. A connection deselection matches all syntactical equivalent connections of B.

can be precised to

> i. A component deselection matches all equally named components of B. Such components must be models, blocks or connectors.
> ii. A connection deselection matches all syntactical equivalent connections of B.

Thus, we have two types of deselection, component and connection. There is no need to explicitly says _"that's it, it is exhaustive, nothing else can be deselected"_ because this are all types defined (and expressible by the syntax).

# Question 2

 > I guess it is expected that any connect equation would be removed. I could not find the direct mention of it in Syntax and semantic.  I could not find the direct mention of it in Syntax and semantic.

MCP answer from the _Summary_ Section:

 > Deselected elements are treated in extending models as if they never have been defined in their base-class. In case of deselected components, also all their connections are deselected.

MCP answer from the _Semantic rules_ Section:

 > Given a class C with an extends-clause E extending class B and with a deselection D, the following rules apply for D:
 >  2. D must match at least one element of B. All matched elements are excluded from inheritance to C via E (i.e., are removed from B when adding its elements to instantiate C).

I can -- and should -- for clarity extend

 > i. A component deselection matches all equally named components of B.

to

 > i. A component deselection matches all equally named components of B and all connections with such.

If you want a more formal definition, please have a look in the conference paper mentioned as **prerequisite** in the MCP. It defines the whole **semantic** formally, we only decided on a different syntax, but the terminology and formal semantic of the paper still holds: [Modelica language extensions for practical non-monotonic modelling: on the need for selective model extension](https://modelica.org/events/modelica2019/proceedings/html/papers/Modelica2019paper3B1.pdf)

# Question 3

 > Another interrelated issues I have is [..] what to do with any equations or modifications where the deselected component is referenced. 
 > [..] how should modifications or other equations be treated?

MCP answer from the _Semantic rules_ Section:

 > As a consequence of (1), deselected components must not be modified because they do not exist anymore when modifications are applied.

There are also unit tests for these kind of errors in the provided examples (i.e., models with selective model extension that must be rejected because a deselected component is modified). Cf. e.g. `SelectiveExtension_13th_Modelica_Conference.UnitTests.Negative.ModifyDeselected_1`.

# Question 4

 > In semantic rules, it says:
 >
 > > D is applied before any other, non selective model extension related, modifications of B via E;
 >
 > I believe that the intention is that we should be able to set the inheritance modification on any component of B, whether defined explicitly in B or inherited from some extends clause in B.

That is not the intention for this rule (although of course we want that we can deselect indirectly inherited components).

The reason to do deselection before modification is, because we want modifications of deselected components to be semantic errors; we want to reject such models. You can not say, _"I don't want `a`"_ **and** _"I want `a` to be modified, e.g., to have another start value"_ because you can not modify what doesn't exist.

Another motivation for this rule is, that for deselection we want to treat deselected conditional components as if they are there. We first deselect them, and then ... they are gone; it doesn't matter if their condition evaluates to `true` or `false`. It is **not** an error to deselect a conditional component whose condition would have evaluated to `false`. In other words, deselecting a conditional component is as if the component's condition evaluates to `false` **and** all its connections are deselected.

**Comment by christoff-buerger** [comment]
@eshmoylova: Do my above answers clarify all your issues? Is refinement of

 > "i. A component deselection matches all equally named components of B."

to

 > "A component deselection matches all equally named components of B and all connections with such. The matched components must be models, blocks or connectors."

tackling your main issues?

**Comment by eshmoylova** [comment]
Almost. I am still missing either the restriction that deselected components can only be used in connections or, if it's not the case, the rule specifying what happens if it is found in modifications or equations.

I also want to see if we can come up with a different rule based on your answer to Question 4. With the current formulation:
> _D_ is applied before any other, non selective model extension related, modifications of _B_ via _E_;

I have to apply first apply deselection, then other modifications, and then process extends clauses _B_, given the restrictions on how we inherit elements. That means I cannot properly deselect any elements that are not defined directly in _B_. For me to make the examples that you provide work I would need to disregard that rule. I would need to first apply non-selective modifications, then inherit all necessary elements from extends clauses in _B_ and only then apply deselection. What I can do in addition to satisfy the requirement that "deselected components must not be modified because they don't exist" is before applying non-selective modifications from _E_ check that none of them contain deselected components specified in _E_.

I would rather not have a rule that I have to immediately hack because it either does not accomplish what was intended (based on the examples and not direct specification) or contradicts another rule. I would prefer it if it was formulated as two different rules. Something like:
> "All elements need to inherited from the extends clauses in _B_ before performing deselection."
> "Non-selective model-extension-related modifications of _B_ via _E_ must not include the deselected components."

**Comment by christoff-buerger** [comment]
# Question 5:

 > I am still missing either the restriction that deselected components can only be used in connections or, if it's not the case, the rule specifying what happens if it is found in [..] equations.

Nothing special happens. If you deselect a component used in non-connection equations your model is invalid due to a name-analysis/look-up error.

Selective model extension does not violate, bypass or deactivate existing Modelica semantics.

Or as stated in the _"Backwards compatibility"_ Section:

 > Particularly, on the one hand deselections must actually deselect something whereas at the same time it is close to impossible that just deselecting something results in a valid model (consider that deselected elements are likely used somehow and are therefore missing in the resulting model because of existing Modelica well-formedness constraints like “referenced components must be declared” and “the system of equations must be well-defined”).

**Comment by christoff-buerger** [comment]
> I also want to see if we can come up with a different rule based on your answer to Question 4. With the current formulation:
 >
 >  > D is applied before any other, non selective model extension related, modifications of B via E;
 >
 > I have to apply first apply deselection, then other modifications, and then process extends clauses B, given the restrictions on how we inherit elements. That means I cannot properly deselect any elements that are not defined directly in B. For me to make the examples that you provide work I would need to disregard that rule. I would need to first apply non-selective modifications, then inherit all necessary elements from extends clauses in B and only then apply deselection. What I can do in addition to satisfy the requirement that "deselected components must not be modified because they don't exist" is before applying non-selective modifications from E check that none of them contain deselected components specified in E.

I can not comprehend the problem.
Deselection is independent of any modification. That is one of its main properties. You do not have to evaluate the conditions of conditional declarations of any base-class (because if deselected its just not there). Deselection cannot depend on any values (whether parameters or whatever); it is independent of redeclarations or any modifications. You can decide on what is deselected without considering modification, neither of your class nor its base classes.

You don't need to instantiate any classes to know that something is not there for every possible instance of the model with the deselection. An instance tree is not required.

Selective model extension operates on the syntactic level only.

Your issue that

 > That means I cannot properly deselect any elements that are not defined directly in B.

would only be the case when selective model extension would require instantiation and modification of base-classes and/or parameter evaluation to be decideable. But it doesn't.

**Comment by eshmoylova** [comment]
> # Question 5:

> Nothing special happens. If you deselect a component used in non-connection equations your model is invalid due to a name-analysis/look-up error.

Then it should be explicitly stated as such: deselecting a component that is used outside of connect equations will result in an error. It should be stated to make it clear that this is the intended outcome and not an overlooked case. If it is not stated explicitly, it leaves developers wondering what we should do in the other cases and users wondering why their models give an error that it cannot find a component when I clear deselected this component, so, of course, it is not there and why is the compiler looking for it anyway?!

I don't think that rules should be stated in the Backwards Compatibility section. Maybe I have unrealistic expectations? I thought that Syntax and semantic part of the proposal is the actual update to the rules. And I expected that the Backward Compatibility is a discussion of how those rules would affect any existing models that were written with earlier versions of the language. Hence, I believe it is insufficient to just mention that a model may become invalid if something is deselected from it in the Backwards Compatibilty section.

**Comment by eshmoylova** [comment]
> I can not comprehend the problem. Deselection is independent of any modification. That is one of its main properties. You do not have to evaluate the conditions of conditional declarations of any base-class (because if deselected its just not there). Deselection cannot depend on any values (whether parameters or whatever); it is independent of redeclarations or any modifications. You can decide on what is deselected without considering modification, neither of your class nor its base classes.

It has nothing to do with conditional components. I have not mentioned comditional components. It has to do with **inherited** components and the order of operations. Take, for example, CoupledClutches/CoupledClutches_Component.mo from SelectiveExtension_13th_Modelica_Conference 0.4.0.zip. You have:Is the model supposed to be valid. From the comments in there it looks like it is supposed to be. It has:
```
model CoupledClutches_Component
  "..."
  extends CoupledClutches_FMU(
    break torque,
    break fixed,
    break tau);
```
`torque`, `fixed`, `tau` must exist in the model, according to the proposed rules. Look at the definition of `CoupledClutches_FMU`. Do you see them in CoupledClutches/CoupledClutches_FMU.mo? No, they are not there. This is what a compiler sees if it just looks `CoupledClutches_FMU` without doing any processing. But we have:
```
model CoupledClutches_FMU
  "..."
  extends Modelica.Mechanics.Rotational.Examples.CoupledClutches(....
```
Oh, we have an extends clause. Can they be defined in there? How can I check? I need to process the extends clauses. I am supposed to process extends clauses under the specified modifications. Why? Because there might be some redeclarations that affect what is or is not defined in the class. It is not just a matter of "a =2". Yes, those have no effect on the structure of the model. But redelcarations are crucial and must be processed at that time. But I am not allowed to look at them until I process deselections. So let me process deselections first. Oh, I need to process the extends clauses for it. You get into a loop. And it makes no sense to process it that way. Except, this is what your rule and examples currently imply. Actually, the rule does not say that you need to process extends. But the examples and your responses say you do.

Hence, it would be better to clearly state that deselection can be applied to the elements defined explicitly or inherited, and that, **when applying the modifications in the extends clause _E_**, deselection modification are applied first.

**Comment by eshmoylova** [comment]
Actually, one other thing that I do not see discussed. So here is:
# Question 6:
It is not stated that classes with deselections should not be considered as valid replacements for replaceable classes for classes. Yes, it follows that the types would not match and that the tool should give an error. And, yet, we still need to mention it, so that the tools developers and the users would be aware of it. Why? Because if you do not mention it, it may be overlooked.

Consider of how choicesAllMatching is build up. Right now, some tools may look only at the extends clauses to build up the inheritance dependencies. It does not provide the exhaustive list but the minimal that should satisfy the restriction. With the proposed change that rule should be updated. If a tool developer overlooks this, it may result that some choices would be included that are not valid. Sure, there will be an error. But there will also be an angry user who says why did you show me this choice if it is not matching. So it is good to make any tool developer aware that there will be other places that need to be updated.

And, no I have not looked through all the existing earlier discussions to see if it was addressed already. If it was discussed but did not make it to the proposal, it is not part of the proposal. It can be that it is not in the proposal because it was overlooked or it can be deliberate. If it is meant to be in the proposal, it should be in the proposal. It should not be expected that the developers and the users are going to look at all discussions that led to a decision. Also, it is not healthy for the proposal. If I was to read through all the discussion, I would acquire the same biases that the authors had. It becomes hard to separate what you learned through the wider discussion from what you learned from looking just at the resulting proposal. 

These are my observations based on how I would try to implement what is written. And what I am trying to say here is: I cannot even begin to implement it because it is not clear to me what is intentional and what is overlooked. I can surmise what would make sense. But there is no guarantee that somebody else would arrive to the same conclusions, and that's where we get into lots of problems. You can take my comments or leave them. But if you were to file a PR with just the way it was written, I would ask the same questions.

**Comment by christoff-buerger** [comment]
> > # Question 5:
> 
> > Nothing special happens. If you deselect a component used in non-connection equations your model is invalid due to a name-analysis/look-up error.
> 
> Then it should be explicitly stated as such: deselecting a component that is used outside of connect equations will result in an error. It should be stated to make it clear that this is the intended outcome and not an overlooked case. If it is not stated explicitly, it leaves developers wondering what we should do in the other cases and users wondering why their models give an error that it cannot find a component when I clear deselected this component, so, of course, it is not there and why is the compiler looking for it anyway?!
> 
> I don't think that rules should be stated in the Backwards Compatibility section. Maybe I have unrealistic expectations? I thought that Syntax and semantic part of the proposal is the actual update to the rules. And I expected that the Backward Compatibility is a discussion of how those rules would affect any existing models that were written with earlier versions of the language. Hence, I believe it is insufficient to just mention that a model may become invalid if something is deselected from it in the Backwards Compatibilty section.

This is normal, already existing and well-defined Modelica semantic, part of the current Modelica Standard. I see no need to repeat how name analysis works. If an MCP changes existing semantic, or even violates such, **then, and only then**  it has to explain and specify this. But if not, I am sorry, this is not required. And selective model extension does not change the rule that everything that is used must be declared.

We can not repeat that undeclared elements are an error at each and every point in the specification where we use elements. There are existing rules that are applied and must be satisfied. I am not going to list all existing rules that have to be followed -- all in the current Modelica Standard given rules that are not explicitly changed by the MCP must be followed, without any exception.

**Comment by christoff-buerger** [comment]
> > I can not comprehend the problem. Deselection is independent of any modification. That is one of its main properties. You do not have to evaluate the conditions of conditional declarations of any base-class (because if deselected its just not there). Deselection cannot depend on any values (whether parameters or whatever); it is independent of redeclarations or any modifications. You can decide on what is deselected without considering modification, neither of your class nor its base classes.
> 
> It has nothing to do with conditional components. I have not mentioned comditional components. It has to do with **inherited** components and the order of operations. Take, for example, CoupledClutches/CoupledClutches_Component.mo from SelectiveExtension_13th_Modelica_Conference 0.4.0.zip. You have:Is the model supposed to be valid. From the comments in there it looks like it is supposed to be. It has:
> 
> ```
> model CoupledClutches_Component
>   "..."
>   extends CoupledClutches_FMU(
>     break torque,
>     break fixed,
>     break tau);
> ```
> 
> `torque`, `fixed`, `tau` must exist in the model, according to the proposed rules. Look at the definition of `CoupledClutches_FMU`. Do you see them in CoupledClutches/CoupledClutches_FMU.mo? No, they are not there. This is what a compiler sees if it just looks `CoupledClutches_FMU` without doing any processing. But we have:
> 
> ```
> model CoupledClutches_FMU
>   "..."
>   extends Modelica.Mechanics.Rotational.Examples.CoupledClutches(....
> ```
> 
> Oh, we have an extends clause. Can they be defined in there? How can I check? I need to process the extends clauses. I am supposed to process extends clauses under the specified modifications. Why? Because there might be some redeclarations that affect what is or is not defined in the class. It is not just a matter of "a =2". Yes, those have no effect on the structure of the model. But redelcarations are crucial and must be processed at that time. But I am not allowed to look at them until I process deselections. So let me process deselections first. Oh, I need to process the extends clauses for it. You get into a loop. And it makes no sense to process it that way. Except, this is what your rule and examples currently imply. Actually, the rule does not say that you need to process extends. But the examples and your responses say you do.
> 
> Hence, it would be better to clearly state that deselection can be applied to the elements defined explicitly or inherited, and that, **when applying the modifications in the extends clause _E_**, deselection modification are applied first.

Well...

 > Oh, we have an extends clause. Can they be defined in there? How can I check? I need to process the extends clauses. 

exactly. You need to consider **all** components and connect-equations of the base-class.

 > I am supposed to process extends clauses under the specified modifications.

No, modifications do not have to be considered to decide if deselections are valid and what is deselected. If you want, you can do that (if for some reason your compiler implementation would be more easy doing so) -- but it is not a requirement to implement deselections.

I can only repeat myself:
> Deselection cannot depend on any values (whether parameters or whatever); it is independent of redeclarations or any modifications. You can decide on what is deselected without considering modification, neither of your class nor its base classes. You don't need to instantiate any classes to know that something is not there for every possible instance of the model with the deselection. An instance tree is not required.

Regarding redeclarations:

 > I am supposed to process extends clauses under the specified modifications. Why? Because there might be some redeclarations that affect what is or is not defined in the class. 

No, that is wrong. Redeclarations never change the components or connections defined in the base-class. They change the components and connections **within** the redeclared components. But such cannot be deselected since deselection only works on simple names and not qualified. Thus, in a class _C_ extending _B_, whereas _B_ has a component _cb_ that has a component _ci_, we can not deselect _ci_ from _C_ because `extends B(break cb.ci)` is a syntax error; qualified names in `break` clauses of deselections are not supported according to the proposed syntax.

**Comment by christoff-buerger** [comment]
> Actually, one other thing that I do not see discussed. So here is:
> 
> # Question 6:
> It is not stated that classes with deselections should not be considered as valid replacements for replaceable classes for classes. Yes, it follows that the types would not match and that the tool should give an error. And, yet, we still need to mention it, so that the tools developers and the users would be aware of it. Why? Because if you do not mention it, it may be overlooked.
> 
> Consider of how choicesAllMatching is build up. Right now, some tools may look only at the extends clauses to build up the inheritance dependencies. It does not provide the exhaustive list but the minimal that should satisfy the restriction. With the proposed change that rule should be updated. If a tool developer overlooks this, it may result that some choices would be included that are not valid. Sure, there will be an error. But there will also be an angry user who says why did you show me this choice if it is not matching. So it is good to make any tool developer aware that there will be other places that need to be updated.
> 
> And, no I have not looked through all the existing earlier discussions to see if it was addressed already. If it was discussed but did not make it to the proposal, it is not part of the proposal. It can be that it is not in the proposal because it was overlooked or it can be deliberate. If it is meant to be in the proposal, it should be in the proposal. It should not be expected that the developers and the users are going to look at all discussions that led to a decision. Also, it is not healthy for the proposal. If I was to read through all the discussion, I would acquire the same biases that the authors had. It becomes hard to separate what you learned through the wider discussion from what you learned from looking just at the resulting proposal.
> 
> These are my observations based on how I would try to implement what is written. And what I am trying to say here is: I cannot even begin to implement it because it is not clear to me what is intentional and what is overlooked. I can surmise what would make sense. But there is no guarantee that somebody else would arrive to the same conclusions, and that's where we get into lots of problems. You can take my comments or leave them. But if you were to file a PR with just the way it was written, I would ask the same questions.

I am not sure what the open question of Question 6 is.

It looks like you found a case where your tool implementation has to take care of to stay user friendly if deselections are present. Sounds good...

...but doesn't sound like something that must be explained in the standard. If we feel the need to add such tool quality statements or tips and tricks for implementing something we should consider writing a rationale like other programming language standards.

I tend to see it the other way around: formal language specification quality increases by having short, orthogonal rules (hence, naturally combining) without repetition (which would just give rise for contradictions).

Only specify the execptions to existing rules; do not repeat again and again what is already specified to reduce specification bloat and the risk of actually really overlooking something.

**Comment by eshmoylova** [comment]
I would quote a number of cases in the specification where we had to insert clarifications, often as non-normative blocks, and links to the rules that intersect/relevant to the case. But I cannot spend any more time on this issue at this time. I will not be able to look at it for the next three weeks at least. If you care for my feedback, ping me in 4 weeks with what you want feedback on or we can postpone the discussion until the next design meeting.

**Comment by christoff-buerger** [comment]
> 
> 
> Hi!
> 
> In the section of breaking connects inside a for-equation, it may be good adding an example of a case that would not work, just for clarification purposes. Something like this
> 
> ```
> break /* for i in 2:10 */ connect(a[i + 1], b[2 * i + 1])
> ```

I will add such example to the MCP.

Note however, that your example is correct as long as the deselection matches some base-class connection. The whole connection-deselection is based on simple abstract syntax matching. Thus, as long as there is a `connect(a[i + 1], b[2 * i + 1])` clause in the base class -- regardless where, inside a for loop, just as such, whatever -- the `break connect(a[i + 1], b[2 * i + 1])` deselection matches it and would be Ok.

This means, if you have a broken base-class you can "fix" it by deselecting the broken stuff when extending. Of course, this is not a common use-case; but the related case of fixing issues due to multiple inheritance conflicts is useful (if you have for example conflicting modifications or structural different, but equally named, components, then you can fix the diamond-problem by deselecting all but one of the conflicting base-components/connections).

**Comment by christoff-buerger** [comment]
@modlfo, @henrikt-ma: Do you have any more comments I should incorporate into the MCP?

I will update now with what you have commented so far to be ready for the MAP-LANG meeting 2021-12-08 in two days.

**Comment by henrikt-ma** [comment]
> @modlfo, @henrikt-ma: Do you have any more comments I should incorporate into the MCP?
> 
> I will update now with what you have commented so far to be ready for the MAP-LANG meeting 2021-12-08 in two days.

I'm leaving this in the hands of @modlfo, so I have no additional comments for you to consider.

**Comment by christoff-buerger** [comment]
@eshmoylova, @henrikt-ma, @modlfo: I now updated the MCP, incorporating all your comments. This resulted in the new _"Non-normative explanation of some interesting consequences of the semantic rules"_ Section, which should cover all discussed interesting corner cases resulting from the proposed syntax and semantic.

Please note, that I am happy that this are **non**-normative in the sense that they are consequences that can be derived from a very small simple basic rule set. To which extend we like to add non-normative explanations/rationales in the Modelica specification is up to debate of course.

**Comment by modlfo** [comment]
@christoff-buerger no more commments on my side.
