### ISSUE TITLE
Improve criteria for start value prioritization among alias variables in Modelica

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3008]
The selection of the most appropriate start attribute for alias variables that are eventually involved in nonlinear systems of equations is a critical feature of Modelica compilers, because it can determine the success or failure of initialization in models with nonlinear initial equations systems. 

The topic is addressed in [Section 8.6.2](https://specification.modelica.org/master/equations.html#recommended-selection-of-start-values) of the specification. 

Unfortunately, the currently stated criteria seem to me not to be completely up to the task. I am constantly getting truckloads of warnings about inconsistent start values in situations where in my opinion there should be no conflict at all. I believe the whole subject should be reviewed.

I have prepared a small testsuite to illustrate some of the typical situations that arise in application libraries.

```
package Aliases
  type Temperature = Real(start = 300, unit="K");
  type Power = Real(unit="W");
  type Conductance = Real(unit="W/K");

  connector Port
    Temperature T;
    flow Power Q;
  end Port;

  model TemperatureSource
    parameter Temperature Tstart = 320;
    Temperature T1;
    Temperature T2(start = 310);
    Temperature T3(start = Tstart);
    Port port;
  equation 
    port.T = T1;
    T1 = T2;
    T2 = T3;
    T1+1e-6*sin(T1) = 300 "Implicit equation on T1";
  end TemperatureSource;

  model PowerSource
    parameter Temperature Tstart = 320;
    Port port;
    Temperature T1;
    Temperature T2(start = 330);
    Temperature T3(start = Tstart);
    Conductance G = 1;
  equation 
    port.T = T1;
    T1 = T2;
    T2 = T3;
    port.Q - G*(port.T-300) = sin(time);
  end PowerSource;

  model WrappedTemperatureSource
    parameter Temperature Tstart = 345;
    Port port;
    TemperatureSource ts(Tstart = Tstart);
  equation 
    connect(ts.port, port);
  end WrappedTemperatureSource;

  model WrappedPowerSource
    parameter Temperature Tstart = 345;
    Port port;
    PowerSource ps(Tstart = Tstart);
  equation 
    connect(ps.port, port);
  end WrappedPowerSource;

  model System1
    TemperatureSource ts;
    PowerSource ps;
  equation 
    connect(ts.port,ps.port);
  end System1;

  model System2
    TemperatureSource ts(Tstart = 350);
    PowerSource ps;
  equation 
    connect(ts.port,ps.port);
  end System2;

  model System3
    TemperatureSource ts(T1(start = 360));
    PowerSource ps;
  equation 
    connect(ts.port,ps.port);
  end System3;

  model System4
    WrappedTemperatureSource ts(Tstart = 370);
    PowerSource ps;
  equation 
    connect(ts.port,ps.port);
  end System4;

  model System5
    TemperatureSource ts;
    WrappedPowerSource ps(Tstart = 380);
  equation 
    connect(ts.port, ps.port);
  end System5;

  model System6
    WrappedTemperatureSource ts(ts(T1(start = 390)));
    WrappedPowerSource ps(Tstart = 400);
  equation 
    connect(ts.port, ps.port);
  end System6;
end Aliases;
```
At the end of the day, after alias elimination, each of these models has two unknowns: a power flow and a temperature. Everything else are aliases.

The following table reports: the start value of the temperature I would expect to see as a library developer, the start value I get with OMC v1.19.0-dev-256-g680066, and the start value I get with Dymola 2021x. Both tools select the temperature as iteration variable for the 2x2 nonlinear system.

| Test    | Exp | OMC | Dymola |
|---------|-----|-----|--------|
| System1 | 320 | 320 | 320    |
| System2 | 350 | 350 | 350    |
| System3 | 360 | 320 | 360    |
| System4 | 370 | 320 | 320    |
| System5 | 380 | 320 | 320    |
| System6 | 390 | 345 | 390    |

Apparently Dymola does a better job at capturing my expectations, at 67% success, than OMC, at 33% success. I'm not 100% sure if this is due to a better implementation of what the Specification says, which BTW is non-normative, or if implements better heuristics. However, there are at least two cases where I get values that are obviously not the ones I would expect in both tools.

@henrikt-ma, feel free to add what System Modeller does.

In order to get what I'd like, I wrote some loosely formulated requirements. They need to be formalized into actual rules for the compiler, and possibly made more compact.
- type defaults have the lowest priority, they should only be used if there are no other start value specification overriding them
- start values set by modifications when instantiating components should have higher priority than start values set by default binding equations in component declarations
- the priority of start values given by parameters should be determined on the basis of where the actual parameter value is specified
- direct specifications of the start value from the top level of the model to be simulated via nested modifiers should have the precedence over the other start values specified insied the lower-level components
- even in case the parameters are evaluated, the priority information should be computed by the frontend (particularly when evaluating parameters!) and then passed along to the backend, in order to be able to make the correct choices when performing alias elimination

**Comment by henrikt-ma** [comment]
How System Modeler handles start value prioritization is an area we'd like to improve, and until then we don't have experimental results of any value for this discussion.  I'm afraid that having truly useful criteria and making these less non-normative might be needed in order for improvement in this area to get prioritized, so in this regard I'm glad to see this issue bringing attention to the situation.

One of my concerns, however, is that very detailed criteria could lead to models with de-prioritized modifications of `start` all over the place, whose modifiers will rot over time and then come back into play unexpectedly one day when the highest prioritized `start` is no longer competing for the same initialization.  In my experience, the best models therefore have very few "conflicts" to be resolved by start value prioritization.  Hence, I think we should also consider the completely different path of reducing dependency on resolution based on priorities, and instead encourage the use of the new `break` modifiers to remove the potentially conflicting modifications of `start`.

Encouraging the use of `break` should probably not completely replace the prioritization mechanism, but the prioritization mechanism could probably be simplified (and hence more transparent to the user) if the possibility to `break` modifications is taken into account.

**Comment by casella** [comment]
> In my experience, the best models therefore have very few "conflicts" to be resolved by start value prioritization.

Consider that models with physical connectors typically have at least four aliases for each connector variable: two for the connector variable on each side of the connection (assuming only 2 connectors involved), and another two, one on each side, for equations relating the connector variables to the internal variables of the model, which is good modelling style. In case medium models from Modelica.Media are involved (e.g. BaseProperties), you may easily get another one or two more. Not easy to reduce this number substantially.

> Hence, I think we should also consider the completely different path of reducing dependency on resolution based on priorities, and instead encourage the use of the new `break` modifiers to remove the potentially conflicting modifications of `start`.

I'm not aware of this, can you give me some pointer to the concept? Thanks!

**Comment by henrikt-ma** [comment]
> > Hence, I think we should also consider the completely different path of reducing dependency on resolution based on priorities, and instead encourage the use of the new `break` modifiers to remove the potentially conflicting modifications of `start`.
> 
> I'm not aware of this, can you give me some pointer to the concept? Thanks!

I'm thinking of this MCP where @HansOlsson has been active this year:
https://github.com/modelica/ModelicaSpecification/tree/MCP/0009/RationaleMCP/0009

**Comment by casella** [comment]
I add @hubertus65 and @jespermattsson to the discussion, as I guess they are interested.
