### ISSUE TITLE
Undesired Modelica syntax hightlighting for file name

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#3009]
In section [12.9.4](https://specification.modelica.org/master/functions.html#annotations-for-external-libraries-and-include-files), in the directory structure of the example library resources, the file name package.mo is highlighted as Modelica keyword **package**, which simply is not desired here.

![grafik](https://user-images.githubusercontent.com/14896695/136086580-9568981e-7032-4021-8f5d-3004e121bfeb.png)

**Comment by beutlich** [comment]
In same section, the C code alsohas undesired Modelica highlighting.

![grafik](https://user-images.githubusercontent.com/14896695/136103475-893454ee-68a2-40a4-93f5-9c316cbb601d.png)

Should be a separate issue, I believe.

**Comment by henrikt-ma** [comment]
> In same section, the C code also has an undesired Modelica highlighting.

Looks like a LaTeXML bug; the PDF looks fine.

**Comment by beutlich** [comment]
The issue might vanish once we write

```c
EXTLIB2_EXPORT double ExternalFunc2(double);
```

or

```c
EXTLIB2_EXPORT double ExternalFunc2(double x);
```

**Comment by beutlich** [comment]
It seems, in HTML a line break is missing after the table and before "Note that calling the function".

**Comment by henrikt-ma** [comment]
> It seems, in HTML a line break is missing after the table and before "Note that calling the function".

OK. Probably to open another LaTeXML issue to be mentioned when introducing a pair of hard line breaks around the tabbing environment.  In progress…
