### ISSUE TITLE
Internal error for overconstrained stewart platform model

### ISSUE THREAD

**Issue by robertoalbanese** [modelica/ModelicaSpecification#3023]
OpenModelica v1.17.0 (64-bit)
OMSimulator v2.0.0.post284-gc8ec782-mingw
Modelica Library 3.2.3

Hello,
I'm currently working on the implementation of a dynamic model of a Stewart Platform in OpenModelica similar to the one in https://www.xarg.org/paper/inverse-kine … -platform/ (6RSS parallel robot) and apparently, I'm not able to connect multiple legs to the same platform due to the following error:

```
[1] 13:08:36 Translation Error
Internal error It is not possible to select continuous time states because Number of Equations 18 greater than number of States 17 to select from.

[2] 13:08:36 Translation Error
Internal error - IndexReduction.dynamicStateSelectionWork failed!
```

From what I have seen in the documentation of Modelica, this might be caused by some loop in the spanning tree generated during the translation phase of the model where some non-flow equations became dependent on each other resulting in an overconstrained (even if still solvable) system. I will attach the source code of the package that I have created in which there are present a base, a platform, and only two RSS legs which create the issue.
Since I'm new to Modelica, I think I'm missing some basic concepts of modelling multibody mechanics especially when kinematics loops take place. I've already made some tests on the planar loop fourbar example in the Modelica library but I think this is something different. Is there a way to solve this error and finally obtain a working model of the 6RSS parallel robot?

[sixRSS_parallelRobot.txt](https://github.com/modelica/ModelicaSpecification/files/7486544/sixRSS_parallelRobot.txt)

Thank you in advance for your help!

**Comment by HansOlsson** [comment]
This repo is for reporting issues in the specification. 
Internal errors in tools are tool-specific issues.

**Comment by HansOlsson** [comment]
For general help with models it is better to consider e.g., stackoverflow

**Comment by casella** [comment]
@robertoalbanese the right place to file issues about OpenModelica is [here](https://github.com/OpenModelica/OpenModelica/issues/new/choose).

BTW, before reporting the issue, please try with the latest release 1.18.0, or possibly even with the nightly build.

**Comment by robertoalbanese** [comment]
Thank you for your reply! And sorry for the mistake. I'll try your suggestion and then, if needed, I'll repost the issue in the right place
