### ISSUE TITLE
LaTeX rendering makes "-2" illegal

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3024]
In [Section 3.2](https://specification.modelica.org/master/operators-and-expressions.html#operator-precedence-and-associativity) there is a non-normative section under the table that makes it look like "-2" is illegal in Modelica:
![image](https://user-images.githubusercontent.com/20460714/141474076-3b01da16-f60b-4660-8ede-cb0dd971cc50.png)

Looking at the source, it looks like there might be some escape characters needed. It is written as `--` which LaTeX renders as an en-dash.
https://github.com/modelica/ModelicaSpecification/blob/57e159fbf01bd5fef085951e3e1c730faa8c6f7c/chapters/operatorsandexpressions.tex#L99-L101

Also in the caption of the table the the array construction operator appears as `\{ \}` 
https://github.com/modelica/ModelicaSpecification/blob/57e159fbf01bd5fef085951e3e1c730faa8c6f7c/chapters/operatorsandexpressions.tex#L44

Both `--` and `{}` appear correctly in the pdf.

**Comment by HansOlsson** [comment]
The second issue is reported as https://github.com/brucemiller/LaTeXML/issues/1377 so it seems we can just wait until it is fixed in LaTeXML; as I don't see any obvious good work-around.

**Comment by sjoelund** [comment]
Well, a space between them doesn't hurt that much, right? Otherwise, a zero-width space might work?

**Comment by HansOlsson** [comment]
Yes, I was planning that as a PR for the first issue, was just testing it first.

**Comment by henrikt-ma** [comment]
Now that the fix changed in the last minute from plain space to `$\hspace{0pt}$`, it turned from a nice example into a some sort of hacky workaround.  As such, there should be a comment with a link to the relevant LaTeXML issue so that we can track when it get's fixed and the workaround can be removed.
