### ISSUE TITLE
The meaning of "and scalar arguments gives no legal interpretation"

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3028]
In reviewing PR #3027 we noticed that the way it is written in Section 3.2 there is a discrepancy between singular and plural in "arguments gives":
> `a:b:c:d:e:f:g` // Not legal, and scalar arguments gives no legal interpretation.

See https://github.com/modelica/ModelicaSpecification/pull/3027#discussion_r748590706

But just correcting it to "arguments give" does not really clarify what the comment is trying to say. One interpretation is https://github.com/modelica/ModelicaSpecification/pull/3027#discussion_r748600572

The example above says:
> `x^y^z`         // Not legal, use parenthesis to make it clear

So it would make sense to me that we would address the use of parentheses here as well. To me it would make sense to say that using parentheses cannot make it clear in the `a:b:c:d:e:f:g` case because range operator returns an array and there is no legal interpretation for that.

Does anyone know what the comment is about?

**Comment by henrikt-ma** [comment]
> So it would make sense to me that we would address the use of parentheses here as well. To me it would make sense to say that using parentheses cannot make it clear in the `a:b:c:d:e:f:g` case because range operator returns an array and there is no legal interpretation for that.

Good suggestion.  It would actually be possible (except for space constraints) to expand the current comment in agreement with that interpretation:
> Not legal, and the fact that the operator takes scalar arguments gives no legal interpretation even if parentheses would be introduced.

This could be a shorter alternative that would probably still not fit in a single line:
> Not legal, and parentheses cannot make it legal since operands must be scalar.

To fit in a line, we can move some of the explanation to the running text above:
> Non-associative exponentiation and array range operator (note that the array range operator only takes scalar operands):
> …
> … // Not legal, and parentheses cannot make it legal.

**Comment by HansOlsson** [comment]
> So it would make sense to me that we would address the use of parentheses here as well. To me it would make sense to say that using parentheses cannot make it clear in the `a:b:c:d:e:f:g` case because range operator returns an array and there is no legal interpretation for that.

I believe that was the intended meaning.
