### ISSUE TITLE
"!" in "constant!variable"

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3041]
There is "!" in definitions of "constant!variable" in the code
https://github.com/modelica/ModelicaSpecification/blob/7ad198650e8ac01f6e50c700ba3e30e79eb335b4/chapters/classes.tex#L344
and it shows up in HTML and PDF too. This is from HTML:
![image](https://user-images.githubusercontent.com/20460714/142653377-ac2ea782-0472-4b1a-8526-2300364a57d6.png)

Is that some artifact of `\firstuse` definition? Or is it really intended to be called constant!variable? Same for parameter!variable.

**Comment by henrikt-ma** [comment]
Good catch.  I'll set up a fix.
