### ISSUE TITLE
Boldface and non-boldface keywords

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3044]
In 1.4 Notation and Grammar, it says:
> Boldface denotes keywords of the Modelica language.

[The table that lists the keywords in 2.3.3](https://specification.modelica.org/master/lexical-structure.html#modelica-keywords) has some in boldface and others not. I recall that there was a discussion about highlighting different types of keywords in a different way (don't want to search for it right now.) So I believe the table is as intended but Section 1.4 should be updated to reflect the syntax highlighting. Is there any other place in the Specification where it is documented what syntax highlighting means?

**Comment by henrikt-ma** [comment]
I also find it problematic that we already in the introduction go into details like this:
> Keywords are reserved words and shall not be used as identifiers, with the exception of \lstinline!initial! which is a keyword in section headings, and \lstinline!der! which is a keyword for declaration functions, but it is also possible to call the functions \lstinline!initial! and \lstinline!der!.

Doesn't this belong where the table of keywords is given?

**Comment by henrikt-ma** [comment]
There's also a similar but actually independent error in the _Modelica Concrete Syntax_ chapter:
> Boldface denotes keywords of the Modelica language.

Here, boldface refers to the highlighting of the _grammar_ language, and for this language there's no use of boldface at all.

**Comment by henrikt-ma** [comment]
Another problem is that this seems to be out of synch with actual grammar:
> Keywords are reserved words and shall not be used as identifiers, with the exception of \lstinline!initial! which is a keyword in section headings, and \lstinline!der! which is a keyword for declaration functions, but it is also possible to call the functions \lstinline!initial! and \lstinline!der!.

The grammar says
```
primary :
   …
   | ( component-reference | der | initial | pure ) function-call-args
   …
```
so there is no need to say that `der` and `initial` aren't keywords in some situations.

**Comment by henrikt-ma** [comment]
As you can see, this discussion triggered a long list of small changes in #3045.  Let's continue the discussion there.
