### ISSUE TITLE
Links to www.modelica.org or modelica.org?

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3054]
There are multiple links to https://www.modelica.org and subpages thereof in the specification:

https://github.com/modelica/ModelicaSpecification/search?l=TeX&q=www.modelica.org

However, visiting them, you get redirected to https://modelica.org (without the `www`).
Should the links use the shorter form that modelica.org seems to prefer?

**Comment by HansOlsson** [comment]
I believe it depends on how we want modelica.org to work in the future, but assumedly we want it without the "www." and thus we should use that consistently.

Looking at other sites I also notice that the "www." prefix seems to be disappearing in general  - I assume there should be some texts discussing that somewhere. (Yes, I seem to have realized this at least a decade too late.)
But searching for this disappearing isn't easy; even https://en.wikipedia.org/wiki/World_Wide_Web#WWW_prefix doesn't discuss it in detail - it just seems that everything is http(s) nowadays.
