### ISSUE TITLE
Broken link to openprod

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3055]
This link is broken:

https://github.com/modelica/ModelicaSpecification/blob/7ca3c91d4a4ba86380580f9b79a52c66418d897b/chapters/revisions.tex#L1726

**Comment by henrikt-ma** [comment]
Thanks, looks like an easy fix, but is this really what we want to link to?
https://www.openprod.org/

It doesn't look like the kind of ITEA2 project I expected…

**Comment by sjoelund** [comment]
whois says Creation Date: 2021-08-20T12:14:04Z. I guess the domain expired. archive.org says:
```
Got an HTTP 301 response at crawl time

Redirecting to...

https://www.ida.liu.se/labs/pelab/OpenProd/
```

**Comment by HansOlsson** [comment]
I agree that openprod.org seems to be something else now.

And all of the various pages seem to be in various states of decay.

https://itea4.org/project/openprod.html has an overview, and lots of documents, - but also links to non-existing http://www.ida.liu.se/~pelab/openprod 

https://www.ida.liu.se/labs/pelab/OpenProd/ was last updated 2012, and starts with a link to something non-existing and it's not clear whether it is a page for OpenProd or PELAB's OpenProd contribution.

I would say https://itea4.org/project/openprod.html is the best so far.
