### ISSUE TITLE
Broken link in produced HTML and PDF formats

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3056]
The link here is broken if you look at it in both the HTML and PDF versions:

https://github.com/modelica/ModelicaSpecification/blob/4103f3060df16f2858b1f6f4149faaa3b788866b/mls.bib#L42

**Comment by henrikt-ma** [comment]
Thanks, I'll take a look.

**Comment by henrikt-ma** [comment]
The problem is that the backslash that is supposed to guard the `&` in the URL is taken literally and getting URL encoded as `%5C`.  If those are removed from the link, it works correctly.  I'll prepare a fix, probably later today.
