### ISSUE TITLE
Parameter expressions as argument of previous()?

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3074]
In [Section 16.4](https://specification.modelica.org/master/synchronous-language-elements.html#clocked-state-variables) I read the following statements:
> A variable to which previous has been applied is called a clocked state variable.
>
>Operator 16.6 previous
>
> previous(u)
>
 >   The input argument `u` is a component expression (definition 16.6) _or a parameter expression_.

I'm not sure I understand why u can be a parameter expression. How can a parameter expression be a clocked state variable, since it is by definition constant?

**Comment by HansOlsson** [comment]
That formulation is odd, but I don't see any major reason to change it.
What should be stated is that there are two possibilities for the argument with different consequences:

- A component expression, that variable is then a clocked state variable
- A parameter expression.

If you close at least one eye and squint you can see that it is just clarifying the existing text.
