### ISSUE TITLE
HTML entry page isn't index.html

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3076]
Couldn't we be normal and rename _MLS.html_ → _index.html_?  That way, a link to the specification would look nicer, avoiding the _MLS_ abbreviation which is so often getting mixed up with with _MSL_, for example:
- https://specification.modelica.org/maint/3.5/

**Comment by sjoelund** [comment]
Or we could upload symbolic links from index.html to MLS.html

**Comment by henrikt-ma** [comment]
I suppose we should keep a symbolic link from _MLS.html_ to _index.html_, but in the long run it would really be nice to get rid of the _MLS.html_ name altogether.

**Comment by HansOlsson** [comment]
I understand @sjoelund 's idea that we just link from index.html to MSL.html; which is a simple solution. We do something similar for all of the chapters. The advantage I see is that it allows us to add more information in the directory if we want to.
It has little impact as most links are to individual chapters.

**Comment by sjoelund** [comment]
The thing with removing names is perhaps breaking old links (for master, already existing branches). It would be easier to remove it only for new branches.

**Comment by henrikt-ma** [comment]
But aren't the other links only provided for the purpose of increasing the chance of links into an older version of the specification for being valid also in a later version?  The naming of the entry file seems like a different story.

**Comment by henrikt-ma** [comment]
> The thing with removing names is perhaps breaking old links (for master, already existing branches). It would be easier to remove it only for new branches.

Yeah, suddenly removing _MLS.html_ without linking it to _index.html_ would just be a silly exception from the current attempt to keep old links valid also in newer versions.

**Comment by sjoelund** [comment]
So I guess renaming it to `index.html` and having a symbolic link `MLS.html` to `index.html` would be backwards compatible and more in line with what we would want new branches to have.

**Comment by henrikt-ma** [comment]
Since it seemed clear that we wanted to make it possible to enter at _index.html_ one way or another, I set up a #3077 where we can continue the discussion about precisely how to achieve it.
