### ISSUE TITLE
Clumsy logic with if-expressions in 'State Machines'

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3080]
The _State Machines_ chapter is full of logical expressions like this one:
```
    {if activeState == i then false else activeResetStates[i]
      for i in 1 : nStates}
```

It would be more concise and easier to make the listings look good if we could avoid all `if`-expressions where the consequence or alternative is a constant Boolean value.  For the example above, this would result in:
```
    {activeState <> i and activeResetStates[i] for i in 1 : nStates}
```

For me, this is more than just a matter of avoiding expressions going over several lines in the listings – I also find it easier to digest the expression with only logical connectives than the clumsy variant with an `if`-expression.

**Comment by henrikt-ma** [comment]
This was found when preparing #3082, so it is probably a good idea to make sure that PR is merged before initiating a fix for the present issue.

I can prepare a fix as soon as there is agreement to get rid of the clumsy logic.

**Comment by HansOlsson** [comment]
Yes, and there's also: ` max(if  t[j].from == i then 1 else 0 for j in 1:size(t,1)) == 0`
which would be  `not max(t[j].from == i for j in 1:size(t,1)) `, or `min(t[j].from <> i for j in 1:size(t,1)) `, right?

It's also good to review that the logic is complete; as I recall we had to add the sentence 'The transitions are sorted with lowest priority number last in the array; and the priorities must be unique for each value of from.' and there might be similar missing assumptions in other places.

**Comment by henrikt-ma** [comment]
> Yes, and there's also: ` max(if t[j].from == i then 1 else 0 for j in 1:size(t,1)) == 0` which would be `not max(t[j].from == i for j in 1:size(t,1)) `, or `min(t[j].from <> i for j in 1:size(t,1)) `, right?

Yes, very good suggestion.  For someone who doesn't want to do the derivation, these are my steps of verification:
- `max(if t[j].from == i then 1 else 0 for j in 1:size(t,1)) == 0`
- not (exists `j`: `t[j].from == i`)
- forall `j`: `t[j].from <> i`
- `min(t[j].from <> i for j in 1 : size(t, 1)`

**Comment by henrikt-ma** [comment]
> It's also good to review that the logic is complete; as I recall we had to add the sentence 'The transitions are sorted with lowest priority number last in the array; and the priorities must be unique for each value of from.' and there might be similar missing assumptions in other places.

Sounds like a good suggestion, but not necessarily something we need to consider part of this issue.  If we don't, it will be more straight-forward to tell when a PR is a valid fix for this issue.

**Comment by perost** [comment]
> Yes, and there's also: ` max(if t[j].from == i then 1 else 0 for j in 1:size(t,1)) == 0` which would be `not max(t[j].from == i for j in 1:size(t,1)) `, or `min(t[j].from <> i for j in 1:size(t,1)) `, right?
> 
 `product(t.from .- i) <> 0` should also be equivalent I think, but maybe that's taking it a step to far.

**Comment by HansOlsson** [comment]
> > Yes, and there's also: ` max(if t[j].from == i then 1 else 0 for j in 1:size(t,1)) == 0` which would be `not max(t[j].from == i for j in 1:size(t,1)) `, or `min(t[j].from <> i for j in 1:size(t,1)) `, right?
> 
> `product(t.from .- i) <> 0` should also be equivalent I think, but maybe that's taking it a step to far.

The product may overflow, so we should avoid that.

**Comment by henrikt-ma** [comment]
> > `product(t.from .- i) <> 0` should also be equivalent I think, but maybe that's taking it a step to far.
> 
> The product may overflow, so we should avoid that.

Yes, and I prefer staying in the Boolean domain also for conceptual reasons.

**Comment by henrikt-ma** [comment]
It sounds as there is agreement to at least get rid of the clumsy logic, so then I'm only waiting for #3082 to get merged before I can start preparing a fix.
