### ISSUE TITLE
Conversion annotation examples use too long names

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3081]
The conversion annotation examples would be much easier to format and read if we avoided long names like these:
```
convertClass(
   "Modelica.Electrical.Machines.BasicMachines.QuasiStationaryDCMachines",
   "Modelica.Electrical.Machines.BasicMachines.QuasiStaticDCMachines");
convertElement("Modelica.Electrical.Machines.Interfaces.PartialBasicDCMachine",
               "quasiStationary", "quasiStatic");
convertElement("Modelica.Electrical.Machines.BasicMachines.QuasiStationaryDCMachines.DC_ElectricalExcited",
               "quasiStationary", "quasiStatic");
```

**Comment by henrikt-ma** [comment]
This was found when preparing #3082, so it is probably a good idea to make sure that PR is merged before initiating a fix for the present issue.

**Comment by HansOlsson** [comment]
As I understand that example is built on two parts:
- Part of actual MSL conversion
- Both changing class and element in class

I guess something in Modelica.StateGraph.Temporary like 
```
   Modelica.StateGraph.Temporary.IndicatorLamp lamp;
equation
   lamp.u=time>10;
```
would work

**Comment by henrikt-ma** [comment]
> As I understand that example is built on two parts:
> 
> * Part of actual MSL conversion

I think it would be even better to not have this kind of interdependency.

> * Both changing class and element in class

Definitely sounds worth keeping.

**Comment by HansOlsson** [comment]
To me the part of actual MSL conversion wasn't to be dependent on MSL, but because it shows that such cases do occur in practice.
