### ISSUE TITLE
Handling of both choices and choicesAllMatching annotations

### ISSUE THREAD

**Issue by adrpo** [modelica/ModelicaSpecification#3084]
Currently the specification says what to do if you have choices or choicesAllMatching but says nothing if you have them both, for example:

```
replaceable model MyResistor = Resistor
  annotation(choicesAllMatching=true, 
                     choices(choice(redeclare model MyResistor=lib2.Resistor(a={2}) "cmt1"),
                                  choice(redeclare model MyResistor=lib2.Resistor2 "cmt2")));

```

Should the tool give a warning or just concatenate (or unify) both lists and display that? Any comments on this one?

**Comment by casella** [comment]
I guess they should be concatenated. 

choicesAllMatching is a nice wildcard, while the choice() annotation allows to also put specific values and stuff like that, so I don't see tham as mutually exclusive. I don't think there is any need to unify the lists (which I guess means removing duplicate terms) because that would send us down the rabbit holed of defining exactly what a duplicate is. IMO that's not worth it.

**Comment by henrikt-ma** [comment]
Yes, especially as long as `choicesAllMatching` "suffers from" _Exact criteria for inclusion in such a menu are not defined_, it sounds like combining it with `choices` could be useful.  I suppose tools can keep doing their own intelligent interpretation of `choicesAllMatching` and exclude duplicates if they want to; at least we should't prevent them from doing that by requiring them to concatenate the alternatives.

**Comment by sjoelund** [comment]
I would guess a basic set union would not be hard for any tool to implement. It's probably a similar effort to concatenation. But we might not need to specify how to present the choices, only that it is possible to specify both `choices` and `choicesAllMatching` (or: they are not mutually exclusive).

**Comment by HansOlsson** [comment]
> I would guess a basic set union would not be hard for any tool to implement. It's probably a similar effort to concatenation. But we might not need to specify how to present the choices, only that it is possible to specify both `choices` and `choicesAllMatching` (or: they are not mutually exclusive).

That would be good as a PR, and to me it seems just a clarification.

**Comment by casella** [comment]
@sjoelund, would you mind going ahead with a PR amending the specification?
