### ISSUE TITLE
Access of function inside record of instantiated class

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3089]
Please consider the following MWE:
```modelica

package MWE
  record RecordWithFunction
    function Function = GetOne;
  end RecordWithFunction;

  function GetOne "Get one"
    input Boolean GetNumber  "True: gets one, else gets zero";
    output Integer y;
  algorithm 
    if GetNumber then
    y:=1;
    else
      y:=0;
    end if;
  end GetOne;

  model Component
    RecordWithFunction recordWithFunction;
  end Component;

  model TestCase
    Component instanceComponent;
    Integer int = instanceComponent.recordWithFunction.Function(true);
  end TestCase;
end MWE;
```
The lookup rules for `instanceComponent.recordWithFunction.Function(true)` are given in [Section 5.3.2](https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#composite-name-lookup), bullet 3:
> If not found, and if the first identifier denotes a scalar component, or component[j] where component is an array of components and the indices j can be evaluated at translation time and component[j] is a scalar; and if the composite name is used as a function call, the lookup is also performed among the declared named class elements of the scalar component, and must find a non-operator function. **All identifiers of the rest of the name (e.g., B and B.C) must be classes**.

In this specific case, everything fits except the last sentence, because `B` in this case is not a class, but rather an instance `recordWithFunction` of a record of type `RecordWithFunction`. Hence, according to the specification, the model is invalid.

@sbaetzing reported this to us as an issue, because this construct is handy for one of their libraries. Besides, Dymola accepts it. @perost reports that also OpenModelica could, if we decided not to follow Section 5.3.2.

Is there any rationale for the restriction reported above in boldface, so we should really not accept this MWE, or should we lift it and allow `B` and `C` to also be instantiated components?

**Comment by HansOlsson** [comment]
> Is there any rationale for the restriction reported above in boldface, so we should really not accept this MWE, or should we lift it and allow B and C to also be instantiated components?

It also rules out more messy mixing up instances of classes; and I don't know how well they work. If it is restricted to instance.instance.instance.class.class.class that problem is avoided.

As I recall the reason for the restriction was that it did the minimum to lift the previous restriction (only classes); and the other cases weren't studied in detail as it didn't seem important. (And the original `world.gravity(...)` was added in MSL, in part due to Dymola didn't checking the restriction.)

**Comment by HansOlsson** [comment]
Note: I have tried to think if there are any issues related to declaration order for this, but I don't see any obvious ones.

**Comment by casella** [comment]
> It also rules out more messy mixing up instances of classes; and I don't know how well they work. If it is restricted to instance.instance.instance.class.class.class that problem is avoided.
> 
> As I recall the reason for the restriction was that it did the minimum to lift the previous restriction (only classes); and the other cases weren't studied in detail as it didn't seem important. (And the original `world.gravity(...)` was added in MSL, in part due to Dymola didn't checking the restriction.)

Sounds reasonable, given that the goal back then was basically to make `world.gravity()` legal right away in Modelica 3.2 rev. 1, because it was needed and worked fine, while avoiding potential further problems.

As of today, 11 years later, it seems that
- three tools actually allow instance.instance.class.class for function calls: Dymola allows it, MapleSim allows it (with good motivations, see comment by @eshmoylova), and OpenModelica could also allow it if we just removed the check that forbids it
- there is a concrete use case from Bosch-Rexroth that needs this feature, see [OpenModelica #8428](https://github.com/OpenModelica/OpenModelica/issues/8428) (the MWE from above is inspired on that).

So this sounds like a good candidate for an amendment of the specification: we have a motivating end-user case, a rationale for it, and two-thee test-implementations.

@HansOlsson, do we need to go through the entire formal MCP process, or given the small momentum can we deal with this proposal inside this ticket? In fact, it looks more like a clarification than a real change in the language.

Thanks!
