### ISSUE TITLE
Disappearing Index and References

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3093]
In HTML when you first open the [master](https://specification.modelica.org/master/) there is no Index or References entries in the menu:
![image](https://user-images.githubusercontent.com/20460714/150192021-f6b7564a-6b92-4639-87bc-5c3d0fe6c53b.png)

If you click on something in the menu (e.g. [B Modelica DAE representation)](https://specification.modelica.org/master/modelica-dae-representation.html) they appear:
![image](https://user-images.githubusercontent.com/20460714/150192366-db70bd68-badb-48c1-8be0-0ae8011fd257.png)

If you click on [References,](https://specification.modelica.org/master/bib.html) it shows the References section in the main window but References entry disappears from the menu.
![image](https://user-images.githubusercontent.com/20460714/150192510-69871ffc-ea2c-4a13-b21d-d4748b5f517a.png)

The same happens with Index. It does not happen for regular chapters that do not contain sections, e.g. B Modelica DAE representation.

**Comment by henrikt-ma** [comment]
This is a known LaTeXML bug: https://github.com/brucemiller/LaTeXML/issues/1401

I suppose it will be fixed once we switch next time we upgrade LaTeXML.

As I see it, we don't need to have an issue open to remind us about this.

**Comment by eshmoylova** [comment]
OK, closing.
