### ISSUE TITLE
Question on new line in Modelica file

### ISSUE THREAD

**Issue by christiankral** [modelica/ModelicaSpecification#3098]
Does a Modelica file have to end with a new line at the end of the file (which basically adds an empty last line)

![image](https://user-images.githubusercontent.com/4184218/150506916-2581150d-19b0-4ee5-91f1-086b0fb065fb.png)

 or is this unspecified so that the last new line can be omitted?

![image](https://user-images.githubusercontent.com/4184218/150507093-71d97ed0-5b88-4407-abb0-f901ee263c3e.png)

I was, however, not able to find anything about it in the Modelica Language Specification.

**Comment by dietmarw** [comment]
It's not Modelica specific but more general coding style specific especially when working on versioned files. See also: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

**Comment by dietmarw** [comment]
Btw, running a library through [ttws](https://github.com/dietmarw/trimtrailingwhitespaces) will always fix all files to contain the newline.

**Comment by sjoelund** [comment]
The Modelica grammar does not include whitespace, so both are equivalent according to it and should be accepted by any Modelica tool. I would recommend a trailing newline.

**Comment by henrikt-ma** [comment]
> Does a Modelica file have to end with a new line at the end of the file (which basically adds an empty last line)

Instead of seeing it as an empty line at the end, try to see it as every line ending in a newline.  (So maybe, _lineend_ would have been a better name than _newline_ – after all, we don't put a newline before the beginning of the first line.)

**Comment by christiankral** [comment]
> The Modelica grammar does not include whitespace, so both are equivalent according to it and should be accepted by any Modelica tool. I would recommend a trailing newline.

@sjoelund When I save a Modelica file in OMEdit after removing the last line in the Text View,

![image](https://user-images.githubusercontent.com/4184218/150509063-6d11a053-ef4e-47b6-8052-1122b6266c72.png)

it is saved without a *lineend* of the last line. Shall that be considered to be an issue in OpenModelica or shall that be seen as an OK behavior?

**Comment by henrikt-ma** [comment]
> @sjoelund When I save a Modelica file in OMEdit after removing the last line in the Text View,

What you removed wasn't the last line; you removed the _lineend_ of the last line, and OMEdit didn't automatically put one back for you.

**Comment by HansOlsson** [comment]
> It's not Modelica specific but more general coding style specific especially when working on versioned files. See also: https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

And in some version control systems the newline is required (for text files).
