### ISSUE TITLE
Are there good reasons to not allow nested Boolean expressions in an if-expression

### ISSUE THREAD

**Issue by gwr69** [modelica/ModelicaSpecification#3108]
I note that while something like following is legal in Modelica:

`if Boolean-expression1 or Boolean-expression2 then ... // e.g., if x < xl or x > xh then ...` 

this is not:

`if Boolean-expression1 == Boolean-expression2 then ...`

To give an example: I wanted to port interpolation related code from the well-known _Numerical Recipes Third Edition_ (Press et al., 2007, pp. 115-117) to Modelica, e.g., the function `hunt`.

There we have something in this vein:

```
function hunt
  input Real x "Value to locate in a list";
  input Real[:] xVals "Ordered list of values";
  input Integer jsav = 1 "Start index value for the search";
  output Integer res "Index for the list so that xVals[res] <= x <= xVals[res+1]";
protected
  Integer n = size(xVals, 1);
  Boolean ascendingQ "= true, if the list of values is ascending";
  Integer jl, jm, ju;
  ...
algorithm
   ascendingQ := xVals[n] >= xVals[1];
   jl := 1;
   ...
      if (x >= xVals[jl]) == ascendingQ     // this is quite elegant, but illegal in Modelica afaik
         then // hunt up ...
         else // hunt down 
      end if;
   ...
end hunt;
```

Are there good reason to not allow this or could the specs be relaxed to allow this?

**Comment by HansOlsson** [comment]
https://specification.modelica.org/master/operators-and-expressions.html#equality-relational-and-logical-operators
restricts the operands to be simple types for equality and Booleans are simply types.
For a<b the result for Booleans is explicitly defined (false<true).

**Comment by gwr69** [comment]
@casella Indeed I should mention that SystemModeler does throw an error for my use case and @maltelenz pointed me to
https://specification.modelica.org/master/modelica-concrete-syntax.html#S2.SS7.p1

Since I couldn't see a good reason for it being illegal, I raised the issue. But from what you are showing me here there should not be any issue with that use case, should there?

**Comment by gwr69** [comment]
Thanks for the clarification; the issue has obviously been raised at the correct location initially. ;-)

**Comment by perost** [comment]
> @casella Indeed I should mention that SystemModeler does throw an error for my use case and @maltelenz pointed me to https://specification.modelica.org/master/modelica-concrete-syntax.html#S2.SS7.p1

I guess the grammar is a bit nonintuitive in this case, because the rule for a relation is `arithmetic-expression [ relational-operator arithmetic-expression ]`, where the first `arithmetic-expression` in this case boils down to an `output-expression-list` instead of an `expression`.

That's a bit unexpected since an output expression list is usually used on the lhs of a function call, i.e.:
```Modelica
(a, b, c) = f();
```
So the grammar allows it, but calling it `output-expression-list` is perhaps a bit confusing in this context.

**Comment by HansOlsson** [comment]
> > @casella Indeed I should mention that SystemModeler does throw an error for my use case and @maltelenz pointed me to https://specification.modelica.org/master/modelica-concrete-syntax.html#S2.SS7.p1
> 
> I guess the grammar is a bit nonintuitive in this case, because the rule for a relation is `arithmetic-expression [ relational-operator arithmetic-expression ]`, where the first `arithmetic-expression` in this case boils down to an `output-expression-list` instead of an `expression`.
> 
> That's a bit unexpected since an output expression list is usually used on the lhs of a function call, i.e.:
> 
> ```modelica
> (a, b, c) = f();
> ```
> 
> So the grammar allows it, but calling it `output-expression-list` is perhaps a bit confusing in this context.

Which is due to the grammar having been left-factored https://en.wikipedia.org/wiki/LL_parser#Left_factoring and merged to avoid duplication and still allow:

```modelica
 (a.b+2) = f();
 ```
Here we need to parse "(" "a" "." "b" before encountering "+" to realize that it is just an expression in parenthesis and not a list of expressions to the left of a function call.

**Comment by henrikt-ma** [comment]
There actually is an underlying inconsistency in the specification here, but as the initial report above could be rather misleading I reported the underlying inconsistency separately as #3110 instead of reopening this issue.
