### ISSUE TITLE
Operator precedence table problems

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3110]
I suppose I could also have reopened #3108, but I think there is too much confusion and focus on the wrong things in that issue, so I wanted to give a fresh start for the discussion of the problem hiding behind the report of that issue.  What on first glance – also to me – clearly looked like a very tool-specific inconsistency on the System Modeler side, turns out to be a reflection of an inconsistency in the specification.  This is the first of three problems with the operator precedence table in [3.2 _Operator Precedence and Associativity_](https://specification.modelica.org/master/operators-and-expressions.html#operator-precedence-and-associativity) that I'd like to discuss in this issue.  The inconsistency in the specification lies in section 3.2's failure to clearly reflect what's in [A.2.7 _Expressions_](https://specification.modelica.org/master/modelica-concrete-syntax.html#expressions1).

These are the problems:
1. The relational operators are described as left associative (they are binary operators as far as I understand), while the grammar (for very good reasons) makes them non-associative.
1. The associativity of unary prefix `not` is not described, but the operator's associativity is non-associative according to the grammar.  (Note that a right associative unary prefix operator wouldn't have been such a bad idea either, so section 3.2 really should state what it is.)
1. I don't see how Modelica's unary prefix plus and minus can be described in terms of precedence and associativity.  Unless I am mistaken, this should be reflected more clearly in section 3.2.

I also note that the way the grammar is written, it actually doesn't define the operator associativity, meaning that we really need to rely on 3.2 as the main reference for the semantics of expression trees.  As I understand it, the way the syntax is presented in the grammar using the BNF repetition construct only makes sense for operators that are associative in the mathematical sense, such as `+` and `*`.  For example, reading the grammar alone, one wouldn't know how to evaluate `1 - 1 - 1`.

Edit: Another problem with the table is that `.^` is missing.

**Comment by henrikt-ma** [comment]
For the unary plus and minus, would it be correct to say that they have higher precedence than binary plus and minus, but that the unary use of plus and minus is not allowed following another plus or minus operator?

I should mention that for purposes of turning Modelica expression trees into valid Modelica syntax, it seems like defining unary plus and minus as being left associative with the same syntax as their binary counterparts actually produces neat and correct results.  I'm afraid, however, that this is more of a coincidence than a valid reason for defining the operators this way.

In particular, defining the unary operator as associative would make things like `+ + 1` valid syntax.  While right associativity (`(+ +) 1`) wouldn't work in Modelica at all as an operator isn't a valid operand, our grammar doesn't allow for the left associativity interpretation (`+ (+ 1)`) either.  On the other hand, defining them as non-associative with the current precedence would make them always require parentheses when more terms follow, for example `(+1) + 1` instead of `+1 + 1`.

**Comment by henrikt-ma** [comment]
We should also fix the missing semicolon after the second _expressions_ here: https://github.com/modelica/ModelicaSpecification/blob/ae71c001e106177630dde5e99811204be3bc53d4/chapters/operatorsandexpressions.tex#L58

**Comment by HansOlsson** [comment]
> I don't see how Modelica's unary prefix plus and minus can be described in terms of precedence and associativity. Unless I am mistaken, this should be reflected more clearly in section 3.2.

I don't see a problem with the current definition of precedence, matching that of binary plus/minus.
In particular this means that both  `0-2^2` and `-2^2` evaluates to `-4`, since exponentiation has higher precedence.

> In particular, defining the unary operator as associative would make things like `+ + 1` valid syntax. While right associativity (`(+ +) 1`) wouldn't work in Modelica at all as an operator isn't a valid operand, our grammar doesn't allow for the left associativity interpretation (`+ (+ 1)`) either.

For people familiar with C-like languages the problem with `+ + 1` is that if we allow that form we also have to allow `++i` meaning `+(+ i)` (due to the maximum munch principle and that we don't have any `++`operator), which is surprising for C-programmers.
And I don't see a major use case for it.

However, I agree that the precedence table should better match the grammar.

**Comment by henrikt-ma** [comment]
> > I don't see how Modelica's unary prefix plus and minus can be described in terms of precedence and associativity. Unless I am mistaken, this should be reflected more clearly in section 3.2.
> 
> I don't see a problem with the current definition of precedence, matching that of binary plus/minus. In particular this means that both `0-2^2` and `-2^2` evaluates to `-4`, since exponentiation has higher precedence.

Of course it is good that exponentiation has higher precedence.  Also multiplication and division should have higher precedence.  The problem is that the precedence needs to be the same as that of binary plus/minus, or we'd end up with the wrong meaning of `-1 + 1` (becoming `-(1 + 1)` in case of lower precedence) or giving meaning to `1 + -1` (becoming `1 + (-1)` in case of higher precedence).  As explained previously, neither left nor right associativity is what we want, and making it non-associative would call for `(-1) + 1` instead of simply `-1 + 1`.

Hence, to express what we have in the grammar, I think we need to use more than just operator precedence and associativity.

**Comment by henrikt-ma** [comment]
Another issue I'd like to sort out is the top two rows of the table.  According to the table, _Postfix array index operator_ has higher precedence than _Postfix access operator_.  Hence, `a[1].b[2]` is parsed like this:
```
(a[1]).(b[2])
```

What does the `b[2]` even mean on its own?  Shouldn't the two have equal priority with left associativity?

As usual, the grammar doesn't give the answer (and for me that is fine as long as the operator precedence and associativity table is clear):
```
component-reference :
   [ "." ] IDENT [ array-subscripts ] { "." IDENT [ array-subscripts ] }
```
