### ISSUE TITLE
Clarification of the concept of clocked variability required

### ISSUE THREAD

**Issue by d-model** [modelica/ModelicaSpecification#3116]
(Throughout this comment, if not mentioned differently, references relate to Modelica Specification 3.5.)

**Three topics are addressed in the subsequent:**

1. **Distinction of clocked variability from discrete-time variability**
2. **Clock ticks vs. 'usual' events**
3. **Specification of language elements of continuous time partitions in case they become part of a clocked discretized continuous-time partition**

### 1. Distinction of clocked variability from discrete-time variability

Clocked variability is introduced in, Section 16.8.1 as a concept orthogonal to the variability concepts introduced in Section 3.8:

> 'If not explicitly stated otherwise, an expression with a variability such as continuous-time or discrete-time means that the expression is inside a partition that is not associated to a clock. If an expression is present in a partition that is not a continuous-time partition, it is a clocked expression and has clocked variability.'

Consequently, a variable cannot have clocked variability and discrete-time variability at the same time.

In contrary: 
- Section 16.2.1 leads to the understanding, that discrete-time variables may be subdivided into piecewise-constant variables and clocked discrete-time. 
- A subpoint of Section 16 (Introduction) states: 'A discrete-time signal (such as ud) is converted to a continuous-time signal with hold.'
  Since the operator hold() converts clocked signals to continuous-time signals, this indicates that ud is discrete-time.
- The definition of continuous-time variability implies, that clocked variability is part of continuous-time variablity, see Section 3.8.4: 
> All expressions are continuous-time expressions including constant, parameter and discrete expressions.

So clocked variables seem to be a subset of discrete-time variables.

This is a contradiction, and clarification on this issue is advised.

The following suggestions would be relatively strict, come however with the advantage of more clarity: 
- Clearly distinguish between the continuous-time variability and clocked variability: 
  - continuous time variability: contains constant, parameter, discrete, and non-discrete-time variability
    -> common property: can be accessed at any time-instant, except of at clock ticks
  - clocked variability 
    -> can be only accessed at clock ticks
  - As a consequence, a signal cannot have clocked variability and discrete-time variability at once.
- Addition of clocked variability already to the list given in 3.8. (This is in line with the proposal given in the discussion of #3014, where a better integration of the synchronous system part of the standard to the first part of the standard is suggested.)
- Clear specification of the type of variability, which is accepted and returned by different operators (e.g. pre, previous, ...) 
- Related aspect: In the current draft for the FMI 3.0 standard, clocked variables have variability ‘discrete-time’. FMI 3.0 currently does not support the notion of clocked variability. (See Section 2.2.8.2 of the current FMI 3.0 draft).

### 2. Clock ticks vs. 'usual' events

Are we correct in the following understanding?

Before entering the solution of a clocked partition, the simulator has to be in a solved state, in particular any discrete variable v with v \neq pre(v) right before the clock tick, needs to be solved before entering the clocked partitions solving. On the other hand, a discrete signal v, which changes its value due to an updated value from a clocked system (v = hold(clocked_v)) triggers immediately after the clock tick an event iteration. 
- As a consequence, there might be ‘usual’ events right before or directly after a clock tick. Yet not necessarily.
- As the equations of a clocked discrete-time partition are solved at once (all clocked equations together), no event iteration should be required for the solution of clocked discrete-time partitions.
- Clocked discretized continuous-time partitions however might trigger internally events. Yet these events are not felt by / transferred to the outside of such a partition.

In summary, clock ticks are not necessarily events in the classical sense.

Suggestion (yet we are aware, that this potentially leads too far): It might be useful to explicitly differentiate between the notion of events and clock ticks :
-> Advantage: This coincides with an explicit distinction between discrete-time and clocked variability: **Discrete-time signals change value at event instants, clocked signals change value at clock ticks.**

### 3. Specification of language elements of continuous time partitions in case they are part of a clocked discretized continuous-time partition

Consider clocked discretized continuous-time partitions:
* All variables become clocked. 
* Event generating operators such as pre(), der(), etc. may then be applied to clocked variables.
* when statements, if statements, algorithm and equation sections controlling continuous time variables, in a sudden become part of a clocked partition.
* etc.

Consequently, the language elements for continuous-time partitions require complete specification for their behavior in case they become part of a clocked discretized continuous-time partition:
- Behavior of event generating operators (der(), pre(), ...) applied to clocked variables
- Equation, algorithm sections (regarding algorithm section, in the discussion of #3107, clarification need is also mentioned).
- etc.

We believe that the specification has still some need for further details in this respect.

**Related discussions:**
* Refer also to #3014 for a discussion on difference between pre and previous. 
* In #3091 clarification on names for clocked partitions is suggested. 
* In #3107 inconsistent initialization for usual algorithms and clocked algorithms is discussed.
* See also #2816, specifically https://github.com/modelica/ModelicaSpecification/issues/2816#issuecomment-790814267

**Comment by HansOlsson** [comment]
Proposed changes:

- Define that expressions in normal clocked partitions are discrete-time expressions (similarly as in when-clauses). This is important to ensure that we avoid events and we preserve variability. The clock partitioning ensures that we still don't mix them with other discrete-time expressions, so I don't see a need to introduce a new variant and define it in detail.
- It's correct that we can have event-iterations before and after the clock-ticks. Event clocks imply that there is a form of overlap between clock-ticks and event-iterations (as an event-clock could be triggered by an event iteration); so I don't see the need for a change.
- There are problems with clocked discretized continuous-time partitions (including their name). I believe we can work with the existing issues for that.
