### ISSUE TITLE
Q-Ident limiter in generated HTML

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#3122]
The Q-Ident limiter in the generated HTML looks like a right single quotation mark (= &rsquo; = U+2019), but would be syntactically more correct/consistent if displayed as apostroph (= &apos; = U+0027).

![grafik](https://user-images.githubusercontent.com/14896695/155201762-8713f5d2-7e3e-4c85-a0a4-5eec21078a56.png)

**Comment by henrikt-ma** [comment]
Yes, of course the character in the document should be the actual character in the lexical units of the language.

I can confirm that while the character in the original source is the real apostrophe, the character in the HTML is precisely what you think it looks like.  The _right single quotation mark_ is also what I get when copying the character from the PDF (this operation _could_ result in different characters depending on the PDF reader, but I would still guess that it is going to be the same regardless).

I'll give the _upquote.sty_ a try…

**Comment by henrikt-ma** [comment]
While _upquote.sty_ worked fine with pdfLaTeX, there seems to be no support in LaTeXML:
```
(Processing definitions /Users/henrikt/ModelicaSpecification/mlsshared.sty...
(Processing definitions /opt/local/share/texmf-texlive/tex/latex/upquote/upquote.sty... 0.00 sec)
(Loading /opt/local/lib/perl5/vendor_perl/5.28/LaTeXML/Package/listings.sty.ltxml...
(Processing definitions /opt/local/share/texmf-texlive/tex/latex/listings/listings.cfg... 0.01 sec) 0.24 sec)
(Loading /opt/local/lib/perl5/vendor_perl/5.28/LaTeXML/Package/color.sty.ltxml... 0.01 sec)
(Loading /opt/local/lib/perl5/vendor_perl/5.28/LaTeXML/Package/xcolor.sty.ltxml...
```

**Comment by henrikt-ma** [comment]
It turns out that the `upquote=true` option to _listings.sty_ also works with LaTeXML.  I'll set up a PR.
