### ISSUE TITLE
Missing equation in appendix B regarding discrete equations

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3127]
[Appendix B](https://specification.modelica.org/maint/3.5/modelica-dae-representation.html) of the MLS contains the mathematical descriptions of hybrid DAEs corresponding to flattened Modelica models.

Equation (B.1b) corresponds to when-equation determining the values of the discrete variables showing up on their RHS. As I understand it, the "otherwise" section should also mention Modelica variables of discrete-valued types _m_, besides Real discrete variables _z_, i.e.:
```
z = pre(z)
m = pre(m)
```
For example, in this model
```
model M
  Boolean b(start = false, fixed = true);
  Integer i(start = 0, fixed = true);
equation
  when sample(0,1) then
    b = not(pre(b));
    i = pre(i) + 1;
  end when;
end M;
```
the equations (B.1b) become:
```
0 = b - not(pre(b))
0 = i - pre(i) - 1
```
at events and 
```
b = pre(b)
i = pre(i)
```
otherwise.

Adding @bernhardbachmann, @kabdelhak, @phannebohm, @AnHeuermann to the loop.

**Comment by henrikt-ma** [comment]
To me it seems that adding the equation `0 = m - pre(m)` would be over-constrained in view of already having equation (B.1c), `m := f_m(v, c)`, which is active also at events.

**Comment by casella** [comment]
@henrikt-ma, you are right, but the problem is that you can have _some_ Boolean and Integer variables assigned in when-equations (B.1b), and _some others_ in regular equations (B.1c). This is not reflected in the current text of the specification.

Maybe we could use two different variable names to identify them, e.g. _s_ for the former and _m_ for the latter, and then add _0 = s - pre(s)_ to (B.1b).

**Comment by henrikt-ma** [comment]
> @henrikt-ma, you are right, but the problem is that you can have _some_ Boolean and Integer variables assigned in when-equations (B.1b), and _some others_ in regular equations (B.1c). This is not reflected in the current text of the specification.

No, (B.1b) is only for discrete-time `Real` variables.  All discrete-valued variables are determined by (B.1c).

**Comment by HansOlsson** [comment]
> The first equation definitely belongs to (B.1c). However, to me it's pretty obvious that the second equation does not belong to (B.1c), because it is only active upon triggering of the when-statement. For the rest of the time, `b2 = pre(b2)`, rather than `b2 = not(pre(b2))`. So, it must belong to (B.1b). But it currently doesn't, hence this ticket 😃
> 
> Do I miss something?

To me some clarification would be good, but I don't agree that it should be part of (B.1.b), since according to https://specification.modelica.org/master/equations.html#defining-when-equations-by-if-expressions-in-equality-equations transformed into ` b2=if edge(sample(0,1)) then not(pre(b2)) else pre(b2);` and thus can be part of (B.1.c).

But to me it's more unclear what B.1.c really means.

**Comment by casella** [comment]
@HansOlsson, by your argument we could also get rid of (B.1b) entirely, and pack all discrete equations into (B.1c). But that would just make it more obscure.

To me it is obvious that the formulation of (B.1b) is meant to include the transformation of a when equation into an if equation explicitly: `var = if edge(condition) then some_expression else pre(var)` is exactly what is written in mathematical form in (B.1b). My point is that I don't see why we should write this explicitly for Real discrete variables and not for Boolean and Integer discrete variables, since they are all handled exactly in the same way.

> But to me it's more unclear what B.1c really means

Why is it? It means that you can have equations outside when statments to assign Integer and Boolean variables based on all variables (continuous, discrete, derivatives, pre, parameters, time) and on some conditions rooted in relations. As in:
```
model M
  Boolean b;
equation
  b = if sin(time) > 0.5 then true else false;
end M;
```
The point of (B.1c) is that you can do that for Boolean and Integers, but not for discrete Reals:
```
model Invalid
  discrete Real x;
equation
  x = if sin(time) > 0.5 then true else false;
end Invalid;
```
This is invalid because of what is stated in section 4.4.4:
> If a Real variable is declared with the prefix discrete it must in a simulation model be assigned in a when-clause, either by an assignment or an equation. 

On the other hand, you can definitely assign Boolean and Integer variables in a when-equation. Hence my proposed update to the spec.

**Comment by phannebohm** [comment]
> ```
> model Invalid
>   discrete Real x;
> equation
>   x = if sin(time) > 0.5 then true else false;
> ```

Just to be exact, you probably want to have Real values on the RHS as well, something like 
`x = if sin(time) > 0.5 then 0.1 else 0.2;`
It should be invalid because of the missing when-equation, not because of types, right?

> ```
> end Invalid;
> ```

**Comment by casella** [comment]
Absolutely, sorry for the mistake :)

What I meant was that this model is invalid
```
model Invalid
  discrete Real x;
equation
  x = if sin(time) > 0.5 then 0.1 else 0.2;
end Invalid;
```
because discrete Real variables can only be assigned in when-equations

**Comment by henrikt-ma** [comment]
> because discrete Real variables can only be assigned in when-equations

This is one of the reasons why we should lift this restriction, and instead rely on the normal variability analysis to ensure that a variable declared `discrete` can only change at events.  That is, it would make our variability concepts more clear.  The other reason is that it would allow us to use that `x` in contexts where discrete-time variability is required without having to express its solution using a `when`-equation.

**Comment by henrikt-ma** [comment]
> The point of (B.1c) is that you can do that for Boolean and Integers, but not for discrete Reals:

I would formulate this as a guarantee rather than a possibility: The point of (B.1c) is to emphasize that all discrete-valued variables are determined by equations in solved form.  This is the key to the de facto standard fixed point procedure of dealing with "mixed equation systems".

(B.1b), on the other hand puts emphasis on the less restricted form of equations for discrete-time `Real` variables, allowing models like this:
```
model WhenSystem
  discrete Real x(start = 0.0, fixed = true);
  discrete Real y(start = 0.0, fixed = true);
equation
  when time > 0.5 then
    x = y - x + time;
    y = 0.5 * x + 1.0;
  end when;
end WhenSystem;
```

Anyway, I agree that it would be good to remind the reader of the conceptual rewriting of `when`-equations that allow `when`-equations for discrete-valued variables to be put in the form (B.1c).

**Comment by casella** [comment]
> I would formulate this as a guarantee rather than a possibility: The point of (B.1c) is to emphasize that all discrete-valued variables are determined by equations in solved form.

OK, now I get your point, discrete-valued variables have additional constraints compared to Real discrete variables. This is not immediately clear in the formulation of (B.1c), but it is explained later on in the text of the specification
> The interpretation of the solved form of (B.1c) is that given values for everything else, there is a closed-form solution for m in the form of a sequence of assignments to each of the variables of m in turn – there must be no cyclic dependencies between the equations used to solve for m

I'm still not sure I understand the _0 = f_z(v,c)_ implicit formulation, given the constraint of [Section 8.3.5.3](https://specification.modelica.org/maint/3.5/equations.html#restrictions-on-equations-within-when-equations), that requires the discrete Real variables to show up on the LHS. Maybe if we wrote _z = f_x(v,c)_ (with an equality sign, not an assigment) that would be clearer.

> (B.1b), on the other hand puts emphasis on the less restricted form of equations for discrete-time `Real` variables, allowing models like this:
> 
> ```
> model WhenSystem
>   discrete Real x(start = 0.0, fixed = true);
>   discrete Real y(start = 0.0, fixed = true);
> equation
>   when time > 0.5 then
>     x = y - x + time;
>     y = 0.5 * x + 1.0;
>   end when;
> end WhenSystem;
> ```

I agree, but it must be _z = f_z(v,c)_, I can't write them as fully implicit in the Modelica code. 

I understand this constraint is necessary in the Modelica code to figure out what are the variables to be kept constant, if they were not explicitly declared as discrete, so once it is understood who are the variables in _z_, an implicit formulation is as good as any. That said, I think _z = f_z(v,c)_ would be clearer, though I can live with the current formulation.

> Anyway, I agree that it would be good to remind the reader of the conceptual rewriting that allows `when`-equations for discrete-valued variables to be put in the form (B.1c).

Absolutely! What about: "[Note that equations in when-clauses with discrete-valued variables on the left-hand side can be cast in the form (B.1c) according to Section 8.3.5.1]".

**Comment by henrikt-ma** [comment]
> I understand this constraint is necessary in the Modelica code to figure out what are the variables to be kept constant, if they were not explicitly declared as discrete, so once it is understood who are the variables in _z_, an implicit formulation is as good as any. That said, I think _z = f_z(v,c)_ would be clearer, though I can live with the current formulation.

I think writing _z = f_z(v,c)_ sounds like a good idea as long as we can convince ourselves that it isn't too constrained in view of things such as `if`-equations inside `when`, etc.  Regarding the `if`-equations, there seems to be no major concern, as it seems clear enough how these could be rewritten using `if`-expressions.  I'll set up a PR, and then we can take it from there.

> Absolutely! What about: "[Note that equations in when-clauses with discrete-valued variables on the left-hand side can be cast in the form (B.1c) according to Section 8.3.5.1]".

I'll include that too in the PR.

**Comment by HansOlsson** [comment]
> I think writing z = f_z(v,c) sounds like a good idea as long as we can convince ourselves

I'm not convinced. The when-clauses allow constructs like:
```
  when sample(1,1) then
    x=pre(x)+sin(x)/2+time;
  end when;
```
Where the lhs-variable is used to indicate which variable to solve for, but it is still an implicit. To me want to avoid such trickery in this semantic overview.

However, we can still do better than before by having the cases:
```
0=f_z(v, c); // At events
z=pre(z); 
```

**Comment by casella** [comment]
> Where the lhs-variable is used to indicate which variable to solve for, but it is still an implicit. 

@HansOlsson, _z = f_z(v,c)_ is indeed implicit, since _v_ in the RHS also includes _z_.

We have the constraint that every equation in (B.1b) must have one element of vector _z_ in the LHS, i.e., every equation in (B.1b) _must involve at least one Real discrete variable_. The formulation _0 = f_z(v,c)_ is too generic for that, as it may actually contain some equations that do not involve elements of _z_ at all. If we write _z = f_z(v,c)_ we make that constraint visible and explicit.

Does that convince you? 😃

**Comment by henrikt-ma** [comment]
Note that in _z = f_z(v,c)_, there's also an inclusion of _z_ in _v_.  Maybe pointing this out could remove the confusion?

**Comment by HansOlsson** [comment]
> > Where the lhs-variable is used to indicate which variable to solve for, but it is still an implicit.
> 
> @HansOlsson, _z = f_z(v,c)_ is indeed implicit, since _v_ in the RHS also includes _z_.
> 
> We have the constraint that every equation in (B.1b) must have one element of vector _z_ in the LHS, i.e., every equation in (B.1b) _must involve at least one Real discrete variable_. The formulation _0 = f_z(v,c)_ is too generic for that, as it may actually contain some equations that do not involve elements of _z_ at all. If we write _z = f_z(v,c)_ we make that constraint visible and explicit.

There are two somewhat unrelated issues:
- The actual issue is whether equation 0=f_z(v, c) can be singular for z and thus lack a solution; whether f_z(v, c) has any equations without z at all is just a sub-set of that. Rewriting it as z=f_z(v, c) hides this issue. Note that we will later have to include clocked variables and equations in this and clocked equations will naturally be on such an implicit form.
- It's not obvious that z=f_z(v, c) is an implicit equation in z.

**Comment by casella** [comment]
>     * The actual issue is whether equation 0=f_z(v, c) can be singular for z and thus lack a solution; whether f_z(v, c) has any equations without z at all is just a sub-set of that.

I see what you mean. As @henrikt-ma noticed previously, conceptually you have to solve (B.1a) and (B.1b) simultaneously.

> It's not obvious that z=f_z(v, c) is an implicit equation in z.

There are many things that are not obvious in Appendix B, given this lengthy discussion :)

Maybe what would be nice could be to have one example in the non-normative part to show how the various parts of a paradigmatic Modelica model are mapped into this representation. What do you think?

**Comment by henrikt-ma** [comment]
> * It's not obvious that z=f_z(v, c) is an implicit equation in z.

Yes, and that's why this deserves being pointed out with a (possibly non-normative) comment.

To really illustrate how little the form _z = f(v, c)_ really means we could even include an example like this:
```
model CrazyWhenSystem
  discrete Real x(start = 0.0, fixed = true);
  discrete Real y(start = 0.0, fixed = true);
equation
  when time > 0.5 then
    x = x + y - time;
    y = y + 3 * x + 1;
  end when;
end CrazyWhenSystem;
```
