### ISSUE TITLE
What is the C representation of nested records?

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3128]
What is the C representation of a nested Modelica record when passed through the external function interface?

Let's use these Modelica classes:

```
record RI
  Real r;
end RI;

record RO
  record RI;
end RO;
```

Is the C representation option A:
```
struct RI {
  Real r;
};

struct RO {
  struct RI ri;
};
```

or option B:
```
struct RI {
  Real r;
};

struct RO {
  struct RI* ri;
};
```

I can read the text in https://specification.modelica.org/master/functions.html#records either way, so I think this requires some clarification.

**Comment by henrikt-ma** [comment]
One reflection regarding option A is that it seems more likely to give problems with binary compatibility between different compilers.  Even though a platform name such as `"linux64"` doesn't say very much, I'd still expect chances of binary compatibility being higher for option B.

**Comment by HansOlsson** [comment]
> What is the C representation of a nested Modelica record when passed through the external function interface?
> 
> Let's use these Modelica classes:
> 
> ```
> record RI
>   Real r;
> end RI;
> 
> record RO
>   record RI;
> end RO;
> ```
> 
> Is the C representation option A:
> 
> ```
> struct RI {
>   Real r;
> };
> 
> struct RO {
>   struct RI ri;
> };
> ```
> 
> or option B:
> 
> ```
> struct RI {
>   Real r;
> };
> 
> struct RO {
>   struct RI* ri;
> };
> ```
> 
> I can read the text in https://specification.modelica.org/master/functions.html#records either way, so I think this requires some clarification.

To me only variant A (struct within struct) is consistent with the specification; seeing that a corresponding C-record is constructed and _then_ passed as a pointer to the external function. In practice a better choice is often to send a nested element directly to/from the function.

But clarifying it would be good.
