### ISSUE TITLE
Use of noEvent inside functions

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3136]
Is the following valid?  What does it mean – will there be an event at time 1.5?
```
model M
  function f
    input Real x;
    output Real y = if x < 0.5 then x elseif noEvent(x < 1.5) then x * (x + 0.5) else 3.0;
    annotation(GenerateEvents = true);
  end f;
  Real y = f(time);
end M;
```

What if `GenerateEvents = false`?

(I have memories of having discussed this not too far ago, but I am unable to find that discussion.)

**Comment by casella** [comment]
> The obvious thing about the second case is that it wouldn't generate any events _if the model is valid_. The main question is whether it is valid to use `noEvent` in the body of a function without `GenerateEvents = true`.

Why not? If noEvent is not relevant (i.e. no events are going to be generated anyway), it will simply be ignored. From a user's perspective, I can't see any problem with that.

> Thus, the main questions are whether the model is valid as shown

I can't see any good reason why it shouldn't

> and if so, whether the use of `noEvent` inside a function can ever make any difference at all.

Of course it does, if GenerateEvents = true it makes the difference between generating an event at time = 1.5 and not generating it. 

 @henrikt-ma, maybe I am missing your point...

**Comment by henrikt-ma** [comment]
> @henrikt-ma, maybe I am missing your point...

Yes, it seems so. :)  My main point, maybe a bit hidden between the lines, is that what you say should be made crystal clear by adding a normative statement like the following to the specification of `noEvent`:
> Inside functions, `noEvent` only makes a difference in combination with the annotation `GenerateEvents = true` (see section-so-and-so), and otherwise has no effect.

I just didn't want to jump immediately to conclusions, but wanted first leave some room for any other interpretation of the current specification.  A mere 14 hours later, nobody else than you have utilized that room to express an opinion/interpretation, and I have already jumped to conclusions. :)

**Comment by HansOlsson** [comment]
> The obvious thing about the second case is that it wouldn't generate any events _if the model is valid_. The main question is whether it is valid to use `noEvent` in the body of a function without `GenerateEvents = true`.

It should be, as there is a list of operators that cannot be used in functions, and noEvent isn't on that list.

Specifically https://specification.modelica.org/master/functions.html#function-as-a-specialized-class almost seems to have copied https://specification.modelica.org/master/operators-and-expressions.html#event-related-operators-with-function-syntax excluding noEvent and smooth (it didn't actually copy it, the list for functions is older).

**Comment by henrikt-ma** [comment]
> It should be, as there is a list of operators that cannot be used in functions, and noEvent isn't on that list.
> 
> Specifically https://specification.modelica.org/master/functions.html#function-as-a-specialized-class almost seems to have copied https://specification.modelica.org/master/operators-and-expressions.html#event-related-operators-with-function-syntax excluding noEvent and smooth (it didn't actually copy it, the list for functions is older).

While this is highly relevant input to the discussion, it only shows that `noEvent` is currently not forbidden inside functions, and the list of forbidden operators in functions is of little help to the typical reader of the specification that is trying to figure out the relation between `noEvent` and `GenerateEvents`.  The semantics of `noEvent` inside functions still require a bit of reading between the lines.

**Comment by casella** [comment]
@henrikt-ma saying that `noEvent` has no effect when `GenerateEvents=false` seems quite obvious to me, since in that case no events are generated anyway. I don't think this requires much reading between the lines.

If you think this is not obvious enough I'm fine with saying it explicitly, though this seems slightly pedantic to me :)

**Comment by henrikt-ma** [comment]
Sure, it's the case when `GenerateEvents = true` that is more interesting, but it didn't see that it hurts to also cover the other case when all it takes is to add _and otherwise has no effect_.
