### ISSUE TITLE
Using homotopy inside function algorithms

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3137]
One can try to address the need to debug models using homotopy with this kind of wrapper functions.
```modelica
model TestHomotopy
  Real y1, y2;
  
  function tilHomotopy "Extended TIL Homotopy function"
      input Real actual "Actual equation";
      input Real simplified "Simplified equation";
      input String initializationMode "Initialization mode";
      input Real lambda "lambda if initialization mode is 'inputLambdaHomotopy'";
      output Real y "Result";
    
  algorithm
    if initializationMode == "homotopy" then
      y := homotopy(actual, simplified);
    elseif initializationMode == "debug homotopy" then
      y := simplified;
    elseif initializationMode == "input lambda homotopy" then
      y := (actual - simplified)*homotopy(1,0)*lambda + simplified;
    else //initializationMode == "standard"
      y := actual;
    end if;
  end tilHomotopy;

equation
  y1 = tilHomotopy(1, 1, "standard", 0);
  y2 = 1 + tilHomotopy(1, 1, "standard", 0);
end TestHomotopy;
```
The Specification, [section 12.2](https://specification.modelica.org/maint/3.5/functions.html), bars using a certain number of operators with function syntax, i.e.  der, initial, terminal, sample, pre, edge, change, reinit, delay, cardinality, inStream, actualStream. The homotopy operator was not included in the list. I'm not sure if that was intentional, or if we overlooked it.

IMO, homotopy debugging should be a tool issue, not something that you program in a Modelica library; besides, the homotopy operator is all about the structrure of _equations_, so burying it within a function algorithm, which is a kind of black box, doesn't look good to me. Hence, I would be inclined to add homotopy to that list. 

On the other hand, if the function could be inlined, then homotopy would work out of the box. I see that, e.g., Dymola supports this construct, so there may be good reasons to do otherwise.

Comments?

Adding @HSchatzTLK, @AnHeuermann to the loop.

**Comment by HansOlsson** [comment]
Note that if we discuss debug-wrappers for homotopy that can clearly also be implemented as blocks; so:
```
model TestHomotopy
  Real y1, y2;
  
  block tilHomotopy "Extended TIL Homotopy function"
      input Real actual "Actual equation";
      input Real simplified "Simplified equation";
      input String initializationMode "Initialization mode";
      input Real lambda "lambda if initialization mode is 'inputLambdaHomotopy'";
      output Real y "Result";
    
  algorithm
    if initializationMode == "homotopy" then
      y := homotopy(actual, simplified);
    elseif initializationMode == "debug homotopy" then
      y := simplified;
    elseif initializationMode == "input lambda homotopy" then
      y := (actual - simplified)*homotopy(1,0)*lambda + simplified;
    else //initializationMode == "standard"
      y := actual;
    end if;
  end tilHomotopy;
  tilHomotopy til1(actual=1, simplified=1, initializationMode ="standard", lambda=0);
equation
  y1 = til1.y;
  
  // Alternative using proposed MCP-0012.
  y2 = 1 + tilHomotopy(actual=1, simplified=1, initializationMode ="standard", lambda=0).y; 
end TestHomotopy;
```
(And enumerations are preferred over strings-faked enumerations; less risk of undetected spelling errors.)

**Comment by CSchulzeTLK** [comment]
I don't see a reason to prevent usage of homotopy() in functions in general. Simplifying function or parts of their code is also a relevant use case - e.g. simplifying pressure drop functions with inverse/LateInline annotation.

This function is not only used for "debugging" but also for "system design" - even though the string suggests debugging. The function shown above solves all issues we had.

Regarding debugging (could be interpreted as tool issue, even though the specification does not indicate how anyone could debug homotopy):
1. It is not only about the structure of equations. Whether homotopy continuously connects simple and actual solution depends on physics and the connections on system level (e.g. loopbreaker).
2. Providing dependent variables/outputs which are not part of the nonlinear system, for the lambda between 0 and 1 is crucial for interpreting physics. (Dymola continuitation.csv does not include relevant variables -> Advanced.DebugHomotopy, figure 7-9 in the paper below)
3. Generating custom residual plots of the nonlinear system with fixed lambda values in [0, 1] is also useful. (figure 1 in the paper below)
4. To fix the structure of the simple equation system, one might want to translate in separately. (equation system statistics, nonlinear systems)

https://ep.liu.se/ecp/157/052/ecp19157052.pdf

However, exporting a ModelExchange FMU with a lambda input has also been a use case. So it is not only used for initialization. There is a need to bypass the homotopy function, and use this feature for continuous time mode.

**Comment by casella** [comment]
> I don't see a reason to prevent usage of homotopy() in functions in general. Simplifying function or parts of their code is also a relevant use case - e.g. simplifying pressure drop functions with inverse/LateInline annotation.

Sure. The question is, what we should we do with homotopy() in functions if they cannot be inlined. I guess the answer is: they return the numerical result with the current lambda-value and that's it. Which is fine, except that you lose the possibility of doing further structural simplifications that may be possible at lambda = 0, because the function is a black box. This feature was proven very effective in the past, losing it can be a big deal.

> This function is not only used for "debugging" but also for "system design" - even though the string suggests debugging. The function shown above solves all issues we had.

Yes. Same consideration applies.

**Comment by HansOlsson** [comment]
> The Specification, [section 12.2](https://specification.modelica.org/maint/3.5/functions.html), bars using a certain number of operators with function syntax, i.e. der, initial, terminal, sample, pre, edge, change, reinit, delay, cardinality, inStream, actualStream. The homotopy operator was not included in the list. I'm not sure if that was intentional, or if we overlooked it.

To me der, sample, pre, edge, change, reinit, delay, inStream, actualStream simply aren't normal functions; and thus they don't fit with functions.
The cardinality is a bit borderline, but the input must be a connector so it doesn't make sense inside a function.
That leaves initial, terminal that depend on where we are in the simulation.

To me homotopy is closest to initial and terminal but still different because it has a well-defined use (returning actual-argument) even outside of simulations; making it similar to noEvent and smooth that we allow in functions.

**Comment by HansOlsson** [comment]
I don't see that we need to change anything here.

**Comment by casella** [comment]
@HansOlsson just for clarification: "no change" means that homotopy() is indeed allowed inside function algorithms, and whether or not the lambda = 0 case can be implemented efficiently is a tool issue?

**Comment by HansOlsson** [comment]
> @HansOlsson just for clarification: "no change" means that homotopy() is indeed allowed inside function algorithms, and whether or not the lambda = 0 case can be implemented efficiently is a tool issue?

Yes.

**Comment by HansOlsson** [comment]
Seems best to leave as is.
