### ISSUE TITLE
Allow to access multiple delay times in the same delay buffer

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3138]
Pure advection phenomena can be efficiently modelled in Modelica by means of the delay() operator. In some cases, however, there are parasitic phenomena, such a friction in wave propagation models, or heat losses in thermal advection models, that require to access the values of _the same_ variable with different delays, e.g.
```modelica
model M
  input Real v_in;
  Real v_out;
  Real v_delay[N];
  parameter Real tau "total delay";
  parameter Integer N "number of intervals";
equation 
  for i in 1:N loop
    v_delay[i] = delay(v_in, i*tau/N);
    v_out = some_function(v_delay);
  end for;
end M;
```
This model works, but it is not very efficient, because each delay operator maintains its own delayed interpolated buffer _of the same variable_ v_in.

We could have a much more efficient implementation if we could call a single, vectorized delay operator, that maintains a unique interpolated buffer of the input variable, but returns an array of outputs corresponding to different delay values, e.g.:
```modelica
model M2
  input Real v_in;
  Real v_out;
  Real v_delay[N];
  parameter Real tau "total delay";
  final parameter taus[N] = (1/N)*linspace(1, N, 1);
  parameter Integer N "number of intervals";
equation 
  v_delay = delay(v_in, taus);
  v_out = some_function(v_delay);
end M;
```
In order to make this possible, the current definition of delay in [Section 3.11](https://specification.modelica.org/maint/3.5/operators-and-expressions.html#modelica:delay) is not good enough, because it allows for vectorization with the rules of [12.4.6](https://specification.modelica.org/maint/3.5/functions.html#scalar-functions-applied-to-array-arguments). These would work in delay(v,t) if v is a scalar and t is an array, but won't work if v is an array, because in this case you'd like to have a 2D array output, where you get _the whole_ array delayed by each of the time values, not each value of the input array delayed by the corresponding delay time.

What do you think?

Keeping @perost, @AnHeuermann and @HSchatzTLK in the loop.

**Comment by HansOlsson** [comment]
To me the sharing is an implementation issue for tools.
However, it's not trivial that sharing the delay-buffer for different delays for the same variable is ideal, since the delay-buffer may have limited temporal resolution, and the sharing may thus cause some results to be degraded.

For the vectorization we only have auto-vectorization of functions returning scalars; any other case is most easily handled by manual vectorization - like `{delay(v[i],t) for i}`. To me that gives extra clarity.

**Comment by casella** [comment]
> To me the sharing is an implementation issue for tools. 

Possibly. The problem is that real users out there find the performance of existing tools dismay, and then they implement their own solutions using external functions. Which is not forbidden, of course, but is not particularly efficient.

>However, it's not trivial that sharing the delay-buffer for different delays for the same variable is ideal, since the delay-buffer may have limited temporal resolution, and the sharing may thus cause some results to be degraded.

Sorry, I don't get this. The temporal resolution is decided when the input of delay() is sampled. Then, it's only a shifting buffer, it doesn't really matter how long the delay is (provided there is enough memory for the buffer, of course). Do I miss something?

**Comment by HansOlsson** [comment]
> > To me the sharing is an implementation issue for tools.
> 
> Possibly. The problem is that real users out there find the performance of existing tools dismay, and then they implement their own solutions using external functions. Which is not forbidden, of course, but is not particularly efficient.

Those problems seems due to using external functions instead of external **objects**.

> > However, it's not trivial that sharing the delay-buffer for different delays for the same variable is ideal, since the delay-buffer may have limited temporal resolution, and the sharing may thus cause some results to be degraded.
> 
> Sorry, I don't get this. The temporal resolution is decided when the input of delay() is sampled. Then, it's only a shifting buffer, it doesn't really matter how long the delay is (provided there is enough memory for the buffer, of course). Do I miss something?

There are other alternatives as not all tools use that mechanism; and even if that were used - what happens if there is not enough memory for the buffer?

**Comment by casella** [comment]
> Those problems seems due to using external functions instead of external **objects**.

I don't mean that they are slow. I mean that reinventing the wheel is not what Modelica was designed for :)

**Comment by HansOlsson** [comment]
I don't see that we should add anything for this.

**Comment by casella** [comment]
@HSchatzTLK, you may add your point of view as a library developer that had this kind of needs.
