### ISSUE TITLE
Should parameter input be explictly forbidden?

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3141]
An OpenModelica user, @Amuri44, recently tried this construct
```modelica
parameter input Real X1 = 1
```
believing that it would lead to a tunable parameter when exporting the model into an FMU (because of the "input" prefix). Of course he got all kind of nonsense. See discussion in [OpenModelica #8568](url).

I understand the current language specification doesn't say anything about the semantics of this combination. On one hand, this is hardly a novelty - there are many possible Modelica code fragments whose semantics is unspecified and, as I understood some time ago in a discussion with @adrpo, trying to enumerate them all and forbid them explicitly might probably be a daunting task, if ever possible.

On the other hand, the fact that an end user tried this out assuming it made sense (it's a parameter, but it's also an input, so it can be changed at runtime, somehow) probably gives us a stronger motivation to make it explicit that the combinations "parameter input" and "input parameters" make no sense in Modelica, and should then generate an explicit compiler error, rather than unspecified behaviour (e.g., the input keyword is just ignored). @TorstenBlochwitz suggested me to open a ticket here about this.

What do you think?

It may also be worth considering some annotations to explicitly specify that one want as parameter to end up as tunable in an FMU, see #3140.

**Comment by henrikt-ma** [comment]
I find `discrete input` to be a closer match to tunable parameters in FMI.  What's missing is a way of telling tools that the value of this input should be specified using the GUI for tunable parameters instead of some other mechanism for exogenous model input signals.  Am I missing something else one would need?

I don't see a problem with allowing a top level `parameter input`.  I'd expect it to be an input signal that is required to have the same value throughout the simulation.  That is, it's like a parameter, but the value is sent via an exogenous model input signal rather than through the usual mechanism for setting parameters during model initialization.

**Comment by casella** [comment]
> I don't see a problem with allowing a top level `parameter input`. I'd expect it to be an input signal that is required to have the same value throughout the simulation. That is, it's like a parameter, but the value is sent via an exogenous model input signal rather than through the usual mechanism for setting parameters during model initialization.

This would be quite confusing in terms of balanced models, see [Section 4.7](https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#balanced-models). 

The _local number of unknowns_ is defined as "the number of unknown variables inside it (excluding parameters)", so it won't be an unknown, being a parameter. However, the _local equation size_ includes "the number of top level public input variables that neither are connectors nor have binding equations".

Therefore, adding a parameter input to a balanced model would automatically make it unbalanced, because it increases the local equation size but not the local number of unknowns. I'd find this a bit odd.

> I find `discrete input` to be a closer match to tunable parameters in FMI.

This would at least keep the balancing, but I'd find it odd that a variable with discrete variability counts as a parameter.

As I understand, the concept of tunable parameter in FMI is that it is just a parameter, for which it makes sense to conceptually stop the simulation, change its value, and then start another simulation with an initial state equal to the previous final state. It is not really a discrete variable.

**Comment by henrikt-ma** [comment]
> The _local number of unknowns_ is defined as "the number of unknown variables inside it (excluding parameters)", so it won't be an unknown, being a parameter. However, the _local equation size_ includes "the number of top level public input variables that neither are connectors nor have binding equations".

The confusion comes from the impression that a `parameter input` would be a parameter.  I'd say it's not; it is an input with parameter variability.  Crystal clear!

**Comment by HansOlsson** [comment]
> > The _local number of unknowns_ is defined as "the number of unknown variables inside it (excluding parameters)", so it won't be an unknown, being a parameter. However, the _local equation size_ includes "the number of top level public input variables that neither are connectors nor have binding equations".
> 
> The confusion comes from the impression that a `parameter input` would be a parameter. I'd say it's not; it is an input with parameter variability. Crystal clear!

But an input with parameter variability is something you in Modelica (not discussing how to externally run models) would have to treat as if it were a parameter: you give it a value and the value is of parameter-variability.

So it's a 'parameter'; and the 'input' is just causing confusion.

**Comment by HansOlsson** [comment]
> As I understand, the concept of tunable parameter in FMI is that it is just a parameter, for which it makes sense to conceptually stop the simulation, change its value, and then start another simulation with an initial state equal to the previous final state. It is not really a discrete variable.

The problem with this is that whether it 'makes sense to conceptually' stop the simulation is complicated to determine, and would require that modelers re-think their models to see if this is true or not.

**Comment by casella** [comment]
> > The _local number of unknowns_ is defined as "the number of unknown variables inside it (excluding parameters)", so it won't be an unknown, being a parameter. However, the _local equation size_ includes "the number of top level public input variables that neither are connectors nor have binding equations".
> 
> The confusion comes from the impression that a `parameter input` would be a parameter. I'd say it's not; it is an input with parameter variability. Crystal clear!

I respectfully disagree. Understanding the difference between being a parameter and having parameter variability seems rather subtle to me.

**Comment by casella** [comment]
> The problem with this is that whether it 'makes sense to conceptually' stop the simulation is complicated to determine

I agree. In fact, I found this concept in the FMI standard a bit awkward. Maybe @TorstenBlochwitz can comment on why it was introduced in the first place, I guess there was some user requirement about it.

> and would require that modelers re-think their models to see if this is true or not.

Yes. That's why I understood this is currently considered as a tool issue, and maybe rightly so.

**Comment by henrikt-ma** [comment]
> > The confusion comes from the impression that a `parameter input` would be a parameter. I'd say it's not; it is an input with parameter variability. Crystal clear!
> 
> But an input with parameter variability is something you in Modelica (not discussing how to externally run models) would have to treat as if it were a parameter: you give it a value and the value is of parameter-variability.
> 
> So it's a 'parameter'; and the 'input' is just causing confusion.

Sure, it causes confusion if you are going to treat it just like any non-directional parameter.  I just wanted to point out that there's another interpretation that comes naturally to me.  On the other hand, I can't say I'm keen on pushing for standardization of this interpretation, and would hence be fine with forbidding top level connectors to combine `parameter` with `input`.

However, I think we should be careful to not disallow the combination `parameter input` more generally, as I think that might both risk conflicts with existing semantics for parameters in connectors, as well as unintentionally constrain use in functions that we haven't even talked about here.

**Comment by casella** [comment]
> as well as unintentionally constrain use in functions that we haven't even talked about here.

BTW, it is not even clear what parameters in functions mean, let alone parameter inputs, see #1594.

**Comment by HansOlsson** [comment]
So, the simple proposal is: A variable declared as `parameter `or `constant `cannot also be an `input`.
Even though we haven't discussed `constant input` it makes even less sense to me.

Note: `discrete input`, and `parameter output` are both difficult to use in practice, but sort of have well-defined semantics - thus I don't see a similar need to forbid them.

**Comment by henrikt-ma** [comment]
> Note: `discrete input`, and `parameter output` are both difficult to use in practice, but sort of have well-defined semantics - thus I don't see a similar need to forbid them.

Could you elaborate each these cases?  Maybe it would make the arguments about `parameter input` more clear…

**Comment by HansOlsson** [comment]
A `parameter output` is simple - it indicates that it is an output (so intended to be used externally) with parameter-variability.
Many example models (in particular in Machines-library) have a number of outputs, to give interesting characteristics - if one of them were fixed statically it could be declared as a parameter.

A `discrete input` (Real) must be given externally to the model, and must be given a value in a when-clause.
A minor caveat is that if not a connector it must be given as a modifier.

Combined the following should thus be a valid model:
```
package P
  connector C=Real;
  model T1
    discrete input C x;
    Real y;
  equation 
    der(y)=x;
  end T1;

  model T2
    T1 t1;
  equation 
    when sample(1,1) then
      t1.x=time;
    end when;
  end T2;
end P;
```
This idea of setting connector inputs from the outside instead of using a connect-statement is standardized (but don't overuse it). Note that something similar is not possible for `parameter input` as connectors cannot have the parameter-prefix.

**Comment by henrikt-ma** [comment]
> Combined the following should thus be a valid model:

It's an interesting model, but I am surprised that it is valid in view of this statement in the specification:
> The variable assigned in a \lstinline!when!-clause shall not be defined in a sub-component of \lstinline!model! or \lstinline!block! specialized class.

(This wouldn't have been an issue if `discrete` was just a variability prefix similar to `parameter` or `constant`.)

**Comment by HansOlsson** [comment]
> > The variable assigned in a \lstinline!when!-clause shall not be defined in a sub-component of \lstinline!model! or \lstinline!block! specialized class.
> 
> (This wouldn't have been an issue if `discrete` was just a variability prefix similar to `parameter` or `constant`.)

Ah, well - we always have 'discrete input Integer x'; where 'discrete' is redundant - since the when-clause part is only for Reals.

**Comment by HansOlsson** [comment]
Conclusion from phone meeting: forbid 'parameter input'
