### ISSUE TITLE
Bad Event clock examples

### ISSUE THREAD

**Issue by m-kessler** [modelica/ModelicaSpecification#3143]
In the chapters _Operator 16.11 shiftSample_ and _Operator 16.12 backSample_ the following exemplary code is used to create event clocks:

```
//  _Operator 16.11 shiftSample_ 
Clock u = Clock(sin(2 * pi * time) > 0, startInterval = xx)

//  _Operator 16.12 backSample_ 
Clock u = Clock(sin(2 * pi * time) > 0, startInterval = 0.0);
```

I suggest to replace these examples, as they are potentially dangerous and give users a wrong impression, how event clocks shall be used. Of course you can do that, but such event clocks can easily break and give unexpected results (at least in Dymola and OpenModelica).

Just simulate this example with default settings (Dassl, equidistant time grid on, 500 output points) in Dymola 2022x or OpenModelica v1.18.1:

```
model EventClock
  Clock clock = Clock(sin(2*Modelica.Constants.pi*10000*time)>0);
  Integer counter(start=0);
equation 
  when clock then
    counter = previous(counter) + 1;
  end when;
end EventClock;
````

`counter` should be 10000 at `t=1s`, but Dymola 2022x gives 3910 and OpenModelica v1.18.1 gives 0.

The reason for that is that the tools fail to detect the zero crossing due to large integrator steps _(when the number of output points are increased we get correct results in both tools, as we force the integrator to take smaller steps)_.

**Comment by henrikt-ma** [comment]
I don't see that this has much to do with event clock issues.  Isn't it just as much a problem that a `Boolean` variable assigned to the event clock condition would have a similar error in the number of positive edges, or that the condition placed directly as the `when`-clause condition wouldn't give the expected number of events?

To me it seems fine to use the examples as they are considering that the problems seen when cranking upp the frequency to 10000 Hz is a fundamental problem with zero crossings that it's hard to do much about in the specification.

I would, however, see a point in not using this kind of triggering expression that allows the clock to be more robustly constructed using one of the other clock constructors.  A frequency sweep, for example, wouldn't allow the clock to be easily expressed in the other forms.

**Comment by casella** [comment]
This is a problem of event detection, not of Clocked variables _per se_. I agree we could add a non-normative warning about this potential issue.

**Comment by henrikt-ma** [comment]
> This is a problem of event detection, not of Clocked variables _per se_. I agree we could add a non-normative warning about this potential issue.

But then that warning should be placed where we discuss general event-generating relations, not when talking about synchronous language features.

**Comment by m-kessler** [comment]
You are both right, this is a general event detection problem and can happen in other cases as well. But when you want to learn about event clocks and read the spec, you are guided into a direction which can make troubles with the tools we have at the moment.
