### ISSUE TITLE
What is the definition of "null region"

### ISSUE THREAD

**Issue by jespermattsson** [modelica/ModelicaSpecification#3150]
Section [18.6.3 Extends-Clause](https://specification.modelica.org/master/annotations.html#extends-clause) says:

> If the extent of the extends-clause defines a null region (the default), the base class contents is mapped to the same coordinates in the derived class, and the coordinate system (including preserveAspectRatio) can be inherited as described in [section 18.6.1.1](https://specification.modelica.org/master/annotations.html#coordinate-systems).

But "null region" is not defined anywhere. I can see 4 possibilities for its meaning:
1. A region with zero area (i.e. x1 = x2 _or_ y1 = y2)
2. A point-shaped region (i.e. x1 = x2 _and_ y1 = y2)
3. Exactly the default value (i.e `{{0, 0}, {0, 0}}`)
4. The annotation does not contain an extent, so the default value is used.

What is the intended interpretation?

I would interpret it as nr 1, but such extents are allowed for `Text`, making it somewhat weird to call that a "null region".

Also, [18.6.1.1 Coordinate Systems](https://specification.modelica.org/master/annotations.html#coordinate-systems) uses "null-region" instead of "null region".

**Comment by HansOlsson** [comment]
But even if zero-areas are allowed for Texts, they have a separate meaning.
And it doesn't look sense if all of the graphics is collapsed to a line.
Having something special whether the extends is specified or not would be awkward, and seems unnecessary.

So I would go with the more general 1 unless someone can find a reason not to.

**Comment by henrikt-ma** [comment]
Simply 4 could have been elegant in my opinion, but it doesn't really work as long as `extents` has a clear default — making a difference between relying on the default and explicitly providing the same value is often causing confusion.  Hence, I think 4 would only make sense as a special case of 3 at the moment.

Aren't 1 and 2 just confusing as they invite users to set up `extent` in obscure ways, when all it means is the same as the default?

I like 3 because it means we get the inheritance unless the `extent` has been specified – with the single exception of specifying it exactly as `{{0, 0}, {0, 0}}`.

**Comment by jespermattsson** [comment]
I agree with Henrik's points, but would like to add that if we go with 3, then using an extent matching case 1 or 2 would still be very confusing - from the user's point of view the graphics from the extended class would just disappear (and a line or point would be added, but that might not be that obvious).

**Comment by HansOlsson** [comment]
> I agree with Henrik's points, but would like to add that if we go with 3, then using an extent matching case 1 or 2 would still be very confusing - from the user's point of view the graphics from the extended class would just disappear (and a line or point would be added, but that might not be that obvious).

Yes, so I would propose to state that null-region mean `{{0, 0}, {0, 0}}` (specified or as default) and other zero-area extents shall not be used.
That means that for other zero-area extents:

- We could later give them some meaning (similarly as for Text).
- Since they shall not be used we can ensure that they are not used etc.

**Comment by jespermattsson** [comment]
> Yes, so I would propose to state that null-region mean `{{0, 0}, {0, 0}}` (specified or as default) and other zero-area extents shall not be used. 

That works for me. What do you propose should happen if the user uses some other zero-area extent despite the "shall not be used"? An error seems too strong to me. We could just say that the result is unspecified in that case.

**Comment by henrikt-ma** [comment]
I think it would be better to not reserve corner cases for special meanings in the future; I think the zero width texts have already caused enough confusion that could have been avoided with a simple Boolean flag like `fitToWdith = true`.

This way, it should be sufficient to just give a non-normative warning about the unpleasant consequences of using any other zero area `extent` than the special `{{0, 0}, {0, 0}}`.

Further, I suggest that we also explicitly cover the case of reversed borders before we consider ourselves done with this discussion.  That it, what is the consequences of specifying `extent = {{0, 0}, {-1, 1}}`?

**Comment by HansOlsson** [comment]
> > Yes, so I would propose to state that null-region mean `{{0, 0}, {0, 0}}` (specified or as default) and other zero-area extents shall not be used.
> 
> That works for me. What do you propose should happen if the user uses some other zero-area extent despite the "shall not be used"? An error seems too strong to me. We could just say that the result is unspecified in that case.

Another alternative is to not specify them, so we have:
1. State that null-region mean `{{0, 0}, {0, 0}}` (default or specified) and any other zero-area extent shall not be used.
2. State that null-region mean `{{0, 0}, {0, 0}}` (default or specified) and that if the region has non-zero area it is mapped to that.
3. State that null-region mean `{{0, 0}, {0, 0}}` (default or specified).

**Comment by HansOlsson** [comment]
> I think it would be better to not reserve corner cases for special meanings in the future; I think the zero width texts have already caused enough confusion that could have been avoided with a simple Boolean flag like `fitToWdith = true`.

A separate flag is not good the way modifiers are handled in Modelica, as that requires modifying two things.
It would work with optional types or something things.

> Further, I suggest that we also explicitly cover the case of reversed borders before we consider ourselves done with this discussion. That it, what is the consequence of specifying `extent = {{0, 0}, {-1, 1}}`?

The logical conclusion is that it will be mirrored, and it works in some tools. Even if I don't see a major use for it I think that makes sense.

Note that we had some problem with reverse borders for components or bitmaps, but they are now fully supported - so it makes sense that this construct also supports it.
The reason for the problem in those cases was was that when graphically constructing a component it is easy to construct a "mirrored" extent, but I don't see a major similar issue for IconMap/DiagramMap.

**Comment by henrikt-ma** [comment]
> The logical conclusion is that it will be mirrored, and it works in some tools. Even if I don't see a major use for it I think that makes sense.

I agree, but in view of the historical unclarity/problems with bitmaps I think we owe the readers to be explicit about defining it in the "sensible" way.

**Comment by jespermattsson** [comment]
If I understand correctly, we are in agreement to define "null region" as `{{0, 0}, {0, 0}}`, but there is some disagreement on the surrounding details?

**Comment by HansOlsson** [comment]
> If I understand correctly, we are in agreement to define "null region" as `{{0, 0}, {0, 0}}`, but there is some disagreement on the surrounding details?

We agree that if you want to have a null region you should either leave it un-modified or use `{{0, 0}, {0, 0}}`.

The disagreement is whether other regions with zero area should be:

- Not specified or error
- Handled the same as that null-region (seems redundant)
- Handled as if a non-null-region (leading to invisible graphics - I don't understand why anyone would like that)
(Possibly with different answer for other regions with zero extent and with zero area.)

**Comment by henrikt-ma** [comment]
The following is not a strong argument in favor of allowing zero area to simply mean transform into line/point, but still worth mentioning: Until there is a way to use selective model extension to avoid inheriting the base class' icon, being able to transform the base class' icon into a zero area region could be a good alternative to covering the base class' icon with a filled rectangle before painting over it.

**Comment by HansOlsson** [comment]
Only `{{0,0},{0,0}}` as null-region. Non-normative: Any other zero-sized area will give invisible results, reversing the order will mirror the base-class contents.
