### ISSUE TITLE
Broken tables in HTML master

### ISSUE THREAD

**Issue by perost** [modelica/ModelicaSpecification#3156]
It seems some tables are broken in the HTML-rendering of master, for example the inheritance table in [7.1.3](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#restrictions-on-the-kind-of-base-class) (note how `expandable connector` incorrectly spans several columns):
![inheritance_table](https://user-images.githubusercontent.com/4406023/165508396-cf74f28f-c733-4578-8526-ccaa62f5e704.png)
Other tables with similar issues are e.g. the operator precedence table in [3.2](https://specification.modelica.org/master/operators-and-expressions.html#operator-precedence-and-associativity) and many tables in [10](https://specification.modelica.org/master/arrays.html) where entire columns are missing text.

I get the same issue in both Firefox and Chrome, and the missing text is actually missing in the HTML source code so it's not just a browser rendering issue. The PDF is fine though, as is the HTML for older versions of the specification.

**Comment by HansOlsson** [comment]
I believe it is best to start understanding the ones in chapter 10 - since the inheritance table has way too much special code; and my first guess is that it is a regression related to the double hline.

**Comment by henrikt-ma** [comment]
OK.  I put it on my to-do list to reproduce one of the problems in chapter 10 with a minimal example.

**Comment by henrikt-ma** [comment]
I guess it is, as I cannot reproduce any of these problems.

**Comment by henrikt-ma** [comment]
I guess we should still report this to LaTeXML, as it used to work with unguarded `\lstinline`?

**Comment by HansOlsson** [comment]
> I guess we should still report this to LaTeXML, as it used to work with unguarded `\lstinline`?

Yup, already done; see link above.

**Comment by henrikt-ma** [comment]
Ah, I didn't pay attention to the automatically generated links.  That's great!
