### ISSUE TITLE
Restrictions on sections in type

### ISSUE THREAD

**Issue by perost** [modelica/ModelicaSpecification#3157]
[4.6](https://specification.modelica.org/master/class-predefined-types-and-declarations.html#specialized-classes) states that the restrictions on `type` are:
> May only be predefined types, enumerations, array of type, or classes extending from type.

[4.5.2](https://specification.modelica.org/master/class-predefined-types-and-declarations.html#combining-base-classes-and-other-elements) adds some more restrictions by saying that it's not allowed to combine an extends from a simple type with other extends or components.

But besides that there doesn't seem to be any other restrictions on what a `type` is allowed to contain, even though there doesn't seem to be much point in allowing types to have equations or algorithms (and e.g. Dymola forbids that). It seems to me that types should just have the same restriction as records and connectors of only being allowed to have public sections.

If that restriction is added then the restrictions on `record` and `connector` can also be simplified a bit. It currently says:
> Only public sections are allowed in the definition or in any of its components

The _"or in any of its components"_ part will become redundant in that case, since the only allowed components in records (record and type) and connectors (connector, record and type) will have that same restriction anyway.

**Comment by HansOlsson** [comment]
> It seems to me that types should just have the same restriction as records and connectors of only being allowed to have public sections.

That's not enough. Currently you can write:
```
record R
  Real x;
  Integer y;
end R;
```
but not 
```
type T
  Real x;
  Integer y;
end T;
```
We could clarify it as:
May only be predefined types, enumerations, array of type, or classes extending from an existing type.
In the latter case it may be combined with public declarations of function and annotations, but no other elements.

**Comment by HansOlsson** [comment]
hmm.. reformulating the latter as a PR

**Comment by perost** [comment]
> > It seems to me that types should just have the same restriction as records and connectors of only being allowed to have public sections.
> 
> That's not enough. Currently you can write:
> 
> ```
> record R
>   Real x;
>   Integer y;
> end R;
> ```
> 
> but not
> 
> ```
> type T
>   Real x;
>   Integer y;
> end T;
> ```
> 
> We could clarify it as: May only be predefined types, enumerations, array of type, or classes extending from an existing type. In the latter case it may be combined with public declarations of function and annotations, but no other elements.

But 4.5.2 already takes care of not allowing that, right?

**Comment by HansOlsson** [comment]
> But 4.5.2 already takes care of not allowing that, right?

Not this specific case. 4.5.2 only handles:
```
type T
   extends Real;
   Real x;
   Integer y;
end T;
```
But it may be better to have in 4.5.2.

**Comment by perost** [comment]
> > But 4.5.2 already takes care of not allowing that, right?
> 
> Not this specific case. 4.5.2 only handles:
> 
> ```
> type T
>    extends Real;
>    Real x;
>    Integer y;
> end T;
> ```
> 
> But it may be better to have in 4.5.2.

Ah, right. I guess there's currently no rule against users defining their own types, which I assume is not intended. One way to solve that might be to say that a type (except for the predefined ones obviously) must extend from another type.

**Comment by HansOlsson** [comment]
> Ah, right. I guess there's currently no rule against users defining their own types, which I assume is not intended. 
One way to solve that might be to say that a type (except for the predefined ones obviously) must extend from another type.

That's one of the things 4.6 does.

**Comment by perost** [comment]
> > Ah, right. I guess there's currently no rule against users defining their own types, which I assume is not intended.
> > One way to solve that might be to say that a type (except for the predefined ones obviously) must extend from another type.
> 
> That's one of the things 4.6 does.

Yeah, I got a bit confused there. I thought there was such a restriction but didn't think to look in 4.6 for some reason. Then I think your PR achieves what I wanted.

**Comment by perost** [comment]
Actually, I would also have liked to forbid protected sections in types, since as I mentioned in the issue description it would simplify the rules for records and block. But unlike equations and algorithms there could conceivably be some use cases for protected classes in types I guess.
