### ISSUE TITLE
Current status of arrayLayout annotation

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3189]
As I have never encountered a library making use of the `arrayLayout` annotation, I'd like to check up on its current status before even planning to implement it.  Is there any tool currently supporting the annotation?  Less important and more out of curiosity, is there any known library making use of the annotation?

The most relevant piece of information I could find when searching the web was the noted lack of support in OpenModelica, where @sjoelund comments that it isn't used anywhere:
- https://trac.openmodelica.org/OpenModelica/ticket/2417

If it turns out to really be a completely dead annotation, I suggest that it is removed from the specification.

**Comment by perost** [comment]
I can confirm that OpenModelica still doesn't support it, and I don't remember anyone ever asking for it.

**Comment by gkurzbach** [comment]
Surprisingly, SimulationX supports this annotation, but I'm also not aware of any library that uses it either.

**Comment by HansOlsson** [comment]
I would believe most libraries that want to use it instead switch between C and Fortran functions (well, who am I kidding - all matrix functions are obviously in Fortran).

**Comment by henrikt-ma** [comment]
In the spirit of increasing portability of Modelica models between tools, and based on what I hear above, it seems like we'd do our community a favor if we didn't even plan to add support for this annotation in System Modeler.
