### ISSUE TITLE
How to mark short inline code listings

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#3191]
As noted we now have single quotes around small language fragments; as far as I can see it was added for some in 
https://github.com/modelica/ModelicaSpecification/pull/2726 in a commit named "Migrate remaining glossary entries".

I understand there might be some need for disambiguating small Modelica-fragments from non-Modelica code in the rendered text, but I don't see that there were any discussion about this change, and I also see suggestions for using special markings for spaces indicating that it doesn't suffice.

The issues I see with this solution are:

- It is not automated.
- There are no 100% clear rules when it applies; the ideal would be to apply the same rule to all for inline fragments - but having single quotes around all inline code fragments would be too much.
- (A less important issue is that we cannot tell Modelica and grammar-fragments apart.)

The most obvious alternative would seem to be to have a slightly different background color for all inline fragments (think a whiter shader of lightgray - not yellow), but lstinline does not support that out of the box. However it seems possible: https://tex.stackexchange.com/questions/30845/how-to-redefine-lstinline-to-automatically-highlight-or-draw-frames-around-all/30851 (except that it fails for line-breaks).

**Comment by henrikt-ma** [comment]
> * (A less important issue is that we cannot tell Modelica and grammar-fragments apart.)

To me this is a solved problem: As soon as there are identifiers in the code, you can tell grammar apart from Modelica.

**Comment by HansOlsson** [comment]
Phone meeting:
Not for identifiers, but for other small arguments.
Not urgent to make consistent - should be mentioned in notation section.
