### ISSUE TITLE
convertClass causes broken Modelica-URIs

### ISSUE THREAD

**Issue by beutlich** [modelica/ModelicaSpecification#3199]
As originally observed by @mwetter in https://github.com/lbl-srg/modelica-buildings/pull/2960.

Currently, if the convertClass rule of a conversion script is applied, existing references in Modelica-URIs (and basically any other text) to the old type become invalid.

Is this a hole in the conversion rules or can it be seen as tool issue?

Example package:

```mo
package P
  block B
    extends Modelica.Blocks.Interfaces.BlockIcon;
    annotation(Documentation(info="<html>
<p>This will become a broken Modelica-URI (after class conversion) in MSL 4.0.0:
<a href=\"modelica://Modelica.Blocks.Interfaces.BlockIcon\">Modelica.Blocks.Interfaces.BlockIcon</a>.
</p>
</html>"));
  end B;
  annotation(uses(Modelica(version="3.2.1")));
end P;
```

**Comment by HansOlsson** [comment]
To me it seems like a tool issue, and it seems that it should be possible to correct.

**Comment by HansOlsson** [comment]
Clearly a tool issue that seems fairly straightforward to correct, as it is the same renaming as usual.
I assume tools will have to schedule this in their release; even though it will not help in this particular case.

**Comment by casella** [comment]
I agree with @HansOlsson. The [specification](https://specification.modelica.org/maint/3.5/annotations.html#conversion-rules) says:
> The conversion should generate correct Modelica models using the new version of the library corresponding to the old version.

which includes getting valid URIs if class names are changed. It also defines

> convertClass(”OldClass”, ”NewClass”) Convert class OldClass to NewClass. 

without specifying in detail _where_ this conversion is going to take place in the code of the class being converted.

Maybe we could add non-normative text to make this clearer, e.g.

> _[Whenever possible tools should preserve the original style of the model, e.g. use of imports. Class name conversions should be applied in all places where they show up in the code, including modelica:// URIs in documentation annotations and binding equations]_
