### ISSUE TITLE
Clarification regarding elsewhen

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3216]
The explanation of elsewhen in [Section 8.3.5](https://specification.modelica.org/master/equations.html#when-equations) is a bit confusing to me towards the end. The model DoubleWhenConflict is indeed erroneous, because it has an equation section, and the single assignment rule holds. However, the following WhenPriority model uses an algorithm section instead, which IMO is a bit confusing. 

I understand the idea is that if you have an _equation_ section, then you really need to use elsewhen, to establish a priority. So, I would put an _equation_ section in model WhenPriority, not an _algorithm_ section.

On the other hand, I understand that if you actually use an algorithm section, the algorithm is executed in the specified order, so there is no need to use elsewhen, because the priority is naturally enforced by the order of execution of the algorithm itself. Hence, I would add one more example showing this case, i.e. like DoubleWhenConflict but with an algorithm section instead.

Do I miss something?

**Comment by casella** [comment]
In fact, I now realize that the algorithm section with elsewhen and with when won't be exactly the same. Assuming both events are triggered simultaneously, the former only executes the first branch, while the latter executes both in sequence.

**Comment by henrikt-ma** [comment]
The merged PR had a typo.  Reopening instead of creating a separate issue.
