### ISSUE TITLE
Semantics of stand-alone function call statements in equation sections

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3227]
The Modelica grammar allows to put stand-alone function calls in equation sections. In some cases (see discussion in #2462) this has a well-defined semantics, e.g. 
- calling `reinit()` changes the value of a state variable
- calling `terminate()` ends the simulation
- caling `assert()` may abort a simulation or issue a warning, depending on conditions being met. This is also true when calling functions that contain asserts in their body, or that call other functions that contain asserts in their body.
- calling `Connections.*` operators establishes topological information about the connection graph

However, there are other cases that are not clear to me, and I'd like to double-check if that is because of a deficiency in the specification, or just to my misunderstanding.

Consider this model
```modelica
model M1
  Real x, y;
equation
  x = sin(1);
  y = cos(time);
  sin(x);
  tan(y);
end M1;
```
In this case the last two statements are not needed to compute the variables of the model and have no side effects, since the built-in functions are pure. Hence, an optimizing compiler `may` skip them outright. Is that correct?

Consider now this case:
```modelica
model M2
  Real x, y;
equation
  x = sin(1);
  y = cos(time);
  when sample(0,1) then
    print(x);
    print(y);
  end when:
end M2;
```
In this case, the `print()` functions being called are impure (whatever that means), so the compiler knows they have some side effect and won't skip computing them. Since they are put in a when statement, it is quite clear when they will be called: each time the event is triggered.

Consider now this case
```modelica
model M3
  Real x, y;
equation
  x = sin(1);
  y = cos(time);
  print(x);
  print(y);
end M3;
```
It is not clear to me what is the intended behaviour in this case. The two `print()` function have side effects, so they should be called and cannot be optimized away.  Besides, they must be called _after_ their arguments have been computed/updated  . The question is, when should they actually be called? At each time step? Since `x` can be computed once and for all at initialization by an optimizing compiler, is it OK if `x` is printed only at initialization?

**Comment by HansOlsson** [comment]
If they have a side-effect (as `print` does) they should be declared as impure and impure functions cannot be called in that way, 

https://specification.modelica.org/master/functions.html#pure-modelica-functions

In general a function that doesn't return anything is assumed to have side-effects or contain assertion-checks. So, 
a pure function with assertion-checks like `myAssert(x);` need only be called once if `x` doesn't change during the simulation, since the assertion either triggers (and in that case the simulation would fail) or it doesn't.

Note that if `myAssert` depended on the external environment in some way it should be impure.

**Comment by henrikt-ma** [comment]
I think the interesting question to be answered here is whether a function that _does_ return something is allowed to be called in this form.

And what about explicitly ignoring the only output in the form of an empty tuple?
```
  function cossin
   input Real x;
   output Real c = cos(x);
   output Real s = sin(x);
  end cossin;
equation
  () = cossin(a);
```

(Note that the specification doesn't allow tuple equation form if the function had only a single output.)

**Comment by HansOlsson** [comment]
> I think the interesting question to be answered here is whether a function that _does_ return something is allowed to be called in this form.

I don't see a problem with it. An impure function or assertion-check function could optionally return some value, if you only want the side effect or assertion check it makes to ignore the return value.

**Comment by henrikt-ma** [comment]
> > I think the interesting question to be answered here is whether a function that _does_ return something is allowed to be called in this form.
> 
> I don't see a problem with it. An impure function or assertion-check function could optionally return some value, if you only want the side effect or assertion check it makes to ignore the return value.

But if we really wanted support that kind of usage, there should have been a way to do this also for functions with just a single output.

Moreover, it seems that the current rule is focusing on the wrong thing: it isn't the number of declared outputs that should matter, but the number of received outputs:
> A call to a function with no declared outputs is assumed to have desired side-effects or assertion checks.

**Comment by HansOlsson** [comment]
> But if we really wanted support that kind of usage, there should have been a way to do this also for functions with just a single output.

Probably. As I understand it we haven't explicitly forbidden: `()=sin(time);`  - it's just that we missed that case.

> Moreover, it seems that the current rule is focusing on the wrong thing: it isn't the number of declared outputs that should matter, but the number of received outputs:

I would say that it is a good deliberate choice. 

The function itself either has side-effects (or assertions) or it doesn't. How the function is used shouldn't matter for that, and it wouldn't make sense that it one call `foo` is assumed to have side-effects or assertions and in another it isn't.
