### ISSUE TITLE
Decide on use of comma after "e.g." and "i.e."

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3235]
Our style guide should give rules for when to use a comma after "e.g." and "i.e.", and the text should be updated to follow whatever is decided.  Currently we have a mix of both:
- i.e. with comma: 111
- i.e. without comma: 56 (one of which without protecting the following space)
- e.g. with comma: 69
- e.g. without comma:85

Based on what I find online, including discussions like this,
https://english.stackexchange.com/questions/16172/should-i-always-use-a-comma-after-e-g-or-i-e
I lean towards always requiring the comma for both abbreviations in our document.  This would also have the advantage that people editing the sources don't need to remember the special LaTeX behavior that requires the following space to be protected when it appears directly after the period.

**Comment by dietmarw** [comment]
I'm also in favour of always using the comma.

**Comment by eshmoylova** [comment]
I have consulted with our documentation team. Their recommendation (based on Chicago Manual of Style) is that comma should be used after. Before there should also be some punctuation mark. Examples of a punctuation mark before (from the specification):
>...trajectories for the model's variables, i.e., the value of the variables...

> ...for rem(x,y) it is div(x,y) - i.e. events are not generated when...

> ...objects (i.e., components).

I haven't looked through all the cases of "i.e." and "e.g". There was one case where there was no punctuation mark before.

**Comment by casella** [comment]
As I understand, "i.e." is short for "id est", Latin for "that is", and "e.g." is short for "exempli gratia", Latin for "for the sake of the example", which in English (and I guess also in medieval Latin) are always preceded and followed by a comma. That's why we should always write them ", e.g.," and ", i.e.,".
