### ISSUE TITLE
Handling of connect equations between duplicate components

### ISSUE THREAD

**Issue by gkurzbach** [modelica/ModelicaSpecification#3238]
Consider 
```
model M
	model B
		Modelica.Blocks.Sources.KinematicPTP kinematicPTP(
		deltaq={1.57},
		qd_max={1},
		qdd_max={1},
		startTime=0.5) annotation(Placement(transformation(extent={{-92,20},{-72,40}})));
		Modelica.Blocks.Continuous.Integrator integrator(initType=Modelica.Blocks.Types.Init.InitialState) annotation(Placement(transformation(extent={{-63,20},{-43,40}})));
	equation
		connect(kinematicPTP.y[1], integrator.u)
		  annotation (Line(points={{-71,30},{-65,30}}, color={0,0,127}));
	end B;
	model A1
	    extends B;
	end A1
	model A2
	    extends B;
	end A2;
	model C
	    extends A1;
	    extends A2;
	end C;
	C c;
end M;
```

This sample uses diamond inheritance. The model B used as common sub base class of both base classes A1 and A2. B contains some components and connect equations.
Because of the defined handling of duplicate components the components of B occur only once if the final instance tree. But what about connection equations. In the current Modelica specification it is not decribed how to handle them. 

* Should duplicate connect equations beeing removed? 
* What about other equations if any? Will they occur twice? 
* And what if connect equations occur in loops with subscipted connectors?

This should be clarified.

This can also happen without diamond inheritance if duplicate components and connection between them exist.

**Comment by HansOlsson** [comment]
Duplicated non-connect equations shall be removed as a deprecated feature (assuming they are syntactically equivalent).
https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#inheritance-extends-clause

> Equations of the flattened base class that are syntactically equivalent to equations in the flattened enclosing class are discarded. This feature is deprecated, and it is recommended to give a warning when discarding them and for the future give a warning about all forms of equivalent equations due to inheritance.

Technically this is true also for connect equations, but since connect equations generate connection sets they don't actually matter.
