### ISSUE TITLE
Clarify relation between balanced models and balanced connectors

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3260]
[Section 4.7](https://specification.modelica.org/maint/3.5/class-predefined-types-and-declarations.html#balanced-models) of the specification discusses balanced models, in particular stating that the local equation size need to count "The number of input and flow variables present in each (top-level) public connector component".

This is technically correct if one needs to implement a balancedness checker in a Modelica compiler. However, it does not provide a key piece of information to fully understand the topic of balancedness, i.e., the fact that flow variables need to be in the same number as effort variables in connectors. This is stated elsewhere in [Section 9.3.1](https://specification.modelica.org/maint/3.5/connectors-and-connections.html#balancing-restriction-and-size-of-connectors). I believe that from a modeller's perspective this should be made clear in Section 4.7 already.

Therefore, I would add a reference to Section 9.3.1 and some further clarification to the non-normative section of Definition 4.2 in Section 4.7 (the added part is in italics):
>The number of input and flow variables present in each (top-level) public connector component.
[This represents the number of connection equations that will be provided when the class is used. _As stated in Section 9.3.1, the number of flow variables in a connector must be the same as the number of effort variables (i.e. not parameter, constant, flow, input, output, or stream variables). Therefore, one should count one additional local equation for each flow-effort variable pair on connectors. This equation will be provided by the components that will be connected to the connector, or by the default connection equation setting the flow variable to zero in case of unconnected connector_.]

**Comment by HansOlsson** [comment]
I would just reference section 9.3.1 - and not attempt to enumerate the effort variables, as we we also have over-determined connectors. Something like: [This represents the number of connection equations that will be provided when the class is used, due to the balancing restrictions for connectors in section 9.3.1.]

**Comment by HansOlsson** [comment]
Will just add if there are not other reactions.
