### ISSUE TITLE
Clarification about encapsulated short class definition

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#3270]
Section 4.5.1 says:
> An exception to the above is that if the short class definition is declared as encapsulated, then the modifiers follow the rules for encapsulated classes and cannot be looked up in the enclosing scope.

Which only provides a constraints for the modifiers.

Does that mean that the following is valid:
```
package P
  model A
    Real x = 1;
  end A;

  encapsulated model B = A;
end P;
```

**Comment by HansOlsson** [comment]
It shouldn't be allowed.
The reason is two-fold:

- It breaks the idea with encapsulation.
- The problem with modifiers is that it can make a class depending on local variables (when allowing using encapsulated models outside of the enclosing class), and you can indirectly do the same with classes.

It was added to resolve https://github.com/modelica/ModelicaSpecification/issues/2743 (where the class names used `.P.A`).

With indirect I mean that the specification currently contains the following to illustrate the rule:
```
model A
 parameter Real R;
...
 encapsulated model Load2=.Resistor(R=2);
end A;
```
But you could also do:
```
model A
 parameter Real R;
...
 model Load3=.Resistor(R=2);
 encapsulated model Load4=Load3;
end A;
```
Where Load4 had the same issue with modifiers as Load2.

**Comment by qlambert-pro** [comment]
Right then we need to rephrase the specs because the suggestion that it only applies to modifiers is ambiguous.

**Comment by qlambert-pro** [comment]
You seem to mean `R=R` for the modifiers. Wouldn't the following be allowed and equivalent by your interpretation?

**Comment by HansOlsson** [comment]
> You seem to mean `R=R` for the modifiers. Wouldn't the following be allowed and equivalent by your interpretation?
> 
> ```
> package P
>   model A
>     Real x = 1;
>   end A;
> 
>   model Main
>     parameter Real p = 2;
>     model B = A(x = p);
>     encapsulated model C = .P.Main.B;
>     C c;
>   end Main;
> end P;
> ```

Local classes can be a problem in general, but P.Main isn't a package and B isn't encapsulated so you are not allowed to use it.

**Comment by qlambert-pro** [comment]
That's not what the specs currently say:
`If the identifier denotes a class, ... If the class does not satisfy the requirements for a package, the
lookup is restricted to encapsulated elements only.`

**Comment by HansOlsson** [comment]
> That's not what the specs currently say:
> 
> > If the identifier denotes a class, [...] If the class does not satisfy the requirements for a package, the
> > lookup is restricted to encapsulated elements only.
> 
> The way it is written only applies to the first part of the name being a package.

Oh, that restriction must be present for all parts (in a normal recursive way). Similarly for the partial restriction.

**Comment by HansOlsson** [comment]
> That's not what the specs currently say:
> 
> > If the identifier denotes a class, [...] If the class does not satisfy the requirements for a package, the
> > lookup is restricted to encapsulated elements only.
> 
> The way it is written only applies to the first part of the name being a package.
> 
> Also, I am not sure what the following mean:
> 
> > that class is temporarily flattened ([...]) and using the enclosing classes of the denoted class
> 
> I guess we should remove `and`?

Hm... I believe we should move the 'and ...' into the parenthesis, giving:

If the identifier denotes a class, that class is temporarily flattened (as if instantiating a component without modifiers of this class, see section 7.2.2 and using the enclosing classes of the denoted class).

**Comment by qlambert-pro** [comment]
ok, for the original issue we could add a non-normative text pointing out that for an encapsulated short-class definition the base class reference must be fully qualified.

**Comment by gwr69** [comment]
> If the class does not satisfy the requirements for a package, the
> lookup is restricted to encapsulated elements only.

It may be helpful to point out that this references section 5.3.2 (Composite Name Lookup).
