### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3274]
This link seems dead:

https://github.com/modelica/ModelicaSpecification/blob/c7631f708e5951a644ed639cbd3cd00caf5b483d/mls.bib#L42

**Comment by HansOlsson** [comment]
It seems to be available on 
https://www.semanticscholar.org/paper/Inline-Integration%3A-A-New-Mixed-Symbolic%2FNumeric-Elmqvist-Otter/b696154cbfb9c82dd4983abbd45ed639a4d5c32c

I note that the new link lacks a DOI, but it seems the previous DOI was incorrect.

**Comment by HansOlsson** [comment]
Note to self: Update it.
