### ISSUE TITLE
Copy and paste from pdf-document

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#3286]
When commenting in https://github.com/modelica/ModelicaSpecification/issues/3275
I tried to copy and paste text from https://specification.modelica.org/master/MLS.pdf

But that didn't work well since the [ligatures](https://en.wikipedia.org/wiki/Ligature_(writing)) "fi" and "fl" were replaced by squares; to me that is a clear usability problem of the specification. 
(Note that this shouldn't impact code samples, since fixed-width fonts as used for code shouldn't have ligatures.)

It seems there are solutions:
https://tex.stackexchange.com/questions/33476/why-cant-fi-be-separated-when-being-copied-from-a-compiled-pdf so it might be a simple matter of applying them.

**Comment by henrikt-ma** [comment]
Can we make sure that this isn't just a deficiency in your PDF viewer?  I just tried copying the word _finally_, and it worked fine, using Skim on macOS.  What word did you try?

**Comment by HansOlsson** [comment]
Well, I tried it with Edge, Chrome, and Firefox on Windows - all failed when copying to Notepad++, Notepad, or Microsoft Word.

As for the solutions, either:
`\usepackage{cmap}`
and
```
\usepackage{libertine}
\input{glyphtounicode}
\pdfglyphtounicode{f_f}{FB00}
\pdfglyphtounicode{f_f_i}{FB03}
\pdfglyphtounicode{f_f_l}{FB04}
\pdfglyphtounicode{f_i}{FB01}
\pdfgentounicode=1
```
Seems to work, and both allow copying the text and _searching_ for it. (But they might require installing additional packages.)

It is possible that either the target-system has a corresponding font so it works, or that some PDF-readers are smarter - but I still think this is something that it would be good to correct.

**Comment by henrikt-ma** [comment]
For the record, also my Adobe Reader was able to both find and copy the "finally" at the end of `shiftSample`.
