### ISSUE TITLE
List item scope in "Restrictions on Equations within When-Equations"

### ISSUE THREAD

**Issue by bilderbuchi** [modelica/ModelicaSpecification#3291]
In the current [master spec](https://specification.modelica.org/maint/3.5/equations.html#restrictions-on-equations-within-when-equations), we have (bold emphasis mine)

>8.3.5.3 Restrictions on Equations within When-Equations
>
>The equations within the when-equation must have **one of the following forms**:
>
>    *  v = expr;
>    *  (out1, out2, out3, …) = function_call_name(in1, in2, …);
>    *  Operators assert, terminate, reinit.
>    *  For- and if-equations if the equations within the for- and if-equations satisfy these requirements.
>    *  The different branches of when/elsewhen must have the same set of component references on the left-hand side.
>    *  The branches of an if-then-else clause inside when-equations must have the same set of component references on the left-hand side, unless the if-then-else have exclusively parameter expressions as switching conditions.
>
>Any left hand side reference, (v, out1, …), in a when-clause must be a component reference, and any indices must be parameter expressions.

I suspect that the last two bullet points should not be _items of_ the list, but should be _following_ the list, so form _additional_ requirements on top of the respective chosen bullet item.

According to the current form quoted above, and taking note of the bolded part, the following example would be legal:

```modelica
 equation
  when x > 2 then
    y = 5; // compliant with bullet 1
  elsewhen x > 3 then
    z = 5;  // compliant with bullet 1
  end when;
```

**Comment by HansOlsson** [comment]
Agreed, and I also think that the trailing restriction could be added to that list.
