### ISSUE TITLE
Broken references

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3302]
It looks like generation of references is broken. For example, in [State Machines](https://github.com/modelica/ModelicaSpecification/blob/d609f556d7a28bdd016c15fc551da112dcc0f160/chapters/statemachines.tex#L4) there is a reference:
```
\parencite{Pouzet2006LucidSynchrone30}
```
It appears as plain text in [the generated html](https://specification.modelica.org/master/state-machines.html):
<img width="375" alt="image" src="https://user-images.githubusercontent.com/20460714/206245345-0ac6eff5-e298-44a2-baf4-9fd64eca9b67.png">

Similarly in [Selective Model Extension](https://github.com/modelica/ModelicaSpecification/blob/d609f556d7a28bdd016c15fc551da112dcc0f160/chapters/inheritance.tex#L1148):
```
\textcite{Buerger2019SelectiveModel}
```
which  appears [as plain text](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#selective-model-extension).

If I click on References in the menu, it is empty:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/20460714/206243613-a1394714-17c4-480c-b4de-14b5777ff782.png">

This is on Chrome.

In pdf, references are generate. For both cases there are hyperlinks. But the appearance is different "(Harel 1987)" vs "Bürger (2019)". In both cases only the year is a hyperlink.

**Comment by eshmoylova** [comment]
@henrikt-ma , when you say "locally", do you mean if you build the html locally?

**Comment by henrikt-ma** [comment]
Yes.

**Comment by henrikt-ma** [comment]
After having updated software on my machine, I now find myself with LaTeXML 0.8.6, and I am able to reproduce the problem.  Any chance that we have upgraded the CI builds from 0.8.5 to 0.8.6 without knowing?

**Comment by sjoelund** [comment]
We are running latexml (LaTeXML version 0.8.6) on the server, indeed. It's what is part of the latest Ubuntu.

I do wonder why my postprocessing is so much slower than yours though: Postprocessing complete 1 error (See /home/marsj/dev/ModelicaSpecification/MLS.latexmlpost.log) (reqd. 1h 53m 26.84s)
