### ISSUE TITLE
Restriction on block

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3309]
The current restriction on **block** as a specialized class states ([4.6 Specialized classes](https://specification.modelica.org/master/class-predefined-types-and-declarations.html#specialized-classes)):
> Same as model with the restriction that each connector component of a block must have prefixes input and/or output for all connector variables.

Is it really "*each* connector component" or is it "*each **public*** connector component"?

I ran tests on a well-respected open-source Modelica library, and I had some failures because there were simulation models with blocks that have private connector components containing flow and effort variables. The library states that it has more than 2000 tests that are continuously being tested in 4 different Modelica tools. So?

It would be nice to have that cleared up before the release of 3.6. Hopefully, it should be quick, so I took the liberty of setting the Milestone as Phone2022-7.

**Comment by HansOlsson** [comment]
I agree that it should be "each public connector component".

**Comment by HansOlsson** [comment]
Phone meeting: Agreement.
