### ISSUE TITLE
Structured streams connectors

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#3336]
https://specification.modelica.org/master/class-predefined-types-and-declarations.html state that

"Variables declared with the stream type prefix shall be a subtype of Real."

The proposal would be to generalize this to:

"Variables declared with the stream type prefix shall be a subtype of Real or a record (or 'structured'?) component where all the primitive elements shall be a subtype of Real."

(Note that corresponding "flow" must still be a scalar Real.)

The benefit is that you can have structured streams-components. 

Currently we have an array of elements for streams-connectors in MSL (for the different species), with this alternative you can use a record with named elements instead for the different species.

It is supported in Dymola, even if it generates pedantic warnings and I don't think it would be complicated to support in other tools.

**Comment by casella** [comment]
LGTM
