### ISSUE TITLE
LaTeX source in generated PDF/HTML

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3342]
In the example in Section 18.8.4 Version Date and Build Information, there is `\ldots$` that makes its way into the generated PDF and HTML. It is in the PR that is supposed to be for the release candidate for 3.6: https://test.openmodelica.org/jenkins/job/ModelicaAssociation/job/ModelicaSpecification/job/PR-3340/1/artifact/MLS.pdf

**Comment by henrikt-ma** [comment]
I'll prepare a fix.
