### ISSUE TITLE
Connection graph equations of redundant overconstrained connect-equations

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3370]
As an extreme case of a redundant `connect`-equation in an overconstrained connect set, consider this simple model:
```
model SelfConnectedFrame
  inner Modelica.Mechanics.MultiBody.World world;
  Modelica.Mechanics.MultiBody.Parts.Body body(m = 1, r_CM = {0, 0, 0});
equation
  connect(body.frame_a, body.frame_a); /* Redundant connect-equation. */
end SelfConnectedFrame;
```

As the connection graph just has a single node, the spanning tree is empty, so according to item (2) in the second item list of https://specification.modelica.org/master/connectors-and-connections.html#generation-of-connection-graph-equations, it results in the equation:
```
0 = Modelica.Mechanics.MultiBody.Frames.Orientation.equalityConstraint(body.frame_a.R, body.frame_a.R)
```

I'd just like to verify that it is really the intention of the specification that redundant `connect`-equations should result in an `equalityConstraint`-equation (making the model above not globally balanced)?

Note that the problem isn't limited to `connect`-equation self-loops, but seems to affect redundant `connect`-equations more generally.  For example, repeating a `connect`-equation would have similar effect.

Here's another variant of a redundant `connect`-equation:
```
model OverConnectedFrames
  inner Modelica.Mechanics.MultiBody.World world;
  Modelica.Mechanics.MultiBody.Parts.Body body1(m = 1, r_CM = {0, 0, 0});
  Modelica.Mechanics.MultiBody.Parts.Body body2(m = 1, r_CM = {0, 0, 0});
  Modelica.Mechanics.MultiBody.Parts.Body body3(m = 1, r_CM = {0, 0, 0});
equation
  connect(body1.frame_a, body2.frame_a);
  connect(body2.frame_a, body3.frame_a);
  connect(body3.frame_a, body1.frame_a);
end OverConnectedFrames;
```

Also this time, it seems surprising that what matters for the balancing of variables and equations is not the connection set, but the structure of the `connect`-equations forming the set.  Am I missing something?

**Comment by henrikt-ma** [comment]
Somewhat related, here is a quote from https://github.com/modelica/ModelicaStandardLibrary/issues/4007#issuecomment-1172387487:
> Note that `connect(p, p)` isn't redundant in itself, as only inside connectors are added as the connection sets - so this connect-statement does ensure that `p.i` is part of a connection set.

**Comment by HansOlsson** [comment]
It doesn't make sense that it should generate such errors, and Dymola does not seem to do that.
One possibility would be to remove redundant edges when building the connection set, but I don't know exactly how to describe the procedure.

**Comment by henrikt-ma** [comment]
> One possibility would be to remove redundant edges when building the connection set, but I don't know exactly how to describe the procedure.

Any suggestion for whom to consult?

**Comment by HansOlsson** [comment]
> > One possibility would be to remove redundant edges when building the connection set, but I don't know exactly how to describe the procedure.
> 
> Any suggestion for whom to consult?

I tried to look more and it, and the solution seems to be:
* Before processing the virtual connection graph _redundant_ breakable branches are removed in each connection set. This is done by building a spanning tree within each connection set (ignoring all breakable branches at this step) and only keeping the breakable branches that are part of those spanning trees.

Example demonstrating possibilities:
```
model SelfConnectedFrame
  Modelica.Mechanics.MultiBody.Parts.Body body(m = 1, r_CM = {0, 0, 0}) annotation (Placement(transformation(extent={{-40,14},{-20,34}})));
  inner Modelica.Mechanics.MultiBody.World world
    annotation (Placement(transformation(extent={{-98,62},{-78,82}})));

  Modelica.Mechanics.MultiBody.Parts.Body body1(m=1, r_CM={0,0,0})      annotation (Placement(transformation(extent={{20,-40},
            {40,-20}})));
  Modelica.Mechanics.MultiBody.Joints.Revolute revolute(useAxisFlange=true)
    annotation (Placement(transformation(extent={{-30,-40},{-10,-20}})));
  Modelica.Mechanics.Rotational.Components.Fixed fixed
    annotation (Placement(transformation(extent={{6,-2},{26,18}})));
  Modelica.Mechanics.MultiBody.Parts.Body body2(m=1, r_CM={0,0,0})      annotation (Placement(transformation(extent={{52,42},
            {72,62}})));
  Modelica.Mechanics.MultiBody.Parts.Body body3(m=1, r_CM={0,0,0})      annotation (Placement(transformation(extent={{126,14},
            {146,34}})));
protected 
  Modelica.Mechanics.MultiBody.Interfaces.Frame_a frame_a1
    "Coordinate system fixed at body"
    annotation (Placement(transformation(extent={{8.4,56.4},{11.6,59.6}})));
protected 
  Modelica.Mechanics.MultiBody.Interfaces.Frame_a frame_a2
    "Coordinate system fixed at body"
    annotation (Placement(transformation(extent={{82.4,28.4},{85.6,31.6}})));
protected 
  Modelica.Mechanics.MultiBody.Interfaces.Frame_a frame_a3
    "Coordinate system fixed at body"
    annotation (Placement(transformation(extent={{96.4,-3.6},{99.6,-0.4}})));
equation 
  connect(body.frame_a, body.frame_a) annotation (Line(
      points={{-40,24},{-58,24},{-58,24},{-40,24}},
      color={95,95,95},
      thickness=0.5));
  connect(revolute.frame_b, body1.frame_a) annotation (Line(
      points={{-10,-30},{20,-30}},
      color={95,95,95},
      thickness=0.5));
  connect(revolute.frame_a, revolute.frame_a) annotation (Line(
      points={{-30,-30},{-48,-30},{-48,-30},{-30,-30}},
      color={95,95,95},
      thickness=0.5));
  connect(revolute.axis, fixed.flange)
    annotation (Line(points={{-20,-20},{-20,8},{16,8}}, color={0,0,0}));
  connect(body2.frame_a, body2.frame_a) annotation (Line(
      points={{52,52},{52,52}},
      color={95,95,95},
      thickness=0.5));
  connect(body2.frame_a, frame_a1) annotation (Line(
      points={{52,52},{32,52},{32,58},{10,58}},
      color={95,95,95},
      thickness=0.5));
  connect(body3.frame_a, frame_a2) annotation (Line(
      points={{126,24},{106,24},{106,30},{84,30}},
      color={95,95,95},
      thickness=0.5));
  connect(frame_a2, frame_a3) annotation (Line(
      points={{84,30},{84,-2},{98,-2}},
      color={95,95,95},
      thickness=0.5));
  connect(body3.frame_a, frame_a3) annotation (Line(
      points={{126,24},{118,24},{118,-2},{98,-2}},
      color={95,95,95},
      thickness=0.5));
  annotation (uses(Modelica(version="4.0.0")));
end SelfConnectedFrame;

```

**Comment by casella** [comment]
@henrikt-ma, @HansOlsson we actually stumbled across this issue recently, see OpenModelica/OpenModelica#10717.

My understanding is that of course any cycle in the connection graph which is made exclusively by breakable branches (i.e., connect statements) corresponds to a redundant connection set, so it must be broken _without adding equalityConstraint() equations_.

I guess the current proposal in PR#3373 is equivalent, but I'm not an expert in graphs either.

**Comment by HansOlsson** [comment]
Yes. It seems to be the same issue.

**Comment by casella** [comment]
[This comment](https://github.com/OpenModelica/OpenModelica/issues/10717#issuecomment-1563609699) contains an MWE which is less involved than the Multibody library, in case it could be useful for testing.

**Comment by henrikt-ma** [comment]
The suggested solution seems logical to me, but I have asked my colleague who is maintaining our implementation to have a look too.

When we know how the text will be changed, I can provide an updated illustration if needed.

**Comment by henrikt-ma** [comment]
I'm told that System Modeler already does skip redundant breakable branches, as suggested here.  Should I prepare a PR including an updated figure 9.2?

**Comment by HansOlsson** [comment]
> I'm told that System Modeler already does skip redundant breakable branches, as suggested here. Should I prepare a PR including an updated figure 9.2?

There is already a PR without the figure, #3373 to start from, or accept it and then make a separate one for just the figure.
And please review the updated #3362 #3360 ( #3313 ) #3284 #3254 as well.

**Comment by henrikt-ma** [comment]
Oh, right.  Yes, let's add the figure later if needed.
