### ISSUE TITLE
Sematics of protected extends clause

### ISSUE THREAD

**Issue by gkurzbach** [modelica/ModelicaSpecification#3396]
Is there any effect of an extends clause in a protected section compared to the one in a public section?
```
model M
   model A
      Real v;
   end A;

   model B
   protected
       extends A;
   end B;

   B b(v=2); // this is valid ?!
   B c;
   equation
       c.v=2; // valid too ?!
end M;
```

According to MLS 3.6 all accesses seem to be valid, because the extends itself cannot be referenced, only the elements and it does not add an additional dot. But then there is no difference whether an extends is protected or not.
This is not really clear in the spec.

**Comment by qlambert-pro** [comment]
Section 7.1 says
> The elements of the flattened base class become elements of the flattened enclosing class, and are added at the place of the extends-clause

We have interpreted to mean that any `public` component becomes protected, but now that I think about it, a consistent interpretation would be to only turn the components in the default public section to `protected` and keep the ones that are in an explicit `public` one `public`

**Comment by eshmoylova** [comment]
[Section 7.1.2](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#inheritance-of-protected-and-public-elements has:)
If an extends-clause is used under the protected heading, all elements of the base class become protected elements of the current class.

**Comment by gkurzbach** [comment]
@eshmoylova thanks. I missed this section.
