### ISSUE TITLE
Integer flow variables?

### ISSUE THREAD

**Issue by HansOlsson** [modelica/ModelicaSpecification#3401]
Currently flow-variables cannot be integers, which seems a bit odd:

https://github.com/modelica/ModelicaSpecification/blob/07ccecd0719e130ad7edfb578f94e72ba5872dbe/chapters/classes.tex#L236

especially since integers do form an additive group. The restriction was added in Modelica 1.1 and I believe we should lift that restriction.
(Note that Boolean and Strings do _not_ form an additive group so we shouldn't generalize it further.)

Use-cases:

- Counting the number of instances of a class (using inner/outer).
- The flow is just an integer; so better to handle it in that way.

Implementation effort:

- Minimal: It seems it is just a matter of removing a restriction - as the resulting equations can be treated as any other equations.
- Dymola currently generates a diagnostics and then handles it.

**Comment by henrikt-ma** [comment]
If allowing it, we should then describe how the resulting equation can be solved.  Currently, an integer can only be solved from an equation in solved form, and the proposed generalization seems to rely on breaking that rule.

**Comment by HansOlsson** [comment]
I tried to find where it is stated that integers can only be solved from equations in solved form and couldn't find it.
The closest is https://specification.modelica.org/master/operators-and-expressions.html#modelica:pre - that indicates that we can use fixed-point iteration

What Dymola is able to handle is (as far as I recall):
- Integer, Boolean, String, and Enumeration: solve `b` from `b=...;` or from `...=b;`
- Integer also solve `i` from `...+...-i=0;`

That suffices for counting - if connect equations are constructed in a sensible form, but if we want to handle flow equations we should also allow solving `i` from `...+/-i+/-...=...;` (and reversed).

I.e., as long as the variable only occur once as part of addition/subtraction we can symbolically solve for it (with suitable protection against overflow). That seems to match the integer-flow equations and be a useful subset. For Boolean equations it would be possible to handle some special equations (specially we can move "not" from one side to the other and similarly for "==" and "<>"), but I don't see a similar need.

**Comment by henrikt-ma** [comment]
From https://specification.modelica.org/master/modelica-dae-representation.html:
> Further, each of the original model equations behind ([B.1c](https://specification.modelica.org/master/modelica-dae-representation.html#eq:dae-discrete-valued)) must be given in solved form, at most requiring flipping sides of the equation to obtain the used assignment form.

**Comment by HansOlsson** [comment]
> From https://specification.modelica.org/master/modelica-dae-representation.html:
> 
> > Further, each of the original model equations behind ([B.1c](https://specification.modelica.org/master/modelica-dae-representation.html#eq:dae-discrete-valued)) must be given in solved form, at most requiring flipping sides of the equation to obtain the used assignment form.

So, we would need to generalize it to allow it to only occur once, and as a term without multiplicative factor on either side of the equation. (For Integers).

**Comment by henrikt-ma** [comment]
> So, we would need to generalize it to allow it to only occur once, and as a term without multiplicative factor on either side of the equation. (For Integers).

I don't think that would be too crazy.

**Comment by HansOlsson** [comment]
Phone meeting: Agree to move forward. (Unique choice based on strong components; since it must be one variable matched with one equation.)
May get tricked if wrong integer variable is solved (in incorrect models)?
