### ISSUE TITLE
Validity of inner/outer construct with subtyping

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3413]
Consider:

```
model IO
  model MSA
    parameter Real p =1;
  end MSA;

  model MSB
  end MSB;

  model A
    outer MSA ms;
  end A;

  model B
    outer MSB ms;
  end B;

  model C
    A a;
    B b;
  end C;

  C c;
  inner MSA ms;
end IO;
```

Is `IO` a valid model?

Is `IO.C` a valid model?

**Comment by HansOlsson** [comment]
C is illegal

IO is valid, even though I would prefer to write it as:
```
model IO
  C c;
  inner MSA ms;
end IO;
```
This is explicitly covered by: https://specification.modelica.org/master/scoping-name-lookup-and-flattening.html#inner-declarations-instance-hierarchy-name-lookup

> An outer element reference in a simulation model requires that one corresponding inner element declaration exists or can be created in a unique way:
> - If there are two (or more) outer declarations with the same name, both lacking matching inner declarations, and the outer declarations are not of the same class it is an error.
> ...
> The inner component shall be a subtype of the corresponding outer component.

**Comment by maltelenz** [comment]
Thank you Hans, this was the interpretation I wanted confirmation on. While "a bit valid" could be a tricky proposition for tools to deal with in validation, this is probably a tool issue to figure out how to present to their users in various workflows.

I agree the pieces you quoted clarify the issue.

Closing.
