### ISSUE TITLE
Is 1 + 1 a scalar constant?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3427]
Is this a valid call to the external function `myExtFun`?
```
model OnePlusOne
  function f
    output Integer y;
  external "C"
    y = myExtFun(1 + 1);
      annotation(Include = "
int
myExtFun(int x)
{
  return x;
}
");
  end f;
  
  Integer k = f();
end OnePlusOne;
```

The specification says that _scalar constants_ are allowed as arguments, but I'd like clarification on whether this is supposed to only allow literal values rather than more general constant scalar expressions.

**Comment by HansOlsson** [comment]
Is there any reason for wanting this?

**Comment by henrikt-ma** [comment]
I encountered it when polishing one of the examples in https://github.com/henrikt-ma/TernaryTest, as one cannot express `Ternary(false)` as a literal.

**Comment by HansOlsson** [comment]
Well, since it says "scalar constant" I would assume it is allowed to be a constant, not a literal.

**Comment by henrikt-ma** [comment]
OK, so far so good.  But do you know of any library out there where a non-literal expression is actually used?  If not, maybe other tool vendors (not only Wolfram) should have a look at their external function handling…

**Comment by perost** [comment]
I would have interpreted _scalar constant_ to mean _scalar literal_, but it seems past me disagrees since OpenModelica allows constant expressions to be used in external calls. I don't remember if there's any actual reason for why I implemented it like that though.

But regardless I think _constant_ on its own is ambiguous, it should either be _constant literal_ or _constant expression_.

**Comment by HansOlsson** [comment]
> I would have interpreted _scalar constant_ to mean _scalar literal_, but it seems past me disagrees since OpenModelica allows constant expressions to be used in external calls. I don't remember if there's any actual reason for why I implemented it like that though.
> 
> But regardless I think _constant_ on its own is ambiguous, it should either be _constant literal_ or _constant expression_.

So, change to _scalar constant expression_ in that case.

(The scalar part is important since the passing of arrays is complicated enough already.)
(Separately, I note that we don't use the term _constant literal_, but either _literal_ or _literal constant_.)

**Comment by henrikt-ma** [comment]
> > But regardless I think _constant_ on its own is ambiguous, it should either be _constant literal_ or _constant expression_.
> 
> So, change to _scalar constant expression_ in that case.

Sounds like a plan.

> (Separately, I note that we don't use the term _constant literal_, but either _literal_ or _literal constant_.)

I suggest that we get rid of _literal constant_ in favor of just _literal_, as literals are always constant.

**Comment by HansOlsson** [comment]
Language group: Ok.
