### ISSUE TITLE
No such thing as a "function’s public variable section".

### ISSUE THREAD

**Issue by qlambert-pro** [modelica/ModelicaSpecification#3437]
Section 12.2 says:
> Only input and output formal parameters are allowed in the function’s public variable section.

There is no such thing as a "function’s public variable section", the item should say
> All components in the public section must have prefixes input or output.

**Comment by HansOlsson** [comment]
Wouldn't it be easier to skip the sections altogether and say "All public components (of functions) must have prefixes input or output."? (The text in parenthesis can be omitted or not (the parenthesis shall be removed). I believe the extra text helps even if obvious from context.)

There are currently two uses of "public section" but that is in Specialized classes to contrast with protected, equation, algorithm etc.

**Comment by qlambert-pro** [comment]
That's fine by me as long as it is clear that the one can have public class declaration, in a function definition.
