### ISSUE TITLE
Overconstrained connectors are not considered in the definition of Balanced Models

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3441]
In Modelica 3.0, Balanced Models ([Section 4.7](https://specification.modelica.org/maint/3.6/class-predefined-types-and-declarations.html#balanced-models)) and Overconstrained Connections ([Section 9.4](https://specification.modelica.org/maint/3.6/connectors-and-connections.html#equation-operators-for-overconstrained-connection-based-equation-systems1)) were introduced. 

However, unless I am mistaken, the interplay between these two concept is not fully clarified in the text of the specification.

[Section 9.3.1](https://specification.modelica.org/maint/3.6/connectors-and-connections.html#balancing-restriction-and-size-of-connectors) introduces an important concept:
> For each non-partial non-expandable connector class the number of flow variables shall be equal to the **number of variables** that are neither parameter, constant, input, output, stream nor flow. The number of variables is the number of all elements in the connector class after expanding all records and arrays to a set of scalars of primitive types. The **number of variables of an overdetermined type** or record class (see [section 9.4.1](https://specification.modelica.org/maint/3.6/connectors-and-connections.html#connection-graphs-and-their-operators)) is **the size of the output argument** of the corresponding **equalityConstraint()** function.

Hence, when considering balanced connectors, overdetermined type variables should only be counted for their constraints, not for their actual numbers.

However, I can't find any mention of overdetermined types in [Section 4.7](https://specification.modelica.org/maint/3.6/class-predefined-types-and-declarations.html#balanced-models). The definitions of _local number of unknowns_ regarding connectors states:

> For each declared component of specialized class connector component, it is the number of **unknown variables** inside it (i.e., excluding parameters and constants and counting the elements after expanding all records and arrays to a set of scalars of primitive types).

It is not clear to me if "unknown variables" here must be interpreted in the same sense as "number of variables" in Section 9.1.3. In that case, I guess we should state it explicitly, but I don't think this is actually the case.

Correspondingly, on the equation side I can't find any mention of overconstrained connection operators in the definition of _local equation size_. In particular, there is no mention about how equations that are conditionally activated by statements such as
```modelica
if Connections.isRoot(A.R) then
  <some equation(s)>
end if;
```
should be counted.

I guess this should be fixed in the next version of the specification, otherwise it is not too clear how one can check the balancedness of models using overconstrained connections.

**Comment by casella** [comment]
I prepared a small MWE to help working on this ticket:
```modelica
package TestOverconstrained
  type ReferenceSpeed
    extends Real;

    function equalityConstraint
      input ReferenceSpeed omega1;
      input ReferenceSpeed omega2;
      output Real residue[0];
    algorithm
      assert(abs(omega1 - omega2) < 1e-10, "inconsistent omega reference across the branch");
    end equalityConstraint;
  end ReferenceSpeed;

  connector Pin
    Real v;
    flow Real i;
    ReferenceSpeed omega;
  end Pin;

  model Gen
    Pin p;
  equation
    p.v = 0;
    Connections.potentialRoot(p.omega);
    if Connections.isRoot(p.omega) then
      p.omega = 1;
    end if;
  end Gen;

  model Line
    Pin p_a;
    Pin p_b;
    parameter Real R = 1;
  equation
    p_a.i + p_b.i = 0;
    p_a.i - p_b.v = R*p_a.i;
    p_a.omega = p_b.omega;
    Connections.branch(p_a.omega, p_b.omega);
  end Line;

  model Load
    Pin p;
    parameter Real R = 1;
  equation
  p.v = R*p.i;
  end Load;
  
  model System2
    Gen gen1;
    Load load;
    Line line1;
    Line line2;
  equation
    connect(gen1.p, line1.p_a);
    connect(line1.p_b, load.p);
    connect(gen1.p, line2.p_a);
    connect(line2.p_b, load.p);
  end System2;
end TestOverconstrained;
```

**Comment by casella** [comment]
Here is a tentative informal formulation of rules about how to count equations and variables when overdetermined types and overconstrained connection operators are used:
1. when computing the _local number of unknowns_ (Definition 4.1), overdetermined type variables and records in connectors should be treated as regular types, i.e., after expanding them, all scalar variables inside them should be counted;
2. when computing the _local equation size_ (Definition 4.2) , `Connections.isRoot(A.R)`, where `A.R` is an instance of an overdetermined type or record showing up in connector instance `A`, should be assumed to return `true`;
3. when computing the _local equation size_ (Definition 4.2), one should also count the number of variables of `A.R` once (after expanding arrays and records to basic scalar types) for each `Connections.branch()` statement referring to it.

The rationale of rules 1. and 2. is that root nodes are meant to compute all values of overdetermined type variables on connectors, so one shoud activate there optional computation based on being the root node, and consider all the corresponding variables on connectors as unknowns.

The rationale of rules 1. and 3. is that branches are supposed to get all the overdetermined variables from one connector of the branch, and to compute all the overdetermined variables on the other branch, which will passed down the tree of the connection graph once the redundant connection equations have been eliminated. So, we account for all those variables in the local number of unknowns, and then we add a suitable number of equations to the local equation size to set them on one of the two involved connectors.

Note that the constraints equations returned by the `equalityConstraint()` function of the overdetermined types are relevant when handling _connection equations_, but they aren't (as far as I understand) when examining a single model for balancedness.

@HansOlsson do you think I got the rules right? As I understand,they work fine with the above MWE, though I'm not 100% sure about more complex cases. If so, I can try to formulate a PR to amend the specification text.

Thank you!

**Comment by HansOlsson** [comment]
> It is not clear to me if "unknown variables" here must be interpreted in the same sense as "number of variables" in Section 9.1.3. In that case, I guess we should state it explicitly, but I don't think this is actually the case.

My first reaction was that it wasn't so we shouldn't add anything (since adding "counted normally - ignore section 9.1.3" would just be confusing). Then I had some second thoughts, and then I got the result at the end.

> Correspondingly, on the equation side I can't find any mention of overconstrained connection operators in the definition of local equation size. In particular, there is no mention about how equations that are conditionally activated by statements such as

Note that there is no isRooted operator, but rooted and isRoot:
- For isRoot we just add it in the normal way, but there is some other magic!
- The rooted operator should be unproblematic, and as I understand the two branches must be matched in size.

After some thinking I believe the idea is as follows:
- Treat overconstrained connectors as normal variables
- Compute the equation size in the normal way
- However, each root-less spanning tree adds the size of the root (counted as normal variables) minus the equalityConstraint-output size!
(Yes, Dymola has already implemented something like - I should use the source.)

So:
- If we only want to consider simulation models there is nothing to change (as each spanning tree must have exactly one root!)
- If we use overconstrained connectors when not needed (where equalityConstraint is just a-b), the count isn't unchanged, which is a good sanity check.

Applying the rule:
Gen:
Unknowns: 3
Equations: 1 normal, 1 for flow, and then (if Connections.isRoot(p.omega) then 1 else 0)+(if Connections.isRoot(p.omega) then 0 else 1)

Line: 
Unknowns: 6
Equations: 3+2 (flow-variables)+1 (spanning-tree without root!)

If we modify Line to remove Connections.branch we would have two spanning trees, and thus 7 equations and 6 unknowns!

Load:
Unknowns: 3
Equations: 2+1 (no root!)

For MBS it means that we add 6 equations for each root-less spanning tree (if we have 3x3 rotation matrices in the frames).

**Comment by HansOlsson** [comment]
> @HansOlsson do you think I got the rules right? As I understand,they work fine with the above MWE, though I'm not 100% sure about more complex cases. If so, I can try to formulate a PR to amend the specification text.

It is somewhat similar to what I wrote, but it failed on some edge cases.
E.g., consider a model with two potentialRoots - in the same spanning tree. 
Counting both of them wouldn't make sense, right?

**Comment by casella** [comment]
> Note that there is no isRooted operator, but rooted and isRoot:

My mistake, sorry, I meant isRooted. I have corrected the text now.

**Comment by casella** [comment]
I have to admit that I just considered "flat" models, where models defined by equations are connected at the same level. We should of course consider hierarchically structured models, where models can contain other models and so on. I understand your formulation covers that as well.

So, I understand the extra rule to add to Definition 4.2 would be:
- for each root-less spanning tree involving overdetermined types or records, the size of the root (once expanded to basic scalar types) minus the equalityConstraint-output size

In the case of `Gen`, either you assume that `p.omega` is not root, and then you have a degenerate root-less spanning tree with just one node, so you need to add the size of the root (1) minus the size of the constraints (0), or you decide `p.omega` is root, and then you have the third conditional equation active, but no additional equation because the spanning tree is a root node, so it's not rootless. A tool should probably check both options.

In the case of `Line`, there is a rootless spanning tree connecting `p_a.omega` and `p_b.omega`, so you need to add one equation for that, bringing the total to 6 (three in the equation section, two for flow variables, and one for the rootless spanning tree), which is the local number of unknowns.

In the case of `Load`, the rootless spanning tree is the node `p.omega`, thus we need to add one equation to the equation in the equation section and to the equation for the flow variable on the connector, totalling three, which is the local number of unknowns.

In the case of `System2`, there are no rootless spanning trees, so there is no equation to add besides the component equations and the usual connection equations.

Do I get it right?

**Comment by casella** [comment]
@HansOlsson shall I open a PR to the specification text accordingly, or can you do that?

**Comment by HansOlsson** [comment]
> @HansOlsson shall I open a PR to the specification text accordingly, or can you do that?

I can do it, hoping that someone can review the PRs.
