### ISSUE TITLE
Grammar issue in drawing ordering sentence

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3445]
To me this sentence sounds grammatically wrong:

https://github.com/modelica/ModelicaSpecification/blob/8d587bf1d3f22da50d801d7440c5f8bf96c28176/chapters/annotations.tex#L625

Should it be one of these alternatives?
> First base class contents are drawn...

> First base class content is drawn ...

**Comment by gwr69** [comment]
It should be:

> First, base class contents are drawn ...
