### ISSUE TITLE
Providing experiment annotation always override base class StartTime

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3450]
This is a follow-up to https://github.com/modelica/ModelicaSpecification/pull/2999, since I'm not happy with my conclusion about the consequences in https://github.com/modelica/ModelicaSpecification/issues/2985#issuecomment-1822440449.

The problem is this part of the synopsis of `experiment`:
```
  Real StartTime(unit = "s") = 0;
```
because it means it is not possible to inherit `StartTime` from a base class.

In order to properly support inheritance of experiment options, I think we have to move the default value for `StartTime` out of the synopsis, and instead describe it in the semantics part.

**Comment by HansOlsson** [comment]
Note that inheritance of experiment is part of #2535 and has not yet been merged.

I agree that it should be possible to inherit a modified StartTime, but I don't think the consequences are like that. 
Clearly it must be clarified, to avoid ambiguities.

I view experiment as similar to a parameter record in the class, and modifiers as _modifiers_ - not as _record constructors_.

If we include the parameter record we see the similarity:
```
model A
  Experiment experiment2(StartTime=-1.0);
  annotation(experiment(StartTime = -1.0));
end A;

model B
  extends A(experiment2);
  /* This model has StartTime = -1.0, inherited from A. */
  annotation(experiment); /* Not a valid experiment annotation?; as a modifier it modifies nothing */
end B;

model C
  extends A(experiment2());
  /* This model also has StartTime = -1.0, inherited from A. */
  annotation(experiment()); /* Valid annotation. */
end C;

model D
  extends A(experiment2=Experiment()); /* Ignores StartTime value */
  annotation(experiment=Experiment()); /* Should not be valid */
end D;
```

It may be that we should change it to `record Experiment ... end Experiment;parameter Experiment experiment;` to make it clearer, and possibly state that the name Experiment is internal.

**Comment by henrikt-ma** [comment]
Sorry, I forgot that #2535 isn't merged yet.  Anyway, I think we have identified an important ambiguity regarding the meaning of annotations defined by pseudo-code records.  Better than `record Experiment … end Experiment; parameter Experiment experiment` would be to explain in the [Notation](https://specification.modelica.org/master/introduction1.html#notation) section what it means to define an annotation by a record, and then link to this explanation from the introduction to [Annotations](https://specification.modelica.org/master/annotations.html).

**Comment by HansOlsson** [comment]
> Sorry, I forgot that #2535 isn't merged yet. Anyway, I think we have identified an important ambiguity regarding the meaning of annotations defined by pseudo-code records. Better than `record Experiment … end Experiment; parameter Experiment experiment` would be to explain in the [Notation](https://specification.modelica.org/master/introduction1.html#notation) section what it means to define an annotation using record syntax, and then link to this explanation from the introduction to [Annotations](https://specification.modelica.org/master/annotations.html).

That is the idea in #3448 except that it is explained in the annotation-chapter; instead of at the start (and then linked) - to hopefully make it slightly easier to find, and having a less overwhelming start of the specification.

**Comment by HansOlsson** [comment]
As far I understand #3448 will resolve this.

**Comment by henrikt-ma** [comment]
> As far I understand #3448 will resolve this.

Yes, this is also my understanding; the important part is the clarification that annotations shall be seen as modifications, not record construction with defaults.
