### ISSUE TITLE
Are different external functions allowed to Include non-static definitions of the same function?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3451]
Background: We are trying to support a situation where a library needs to control the effect of `#include <math.h>` in an external function `Include` annotation, by having certain macros defined during the include.  If code for different external functions are put in the same compilation unit, and some other external function also does `#include <math.h>`, the use of include guards means that only the external function whose `Include` annotation is included first will get _math.h_ the way it wants.  The only solution I can see to this problem is to generate separate C files for each external file, so that there is no harmful leakage of `Include` annotation contents from one external function to another.

However, to implement this strategy we need some `Include` annotation sanity, which I wonder if the specification could provide.  In essence, this is what I would like to forbid:
```
function f
  output Real y;
external "C"
  y = fExt()
    annotation(Include = {
      "
/* Function implementations from f */
double fExt() { return 1.0; }

double gExt() { return 1.0; }
"});
end f;

function g
  output Real y;
external "C"
  y = gExt()
    annotation(Include = {
      "
/* Function implementations from g */
double fExt() { return 1.0; }

double gExt() { return 1.0; }
"});
end g;
```

That is, both `f` and `g` have `Include` annotations that bring in definitions of the external functions `fExt` and `gExt`.  If all external code is gathered in one compilation unit, one needs to solve the problem of having multiple definitions for `fExt` and `gExt` in the same compilation unit, but this can often be avoided by never including the same `Include`-string more than once (in the example above, it doesn't work due to the difference in comments, but anyway).

If each external code is handled as a separate compilation unit, on the other hand, each compilation unit will be fine by itself, but the linker won't like that the symbols `fExt` and `gExt` are found in several object files.

Would it be possible to state that the user is responsible for avoiding `Include` annotations with conflicting symbol definitions, and that the tool is responsible for including any `Include` annotation string at most once and in at most one compilation unit?

Should the specification make a difference if the functions are made static?  Let's say we have _my_ext_funs.c_:
```
/* my_ext_funs.c */
static double fExt() { return 1.0; }

static double gExt() { return 1.0; }
```
and then do
```
function f
  output Real y;
external "C"
  y = fExt()
    annotation(Include = "my_ext_funs.c");
end f;

function g
  output Real y;
external "C"
  y = gExt()
    annotation(Include = "my_ext_funs.c");
end g;
```
This works with the approach of one compilation unit per external function, but should such usage be supported by the specification?

**Comment by HansOlsson** [comment]
Having include guards to guard against multiple inclusion is fairly standard C and could be applied to these functions as well. 

However, requiring setting flags before including math.h seems very weird.

Obviously repeating the same include seems a bit confusing and tools should be able to avoid that, but since it is possible to make minor white-space changes that turn two seemingly identical lines into different ones I don't think we should spend time on that in the specification; as the guards are anyway needed.

Requiring multiple translation unit for a model would complicate the build process, and likely slow it down.
The idea with multiple translation units is instead to precompile the library and link with it - and in that case functions should clearly not be static.

**Comment by henrikt-ma** [comment]
> Having include guards to guard against multiple inclusion is fairly standard C and could be applied to these functions as well.

This only solves the problem of multiple function definitions when all external functions are handled in the same translation unit, it doesn't solve the issue of the symbols becoming defined in multiple translation units.

> Requiring multiple translation unit for a model would complicate the build process, and likely slow it down.
The idea with multiple translation units is instead to precompile the library and link with it - and in that case functions should clearly not be static.

I'm not proposing that the specification requires the use of multiple translation units, only that the specification supports such treatment, as this is the only safe way I can think of to avoid problems due to bad interaction between `Include` annotations.

Generally, I am strongly in favor of the precompiled library approach, but there are problems with this approach since the specification hasn't solve the problem of how to build these libraries (https://github.com/modelica/ModelicaSpecification/issues/1668).  In particular, code that wants to make use of the functions in _ModelicaUtilities.h_ both needs a way of finding this header to get the correct function prototypes, and a way to link with a library that provides the function symbols.  In view of this, I can understand why some external functions are being defined inside `Include` annotations.

**Comment by henrikt-ma** [comment]
I examined a small subset of the models in our test suites, and found that having 9 different external functions could be a relevant numer for investigating the performance aspect of handling each external function in a separate translation unit.

Yes, there was a difference in the time to compile and link (I didn't make separate measurements), but it was in the order of a few tens of a second.  In comparison to the total time to translate and compile a model, this difference is not noticeable.

**Comment by HansOlsson** [comment]
> I'm not proposing that the specification requires the use of multiple translation units, only that the specification supports such treatment, as this is the only safe way I can think of to avoid problems due to bad interaction between `Include` annotations.

To me this is just a requirement on library developers.

Clearly we can add that multiple identical include-directives should not be repeated in one translation unit, but it will not handle the case if there any minor differences.

If we use multiple translation units and the include contains actual code (not just header-stuff) the functions must either be static or weak definitions to allow them to link together. (Standard C doesn't have weak definitions as far as I know, the inline in C++ gives a weak definition.)

But if they are included multiple times in the same translation unit neither of those variants work, only include guards suffice.
So, we could add that it should be treated as headers, i.e., include guards **and** support including it in multiple translation units that are linked together.

**Comment by henrikt-ma** [comment]
Sounds like we'd like to do _something_ about the situation.  I'll set up a PR where we can discuss _what_ to do.
