### ISSUE TITLE
Who is responsible for providing size_t inside Include annotations?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3456]
I am trying to make sure that external C functions created with Wolfram System Modeler have maximum compatibility also with other tools, which has finally led me to the question of who is responsible for providing `size_t` inside `Include` annotations.

I see three main alternatives:
- Tool is responsible.
- Deprecated feature that tool is responsible.
- User is responsible.

In case it would be a tool responsibility, there are two more questions (in case of deprecated responsibility, I'd like to leave this sort of details unspecified):
- How?
  * Tool shall automatically include _stddef.h_ (which I suppose is the main candidate of several possible headers).
  * Explicitly stating that how the tool should do it is unspecified.
- When?
  * When array dimensions are being passed (minimizing `Include` annotation dependency on this feature).
  * For all functions (trivial to implement).

Edit: The following example illustrates what this question is about:
```
function myArraySum
  input Real[:] u;
  output Real y;
external "C"
    annotation(
      Include = {
        "#include <stddef.h>", /* Is this needed? */
        "
double myArraySum(const double* u, size_t len) /* Specification mandates use of size_t here. */
{
  double acc = 0;
  const double* end = u + len;
  for (; u != end; ++u) {
    acc += *u;
  }
  return acc;
}
"
      }
    );
end myArraySum;
```

**Comment by henrikt-ma** [comment]
Personally, I'd like to go with the deprecation approach, but I think it should be pointed out that it is not trivial to report a deprecation warning.

However, I can at least see how a deprecation check could be approximated:
- Scan contents of the `Include` annotation, looking for:
  * Include directives with any of the headers known to provide `size_t`.
  * The `size_t` identifier.
- If the `size_t` identifier is encountered before any include directive, give the warning that it _looks like_ deprecated behavior.  The warning can explain how it can be silenced by clearly including one of the recognized headers with `size_t`.  For example, putting `"#include <stddef.h>"` as the first element of the `Include` annotation array should work.
- As the warning only approximates the precise check, _always_ automatically include _stddef.h_ before the `Include` annotation content during the deprecation period.
- Use a simple regexp search for easy implementation, or proper C tooling (including preprocessor) for more accurate results.

**Comment by HansOlsson** [comment]
I believe would say that tools have to ensure that size_t is defined when part of a definition, but leave exactly how unspecified. But I could also consider that it is required to be part of the Include-text; as it makes the Include-text self-contained.

If Include annotations are just part of the source-code of the model it doesn't seem that anything is needed (as some header defining size_t is almost certain).

Even if the Include annotation is separately compiled I don't see a major issue - I assume the thing that is separately compiled is a wrapper generated by the tool (to be declared and called in the main model code) and the Include-header contents. Thus requiring  a suitable include as e.g.,  `#include <stddef.h>` as well doesn't seem too demanding. If that include slows down the compilation too much there are likely compiler-specific fixes.

Note that even if it is a bit complicated to check whether size_t is needed, the Include code should be robust enough that it can handle a redundant definition of size_t (and certainly not define size_t in a way that would cause conflicts).

**Comment by henrikt-ma** [comment]
> I believe would say that tools have to ensure that size_t is defined when part of a definition, but leave exactly how unspecified. But I could also consider that it is required to be part of the Include-text; as it makes the Include-text self-contained.

I find the latter – self-contained external function declarations – the most elegant, but I'm sure it would invalidate too much existing code if we would make it a library requirement overnight to ensure of `size_t` is defined.  This is why the deprecation approach is my favorite.

> If Include annotations are just part of the source-code of the model it doesn't seem that anything is needed (as some header defining size_t is almost certain).

Yes, and this is why we need to be a bit careful and not make it a hard requirement overnight, as there are probably lots of functions out there that currently don't provide for `size_t` themselves, as they have poor chances of detecting the need to do so with current tools (and unclear separation of responsibilities).

> Even if the Include annotation is separately compiled I don't see a major issue - I assume the thing that is separately compiled is a wrapper generated by the tool (to be declared and called in the main model code) and the Include-header contents. Thus requiring a suitable include as e.g., `#include <stddef.h>` as well doesn't seem too demanding. If that include slows down the compilation too much there are likely compiler-specific fixes.

I am not at all concerned about the compilation cost, guessing that the extra time it may take to include _stddef.h_ isn't noticeable.  I'm raising the question because I'd like the responsibility for `size_t` availability to be clearly on either the tool or the library author side.

> Note that even if it is a bit complicated to check whether size_t is needed, the Include code should be robust enough that it can handle a redundant definition of size_t (and certainly not define size_t in a way that would cause conflicts).

Certainly.

**Comment by HansOlsson** [comment]
Language group:
- Tool responsibility: Include any header that defines `size_t` if the C-code uses array
- User responsibility that code is compileable as a standalone unit with #include <stddef.h> prepended if any array is used
