### ISSUE TITLE
convertElement to an empty string

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3459]
I'm looking at a version conversion script in a pretty old library. I believe it predate standardization of the conversion scripts. It is given as a Dymola script. However, I found the following construct in it:
```
convertElement("OldClass","OldName","")
```
Is it acceptable construct? Is it still supported in Dymola? Does it mean that if OldName is used in a connect-equation, the whole connect-equation needs to be removed?

**Comment by HansOlsson** [comment]
That variant is not specified.

The specification has the special case `convertModifiers("OldClass", {"OldName"}, fill("",0));` and internally Dymola handles them the same. I don't see that we need to have two constructs for that. As for what happens OldName isn't used in a modifier, but elsewhere: I don't think that is specified.

**Comment by HansOlsson** [comment]
I believe that clarifies it.

**Comment by eshmoylova** [comment]
But does Dymola handle it the same way as a convertModifier or as convertElement? convertModifier simply needs to remove any modification with "oldName" from modifications. convertElement needs remove from the modifications and also from any equations. Are you saying that if new name is "" in convertElement, equations are not considered?

**Comment by HansOlsson** [comment]
> But does Dymola handle it the same way as a convertModifier or as convertElement? convertModifier simply needs to remove any modification with "oldName" from modifications. convertElement needs remove from the modifications and also from any equations. Are you saying that if new name is "" in convertElement, equations are not considered?

Exactly, and I don't think that's something that we need standardized.

**Comment by HansOlsson** [comment]
I believe this can be closed without any change.

**Comment by eshmoylova** [comment]
I was hoping we could discuss it at the phone meeting, so that I don't have to type and that we can hear other people's opinions. But here it goes... The specification has the following non-normative text:
> In case a parameter is simply renamed it is preferable to use convertElement, since that also handles, e.g., binding equations using the parameter.

To me, it means there is a promise that if convertElement is used, equations and modifiers will also be taken care of. Hence, my question, how are we supposed to take care of the equations and binding equations in this case? I was hoping we could get more opinions whether it is clear that if convertElement "deletes" an element, we just delete a modifier for this particular element and if it is used anywhere else, it will result in an error in due course. From a point of view of a library developer, a change that deletes an element would then be a backward incompatible change even with the conversion scripts. Is it not worth being made aware of?

**Comment by eshmoylova** [comment]
Actually, I decided to reopen it after all. If we don't have a chance to discuss it tomorrow, I will close it.

**Comment by HansOlsson** [comment]
Language group:
Add case to specification: Elena, Gerd
Forbid case: Gerd, Hans, Henrik, Markus
Tools can warn, and take sensible action.
