### ISSUE TITLE
[Need Clarify] Can event clock ticks multiple times at the same time?

### ISSUE THREAD

**Issue by TongYuan-MC** [modelica/ModelicaSpecification#3460]
![image](https://github.com/modelica/ModelicaSpecification/assets/153701357/2d81f6cb-9764-4c73-8c26-ad60fc2da19c)

[Modelica specification 3.6](https://specification.modelica.org/maint/3.6/synchronous-language-elements.html#clock-constructors): "The result is of base type Clock that ticks when `edge(condition)` becomes true".  
It is unclear whether **the event clock can ticks multiple times  at the same time**?

We have an example model which contains three event clock, the clock `c1` ticks twice in time 0 and  $t_0 =  (20 \pi - \frac{\pi}{6}) / 30 \approx 2.07694$

``` modelica
model ClockActivedMoreThanOnce
  Real uc = sin(30 * time);
  Integer k1, k2, k3;

  Boolean b1(start = false);
  Integer m1(start = 0);

  Integer d1(start = 0);
  Integer d2(start = 0);
  Integer d3(start = 0);
  Clock c1 = Clock(b1, 1);
  Clock c2 = Clock(rem(k1, 2) == 1, 0.1);
  Clock c3 = Clock(uc >= -0.5, 0.1);
equation
  k1 = hold(d1);
  k2 = hold(d2);
  k3 = hold(d3);
  when {rem(k1, 2) == 1, rem(k2, 2) == 1, rem(k3, 2) == 1} then
    b1 = not pre(b1);
    m1 = pre(m1) + 1;
  end when;

  when c1 then
    d1 = previous(d1) + 1;
  end when;
  when c2 then
    d2 = previous(d2) + 1;
  end when;
  when c3 then
    d3 = previous(d3) + 1;
  end when;
end ClockActivedMoreThanOnce;
```

The left limit of `d1 = 4, d2 = 2, d3 = 10` at $t_0$ are even numbers and `b1 = false`

At time $t_0$, we have

1.  `uc = -0.5`,  `edge(uc >= -0.5) = true`, so `c3` ticks 
2. `d3 = 11, k3 = hold(d3)` becomes odd, the when condition satisfied
3. `b1 = true, edge(b1) = true`, `c1` ticks 
4. `d1 = 5, k1 = hold(d1)` becomes odd, `c2` ticks  and the when condition satisfied
5. `b1 = false` and `d2 = 3, k2 = hold(d2)` becomes odd, the when condition satisfied
6. `b1 = true, edge(b1) = true`, `c1` ticks  **again**
7. `d1 = 6` finish

We see in above example, clock $c1$ ticks twice at time $t_0$.

When simulated in OpenModelica 1.21.0, we see the following result:
![OpenModelica](https://github.com/modelica/ModelicaSpecification/assets/153701357/8adcdb68-377b-4459-8472-91455b0ad5f4)

At time $t_0 = (20 \pi - \frac{\pi}{6}) / 30 \approx 2.07694$, `k1` jump from 4 to 6 which means clock `c1` be **activated twice** at time $t_0$ just like above analysis. Same result in Dymola 2023x. 

Can event clock ticks multiple times at the same time? Equivalent to saying are OpenModelica and Dymola handled the example model in the right way?

**Comment by HansOlsson** [comment]
I would say that event clocks can tick multiple times at the same time-value, because I cannot see any better alternative.

**Comment by christoff-buerger** [comment]
> It is unclear whether the event clock can ticks multiple times at the same time?

Yes, like any other event, many events (including the very same one several times) can be triggered at the very same time point.

Note, that the condition triggering an event clock is evaluated in continuous time (it is part of the continuous time partition); it is subject to ordinary zero-crossing event evaluation -- nothing special about it. Thus it can have a "rising edge" several times for the same time time point; and an event clock must tick for each rising edge of its condition.

In fact, you can easily construct an event clock that would tick infinite often at a single time point, thus, makes your simulation "freeze". But this is nothing new; you can construct such non-terminating simulations with normal events as well. The keyword here is: fixpoint computation; you have to evaluate until a fixpoint for your conditional discrete values is reached.
