### ISSUE TITLE
Incorrectly specified color in annotation?

### ISSUE THREAD

**Issue by maltelenz** [modelica/ModelicaSpecification#3462]
Should this just be ` = Black` like the other cases in the vicinity?
https://github.com/modelica/ModelicaSpecification/blob/5b9562ce19e22d8a606167582818c4cb45e78c71/chapters/annotations.tex#L929

**Comment by HansOlsson** [comment]
> Should this just be ` = Black` like the other cases in the vicinity?
> 
> https://github.com/modelica/ModelicaSpecification/blob/5b9562ce19e22d8a606167582818c4cb45e78c71/chapters/annotations.tex#L929

Yes, those **two** cases of `= Color.Black` should just be `= Black`.
