### ISSUE TITLE
Purpose of stored-definition with several class definitions, and the within-clause

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3466]
What is the purpose of allowing `stored-definition` to have zero or several class definitions?

If we are to keep it this way, the definition of the `within`-clause would need to be updated to better cover the case of not just a single class definition.

**Comment by HansOlsson** [comment]
> What is the purpose of allowing `stored-definition` to have zero or several class definitions?

Historically it has been used (e.g., for "SaveTotal") - especially without within. Really annoying users can use it combination with within.

> If we are to keep it this way, the definition of the `within`-clause would need to be updated to better cover the case of not just a single class definition.

I don't see that `within `causes a problem for it. Consider the following silly example of a package `P` containing a mo file as follows on Windows:
```
within P;
model MA
end MA;

model ma
end ma;
```
I don't know if there's a more relevant use case for this.

**Comment by HansOlsson** [comment]
Basically `within` allows tools to detect if files have just been moved around in the directory; thus it makes sense that there's only one `within` per file.

**Comment by henrikt-ma** [comment]
> I don't see that `within `causes a problem for it. Consider the following silly example of a package `P` containing a mo file as follows on Windows:
> 
> ```
> within P;
> model MA
> end MA;
> 
> model ma
> end ma;
> ```

There wouldn't be a clear way to name that file.  So in addition to generalizing the `within`-clause to applying to every class in the `stored-definition`, we'd also have to say something about the filename-class mapping.

> I don't know if there's a more relevant use case for this.

I'd prefer steering away from `stored-definition` with anything but a single class definition, rather than trying agree on exactly how it should work.  As usual, tools would still keep support for legacy files with multiple classes for a long time. :)

**Comment by HansOlsson** [comment]
> What is the purpose of allowing `stored-definition` to have zero or several class definitions?
> 
> If we are to keep it this way, the definition of the `within`-clause would need to be updated to better cover the case of not just a single class definition.

I checked https://specification.modelica.org/master/packages.html#mapping-a-package-class-hierarchy-into-a-single-file-nonstructured-entity and already in Modelica 3.0 (possibly earlier) it is split into three cases:
- A file stored inside a package: Here within is required and stored-definition may only contain one class.
- A top-level class loaded from ModelicaPath: within can be omitted  (or include empty name), but stored-definition may only contain one class
- A top-level class loaded explicitly. within can be omitted (or include empty name) and stored-definition may contain multiple classes.

So, I don't see a major issue with the within-clause in combination with several class definitions.

**Comment by henrikt-ma** [comment]
> * A file stored inside a package: Here within is required and stored-definition may only contain one class.

This is only when mapping a package hierarchy to the file system.

> * A top-level class loaded from ModelicaPath: within can be omitted  (or include empty name), but stored-definition may only contain one class

Right, so no need to worry about ModelicaPath here.

> * A top-level class loaded explicitly. within can be omitted (or include empty name) and stored-definition may contain multiple classes.

What prevents _MyClasses.mo_ from placing classes within some package?

Anyway, at least I have a difficulty extracting the rules and purpose of files with non-1 class definitions from the current text.  Wouldn't it be easier to express clearly by describing such files in a separate paragraph somewhere?

**Comment by henrikt-ma** [comment]
> > What prevents _MyClasses.mo_ from placing classes within some package?
> 
> That `within` should correspond to the enclosing structure and there isn't any. Is there a need to clarify that within is used for consistency checking and not to move classes arbitrarily?

Yes, I think that would be helpful, especially if combined with something along the following lines in a separate section before _File System Mapping of Package/Class_:
> A `stored-definition` not containing exactly one class definition can only be used to define top-level classes, cannot be used for mapping packages or class-hierarchies to files, and cannot be located using the `MODELICAPATH`.  It follows that any `within`-clause (see below) in such a `stored-definition` shall not contain a name.

Any suggestions for what would be a good title of that section?  How about _Stored Definitions Containing Multiple Class Definitions_?
