### ISSUE TITLE
Pixelated fonts in Language Specification PDF

### ISSUE THREAD

**Issue by markusandres3DS** [modelica/ModelicaSpecification#3476]
The official PDF of the MLS uses pixel-fonts. This makes readability sub-optimal. 

For a standalone PDF viewer (Acrobat Reader and PDF XChange) this results in fonts like (first words of the abstract):  
![grafik](https://github.com/modelica/ModelicaSpecification/assets/25923908/6e91555d-a26d-4cf1-b713-10effb57c185)

Browsers do usually do a bit of smoothing, resulting in
![grafik](https://github.com/modelica/ModelicaSpecification/assets/25923908/92029393-06b5-4ab1-913f-af3883e64a74)

The solution for me was to install the LaTeX-package `cm-super` on the computer generating the PDF, as mentioned here: https://tex.stackexchange.com/questions/1291/why-are-bitmap-fonts-used-automatically/546882#546882. 

According to my tests, this generates a document with vector-based fonts and virtually unchanged file-size.

**Comment by henrikt-ma** [comment]
Thanks for reporting this.  As I personally never look in the published PDFs, and as my locally generated PDFs don't suffer from this, I would never have noticed.  I wonder why this isn't seen in my local build…

Do you mean that you can reproduce the pixel-fonts in a local build without the `cm-super` fix?

**Comment by markusandres3DS** [comment]
> Do you mean that you can reproduce the pixel-fonts in a local build without the `cm-super` fix?

This is what I did. Without `cm-super` installed on my computer, the fonts are pixelated, adding the package gives perfectly scalable vector-fonts, no changes to the TeX file required. It seems, the computer building the PDF does not have `cm-super` installed. I have tested on Windows using MiKTeX Console.

BTW: I think this should be added to the "How to edit and generate final documents" section in the [README](https://github.com/modelica/ModelicaSpecification).

**Comment by dietmarw** [comment]
#3478 should take care of this. Of course the Docker image also needs to then get generated and deployed. Not sure if this is done automatically, @sjoelund ?

**Comment by henrikt-ma** [comment]
> BTW: I think this should be added to the "How to edit and generate final documents" section in the [README](https://github.com/modelica/ModelicaSpecification).

I think it would be better to modify the text in the _README.md_ to not say _final_:
```
How to edit and generate documents:
```

This way, we don't need to describe every detail of the correct CI build setup on the repository front page.  The CI setup can then speak for itself.
