### ISSUE TITLE
 Avoid line breaking just before closing parenthesis

### ISSUE THREAD

**Issue by tobolar** [modelica/ModelicaSpecification#3490]
A line breaking just before closing parenthesis is odd. Probably caused here by used `\lstinline` which shall be fixed.

![grafik](https://github.com/modelica/ModelicaSpecification/assets/9588978/c765ef0f-691b-459f-b693-141115d74d9d)

**Comment by henrikt-ma** [comment]
Unfortunately, this sort of problem is pretty common when using `\lstinline`.  I'm not convinced it's worth trying to keep track of all glitches like this; we might end up with a source which is full of obsolete hacks and a pain to maintain.

**Comment by HansOlsson** [comment]
Well, in the specific case one solution is to just remove the parenthesis (including its contents).

It took me a few seconds to realize that it means that if you have `convertMessage("OldPackage", "Don't use");` it means that `OldPackage.OldModel` will also give a warning, but to me that does sort of fall under "use of OldPackage", and the extra text was more confusing than helping.

**Comment by tobolar** [comment]
> in the specific case one solution is to just remove the parenthesis (including its contents).

IMO a good written text rarely needs parentheses.

**Comment by gwr69** [comment]
... the sentence also looks grammatically awkward to me. If content needs to be kept I suggest:

>For any use of `OldClass` or elements thereof report ...
