### ISSUE TITLE
General deprecation of assignment modification?

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3493]
I was surprised to find that this use of the assignment operator is deprecated:
```
function f
  input Real u := 1.0;
end f;
```
while this is not, even though they are both cases of `modification` in the grammar:
```
Real x(start := 1.0);
```

It is not clear to me whether this is also deprecated, since the rule about deprecation is given in the context of functions, but could be interpreted more generally:
```
model M
  Real x := 1.0;
end M;
```

Isn't it about time we generally deprecate the assignment operator in `modification`, so that it is only used in `statement`?

(If it really only is the declaration assignment in functions which is deprecated, implementing the deprecation warning is a lot messier than if assignment modification would be generally deprecated, or if at least the restriction to function was lifted.)

**Comment by HansOlsson** [comment]
Bindings for variables should now only use `=` not `:=`. As far as I recall it was only function-variables that used `:=` before.

The reason for that - and the mess with deprecating it are related:
- Attributes are one complication.
- For inputs to functions one can change it later - and that uses `=` and the function cannot internally change the value of the input; so `=` makes the most sense.
- For non-inputs to functions it is similar to assignments in the functions, but having different syntax for inputs and non-inputs to functions is both confusing and difficult to implement. If the non-input is a record it makes to also allow assignment to the specific element.

So, the simplest is to just remove it completely from modifications.

**Comment by henrikt-ma** [comment]
OK, so we interpret the current specification as having deprecated all uses of `:=` in `modification`, and then we're talking about actually removing something which has been deprecated for a long time?!

**Comment by HansOlsson** [comment]
> OK, so we interpret the current specification as having deprecated all uses of `:=` in `modification`, 

At least that all uses of `:=` in modifications should be replaced by plain `=`. Whether they have actually been ok, and are now deprecated is less clear.

> and then we're talking about actually removing something which has been deprecated for a long time?!

**Comment by HansOlsson** [comment]
Is there something unclear here, and/or something that needs updating?

**Comment by henrikt-ma** [comment]
I'll make a PR where the details can be sorted out.
