### ISSUE TITLE
reinit does not update related equations

### ISSUE THREAD

**Issue by RandyParedis** [modelica/ModelicaSpecification#3497]
I was recently toying around with some experimentation in Modelica (I use OMEdit) and noticed the following weird situation. The model below will always yield `y = 1`, which is not what I was expecting. Shifting the `when` does not solve the issue.
```
class TestAnomaly
  output Real y;
  Real u = 1;
  Real next = 10.0;
equation
  y = /*Real*/(u);   // Problematic line
  when time > next then
    reinit(u, 1 - u);
  end when;
end TestAnomaly;
```

Marking `u` as an `Integer` and using `pre` appears to work until the state event is called again. Consider the following model:
```
class TestAnomaly
  output Real y;
  Integer u = 1;
  Real next = 10.0;
equation
  when time > next then
    reinit(u, 1 - u);
    reinit(next, next + 10.0);
  end when;
  y = /*Real*/(pre(u));
end TestAnomaly;
```
I would expect `y` to behave like `u`, which it does... But now both `u` and `y` are not following the desired behaviour (switching between 1 and 0, every 10 seconds).

Is there something I am missing? Is there a compiler optimization happening here, which counteracts the desired behaviour?

Thanks in advance!

**Comment by HansOlsson** [comment]
Both of the models are illegal and should be rejected as far as I can tell - https://specification.modelica.org/master/equations.html#reinit

> The operator reinitializes x with expr at an event instant. x is a component-reference (where any subscripts are evaluable) referring to a Real variable (or an array of Real variables) that must be selected as a state (resp., states), i.e., reinit on x implies stateSelect = StateSelect.always on x. expr needs to be type-compatible with x.

- For the second model: The first argument to `reinit` must be a real variable or an array of such, so `u` as an integer isn't legal.
- For both models: The first argument to `reinit` must be a state, and `Real u=1;` is not a state.

**Comment by RandyParedis** [comment]
Interesting.. So a "square wave" with varying "widths" should not really be done like this then?

Ideally, I want my output to be 1 for the first `x` seconds and 0 for the following `y` seconds, before repeating. Currently, I "solved" it by using a repeating table, but I am curious if there is another solution, such that both `x` and `y` may also be randomized after each "event"..

**Comment by HansOlsson** [comment]
> Interesting.. So a "square wave" with varying "widths" should not really be done like this then?
> 
> Ideally, I want my output to be 1 for the first `x` seconds and 0 for the following `y` seconds, before repeating. Currently, I "solved" it by using a repeating table, but I am curious if there is another solution, such that both `x` and `y` may also be randomized after each "event"..

I would look at `Modelica.Blocks.Sources.Pulse` and similar components

**Comment by RandyParedis** [comment]
Thank you so much for the help!
Cheers!

**Comment by HansOlsson** [comment]
Ok, question resolved.
