### ISSUE TITLE
when equations in algebraic loop?

### ISSUE THREAD

**Issue by gkurzbach** [modelica/ModelicaSpecification#3498]
Is it allowed for when equations to be part of an algebraic loop?
Following model leads to an error in Dymola but not in OMEdit:

```
model algebraicLoop 
	Real x;
	Real y(start=0.5,fixed=true);
	equation
		x = time - y;
		when time>0.5 then
		    y = -x/2;
		end when;
end algebraicLoop;
```
I have not found any statement to this regard in the specification. Please clarify.

**Comment by HansOlsson** [comment]
I believe the impure part can be handled in #3499 - The remaining part is thus just to state that there is nothing special with when-clauses and they can be part of systems of equations.

**Comment by henrikt-ma** [comment]
For what it's worth, System Modeler also builds and simulates this without any complaint.

**Comment by HansOlsson** [comment]
Dymola 2024x Refresh 1 also builds and simulates this without any complaint.

**Comment by HansOlsson** [comment]
I thus believe it was just a tool-issue, but it might be that the specification should be clearer.

**Comment by HansOlsson** [comment]
Language group: Agreement
