### ISSUE TITLE
Missing mention of deprecated differences between the two Text-annotations

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3512]
For the `Text`-annotation for connections in https://specification.modelica.org/master/annotations.html#connections1, it is said that the differences to the `Text`-annotation graphics primitive in https://specification.modelica.org/master/annotations.html#text are described in the description strings:
> It has the following definition (it is not equal to the `Text` primitive as part of graphics – the differences are marked after _Note_ in the description-strings):

This covers the differences regarding the members visible in the `Text` records, but doesn't mention the fact that the `Text`-annotation for connection also supports deprecated use of members from `FilledShape`.

I see two possible resolutions:
- Describe that the deprecated use of members from `FilledShape` is another difference between the two `Text`-annotations.
- Also allow deprecated use of members from `FilledShape` for the `Text` graphics primitive.

**Comment by HansOlsson** [comment]
https://github.com/modelica/ModelicaSpecification/pull/3316 removed FilledShape instead of keeping it deprecated; so it seems that we missed removing the text about deprecated contents - when we removed the contents.

**Comment by henrikt-ma** [comment]
Wonderful!  I'll prepare a fix.

**Comment by HansOlsson** [comment]
> Wonderful! I'll prepare a fix.

Already done, you can review instead!

**Comment by henrikt-ma** [comment]
I was too busy getting the sentence-based line breaking out of the way to see your comment in time…
