### ISSUE TITLE
`lineThickness` used in the description of arrows in `Line`

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3523]
[Line](https://specification.modelica.org/master/annotations.html#line) has `thickness` defined. But since it does not extend from `FilledShape`, it should not have `lineThickness`. The paragraph that explains how to draw the arrows keeps referring to `lineThickness`. Is it supposed to be `thickness`?

**Comment by casella** [comment]
Thanks @eshmoylova, I also noticed that as soon as you spotted my confusion between thickness and lineThickness. I was not alone in being confused 😄
