### ISSUE TITLE
Decide on one of 'member access operator' and 'postfix access operator'

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3541]
Avoiding scope creep in #3516 by isolating the problem that we have two different names for `a.b`:
- _postfix access operator_
- _member access operator_

We need to decide on which of these to use, and then apply the change.

My preference would be _member access operator_.

**Comment by HansOlsson** [comment]
> Avoiding scope creep in #3516 by isolating the problem that we have two different names for `a.b`:
> 
> * _postfix access operator_
> * _member access operator_
> 
> We need to decide on which of these to use, and then apply the change.
> 
> My preference would be _member access operator_.

I would also prefer that, since "postfix" just describes the syntax, not the semantics, and there are no prefix or infix access operators in Modelica as far as I know.
