### ISSUE TITLE
Enable an assert just once

### ISSUE THREAD

**Issue by PYF-FR** [modelica/ModelicaSpecification#3553]
As explain here, 
https://stackoverflow.com/q/78695608/26398063
The assert function behaves differently when called within a function.
It could be nice to add a new characteristic to the assert in order to use it only once even if used in a function.

It could help to reach the : "It is recommended to report the warning only once when the condition becomes false, and it is reported that the condition is no longer violated when the condition returns to true." of the specification : https://specification.modelica.org/master/equations.html#S3.SS7.p1 in 8.3.7

**Comment by HansOlsson** [comment]
To me this is primarily a tool-issue. The problem here is that it is difficult to keep track of whether it is the same warning or not - but I believe it can be improved.

However, you should duplicate the contents of the stackoverflow question here, since it seems the question has been removed for some reason.

**Comment by PYF-FR** [comment]
Hi, Thanks for having a look to my suggestion
I updated the link in my first comment

**Comment by HansOlsson** [comment]
As indicated I think this is a tool-issue, so I will close it shortly (after giving tool-vendors the chance to react and prioritize internally). I don't think that adding e.g., another enumeration member for this case would speed up tool-development.

**Comment by HansOlsson** [comment]
(So closing. Firmly believing that one or more tool-vendors will implement this functionality in coming releases.)
