### ISSUE TITLE
Number of input parameters of the derivative function

### ISSUE THREAD

**Issue by TongYuan-MC** [modelica/ModelicaSpecification#3554]
``` modelica
model IssueAboutDerivatives
  function fn
    input Real x;
    output Real y;
  algorithm
    y := x ^ 2 + 1;
    annotation(Inline = false, derivative = der_fn, smoothOrder = 2);
  end fn;

  function der_fn
    input Real x;
    input Real dx;
    output Real dy;
  algorithm
    dy := 2 * x * dx;
    annotation(Inline = false, smoothOrder = 1);
  end der_fn;

  Real x = sin(time);
  Real y = fn(x);
  Real d1y = der(y);
  Real d2y = der(d1y);

  Real y2 = der_fn(x, time);
  Real d1y2 = der(y2);
end IssueAboutDerivatives;
```

In the above model, we know that `d1y = der(y) = der(fn(x)) = der_fn(x, der(x))`, but there are two ways to handly `d2y = der(d1y)`:

1. d2y = der(d1y) = der_fn:der(x, der(x), der(x, 2))
2. d2y = der(d1y) = der_fn:der(x, der(x), der(x), der(x, 2))

which one is correct?

And what about `d1y2 = der(y2) = der(der_fn(x, time))`?

**Comment by HansOlsson** [comment]
Both are possible - but require different derivative functions, so I would more say that:
- d2y = der(d1y) = der_fn:der1(x, der(x), der(x, 2))
- d2y = der(d1y) = der_fn:der2(x, der(x), der(x), der(x, 2))

are both valid ways of handling that. Obviously they should both generate the same correct result.

The second function can also be used to handle the next case:
- d1y2 = der(y2) = der_fn:der2(x, time, der(x), 1)

**Comment by henrikt-ma** [comment]
Note that when the tool internally links `der_fn:der1` or `der_fn:der2` as derivatives of `der_fn`, it should get the `order` right; which means doing the equivalent of `derivative(order=2) = der_fn:der1` or `derivative(order=1) = der_fn:der2`.  Nothing prevents the tool from adding both.
