### ISSUE TITLE
Table in Section 2.4.4 is incorrect in HTML version but correct in PDF version of specs

### ISSUE THREAD

**Issue by gwr69** [modelica/ModelicaSpecification#3572]
I just note that the table in [section 2.4.4](https://specification.modelica.org/master/lexical-structure.html#strings) of `v3.7-dev` is off in HTML version (single and double quote entries are false):

![image](https://github.com/user-attachments/assets/75f9c88e-c94c-4707-85eb-e7e4ebb4a7bc)

**Comment by henrikt-ma** [comment]
Looks like yet another LaTeXML issue.  I'll look into minimizing the problem and reporting it, as well as look for a workaround to use until the external issue has been fixed.

**Comment by henrikt-ma** [comment]
Reported as https://github.com/brucemiller/LaTeXML/issues/2417.
