### ISSUE TITLE
Confusing use of "that"

### ISSUE THREAD

**Issue by eshmoylova** [modelica/ModelicaSpecification#3576]
In reviewing #3545, I tried to read what is supposed to happen with modifications on constrainedby clause in [Section 7.3.2](https://specification.modelica.org/master/inheritance-modification-and-redeclaration.html#constraining-type), and I found that I cannot fully understand this sentence:

> The modifiers for subsequent redeclarations and constraining type are the modifiers on the component or short-class-definition if that is used in the original declaration, otherwise empty.

What does "that" in "if that is used" refers to? The way it is written it appears to refer to component or short-class-definition. Or even just the short-class-definition. But if short-class-definition is not used, then we fall into "otherwise empty" which does not make sense. And it's the modifiers that are supposed to be empty, right?

**Comment by HansOlsson** [comment]
I believe we can skip text here and just write:

The modifiers for subsequent redeclarations and constraining type are the modifiers on the original component or short-class-definition.

.
The modifiers are often empty - but we don't have to make a separate rule to ignore them in that case (as they don't matter); especially if it just causes more confusion. We could non-normatively add that they are often empty, but I don't see it as needed.
