### ISSUE TITLE
Typo in Appendix B of the specification document, HTML version

### ISSUE THREAD

**Issue by casella** [modelica/ModelicaSpecification#3586]
The description of the simulation process in Appendix B of the MLS 3.6, [PDF version](https://specification.modelica.org/maint/3.6/MLS.pdf), says:
![immagine](https://github.com/user-attachments/assets/af562491-ec4e-4687-bc67-0eeda9289fe9)

![immagine](https://github.com/user-attachments/assets/39ab3d6a-f809-44f1-b53c-e2ad7182f42c)

while the [HTML version](https://specification.modelica.org/maint/3.6/modelica-dae-representation.html) says:

![immagine](https://github.com/user-attachments/assets/f8a3bddb-64bf-474f-baf1-d85a814a6403)

which doesn't make sense, because (B.1d) is not a mixed system of equations but just a bunch of relations. Aren't both versions obtained from the same source? Why did "B.1" become "B.1d" in the HTML version?

**Comment by HansOlsson** [comment]
They are obtained from the same source but processed by different tools. There have been some bugs in the HTML-generation - I will investigate.

**Comment by HansOlsson** [comment]
Reported as https://github.com/brucemiller/LaTeXML/issues/2432
