### ISSUE TITLE
Meaning of 'each', 'final' and 'redeclare' in annotations

### ISSUE THREAD

**Issue by henrikt-ma** [modelica/ModelicaSpecification#3615]
The very open grammar for annotations leaves may open questions:
```
annotation-clause :
   annotation class-modification
```
I'll give some examples.

What is the meaning of `final` below?
```
parameter Real p = 1.0 annotation(final Evaluate = true);
```

What is the meaning of `each` below?
```
parameter Real[5] p = fill(1.0, 5) annotation(each Evaluate = true);
```

Is it the following a valid way of saying `Evaluate = true`?
```
parameter Real p = 1.0 annotation(redeclare Boolean Evaluate = true);
```

Aren't we missing some general semantic restrictions for the `annotation-clause`?  Besides giving increased portability of annotations between tools, it would be of great help for tools that try to implement correct (interpretation and) manipulation of annotations.

**Comment by HansOlsson** [comment]
I would say that `final`, `each`, and `redeclare` in modifiers shall only be used in choices-annotations outside of vendor specific annotations. For vendor specific annotations the vendor is recommended to impose similar restrictions.

**Comment by henrikt-ma** [comment]
Good.  As long as we state that these should not be used with the standard annotations except where explicitly allowed, I don't think we have to say anything specifically about the vendor annotations.

**Comment by HansOlsson** [comment]
@henrikt-ma to write PR (note that "replaceable" without redeclare should also be in the list).
