### ISSUE TITLE
access of conditional instantiated components via equations

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#364]
**Reported by AHaumer on 27 Apr 2010 20:18 UTC**
Is it impossible to allow accessing conditional instantiated components in equations, depending on the same Boolean parameter? Here's a small example:
```
...
  parameter Boolean useHeatPort
    annotation(Evaluate=true);
...
  Modelica.Electrical.Analog.Basic.Resistor R(
    final useHeatPort=useHeatPort);
...
  output Modelica.SIunits.Power lossesR = 
    if useHeatPort then R.heatPort.Q_flow else 0;
...
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/364

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 28 Apr 2010 06:29 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by mgraeber on 28 Apr 2010 10:52 UTC**
I believe this should work if we change the restrictions of declaring conditional components. The if condition of conditional components must be one boolean parameter. The conditonal component can be used in euquations if it is enclosed by an if conditon with exactly the same boolean parameter.

To your example this would mean a minor change:

```
output Modelica.SIunits.Power lossesR = 
    if R.useHeatPort then R.heatPort.Q_flow else 0;
```
The if condition of the equation must be R.useHeatPort instead of useHeatPort, because this is the parameter the condtional heat port is declared with.

**Comment by modelica-trac-importer** [comment]
**Comment by HansOlsson on 28 Apr 2010 16:19 UTC**
I don't understand the example, and would simply write:

```
   output Modelica.SIunits.Power lossesR = R.LossPower;
```

since the losses are present regardless of whether you have a heatPort or not.
It also ensures that losses are >= 0 whereas R.heatPort.Q_flow is <= 0.

I'm not sure if there is a proposal above for changing if-conditions of conditional components from parameter-expression to parameter; and if so the reason for it.

**Comment by modelica-trac-importer** [comment]
**Comment by AHaumer on 28 Apr 2010 17:28 UTC**
Come on Hans, this was just a simple example. 
There might be the case that R itself is conditionally instantiated. 
If R is present, I want to set lossesR = R.lossPower (fine); 
if R is conditionally removed, I want to set lossesR = 0.

**Comment by modelica-trac-importer** [comment]
**Comment by anonymous on 30 Apr 2010 07:05 UTC**
Replying to [comment:3 HansOlsson]:

> I'm not sure if there is a proposal above for changing if-conditions of conditional components from parameter-expression to parameter; and if so the reason for it.

Yes, that is the proposal. The reason for it is a much nicer way of using conditional components. I will give an example, as it occcurs several times in our Library TIL: a pump with a conditional mechanical port. If the port is switched off, an fixed speed (parameter value) is used. Since it is only allowed to access conditional components via connect(), we had to introduce an additional object with a mechanical port only to get the values from the conditional port:

```
...
  parameter Boolean use_mechanicalPort=false ;    
  RotatoryFlange rotatoryFlange if use_mechanicalPort;
  GetInputsRotary getInputsRotary;
equation
  connect(rotatoryFlange, getInputsRotary.rotatoryFlange);
  w = 2*PI*n;
  if use_mechanicalPort then
    der(getInputsRotary.rotatoryFlange.phi) = w;
    J*a + fluidTorque + getInputsRotary.rotatoryFlange.tau = 0 
      "Momentum balance";
  else
    n = nFixed;
    getInputsRotary.rotatoryFlange.phi = 0.0;
  end if;
...
```
With the proposal we wouldn't need the ugly getInputs construct anymore.

Note, there was an similar proposal by Michael Tiller about a built-in operator, that tells you whether a conditional element is present or not:

```
  Real x if a;  
equation
  if exists(x) then
    x = 1.0;
  end if;
```
I think the functionality would basically be the same.

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 30 Apr 2010 07:20 UTC**
Just a note. More information on the similar proposal can be found in #104.

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 21 May 2010 11:09 UTC**
Milestone ModelicaSpec3.3 deleted

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 2 Mar 2012 09:05 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by ahaumer on 11 May 2016 19:15 UTC**

**Comment by modelica-trac-importer** [comment]
**Changelog removed by ahaumer on 11 May 2016 19:15 UTC**

**Comment by HansOlsson** [comment]
To me this largely overlaps with #104; and after almost 10 years I think it can be closed.
