### ISSUE TITLE
Proposal for an annotation to allow alternate component symbols

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#546]
**Reported by stefanv on 3 May 2011 13:22 UTC**
Currently, to the best of my knowledge, the Modelica Standard Library adopts IEC standard symbols for all the components in the Electrical library. I suspect that other relevant standards are followed for other parts of the MSL.

For some North American users, the IEC symbols are unfamiliar or strange looking. Examples include the Resistor, which is a box in IEC symbology, and a zig-zag line in North American (ANSI?) symbology. Another example is the diode, which has a line passing through it in IEC, and is either hollow or completely solid in ANSI.

Many electronics-only simulation tools allow the user to choose between IEC and ANSI symbology. I wonder if it might be worthwhile to introduce an annotation to allow alternate symbols for Modelica components. It would then be up to the tool vendor to provide a mechanism to let the user select which symbol set they want. I envision that there would be a _default_ set that would be used by tools that don't want to support this, and then one or more named alternates.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/546

**Comment by HansOlsson** [comment]
To me this should be coordinated with multi-lingual support, #302
