### ISSUE TITLE
library dependencies

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#556]
**Reported by AHaumer on 24 May 2011 08:44 UTC**
We should try to enhance the uses-annotation to be more specific; consider the following example:

```
package A
  annotation(uses(B(version="1.0"))); // uses only B.interfaces !!!
end A;

package B
  annotation(version="1.1");
  package interfaces
    annotation(version="1.0"); // stable
  end interfaces;
  package components
    annotation(version="1.1"); // changes
  end components;
end B;

model useModel
  annotation(uses(A(version="1.0"),
                  B(version="1.1"))); // uses B.interfaces and B.components
end userModel;
```
If we create a new version of library B (affecting only the components, not the interfaces), why should we create a new version of library A (changing only the uses(B(version)))!)?
Could we provide the information for a tool regarding the userModel:
* no conversion necessary for uses(A), can use the old version
* conversion is needed for uses(B)

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/556

**Comment by modelica-trac-importer** [comment]
**Comment by ahaumer on 24 May 2011 09:00 UTC**
At the 71<sup>st</sup> Design Meeting, Johan Andreasson gave a presentation about that topic. We decided to have a task force "**Improved Package Concept**": Johan Andreasson, Martin Otter, Kilian Link, Toni Haumer, Dag Brück, Peter Aronsson, Gerd Kurzbach. Johan will initiate a web or phone conference.
Ideas / comments are welcome!

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 24 May 2011 14:04 UTC**

**Comment by t-sommer** [comment]
Can you share the result of the phone conference?

**Comment by HansOlsson** [comment]
This task-force seems inactive. 
And there are also other overlapping proposals, e.g., dependencies on multiple versions. 
The conversions have also been standardized after this issue - and thus tools can now detect whether any change is needed or not (without relying on separating B into two parts etc).
Thus closing for book-keeping reasons.
