### ISSUE TITLE
Suggestion for an "undefined" value

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#612]
**Reported by stefanv on 19 Sep 2011 13:41 UTC**
There is currently a mechanism to give a parameter a default value, yet issue a warning if the user doesn't supply an explicit value via a modification:

```
parameter Real P(start = defaultValue);
```

I think it would be useful to have a mechanism so that it is an<ins>error</ins> for the user to not supply a value, perhaps something like one of these:

```
parameter Real P(start = undefined);
// or
parameter Real P = undefined;
```

Thus, when a class containing such a parameter is instantiated, an error will be raised if there was no modification setting a value for this parameter. The value `undefined` would be compatible with any scalar type. Other possible names for this value would be `unknown`, `no_value`, or `unspecified`.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/612

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 19 Sep 2011 13:52 UTC**
It might be useful if this also worked for non-scalar types (at least arrays):

```
parameter Real P[3] = undefined;
parameter Real Q[:] = undefined;
```

The first one declares an array of 3 initially undefined values, whereas the second declares a 1-dimensional array of undefined size and undefined values.

**Comment by modelica-trac-importer** [comment]
**Comment by volker&#46;beuter on 19 Sep 2011 15:05 UTC**
I think there is already such a mechanism at least when using Dymola: When a parameter is declared
without any value or start value and the model where the parameter is declared is used as an element
in some top level model without providing a value by means of a modification meanwhile Dymola issues
an error (regardless if something depends on that parameter or not). (Dymola 6.1 used zero and false
for the values.) The new behaviour could be standardized in the specification without introducing a new
key word.
  (On the other hand this cannot be done in a backard compatible way when we force the tools to change
handling of missing parameter values.)

**Comment by modelica-trac-importer** [comment]
**Comment by mtiller on 19 Sep 2011 15:08 UTC**
In my presentation on Modelica 4, I also raise this issue. From a usability standpoint, this inability to "unset" values is a bit strange. But there are actually several other related use cases.

For example, currently with Modelica we do not allow recursive data structures. This is because we always assume that all members of of a class are instantiated when the class is instantiated. If, instead, we utilize something more like a "reference semantic", it means that nested instances may or may not have an instance associated with them. So in addition to utilizing "undefined" to indicate missing or undefined values, it could be used to indicate whether a given member is instantiated. This opens the door to recursive data structures and (perhaps?) to a relatively simple way to express conditional components.

Obviously, there are no proposals on the table for the features I'm talking about. I only mention them to show that there are multiple (potential) use cases for this kind of feature.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 19 Sep 2011 16:22 UTC**
The behaviour that Volker described for Dymola would certainly fit the bill, although it does contradict the Modelica specification (since the spec says the default start value for numerics is 0).

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 20 Sep 2011 05:29 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 1 Apr 2016 15:05 UTC**
As reported in #252 there is also the case of making a parameter "undefined" to provide an initial equation for it - we need to coordinate these:
```
model A
  parameter Real x=5.0;
end A;
model B
  extends A( x(fixed=false)=unbound );
initial equation
  x+1=time;
end B;
```

**Comment by modelica-trac-importer** [comment]
**Changelog removed by hansolsson on 1 Apr 2016 15:05 UTC**

**Comment by HansOlsson** [comment]
For removing modifiers we now have #2241, and we are in general clearer with requiring values for parameters. Thus I don't see that there is anything remaining - but I may be mistaken.
