### ISSUE TITLE
Lookup of qualified names where the first part is a class

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#661]
**Reported by jmattsson on 13 Dec 2011 09:19 UTC**
Section 5.3.2 of the spec states (about the lookup of a name A.B or A.B.C):
"If the identifier denotes a class, that class is temporarily flattened with an empty environment (i.e. no modifiers, see Section 7.2.2) and using the enclosing classes of the denoted class. The rest of the name [e.g., B or B.C] is looked up among the declared named elements of the temporary flattened class. If the class does not satisfy the requirements for a package, the lookup is restricted to encapsulated elements only. The class we look inside may not be partial in a simulation model."
("The identifier" refers to the first identifier of the name, "A" in this case.)

There are a couple of problems with this:
 * It is rather confusing what it rally means. For one thing, by extension it covers package constants, but the path there is not spelled out. See the comment at the end of 5.3.3, "_The package-restriction ensure that global name lookup of component references can only find global constants._"
 * The restriction "satisfy the requirements for a package" is weird - most places we require classes to _have_ a specific restriction, why not here?

The first point could be fixed as a clarification, but the second would be a breaking change (Modelon.Media has records containing package constants).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/661

**Comment by modelica-trac-importer** [comment]
**Modified by hansolsson on 1 Mar 2012 09:13 UTC**

**Comment by modelica-trac-importer** [comment]
**Modified by jmattsson on 16 Jun 2016 12:15 UTC**

**Comment by modelica-trac-importer** [comment]
**Changelog removed by jmattsson on 16 Jun 2016 12:15 UTC**

**Comment by HansOlsson** [comment]
@jespermattsson Does Modelon.Media still have those constants relying on that lookup rule?
