### ISSUE TITLE
Lexical scope of redeclarations

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#672]
**Reported by choeger on 2 Jan 2012 12:43 UTC**
The specification seems to be unclear about which redeclarations count as "A redeclare construct as an element". 

```
model Bar
    replaceable model A
        constant Real x = 1;
    end A;
end Bar;

model Foo

   redeclare model A
      constant Real x = 2;
   end A;

   model Baz
      extends Bar;
      constant Real z = x;
   end Baz;
   
end Foo;
```

In the above example, what value does z have for an instance of Baz? In the standard library, this is used e.g. in the Media classes. Though I could not find an entry about this in the relevant section.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/672

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 2 Jan 2012 13:01 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 2 Jan 2012 16:06 UTC**
There must be some trivial typos in the example that is obscuring the actual point for me:
* There is 'z=x' but there is no 'x' in scope of that declaration.
* There is a 'redeclare model A' without any extends-clause in the same scope.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 2 Jan 2012 18:05 UTC**
~~Sorry, I forgot an 'A' in the extends clause. ~~

```
model Bar
    replaceable model A
        constant Real x = 1;
    end A;
    A a;
end Bar;

model Foo

   redeclare model A
      constant Real x = 2;
   end A;

   model Baz
      extends Bar;
      constant Real z = a.x;
   end Baz;
   
end Foo;
```
The point about the "no extends in the same scope" is actually, what I wanted to discuss. I think in Media we see alot of lexical redeclarations, but the spec only mentions the ones from the local scope.

edit: cannot extend from replaceables, forgot that too. This change just makes the example a little larger.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 3 Jan 2012 11:23 UTC**
But the 'redeclare model A' in Foo should be illegal,since 'The redeclare construct as an element requires that the element is inherited'.

The specification states that it redeclares an inherited 'A' - we might clarify this to state that the inherited A has to be in the same scope as the redeclare itself (i.e. 'redeclare model A' in Foo does not apply this redeclaration to all inherited model A in some class inside Foo).
I see it as obvious that 'inherited element' only refers to elements inherited in the local (lexical) scope - but if needed it could be made even clearer.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 3 Jan 2012 15:35 UTC**
It is no problem at all to also make foo inherit A from somewhere. The problem is, that the media library does use such patterns. e.g. all the set_state\* functions use a ThermoDynamicRecord  instance, which is redeclared somewhere above in the lexical scope.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 3 Jan 2012 15:55 UTC**
Replying to [comment:5 choeger]:
> It is no problem at all to also make foo inherit A from somewhere. The problem is, that the media library does use such patterns. e.g. all the set_state\* functions use a ThermoDynamicRecord  instance, which is redeclared somewhere above in the lexical scope.

Then instead of creating a new example with Foo, Bar, Baz:

Start from the actual example and strip it off everything not relevant to the question while keeping the names of identifiers (or shorten them if needed).

That will show both what is the actual pattern used and why it is relevant.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 4 Jan 2012 17:08 UTC**
Have a look at `PartialTwoPhaseMedium` .

It has the following structure:

```
partial package PartialTwoPhaseMedium
    "Base class for two phase medium of one substance"
    extends PartialPureSubstance;

    ....

    redeclare replaceable record extends ThermodynamicState
      "Thermodynamic state of two phase medium"
      FixedPhase phase(min=0, max=2)
        "phase of the fluid: 1 for 1-phase, 2 for two-phase, 0 for not known, e.g., interactive use";
    end ThermodynamicState;

    ....

    redeclare replaceable partial function extends setState_phX
      "Return thermodynamic state as function of p, h and composition X or Xi"
      input FixedPhase phase=0
        "2 for two-phase, 1 for one-phase, 0 if not known";
    end setState_phX;
 
    ....
end PartialTwoPhaseMedium;

The function `setState_phX` clearly returns a `PartialTwoPhaseMedium.ThermoDynamicState`, right? This means, that the redeclaration is from the lexical scope.

```

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
