### ISSUE TITLE
Self inheritance

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#841]
**Modified by choeger on 28 Sep 2012 10:58 UTC**
Hi all,

in Modelica, something like the "partially flattened" class is always considered part of the environment of a class. E.g.

```mo
package Modelica
  extends Modelica.Icons.Package;
```

This means, we can actually use the name "Modelica" before (or during) evaluation of the type "Modelica". As long as "Icons" comes from a concrete type definition (and is not itself inherited), this is not a big deal (just complicates lookup a little bit).

The problem I found was with a smaller model:

```mo
class A
  extends A;
end A;
```

If we don't project something out of "A" what is it's (type-)value? Is it the empty class? This would yield:

```mo
class A end A;
```

or is it an error? And if it is an error how (and where in the specification) do we decide on that?

I consider this a defect, since it seems unspecified to me.

----

**Reported by choeger on 28 Sep 2012 10:54 UTC**
Hi all,

in Modelica, something like the "partially flattened" class is always considered part of the environment of a class. E.g.

```mo
package Modelica
  extends Modelica.Icons.Package;
```

This means, we can actually use the name "Modelica" before (or during) evaluation of the type "Modelica". As long as "Icons" comes from a concrete type definition (and is not itself inherited), this is not a big deal (just complicates lookup a little bit).

The problem I found was with a smaller model:

```
!#mo
class A
  extends A;
end A;
```

If we don't project something out of "A" what is it's (type-)value? Is it the empty class? This would yield:

```mo
class A end A;
```

or is it an error? And if it is an error how (and where in the specification) do we decide on that?

I consider this a defect, since it seems unspecified to me.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/841

**Comment by modelica-trac-importer** [comment]
**Modified by choeger on 28 Sep 2012 10:58 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 28 Sep 2012 11:08 UTC**
I ran a quick test. Dymola 2013 crashes upon check of that model and JModelica.org complains that it can not find the class:
```
pymodelica.compiler.ModelicaClassNotFoundError: A
```

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 28 Sep 2012 13:29 UTC**
MapleSim fails semi-gracefully with _Error, too many levels of recursion_.

However, my opinion is that this should case should be an error. How detailed the error message should be is of course up to the tool vendor. "Class A not found" is fine. Something like "Recursive inheritance of A" would of course be better. I suppose the language spec can't rule out crashing either, but I think the spec can state the construct is not valid.

**Comment by modelica-trac-importer** [comment]
**Comment by per&#46;ostlund on 28 Sep 2012 14:33 UTC**
My opinion is also that this is an error, since the specification says that extends are looked up, flattened and inserted into the extending class when doing partial flattening. This obviously leads to an infinite loop.

However, what about this kind of self inheritance?
```
class A
  class B    
    extends A;
  end B;
end A;
```
This particular model is accepted by both Dymola and OpenModelica, but quickly breaks if you try to actually do something useful in my experience (like use B in A). In my opinion it should be forbidden to extend _any_ of the enclosing classes, not just the immediate enclosing class.

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 28 Sep 2012 14:46 UTC**
Actually I am not sure if this really should be an error. Obviously, (see Modelica.Icons.Package), there **is** a way to acccess the current class in an extends statement. So A is element of the partially flattened class (pointing to itself). This makes the self inheritance a no-op from a type construction perspective.

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 28 Sep 2012 14:55 UTC**
In response to Per's comment, perhaps your example is accepted only because B is never instantiated. MapleSim accepts your example too, but if you change it to,

```
class A
   class B
      extends A;
   end B;
   B b;
end A;
```

then the same _too many levels of recursion_ error results.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 4 Dec 2012 22:51 UTC**
Language group: Delay - no urgent need to change this.

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
