### ISSUE TITLE
Composite name lookup should use (temporarily) partially flattened classes

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#862]
**Reported by hansolsson on 9 Oct 2012 08:24 UTC**
Almost all models in MSL depend on MSL which seems to require a form of on "lazy evaluation" that is not fully specified. 

E.g. in the first model I found:
```
within Modelica.Blocks.Examples;
model PID_Controller 
  "Demonstrates the usage of a Continuous.LimPID controller"
  extends Modelica.Icons.Example;
...
```
The lookup of "Modelica.Icons.Examples" relies on semantics that can be specified better. The composite name lookup is in general specified 5.3.2 as:
"If the identifier denotes a class, that class is temporarily flattened with an empty environment (i.e. no modifiers, see Section 7.2.2) and using the enclosing classes of the denoted class. The rest of the name [e.g., B or B.C] is looked up among the declared named elements of the temporary flattened class."

Thus we need to flatten Modelica before we can flatten Modelica! 

This can be solved by a sort of lazy evaluation, specifically that we only perform the partial flattening (5.6.1) for "Modelica" and "Modelica.Icons" at this point and not the flattening of all elements specified in 5.6.2.

This just needs to be clarified, all tools assumedly already handle this. Obviously this applies to all lookup - including import; #861.

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/862

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
