### ISSUE TITLE
Clarification on lexical class scope & inheritance

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#863]
**Modified by choeger on 9 Oct 2012 09:11 UTC**
It seems to me, the specification is unclear about what to evaluate first: local types or inheritance:

The first model inherits from a locally declared type:

```mo
model DeclarationsFirst
    class A
      type T = Real;
    end A;

    T x;

    extends A;
end DeclarationsFirst;
```

The next two models demonstrate the opposite approach:

```mo
model ExtendsFirstBase
    type T = Real;
end ExtendsFirstBase;

model ExtendsFirst
    class A
      T t;
    end A;

    extends ExtendsFirstBase;
end ExtendsFirst;
```

Now what is correct Modelica? The problem is: One cannot 'see' what name an extends-statement will introduce. Thus, one has to evaluate (look it up) it completely in order to not miss any possible declaration:

```mo
model Mixed
    class A
      T t;
    end A;
    class B
      type T = Real;
    end B;
    extends A;
    extends B;
end Mixed;
```

In the model above, if one would like to instantiate the model Mixed.A, the evaluation order would need to be: Mixed.B -> Mixed.extends B -> Mixed.A (-> Mixed.extends A). 

I wonder if that kind of "blind guessing" evaluation is intentional?

edit:

This seems to boil down to section 5.6.1: 

> Then base-classes are looked up, **flattened** and inserted into the class. 

Thus it seems that model Mixed should be invalid?

----

**Reported by choeger on 9 Oct 2012 09:00 UTC**
It seems to me, the specification is unclear about what to evaluate first: local types or inheritance:

The first model inherits from a locally declared type:

```mo
model DeclarationsFirst
    class A
      type T = Real;
    end A;

    T x;

    extends A;
end DeclarationsFirst;
```

The next two models demonstrate the opposite approach:

```mo
model ExtendsFirstBase
    type T = Real;
end ExtendsFirstBase;

model ExtendsFirst
    class A
      T t;
    end A;

    extends ExtendsFirstBase;
end ExtendsFirst;
```

Now what is correct Modelica? The problem is: One cannot 'see' what name an extends-statement will introduce. Thus, one has to evaluate (look it up) it completely in order to not miss any possible declaration:

```mo
model Mixed
    class A
      T t;
    end A;
    class B
      type T = Real;
    end B;
    extends A;
    extends B;
end Mixed;
```

In the model above, if one would like to instantiate the model Mixed.A, the evaluation order would need to be: Mixed.B -> Mixed.extends B -> Mixed.A (-> Mixed.extends A). 

I wonder if that kind of "blind guessing" evaluation is intentional?

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/863

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 15 Mar 2013 12:21 UTC**
These are non-blocking issues; thus moving to next release so that we can release 3.2rev2 (would have been good to improve these as well, but no time).

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 14 Mar 2017 13:54 UTC**
These issues should be resolved with the new flattening.
If that is not the case they need to reference an issue in the new description.

**Comment by HansOlsson** [comment]
This should by clarified by the new flattening #1829 - if not it should be re-opened with a reference to the new specification.
