### ISSUE TITLE
Ambiguities with . in Modelica language

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#899]
**Reported by rfranke on 2 Nov 2012 09:42 UTC**
.\* and ./ are operators for element-wise operations on arrays, where they can be treated as tokens.

Moreover .\* is used in import clauses, where whitespaces may be in between:
```
import_clause :
     import ( IDENT "=" name | name ["." ( "*" | "{" import_list "}" ) ] ) comment
```

Last but not least an UNSIGNED_NUMBER may end with a dot, which introduces ambiguities in matrix expressions, see ModelicaSpec33.pdf, section 10.6.6:
```
   2./[1,2;3,4] // error, since 2.0/[1,2;3,4]
   2 ./[1,2;3,4] // fine, element-wise division
```

Couldn't the Modelica specification be changed to avoid these ambiguities?
Proposals:

(1) a number must not end with a dot; instead of 2., one can write 2.0 or just 2

(2) no whitespaces allowed between the dot and the star in import clauses:

```
import_clause :
     import ( IDENT "=" name | name [".*" | "." "{" import_list "}" ] ) comment
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/899

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 2 Nov 2012 09:48 UTC**
The issue with import `.*` is not a conflict and can be ignored. The ambiguous behaviour of 2.\*3 is real though. Actually it's not ambiguous since the lexer always matches the longest possible token, 2. in this case. The problem is it is confusing for users.

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 2 Nov 2012 10:07 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by stefanv on 2 Nov 2012 14:19 UTC**
I agree with Martin. In our parser, we treat the grammar for import_clause as follows:

```
import_clause:
  import ( IDENT "=" name | name [ "." "*" | ".*" | "." "{" import_list "}" ] )
     comment
```

Thus both a separate "." and "\*", or the single ".\*" token, are accepted to mean ".\*" in the import clause.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 3 Nov 2012 09:15 UTC**
It is indeed not critical how .\* is used in the import clause and as Stefan writes, ".\*" can be treated as token anyway.

Regarding numbers ending with ".", I wonder if really each lexer will always match the longest possible token. At least the "human lexer" tends to think that the two expressions
```
2 ./[1,2;3,4]
2./[1,2;3,4]
```
are the same (making the simplifying assumption that whitespaces before and after arithmetic operators should not matter). 
Considering that
* Modelica enforces declare before use, e.g. Real a = 2 will give a Real
* Modelica does true division, e.g. 5/9 will result in an untruncated Real
* one can easily add a zero behind the dot, e.g. 2.0 instead of 2.
Is there any use case for numbers ending with dot?

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 20 Dec 2012 13:47 UTC**
Housekeeping, defaulting all new tickets to [milesstone:\*undecided\*] (is normally done automatically)

**Comment by HansOlsson** [comment]
The lexer issue was clarified in #2122 (which now has a PR).
