### ISSUE TITLE
No way to specifiy start, min, max, and nominal attributes for der(x)

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#934]
**Reported by fcasella on 19 Dec 2012 14:02 UTC**
Derivatives can be unknowns of nonlinear algebraic systems of equations, in particular when solving initialization problems. 

Currently, there is no way to specify an initial guess for the iterative solver (i.e., the start attribute), nor to set the min, max, and nominal attributes, which could help the solver doing its job.

See also comment 4 of #933

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/934

**Comment by modelica-trac-importer** [comment]
**Modified by dietmarw on 19 Dec 2012 14:06 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by sjoelund&#x2e;se on 19 Dec 2012 15:03 UTC**
Isn't this as simple as:
```mo
model M
  Real r;
  Real der_r(start = 1.0) = der(r);
equation
  ...
end M;
```

**Comment by modelica-trac-importer** [comment]
**Comment by eshmoylova on 19 Dec 2012 15:14 UTC**
Replying to [comment:2 sjoelund.se]:
> Isn't this as simple as:
> ```mo
> model M
>   Real r;
>   Real der_r(start = 1.0) = der(r);
> equation
>   ...
> end M;
> ```

There is a suggestion in ticket:933 to treat der(v) as variables without the need of introducing intermediate variables.

**Comment by modelica-trac-importer** [comment]
**Comment by msasena on 19 Dec 2012 15:24 UTC**
Replying to [comment:3 eshmoylova]:
> Replying to [comment:2 sjoelund.se]:
> > Isn't this as simple as:
> > {{{#!mo
> > model M
> >   Real r;
> >   Real der_r(start = 1.0) = der(r);
> > equation
> >   ...
> > end M;
> > }}}
> 
> There is a suggestion in ticket:933 to treat der(v) as variables without the need of introducing intermediate variables.

I've tried introducing intermediate variable before so that I could specify the start attribute of a derivative variable included in the nonlinear equations section.  The problem was that, in certain cases, simply introducing that intermediate variable changed the equation sorting, and therefore different variables were chosen to be part of the nonlinear system.  So trying to fix the problem just lead to new problems.  Being able to specify the start attribute of a derivate directly (without intermediate variables) would hopefullly eliminate the kinds of problems I observed.

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 19 Dec 2012 16:05 UTC**
Note that there is also a similar issue for elements of array variables.

In that case you can set start-value for the entire array - but not just set start-values for a few specific elements.

**Comment by modelica-trac-importer** [comment]
**Comment by anonymous on 20 Dec 2012 09:01 UTC**
You might want to have a look at a specific example, e.g. Modelica.Fluid.Examples.HeatingSystem. Besides a closed flow loop, it demonstrates the ability to run dynamic simulations, steady-state simulations and dyanamic simulations with steady-state initial values for one and the same model. Just adjust the global setting under `system.energyDynamics` (Assumptions tab).

Everything is fine with `FixedInitial`. But the plotted results don't look nice as the initial states need to find their values during the dynamic simulation. This is why the default setting should be `SteadyStateInitial`. Asked to be pedantic, Dymola 2013 FD01 raises the error:
```
The following variables are iteration variables of the initialization problem:
der(tank.V)
but they are not given any explicit start values. Zero will be used.
```
Let's apply the work-around proposed in comment:2 above. Change `Modelica.Fluid.Vessels.OpenTank` with:
```
  Real der_V(start = 0) = der(V);
equation
  ...
    Wb_flow = -p_ambient*der_V;
```
First of all: what about physical units for der_V? This change can hardly be committed to the MSL. `Modelica.SIunits` does not seem to be prepared for providing units for time derivatives.

But we have achieved that `SteadyStateInitial` passes the pedandic check now. Let's have a look at the other scenarios. Suddenly `SteadyState` raises the error
```
Failed to reduce the DAE index.
```
Trying to be pedantic we introduced a real problem. This underlines what has been said in comment:4 above.

Couldn't the Modelica specification say that derivatives have the default start value zero?
This would solve many pedantic issues in Fluid today and it appears extensible for the future.

**Comment by modelica-trac-importer** [comment]
**Comment by rfranke on 20 Dec 2012 09:02 UTC**
sign comment:6

**Comment by modelica-trac-importer** [comment]
**Comment by hubertus on 20 Dec 2012 09:59 UTC**
I would also assume that it is important to define a nominal values to derivatives  for difficult and large steady-state cases. So I agree with the short term solution to specify that start for der(x) is 0.0, unless defined through an intermediate variable, but we need to do something about the problem. On the other hand: the problem described in comment:4 could also be classified as a tool problem, not a specification problem.

**Comment by modelica-trac-importer** [comment]
**Comment by fcasella on 20 Dec 2012 13:33 UTC**
One more comment to this long thread. The "pedantic" flag of Dymola is a interesting tool to discover possible issues with models. However, I understand the goal of the MAP-LIB is not to provide code that run in Dymola when in pedantic mode, but rather to provide code which is strictly conforming to the spec and that has no inherent ambiguity, so that all Modelica tools have a chance of producing the same results on an equal basis.

From this point of view, the fact that some iteration variables (including derivatives) which are selected by a specific tool to solve nonlinear algebraic systems do not have a start attribute is by no means an error. The fact that the initial conditions are not unambiguously defined instead is.

What is true is that giving tools the complete freedom to select iteration variables can be problematic for modellers, that do not have a chance to steer the model towards the successful convergence to the desiderd solution of the problem - but this is a different problem and it should be discussed elsewhere

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 21 Dec 2012 11:27 UTC**
Short answer:
For the next release of Dymola we will (likely) change it so that those iteration variables are not treated as errors for pedantic mode.


Long answer:
\--
In general:
However, issues are not always ok or error. There can also be issues that unambigous, well-defined according to the spec; but still should be avoided since they are not good style. In several cases the specification recommends diagnostics even if defining the result - I hope you agree that those should also be avoided.

For this case:
I agree that the specific iteration variables lacking a start-values is not really an issue. However, it is a minor issue that there exists a non-linear system, where a tool will need to select some iteration variables and not all of the possible iteration variables have start-values, since there could be problems with convergence or multiple solutions.

How problematic this is depends on the model and the variables, and derivative-variables are usually the least problematic ones.

**Comment by modelica-trac-importer** [comment]
**Modified by otter on 20 Sep 2013 10:22 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by dietmarw on 15 Nov 2013 13:30 UTC**
80th Design Meeting is long over ... closing that milestone and still open tickets set back to \*undecided\*.

**Comment by HansOlsson** [comment]
After 7 years this does not seem urgent, and it seems the specific tool-issues are reduced - but I may be mistaken.
