### ISSUE TITLE
Arrays and member-access

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/ModelicaSpecification#965]
**Reported by choeger on 16 Jan 2013 10:27 UTC**
As far as I know, the following used to work in Modelica (at least in modification-equations) for years:

```mo
record X
  Real r;
end X;

model M
  Real[3] r 
end M;

X [3] x;
M m(r = x.r); //m.r = {x[1].r, x[2].r, x[3].r};
```

first of all, I think the rule for dot-access of arrays should be formalized into the name lookup section (it could be useful outside of modifications, and I guess all tool vendors already define it that way for simplicity).

second, the precedence of the array index operator needs to be defined:

```mo
model Test
  record Y
    Real[3] r = {1,2,3};
  end Y;

  record X
    Y[2] y;
  end X;
 
  model M     
    Real[2] r;
  end M;

  X x;
  M m(r = x.y.r[3]);
  // (x.(y.r[3])) or (x.y.r)[3] ? we mean: {x.y[1].r[3], x.y[2].r[3]}
end Test;
```

I found the example above in a client's propietary model. The point is that different precedence seems to yield different results. Some tools accept the model while others reject it (complaining about indexing an [2,3] array with only one dimension).

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/965

**Comment by modelica-trac-importer** [comment]
**Comment by hansolsson on 16 Jan 2013 10:42 UTC**
This is defined; but in a different section (as "slicing operation"). Thus I would propose to close this ticket.

And if a tool interprets x.y.r[3] as (x.y.r)[3] it does not follow Modelica 3, 
since Section 10.6.9 Slice Operation states:
...
The slicing operation can be combined with indexing, e.g. a.m[1]. It returns the array of components {a[1].m[1], a[2].m[1], …}, and does not require that size(a[1].m)=size(a[2].m). The number of subscripts on m must exactly correspond to the number of array dimension for m, and is only valid if size(a[1].m[…])=size(a[2].m[…])..

**Comment by modelica-trac-importer** [comment]
**Comment by choeger on 16 Jan 2013 12:52 UTC**
Ah, I knew there was a section about it. I propose to add a link in the name lookup section.

If I get you right, your intention is that `a.x[i]` means "get x[i] from a" where `x[i]` means "get [i] from x". So in case of "slicing" the index belongs to the field (and not to the resolved component), right?

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 11 Jan 2017 22:25 UTC**

**Comment by HansOlsson** [comment]
The actual question is answered. The remaining issue is whether to add a cross-reference - but I'm not sure that it is needed.
